Significant-Gravitas/AutoGPT

scripts/ai_functions.py
scripts/keys.py

This pull request is to test whether the repositories pull request auto-formatter has been set up properly.

Autoformat testing

---

Dockerfile
scripts/requirements.txt

hello, in order to isolate the execution, I added a simple dockerfile using py3.11 (I had to remove the pins to resolve conflicts). 
```sh
docker build -t auto-gpt . && docker run --rm -it auto-gpt
```
I'm also happy to add a dependency manager as well so the project doest have any dep conflicts;  if thats something that might be interesting for you, let me know and I can push another pr using pip-tools or poetry or pipenv etc.

Add Dockerfile and update requirements.txt.

---

scripts/browse.py

fix typo in browse.py

---

requirements.txt
scripts/json_parser.py

Fixes the missing UserDict (caused by migration from python 3.9 to ^3.10)

dirtyjson -> json

---

scripts/file_operations.py

Fix: create file dir if it doesnt exist during write_to_file

---

scripts/data.py

This makes the prompt path relative to the data.py path. Otherwise following the README you get:
```bash
cd Auto-GPT
python scripts/main.py
...
Enter nothing to load defaults, enter nothing when finished.
Goal 1:
Error: Prompt file not found
Error: Invalid JSON
```

don't depend on the path script is run from

---

scripts/data/prompt.txt

#Fixes an issue where it hallucinates on "COMMANDS" 💭
#https://github.com/Torantulino/Auto-GPT/issues/77

Fix Issue with command hallucination 💭

---

scripts/browse.py
scripts/commands.py
scripts/data/prompt.txt

Agents browsing the web are usually looking to find answers to questions.
Currently, the agents blindly summarize the website contents, which is often not useful. For example, if you're wanting to browse Leonardo DiCaprio's wiki to find his birthday, you will see the following:
> This subpage is dedicated to American actor and film producer Leonardo DiCaprio. It includes information about his early life, acting career, other ventures such as activism and philanthropy, personal life, and filmography and accolades. It details his rise to fame with Titanic and his work as an actor and producer since then. It also highlights his activism, philanthropy, and charitable donations. Additionally, there are pages dedicated to his movies, reviews, awards, personal life, and more.
Whereas with my …

Ask questions when browsing websites

---

scripts/data.py

Simplify the load_prompt function by eliminating redundancy
_also fixed a typo_

Refactor load_prompt function

---

scripts/data/prompt.txt

This way it thinks befor it acts

More logical Prompt - found by Agusx1211

---

scripts/speak.py

Agents now have a different voice again.

Adds voice index back in

---

scripts/commands.py
scripts/data/prompt.txt
scripts/file_operations.py

This pull request introduces the `search_files` command to the project, allowing users to search for files within the specified directory. The changes include:
1. Adding the `search_files` command to the `commands.py` file.
2. Implementing the `search_files` function in the `file_operations.py` file, which searches for files in the specified directory.
3. Updating the `prompt.txt` file to include the new `search_files` command in the list of available commands.
These changes will enhance the functionality of the project by providing users with the ability to search for files within a given directory, making it easier to manage and locate files in `auto_gpt_workspace`.

Add search_files command to the project

---

.gitignore
ai_settings.yaml
scripts/ai_config.py

Makes it clearer that there is a `.yaml` file you can edit to change the AI's unput without typing into the command prompt.

Input file

---

scripts/data/prompt.txt

Added double quotes around name on line 14.

Added missing double quotes around name in the prompt.txt text file

---

requirements.txt

To fix this error:
ModuleNotFoundError: No module named 'PIL'
Add Pillow to the requirements.txt
Added and tested locally, fixes the issue.

fix: add Pillow dependency

---

scripts/chat.py

The system has no knowledge of the current time and date.
Added a system message in each context.
Single line change.

Added time and date to the system message for each context

---

scripts/main.py

fix command error check

---

README.md

Due to tiktoken dependency.
https://github.com/Torantulino/Auto-GPT/issues/551

Update README to indicate Python 3.8 minimum

---

scripts/data/prompt.txt

fix typo in prompt.txt

---

scripts/json_parser.py
scripts/json_utils.py

This fixes most errors I've encountered. This is from debugging the vicuna branch.
Implemented serveral method to correct invalid JSON.
Tested locally on vicuna branch.

Fixes for common json errors, cleanup json_parser file.

---

scripts/commands.py
scripts/data/prompt.txt

I noticed that when the AI doesn't want to input any command, it uses this blank action which outputs a reminder to refer to the commands list since nothing isn't a valid command:
```
NEXT ACTION:  COMMAND =  ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Useless-GPT...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command returned: Unknown command ''. Please refer to the 'COMMANDS' list for availabe commands and only respond in the specified JSON format.
```
If the AI didn't want to do anything in the first place, it doesn't need a reminder to look at the commands, especially since multiple of such reminders can take up more tokens than adding a `do_nothing` command to the prompt. …

Add a `do_nothing` command

---

scripts/main.py

Introduce check to OPENAI_API_KEY environment variable if set.

Introduce check to OPENAI_API_KEY

---

Dockerfile

Currently, the Dockerfile doesn't work for running the application. If we copy over requirements.txt, it will allow the Dockerfile to run the app.

Make sure to copy over requirements.txt to Dockerfile.

---

CONTRIBUTING.md
README.md
outputs/logs/message-log-1.txt
outputs/logs/message-log-2.txt
outputs/logs/message-log-3.txt
scripts/ai_functions.py
scripts/commands.py
scripts/config.py
scripts/data.py
scripts/data/prompt.txt
scripts/execute_code.py
scripts/image_gen.py
scripts/main.py
tests/json_tests.py

This happens often in PRs so fixing this everywhere will make many PRs mergeable as they won't include irrelevant whitespace fixes
This is a focused change to enable linting and other large-scale PRs in the future.
Whitespace is eliminated everywhere, results confirmed through git grep. I only changed the space, not double lines of tabs (not sure if they are present).
Some files have a line break added at the end so they are terminated with the line terminator. This is a good practice and it is also enforced by vim, making the repo more vim-friendly.
The change is supposed to be safe.
This is a formatting change so it's untestable.

Remove trailing spaces throughout

---

scripts/chat.py

Change debug_mode to debug in chat.py.

---

scripts/chat.py
scripts/json_parser.py

Fixes erroneous access to `Config#debug_mode`. `Config` has no defined `debug_mode`, the property is named `debug` instead.
Changes the remaining occurrences of `cfg.debug_mode` to `cfg.debug`

Changed occurances of 'cfg.debug_mode'  to 'cfg.debug'

---

scripts/browse.py

Fix of :warning:[Auto-GPT managed to escape its workplace-boundaries via browser commands #666](https://github.com/Torantulino/Auto-GPT/issues/666#issue-1660676426).
This pull request aims to address the issue where the AI could read local files on the host system through the `browse.py` script. To prevent this, I have added a check that restricts the AI from accessing URLs starting with `file://` or `file://localhost`.
Modified the `scrape_text` function in `browse.py` to include a check for local file URLs, restricting access to local files.
In-code comments have been added to explain the restriction on local file URLs.
I can't test this right now as I am experiencing issue #644. I will do so as soon as I am able to. In the meantime, it would be appreciated if someone would test this …

Restrict browse from accessing local files

---

README.md

README pinecone link added

---

scripts/file_operations.py

On Windows files are read using ascii, which leads to errors.
Read files with UTF-8 encoding.
No need to document.
Not tested.
This is a pretty standard thing.

Use UTF-8 encoding for Windows users.

---

.gitignore

It shows up in Github Desktop as a change, although it shouldn't.
Add `\nlog.txt` to `.gitignore`
N/A
N/A?

Add `log.txt` to gitignore

---

scripts/main.py

Removed unneeded imports from `script/main.py`
Unneeded imports removed
Deleted two import lines from `script/main.py`
N/A
Reran the script as well as searched for any dependencies other files may contain; none were found.
Tests are not required for unneeded imports

[Cleanup] Removed unneeded imports

---

scripts/chat.py
scripts/json_parser.py

Fix the remaining inconsistent places using cfg.debug

Make the cfg.debug to cfg.debug_mode consistent across files

---

scripts/spinner.py

Before the change, the spinner completely messed up my terminal.
After the change, the spinner behaves as expected.
Changed the `spin` function to use carriage returns (`\r`), like the `__exit__` function, instead of backspaces (`\b`).

Fix Spinner

---

scripts/ai_config.py
scripts/chat.py
scripts/commands.py
scripts/config.py
scripts/json_parser.py

Fix some typos

---

.github/PULL_REQUEST_TEMPLATE.md

- Changed "thouroughly" to "thoroughly"
- Changed "seperate" to "separate"

Fixed typos

---

scripts/agent_manager.py

agent_manager.py spells "GPT" "GTP". It also refers to it as GTP3 even though 4 is used.
Changed GTP to GTP and removed the 3.
N/A
N/A

Changed spelling from "GTP" to "GPT". Also removed the 3 as this can run on GPT4.

---

README.md

Added Open API Key hyperlink to the README to match other Requirements
Added an OPEN API Key link to the README

Add OpenAPI Key Link to README

---

README.md
scripts/chat.py
scripts/json_parser.py
scripts/logger.py
scripts/main.py
scripts/token_counter.py

This is a re-submit of PR https://github.com/Torantulino/Auto-GPT/pull/434.
For the PR template, see the related PR

logging activity and error in log files in addition to the console - attempt 2

---

scripts/main.py

While using the project, due to inattention, got an error trying to authorize the command (added trailing spaces).
EX: 
```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.scirp.org/pdf/JSEA_2017122814463719.pdf', 'question': ''}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Researcher...
Input:y 
SYSTEM:  Human feedback: y
```
added rstrip() to the condition checking for the 'y' (authorize) input 
code is self-explanatory, adding comments would  make the code less readable
running the project, I inputed 'y  '  y with followed trailing spaces

check for authorise 'y' without trailing space

---

scripts/memory/local.py
tests/local_cache_test.py

- Fixes issue #840 
- Fix #840 
- Added defensive coding for local memory to load the JSON file that was gitignored at 54101c79973ca5ca8ccd7e1ac59856cb282c57d8
- Added unit test placeholder (but doesn't know how to run it - sorry, still newb in python)

Bugfix for #840 - Local memory fix

---

.github/ISSUE_TEMPLATE/1.bug.yml

Too many fluff issues.
Clear directions to reduce volume.

Update github-issue template for bug-report

---

scripts/main.py

Long support for maintainability, it also helps for others to read the code.
- Remove multiple handler for `args.debug`
- Remove Config being instantiated twice.
Not needed
N/A

Remove duplicated unnecessary codes

---

scripts/execute_code.py

If the given image is not found locally, the code will be stuck
using docker api to get the image in local, if not found then pull the image from docker hub. I also log progress when pulling so user can see the progress 
I have specify some comments inside execute_python_file
manual test:
- run python script with docker version that not exist in local
- it should not be stuck
- it should pull the image from docker hub
- it should show the progress
- it should able to continue executing the code

pull image if it's not found locally

---

scripts/ai_functions.py
scripts/logger.py
tests.py

I would like to keep the requirements low on the PR authors for now and gradually improve the pep8 compliance without introducing much breakage.
Some of the previously fixed things creeped in, so I apply all previous fixes again and some new.
N/A
I only included entirely safe line and whitespace improvements.

Fix flake8 E303,W293,W291,W292,E305

---

README.md

add link for pinecone in README

---

README.md

Update README.md on log location

---

scripts/main.py

This main.py is the Number 1 thing that slows development. It killed 100 of hours of development probably already. I know it killed at least 3 hours of mine because of the tricks I implemented to circumvent it:
- it has too many lines.
- it has code at the top level, meaning you can't import anything.
- it has a bunch of global everywhere.
- the loop, which is the most important thing about autogpt, is not in a method !
Let's start simple: 
- just add an if __main__ 
- then indent.
- and tada ! you can import stuff now (almost, we just need to get rid of these globals and put the loop in a method, but this is coming soon)
This one I tested it a lot:

put loop in in if main

---

scripts/memory/no_memory.py
scripts/memory/pinecone.py

Fix flake8 E302

---

scripts/memory/base.py

Hotfix - re-add missing cfg variable to memory/base

---

scripts/memory/base.py

Flake8 linter fix E302

---

scripts/data/prompt.txt

Large Language Models love consistency
- Removed the newline after `"thoughts":`
- Added a space after `"args":`

Fix JSON formatting in prompt.txt

---

README.md

[README] Link to 11Labs website to obtain API_KEY

---

scripts/main.py

this method is useless, it's not called by anything. And we need to trim down main.py.
Let's ask the community to avoid writing more methods in main.py.
removed the method

remove useless load_variables_method

---

scripts/main.py

remove duplicate debug mode logger
remove duplicate debug mode logger
manual handling

fix: remove duplicate debug mode logger

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md

A manually configured python environment on a personal computer may have system-dependent problems, and for novices, solving these problems will take a lot of time.
Added a devcontainer-based environment configuration to use Auto-GPT directly in the container.
Documented in code.
MANUAL: local test

[environments] add devcontainer config

---

scripts/main.py

After this we're almost able to put all of these methods in separate python files depending on what they do, and we can stop having conflicts with main.py
All I did was: 
- create an agent class.
- call the interaction loop from that class
- added self.foobar in interaction loop
Remark: the Agent, AIConfig, Config classes overlap a lot and they need to be refactored to give a clear signature of what defines an agent.

wrap infinite loop in class agent

---

scripts/call_ai_function.py

The word `separated` was misspelled.
I fixed it
Not applicable
Not applicable

fix misspelling

---

scripts/execute_code.py

Don't create containers to run python if we're already inside a container
Adds a codepath if it's detected the code is running inside a container
Smoke tested locally

Execute python via shell if already running in a container

---

requirements.txt

dependency was missing.
there is a similar PR but with dockerfile changes.

added selenium dependencies

---

outputs/logs/message-log-3.txt

In this file alone, Entrepreneur-GPT was referred to as Entrepreneur-GTP 65 times. Curious why, as it doesn't seem like a one time mistake/typo. Was referred to as Entrepreneur-GPT in the rest of the project, so FTFY.
n/a
n/a
n/a
n/a

Fix all 65 typos of it being gtp instead of GPT

---

.env.template
README.md
autogpt/config/config.py
autogpt/memory/__init__.py
requirements.txt
scripts/memory/milvus.py

Milvus can be used as a new optional memory backend. It's a open-source software that can be fast deployed by docker or k8s, and there are also commercial solution providers. 
- existing function is not modified.
- add Milvus as a new optional memory backend.
- part of document about memory backend is updated. 
New module and code is full documented.
A use guide about new feature is add to README.md.
- Auto-GPT works properly in milvus memory backend.
- Auto-GPT using local memory works properly too.

enable milvus as memory backend

---

README.md

the new memory seeiding url was wrong
- [🧠 Memory pre-seeding](#-memory-pre-seeding)
the link was broken, I fixed it
I corrected the line [🧠 Memory pre-seeding](#-memory-pre-seeding)
typo fix
click and check

typo in TOC

---

autogpt/agent/agent_manager.py
autogpt/commands/web_requests.py
autogpt/commands/web_selenium.py
autogpt/llm_utils.py
autogpt/processing/text.py

Fix wrong type annotations:
Use Tuple instead of tuple;
Use List instead of List;

update type annotation

---

autogpt/commands/git_operations.py

Fix invalid config import in git_operations

---

.env.template

Just a general typo in .env.template but could be confusing since this typo happens on a command argument.
Fix typo.

Fix typo in .env.template

---

run.bat

Fix run.bat to use the new module

---

autogpt/llm_utils.py

ATM if we get rate limit errors we do nothing with them even in debug mode and that caused me to debbug the program until i saw it so the point is to throw an error log if that happens so users will know why the script fails.
Added one log statement when rate limiting is reached
simple log
ran it and saw that in debug mode it outputs that log. there is no need for tests here

in debug mode add a log about rate limit error

---

README.md

Use correct var name "ELEVENLABS_API_KEY"

Update README.md "ELEVENLABS_API_KEY"

---

requirements-docker.txt
requirements.txt

add tweepy module

---

requirements-docker.txt

Running docker image directly from command line fails; see #1760 . The problem is with an incomplete list of packages present in `requirements-docker.txt`. The packages `gitpython`, `tweepy` and `pymilvus` are needed.
Added `gitpython`, `tweepy` and `pymilvus` to `requirements-docker.txt`.
Behavior documented in #1760; further documentation unnecessary for such a small change restoring expected behavior.
M1 Mac 13.2.1, Docker 4.18.0
On the current master branch, from a zsh shell:
```
docker build -t autogpt .
docker run -it --env-file=./.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt
```
This now successfully runs. Closes #1760.
Additional tests are unnecessary; this PR restores expected behavior.

Added packages necessary to run docker from terminal

---

autogpt/commands/git_operations.py

When cloning the GitHub repository, it easily leads to failure of network errors.
Add the try-exception in the clone_repository function in the git_operations.py file.
When any network errors occur during the cloning of the GitHub repository, the code works.

Catch exception of repository clone

---

.env.template
README.md

Added in missing clarifications and optional method usages in template so players can refer directly from the template.
In env template and README

Add missing clarifications and method usages

---

autogpt/promptgenerator.py

Add a space to the system prompt.

fix: add necessary space to the prompt

---

.github/workflows/dockerhub-imagepush.yml

Workflow action to run on push to stable branch, will build our dockerfile and create and push an image to Docker Hub at https://hub.docker.com/r/significantgravitas/auto-gpt

Create a Docker image on DockerHub on release to stable

---

autogpt/app.py

Previously, there was an issue with the encoding of the search results in the Google search function. The original code used the `encode()` method to convert the search results to UTF-8, which caused errors when using google api and the result is a list.

 Fix google api fetch error

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

In order to foster a positive and inclusive environment for all contributors, we are introducing a Code of Conduct for the auto-gpt project. Additionally, we aim to improve the clarity and usability of the CONTRIBUTING.md file by updating it to a more general format.
- Add **CODE_OF_CONDUCT.md** file to the project, outlining expected behavior and guidelines for contributors.
- Update **CONTRIBUTING.md** with a more general format, making it easier for new contributors to understand and follow the guidelines.
The new Code of Conduct file will be placed in the root directory of the project, while the updated **CONTRIBUTING.md** file will replace the existing one. Both files are written in clear and concise language, making it easy for contributors to understand the guidelines and …

updated contributing docs

---

autogpt/prompt.py

The path of config.save is always `SAVE_FILE = os.path.join(os.path.dirname(__file__), "..", "ai_settings.yaml")`, but the path of config.load is `CFG.ai_settings_file`.
Pass the same path to both `config.save` and `config.load`.

fix: config save and load path inconsistent

---

README.md

Simply Removed a duplicate section of the Milvus Setup in the README.md file as its not needed 2 times
- [ x] My pull request is atomic and focuses on a single change.
- [ x] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes

simply removing a duplicate "Milvus Setup" in the README.md

---

.env.template

Small fix for the TEMPERATURE in commented documentation to show default as 0, the used default value

Fix .env.template documentation, incorrect default value for TEMPERATURE

---

.github/ISSUE_TEMPLATE/1.bug.yml

Add GPT-3 checkbox & emphasize to search for existing issues first.
Auto-GPT is currently receiving a flood of issues, many of which are duplicate, and many are related to the limitations of GPT-3. This might help.
* Emphasized to search for existing issues first
* Added checkbox to indicate whether someone is using GPT-3. Maybe this can also be used to add a label automatically?
No code changes -> no tests.

Improve bug report template

---

autogpt/app.py

With the latest version of Auto-GPT, some google results can fail to parse, citing that 'list' has no 'encode' method.
A list comprehension is used instead of attempting to decode the list directly. This way, all found URLs will be encoded separately.
The line of code seems self-explanatory, but I can add a comment above if needed.
Multiple prompts were tested, all needing different google results.

Fix google result encoding.

---

autogpt/memory/__init__.py

Remove warnings if memory backend is not installed

---

README.md
autogpt/memory/__init__.py

Added new memory backends to supported memory:
* #424
* #801 
Also changed the README to remove the erroneous list of memory backends when explaining the command line arguments.
Appends memory backends to supported memory

Fixed new backends not being added to supported memory

---

run.sh
run_continuous.sh

Add run scripts for shell

---

.github/workflows/ci.yml
tests/local_cache_test.py

Switches CI to pytest
Switches CI to pytest
Switches CI to pytest
Switches CI to pytest - run ci on this branch

Change ci to pytest

---

autogpt/__main__.py
autogpt/agent/agent.py
autogpt/json_validation/validate_json.py
benchmark/benchmark_entrepeneur_gpt_with_difficult_user.py

The self.user_input is important because it contains this:
```
Determine which next command to use, and respond using the format specified above:
```
and it was originally supposed to be the last thing the AI sees, this is why @Significant-Gravitas didn't add it to the master prompt.
Very early on it was wrongfully overwritten, probably because of the confusing name it had (user_input). It was also used to add human feeback. But human feedback can just be added to the message history, it doesn't need to be the last thing the AI sees.
The fact that it was called user_input made people think it was added by the user.
But this is actually one of the most important pieces of AutoGPT.
It turns out users that gave human feedback were actually confusing the AI even more, because it overwrote the …

fix user input being modified

---

README.md

The Demo video is now 2 weeks old as well as very simple. Due to request, a new video has been created.
Replace the existing video as well as the corresponding date.
There is no documentation needed.
I used GitHub's readme preview feature
No tests needed for a README.md alteration

Implement new demo video into README.md

---

autogpt/memory/local.py

Added one space after period for better formatting

---

README.md

Added Credit to README.md Demo

---

autogpt/commands/execute_code.py

- Move comment to correct position
- move comment to correct position

move comment to correct position

---

requirements-docker.txt

got `ModuleNotFoundError: No module named 'jsonschema'`  with docker 
add jsonschema to requirements-docker.txt

add docker requirements - jsonschema

---

autogpt/config/config.py

【fix】config.py format

---

autogpt/memory/local.py

add a missing import
https://github.com/Significant-Gravitas/Auto-GPT/blob/f41febd3ae9242961dc7e940916cd37255abf7f7/autogpt/memory/local.py#L23

fix a missing import

---

autogpt/config/config.py

* OpenAI API Keys link is changed.
* `beta` to `platform`
* This error message is appeared only if API Key is not set.

config.py: update OpenAI link to platform.openai.com

---

.github/PULL_REQUEST_TEMPLATE.md
autogpt/app.py
autogpt/commands/git_operations.py
autogpt/commands/google_search.py
autogpt/llm_utils.py
autogpt/memory/milvus.py
autogpt/setup.py
autogpt/speech/eleven_labs.py
outputs/logs/message-log-1.txt

Found some spelling mistakes throughout the program, so decided fixed them.
Any spelling mistakes I found, I fixed. (Note there may be more, these were just the ones I found)
N/A - No functional changes made
N/A - No functional changes made

Spelling Fixes

---

README.md

fix a typo and update Milvus description for clarity.

docs: update docs around Milvus

---

autogpt/app.py

memory object move to memory_add block

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Provides warning to contributors on PRs that add non-essential commands.
Adds information to `PULL_REQUEST_TEMPLATE.md` and `CONTRIBUTING.md`

Add non-essential warning for contributors

---

.github/ISSUE_TEMPLATE/1.bug.yml

Once last time guys I swear
fixed attr: label location

[Hotfix] bugs template again

---

autogpt/commands/execute_code.py

Looks like things got changed to WORKSPACE_PATH recently and `execute_shell_popen` got left behind. This PR copies this block from `execute_shell`.
Didn't manage to make it try running this call (it keeps thinking in circles :)), but the change looks trivial.

Fix for execute_shell_popen using WORKING_DIRECTORY

---

autogpt/utils.py

Hotfix - Announcement filename was incorrect

---

autogpt/cli.py
autogpt/utils.py

Communicate to the user if they are running Auto-GPT from a branch that we're not supporting (unless --skip-news)
Some less technical users may be running a less-stable version of Auto-GPT without realising - this communicates that.

Print the current Git branch on startup - warn if unsupported

---

.github/workflows/pr-label.yml

Apparently this needs some more permissions (even though the `conflicts` labeler doesn't)
* Added `issues: write` permission to the `size` workflow

fix shirt-sizing workflow permissions

---

.github/workflows/dockerhub-imagepush.yml

Change the trigger to on-release rather than on-push otherwise image will be tagged with wrong (previous) version

Update docker-hub image push action

---

.github/workflows/dockerhub-imagepush.yml

Patch docker hub CI task into Stable

---

.github/workflows/docker-image.yml

Noticed docker-ci doesn't cancel in progress on a new push in a pr, waned to add here
adds concurrency similar to other workflows

Cancel in-progress docker CI on outdate

---

autogpt/commands/file_operations.py

Fix label of `download_file` command

---

README.md

This pull request aims to improve the user experience when configuring API keys in the Auto-GPT project. The changes include clear instructions for accessing hidden files (`.env.template`) in various operating systems and explaining the rationale behind hiding the file.
- Updated the configuration instructions to explain how to reveal hidden files in different operating systems.
> Locate the file named `.env.template` in the main `/Auto-GPT` folder. This file may be hidden by default in some operating systems due to the dot prefix. To reveal hidden files, follow the instructions for your specific operating system (e.g., in Windows, click on the "View" tab in File Explorer and check the "Hidden items" box; in macOS, press `Cmd` + `Shift` + `.`).
The updated instructions are included in the …

add instruction to show .env

---

README.md

The current plugin installation instructions in the Auto-GPT README.md may lead users to simply download the plugin as a Zip file and place it in the plugin folder. This often results in errors when executing Auto-GPT due to missing dependencies. This PR aims to address this issue by providing clearer and more comprehensive plugin installation instructions.
- Updated the plugin installation section in the README.md to include steps for cloning the plugin repository, installing dependencies, and packaging the plugin as a Zip file.
- Improved the overall structure and text of the plugin installation section for better readability and comprehension.
The changes are documented directly in the updated README.md file.
N/A (Documentation change only)

Improve plugin section in README.md to prevent dependency errors

---

.github/ISSUE_TEMPLATE/1.bug.yml

Sometimes users report issues that occurred on stable or latest release branches.
* Added a drop-down box to the template to ask the user for which version they are using.

Added version select to bug template

---

autogpt/config/config.py

Changes in .env might not be loaded. 
E.g updating ELEVELABS keys might not be loaded, and developers are getting errors while not understanding why
In config.py make `load_dotenv(..., override=True)`
`test_congif.py` passes

Make config load and override for every new run

---

.github/ISSUE_TEMPLATE/1.bug.yml

fix indentation of bug template yml

---

README.md

modify snippet in README
README seems outdated
update example for `IMAGE_PROVIDER`
`sd` does not exists in [image_gen.py](https://github.com/Significant-Gravitas/Auto-GPT/blob/6c5d21cbfc4b649bcdab13d6e3bb898bfd2e6576/autogpt/commands/image_gen.py#L18)

Update README.md ( `IMAGE_PROVIDER=sd`=> `IMAGE_PROVIDER=huggingface` )

---

README.md

No tests have been added as this contribution is only a slight modification to the README.

Update readme to more clearly describe usage between platforms

---

tests/milvus_memory_test.py

The 'err' variable in the except block is an instance of the ImportError class.
Adds console logs detail.

[feat] Update milvus_memory_test.py error log

---

README.md

Fixing some typos in README
Didier

Documentation: fixing typos in README.md

---

README.md

The `README.md` doesn't include steps to setup Eleven Labs speech, but does include steps for memory backend setup, so wanted to keep it consistent and easy to setup.
Update `README.md` with steps to setup with Eleven Labs for `speak` option 
n/a
n/a

Update README to include Eleven Labs speech setup

---

CONTRIBUTING.md

Fixing header of CONTRIBUTING.md

---

autogpt/speech/brian.py

This commit replaces two print statements in the _speech method of the BrianSpeech class with a single call to logging.error. This will log error messages with more detail and make it easier to diagnose issues. The changes are backward compatible and should not affect the functionality of the code.

Replace print statements with logging.error

---

.github/workflows/benchmark.yml
benchmark/benchmark_entrepreneur_gpt_with_difficult_user.py

misc: fix typo in benchmark

---

autogpt/plugins.py

The debug line saying 
Module '__init__.py' not found in the zipfile @ plugins\plugin.zip.
Would always be printed, regardless of loading success

Plugins: debug line always printed in plugin load

---

docs/installation.md

Add note for windows install

---

autogpt/prompts/generator.py

Typo in prompt which may affect json performance

Fix to prompt generator - "Ensure the response can beparsed"

---

tests/unit/test_setup.py

Add missing test decorator

---

autogpt/memory/weaviate.py

File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/weaviate/schema/crud_schema.py", line 708, in _create_class_with_primitives
raise UnexpectedStatusCodeException("Create class", response)
weaviate.exceptions.UnexpectedStatusCodeException: Create class! Unexpected status code: 422, with response body: {'error': [{'message': "'Auto-gpt' is not a valid class name"}]}.
GPT4:
The error message indicates that "Auto-gpt" is not a valid class name. In Weaviate, class names must start with a capital letter and can contain only alphanumeric characters.
Took advice and code and applying to weaviate.py to great result, programs runs now with no error!
Unable to reproduce easily. Might be related to switching memory between Local and Weaviate? Either way, the …

update weaviate.py for weaviate compatibility

---

docs/configuration/memory.md

Documentation: fixing typos

---

docs/configuration/voice.md

auto gpt -> Auto-GPT to ensure naming consistency on the page

Documentation: ensuring naming consistency

---

.github/workflows/documentation.yml

update documentation deploy gh action

---

.env.template
autogpt/config/config.py
autogpt/memory/__init__.py
autogpt/memory/milvus.py
docs/configuration/memory.md

I found that someone encounter some problem when using milvus as memory backend with zilliz cloud.
This PR will make easier to interact with zilliz cloud.
#1812 
- add zilliz cloud to milvus memory backend implement.
- add document to readme.
- new feature and code is full documented.
- no error occur when using the open-source milvus as memory backend.
- no error occur when using the zilliz cloud as memory backend.

Support secure and authenticated Milvus memory backends

---

autogpt/memory/local.py

Update comment to clarify that the function clears data from memory instead of Redis.

Fixed incorrect comment: Clear memory instead of Redis

---

autogpt/app.py
autogpt/prompts/prompt.py

Auto-GPT frequently chooses the do_nothing command with no clear indication as to why #830
This pull request adds an argument, `reason` to the do_nothing command. Auto-GPT will populate the argument with an explanation why the do_nothing command was chosen.
Documented in code.
Ran Auto-GPT. Command arg was utilized.

Add <reason> arg to do_nothing command

---

autogpt/cli.py
autogpt/main.py
autogpt/plugins.py
scripts/install_plugin_deps.py

Install plugin deps script is currently a standalone script in the `scripts` directory. This adds it to the CLI.
Updated the CLI to include an optional `--install-plugin-deps` parameter that installs plugin dependencies during runtime.
You can run it with either:
```
$ ./run.sh --install-plugin-deps
```
Or:
```
$ python -m autogpt --install-plugin-deps
````

Re-add install-plugin-deps to CLI

---

BULLETIN.md

The twitter command 'send_tweet' is Deprecated, as the functionality is covered under the Twitter plugin within the Auto-GPT-Plugins repo.
Updated BULLETIN.MD
Self Documenting 😉
Opened preview in VSCode, deployment pipeline untested(but would be good to clone this repo and run to see if the warning pops up)

Bulletin patch - Updating 'BULLETIN.MD' to warn about the deprecation of baked-in 'send_tweet' command

---

docs/installation.md

Add a little more descriptive installation instruction

---

docs/configuration/imagegen.md

docs fix to image generation

---

autogpt/agent/agent.py
tests/unit/test_get_self_feedback.py

unit test agent feedback

---

CONTRIBUTING.md

> ⚠️ Plugin support is expected to ship within the week. You can follow PR #757 for more updates!
This is outdated and should be removed
Remove that notice

Remove plugin notice from CONTRIBUTING.md

---

README.md

Fix readme centering

---

autogpt/llm_utils.py

My short term goal is to make the config serializable so we can dump it to generate crash reports.  I'm trying to do this sanely by removing import time side effects and global state manipulation in the particular window when the application starts and the configuration is generated for the first time.  This is on my critical path as `configurator` imports `get_supported_memory_backends` which imports memory modules which import `llm_utils`.  
- Load configuration in `llm_utils` at runtime instead of import time.
N/A
Ran test suite and manual application runs.

Remove import time loading of config from llm_utils

---

autogpt/llm_utils.py

Fix `get_ada_embedding` return type

---

docs/configuration/search.md
docs/installation.md
docs/usage.md

Documentation (especially code blocks and list-items) were not formatted correctly for mkdocs's markdown style.

Fix docs alignment

---

autogpt/workspace/workspace.py

Bills workspace is broken again
* Resolve workspace root as well before checking path relativity
Yay CI

Fix(workspace) root resolution

---

autogpt/agent/agent.py
autogpt/app.py
autogpt/prompts/generator.py
autogpt/prompts/prompt.py
tests/integration/goal_oriented/cassettes/test_write_file/test_write_file.yaml

The  do nothing was added because https://github.com/Significant-Gravitas/Auto-GPT/issues/830
since then, a lot of improvements on the prompt happened. We should give it a shot.
Also we have "Exclusively use the commands listed in double quotes" in the prompt.
removed do_nothing from the possible commands the agent can do.
I ran an agent for 100 cycle and it didn't do_nothing once

Remove do_nothing (Do nothing)

---

CONTRIBUTING.md
docs/configuration/voice.md
docs/setup.md

* Fixed a broken link in the contribution guide
* Clarified how we use cassettes in tests
* Removed duplicate info block about ElevenLabs config
Preview: https://docs-git-fork-pwuts-docs-clarify-vcr-and-voice-config-auto-gpt.vercel.app/

Minor improvements to the docs for voice config and testing

---

docs/index.md

Update broken link

---

README.md

Fix README: remove redundant "Disclaimer"

---

tests/test_config.py

we are moving away from using the `unittests` library in favor of using pytest
only changed the test_config.py test case
dropped unittest in favor of pytest
not necessary
running `pytest` as usual

Removing unitest in favor of pytest from test_config.py

---

autogpt/commands/web_selenium.py
tests/unit/test_web_selenium.py

Addresses #3401 
- Catches browser errors and truncates them to a sane length
- Returns an error msg instead of raising an error to allow the agent to recover and try something else.
inline comment
Added a unit test specifically for the error.

More graceful browsing error handling

---

docs/testing.md

fix typo in testing.md

---

autogpt/logs.py
autogpt/main.py

Due to some refactoring in https://github.com/Significant-Gravitas/Auto-GPT/pull/3488
the send chat message method was deleted.
Added report method into typewriter_log method.
Loading plugins capable of report method into logger.
When chat_messages_enabled is True, then the plugins are searched for a plugin that can handle reports.
Those reports are then called from within the typewriter_log method to enable an external user interface such as the existing telegram plugin.
Tested working.

add report method to typewriter_log & load report plugins into logger

---

CONTRIBUTING.md
README.md
autogpt/llm/llm_utils.py
docs/index.md
mkdocs.yml

New website was launched, with docs at `docs.agpt.co`

Update documentation URLs to docs.agpt.co

---

autogpt/core/workspace/base.py

Interface definition for the Agent  workspace class.
I am thinking of the agent workspace as simply a path management tool, as that is how it is abstracted in the current system.  We could also build some kind of `WorkspaceResource` abstraction that hides path management entirely from the Agent (which may be safer.  This is also a pivot we can make later.
New base class for workspaces
Typing and docstrings provided for all public methods.
Peer review

Set up the workspace base class

---

docs/challenges/information_retrieval/challenge_a.md
docs/challenges/information_retrieval/introduction.md
mkdocs.yml

Wiki for information retrieval challenge A

add information retrieval challenge to the wiki

---

autogpt/core/logging/base.py

Rearch: logging interface

---

.github/CODEOWNERS

add code owners policy

---

docs/challenges/memory/challenge_c.md
mkdocs.yml
tests/integration/challenges/memory/cassettes/test_memory_challenge_c/test_memory_challenge_c.yaml
tests/integration/challenges/memory/test_memory_challenge_c.py

Memory Challenge C

---

docs/challenges/memory/challenge_c.md
tests/integration/challenges/memory/test_memory_challenge_c.py

memory challenge c cassette is inconsistent

---

docs/challenges/memory/challenge_b.md
docs/challenges/memory/challenge_c.md

Improve wording on the documentation, fix the command examples of memory challenge A and B 
Improve wording on the documentation, fix the command examples of memory challenge A and B 
the change is on the documentation itself, correction of the command example

Fix for Memory Challenge B & C Documentations

---

autogpt/llm/chat.py

Fixed the issue #4003  - an exception was being thrown due to an incorrect reference to the `prompt_generator` property. The issue was causing the agent to fail during plugin handling in the planning phase.
A small change in `autogpt/llm/chat.py`:
```diff
- agent.prompt_generator, current_context
+ agent.config.prompt_generator, current_context
```

Use correct reference to prompt_generator in autogpt/llm/chat.py

---

docs/setup.md

fix typo in the getting started docs

---

docs/setup.md

I've tried using Auto-GPT for the first time, and noticed that the workspace directory in the suggested `docker-compose.yml` file in the docs is incorrect, so I fixed it :)

Fix path to workspace directory in setup guide

---

docker-compose.yml
docs/setup.md

non-code PR - document the required version of docker-compose for 3.9 of the docker-compose.yml to be supported

document that docker-compose 1.29.0 is minimally required

---

autogpt/core/budget/base.py

This PR contains revisions to the BudgetManager base class as it's integrated into the hello world application described in #3969

Revise budget manager

---

.env.template

trivial non-code / config only change (only adding comment)
as per https://github.com/Significant-Gravitas/Auto-GPT/issues/1994#issuecomment-1535711402

explain temperature setting in env file

---

requirements.txt

https://github.com/deedy5/duckduckgo_search/blob/main/README.md
According to readme in duckduckgo_search repo:
**Attention. Versions before v2.9.4 no longer work as of May 12, 2023!**
With 2.9.4 or earlier you get empty list of results. By updating you get it working again. This is only when autogpt falls back to duckduckgo when trying to do a google search.
Adding this to requirements.txt
No need for docs
No need for test

Update duckduckgo dependency - min should be 2.9.5

---

autogpt/memory/pinecone.py
autogpt/memory/redismem.py

Small fix to Github links that should be updated - https://github.com/Significant-Gravitas/Auto-GPT/issues/3828
Updated the links.

Updated memory setup links

---

scripts/check_requirements.py

We need to be able to push package versions. Example: https://github.com/Significant-Gravitas/Auto-GPT/pull/4142
Reworked check_requirements.py to check for min and max version

Parse package versions so upgrades can be forced

---

.github/workflows/ci.yml
autogpt/prompts/prompt.py

Introduce dummy change to see if the CI makes the calls to OPEN AI

test new CI

---

.github/workflows/ci.yml
autogpt/llm/llm_utils.py
autogpt/prompts/prompt.py

Test new CI pipeline with dummy prompt change

Test New CI Pipeline

---

.github/workflows/ci.yml
autogpt/prompts/prompt.py

the CI pipeline consumes doubles the tokens just because we want to test python 3.11.
We already have a Docker CI that tests 3.11, it's no the end of the world if we stop temporarily 3.11.
It will also reduce rate limiting from openAI.

Feature/fix rate limiting issue Step 1

---

.github/workflows/ci.yml

Put back 3.11 until it's removed as a requirement

---

.github/workflows/ci.yml

Reverts Significant-Gravitas/Auto-GPT#4185

Revert "Put back 3.11 until it's removed as a requirement"

---

autogpt/commands/execute_code.py

… one of the more common questions on github

Improve error message by providing the name of the env file

---

.github/workflows/ci.yml

test prompt change ci (ignore: draft)

test prompt change ci (ignore: draft)

---

.github/workflows/ci.yml

We need to stop creating a separate pull request to commit cassettes.
Instead let's just commit to the current branch of the fork, a suggested by @ntindle.
- added a placeholder step to beat new challenges (very excited about this, this is coming soon !)
- added the autocommit step + a message to inform our users !

Cassettes should be added in the same pull request, without extra pull request

---

.github/workflows/ci.yml
tests/integration/agent_factory.py

set base repo was missing: 
TESTED HERE => https://github.com/Significant-Gravitas/Auto-GPT/pull/4362

CI: set base repo before `gh pr checkout`

---

.github/workflows/sync-submodule.yml

Ci test 22

---

prompt_settings.yaml

Ci test 44

---

autogpt/url_utils/validators.py
tests/unit/test_url_validation.py

Added three more tests to check for edge cases in URL validation

---

docs/challenges/building_challenges.md
tests/integration/agent_factory.py
tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_a.py
tests/integration/challenges/kubernetes/test_kubernetes_template_challenge_a.py
tests/integration/challenges/utils.py
tests/vcr/vcr_filter.py

The information retrieval challenge was missing the task_statuses and google search to pass
- add google search
- add task_statuses
After that we will create a slightly harder because I help a lot in the prompting, by anticipating all the common mistakes AutoGPT does (not using the right commands for example)

Fix Information Retrieval Challenge

---

tests/integration/challenges/current_score.json

Master is in this weird state where it's almost beating challenge b level 1 reliably, but not quiet there yet.
Sometimes it thinks the id is the noise.
We have to downgrade the current_score.json
```shell
black .
isort .
mypy
```

Master doesn't beat memory challenge b level 1 in a consistent manner

---

.github/workflows/ci.yml

Replace the wording prompt change with behavior change
```shell
black .
isort .
mypy
```

Replace 'prompt change' with 'behavior change'

---

.github/workflows/ci.yml
tests/integration/challenges/challenge_decorator/challenge.py
tests/integration/challenges/challenge_decorator/challenge_decorator.py
tests/integration/challenges/challenge_decorator/challenge_utils.py

The current_score.json is automatically rebuilt everytime we run the challenges. It will automatically reflect the tests.
For example, if there are new challenges. It will automatically add them.
- Built the current_score.json at the end of pytest.
- Change ci.yml to push current_score.json
- allow new challenges to not be skipped.
```shell
black .
isort .
mypy
```

Update current score when PR merged

---

autogpt/main.py
docs/challenges/information_retrieval/challenge_a.md
tests/integration/agent_factory.py
tests/integration/challenges/challenge_decorator/challenge_decorator.py
tests/integration/challenges/current_score.json
tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_a.py

If we make an existing regression challenge harder we expand the circle that defines what AutoGPT can do. This means existing challenges cover more capabilities.
Now the information retrieval challenge has the same default commands as someone that runs AutoGPT without precising any commands.
- goal shorter and gives less hints
- level 2 and level 3 created 
```shell
black .
isort .
mypy
```

Increase difficulty of the "information retrieval" challenge and add a new level

---

.env.template
autogpt/config/config.py

Adding support for openai_organization env variable

---

tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_b.py

```shell
black .
isort .
mypy
```

Ci test (draft)

---

.github/workflows/ci.yml
.gitmodules
tests/integration/agent_factory.py
tests/integration/challenges/basic_abilities/test_browse_website.py
tests/integration/challenges/basic_abilities/test_write_file.py
tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_a.py
tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_b.py
tests/integration/challenges/kubernetes/test_kubernetes_template_challenge_a.py
tests/integration/challenges/memory/test_memory_challenge_a.py
tests/integration/challenges/memory/test_memory_challenge_b.py
tests/integration/challenges/memory/test_memory_challenge_c.py
tests/integration/memory/test_json_file_memory.py

CI test (draft, ignore)

---

.github/workflows/ci.yml

Set proxy headers as secrets, already tested successfully.
```shell
black .
isort .
mypy
```

Set proxy headers as secrets

---

tests/challenges/current_score.json

The challenge is flaky, we will discuss about next steps for challenges in general.
```shell
black .
isort .
mypy
```

Decrement information retrieval challenge a so that it doesn't break the CI

---

tests/challenges/current_score.json

It's a flaky challenge.
```shell
black .
isort .
mypy
```

Decrement memory challenge c

---

autogpt/agent/agent.py
autogpt/llm/chat.py
autogpt/main.py
autogpt/memory/message_history.py
tests/integration/agent_factory.py
tests/unit/test_agent.py
tests/unit/test_get_self_feedback.py

We should be able to get the config object out of the agent. It shouldn't be instantiating its own config object. The previous `config` attribute was actually `ai_config` and that is very confusing.
- Rename `Agent.config` to `Agent.ai_config`
- Add `Agent.config` which is an actual `Config` object
- Change necessary references
```shell
black .
isort .
mypy
```

Add config as attribute to Agent, rename old config to ai_config

---

.github/workflows/benchmarks.yml
tests/challenges/challenge_decorator/challenge_decorator.py
tests/challenges/memory/test_memory_challenge_d.py

We want benchmarks to run regularly.
For now the benchmarks will run the regression tests and the unbeaten challenges 1 level above.
added benchmarks.yml:
- triggerable manually
- runs every day 8 AM UTC
- uploads cassettes and logs as artifacts
- runs regression tests (Mandatory Tasks)
- runs unbeaten challenges (Challenging Tasks)
Some cleanup with the challenge decorator.
```shell
black .
isort .
mypy
```

Create benchmarks that will run Regression Tests and unbeaten challenges

---

requirements.txt
tests/challenges/basic_abilities/test_browse_website.py
tests/challenges/basic_abilities/test_write_file.py
tests/challenges/challenge_decorator/challenge_decorator.py
tests/challenges/debug_code/test_debug_code_challenge_a.py
tests/challenges/information_retrieval/test_information_retrieval_challenge_a.py
tests/challenges/information_retrieval/test_information_retrieval_challenge_b.py
tests/challenges/kubernetes/test_kubernetes_template_challenge_a.py
tests/challenges/memory/test_memory_challenge_a.py
tests/challenges/memory/test_memory_challenge_b.py
tests/challenges/memory/test_memory_challenge_c.py
tests/challenges/memory/test_memory_challenge_d.py

Regression tests are tests we assume always pass. But this is only an assumption. We need a process in order to not waste our time on them.
Process: 
- the benchmarks runs every day and will catch the flaky regression tests
- while these regression tests are "fixed", the CI pipeline will still pass because we retry the tests
- we apply the fix
- done, everyone happy, no time wasted
- added flaky library to challenges
- refactored decorator to reduce code
```shell
black .
isort .
mypy
```

Retry regression tests

---

autogpt/memory/message_history.py
tests/unit/test_message_history.py

This pull request introduces a new approach to managing the context length when calling the chat completion API to get a running message of previous events in the MessageHistory class. The improvements include processing new events in batches and summarizing them before appending to the existing summary. These changes aim to address the issue where the context length exceeds the model's maximum token limit (4097 tokens for gpt-3.5-turbo).
1. Batch Processing of New Events in **update_running_summary** function: To manage the context length and avoid exceeding the maximum token limit, new events are now processed in batches. Each batch's size is determined by the token length limit of the language model. This ensures that the length of the context stays within the allowable limit, avoiding …

Implement Batch Summarization in MessageHistory Class to manage context length under model's token limit

---

.github/workflows/benchmarks.yml
tests/challenges/memory/test_memory_challenge_c.py

Sometimes the LLM would write the sentences of the memory challenge c but without a .
the matrix in the benchmark doesn't work with ["3.10"] as an array
- removed a python version as array in benchmark.yml
- removed the dot in challenge sentences
- added more noise, so that we can test for regression of this fix: https://github.com/Significant-Gravitas/Auto-GPT/pull/4652
```shell
black .
isort .
mypy
```

Change memory challenge c expectations

---

netlify.toml

Because of scale issues with Vercel, we are moving to Netlify.
* Add netlify.toml with basic settings for deploying the docs
x
We'll see

Add basic Netlify config

---

autogpt/agent/agent.py
autogpt/app.py
autogpt/command_decorator.py
autogpt/commands/analyze_code.py
autogpt/commands/audio_text.py
autogpt/commands/execute_code.py
autogpt/commands/file_operations.py
autogpt/commands/git_operations.py
autogpt/commands/google_search.py
autogpt/commands/image_gen.py
autogpt/commands/improve_code.py
autogpt/commands/task_statuses.py
autogpt/commands/web_selenium.py
autogpt/commands/write_tests.py
autogpt/config/ai_config.py
autogpt/main.py
autogpt/models/command.py
autogpt/models/command_registry.py
autogpt/prompts/generator.py
tests/conftest.py
tests/integration/agent_factory.py
tests/mocks/mock_commands.py
tests/unit/test_commands.py

Pulling out a change from #4683 to make that diff smaller.
This just moves around code related to commands so that it's easier to work with. No functionality change.

Refactor module layout of command classes

---

autogpt/json_utils/utilities.py
autogpt/memory/message_history.py

The method now used to check if a string is a valid JSON is :extract_json_from_response, not is_string_valid_json
Because of the wrong method being used, the per_cycle method wasn't working and we would summarize the context window prematurely
The method now used to check if a string is a valid JSON is :extract_json_from_response
Use extract_json_from_response instead of is_string_valid_json
```shell
black .
isort .
mypy
```

Fix summarization happening in first cycle

---

BULLETIN.md
pyproject.toml

Bulletin.md update for 0.4.1 release

Bulletin.md update for 0.4.1 release

---

autogpt/agent/agent.py
autogpt/app.py
tests/unit/test_execute_command.py

Fix execute_command coming from plugins in 0.4.1

---

autogpt/core/ability/builtins/file_operations.py

Adds support for the File Write Ability to the Re-Arch
Adds support for the File Write Ability to the Re-Arch
```shell
black .
isort .
mypy
```

[re-arch] Ability: Write File

---

autogpt/llm/utils/__init__.py

(cherry-picked from commit 244393e4ef4ee47d84b18958c2467a149c0201f5)
Redoing commit clobbered during commit eb2410ac6ca76ad769c9d67c05334fa39601163a ("Merge remote-tracking branch 'upstream/master' into Release-v0.4.1")

Add fallback token limit in llm.utils.create_chat_completion

---

autogpt/core/ability/builtins/file_operations.py
autogpt/core/ability/schema.py

```shell
black .
isort .
mypy
```

Add default value for new_knowledge

---

autogpt/core/ability/builtins/file_operations.py
autogpt/core/ability/schema.py

```shell
black .
isort .
mypy
```

Update existing abilities to return all fields in the AbilityResult

---

config.json

Signed-off-by: Merwane Hamadi <merwanehamadi@gmail.com>
```shell
black .
isort .
mypy
```

Update config for benchmark changes

---

autogpt/utils.py

The signal handler in the autogpt/main.py doesn't work properly because of the clean_input(...) func. 
The issue is mentioned in
https://github.com/Significant-Gravitas/Auto-GPT/pull/4799/files/3966cdfd694c2a80c0333823c3bc3da090f85ed3#r1264278776
This commit fixes the root cause of the issue by disabling some other sigint handler inside clean_input(...) func.
The reason for such a change is provided in the code as a comment.
Manually tested before and after the change, everything works as expected.
```shell
black .
isort .
mypy
```

hot fix the SIGINT handler

---

BULLETIN.md
autogpt/config/config.py
pyproject.toml

Update BULLETIN.md and version numbers for 0.4.5

Update BULLETIN.md and version numbers

---

autogpt/agents/__init__.py
autogpt/main.py
autogpt/spinner.py
tests/unit/test_spinner.py

The SIGINT handler does not work in master, unfortunately.  #4997 partially addressed this issue, but did not completely resolve the problem.
- Expose `CommandName`, `CommandArgs`, and `AgentThoughts` for use in typing in the application code.
- Add `start` and `stop` methods to the `Spinner` so we can use it in a non-context manager setting.  This allows us to pause the UI spinning, send a message to the user, and then resume the UI spinning.  Otherwise anything logged in the SIGINT handler gets garbled by the Spinner execution.
- Pull the user update functionality into an `update_user` function.  
- Pull the user input functionality into a `get_user_feedback` function.  Use an enum for feedback types.
- Fix the cycle budget logic.  
Docstrings and comments.
A bunch of manual testing. …

Update the sigint handler to be smart enough to actually work

---

BULLETIN.md
autogpt/config/config.py
pyproject.toml

Merging v0.4.5 into master

---

.gitignore
BULLETIN.md
docs/configuration/memory.md
pyproject.toml

Bulleting update & version bump

Bulleting update & version bump

---

.gitignore
BULLETIN.md
docs/configuration/memory.md
pyproject.toml

Sync release into master

---

autogpt/speech/stream_elements_speech.py

```shell
black .
isort .
mypy
```

Fixed stream elements speech function

---

.github/workflows/benchmark-ci.yml
benchmark/agents_to_benchmark.json

Now all the agents in agent_to_benchmark.json will be benchmarkable. Maintainers of the repo will be able to benchmark their agent by triggering a manual CI run.

Benchmark all agents

---

forge/forge/__main__.py
forge/forge/agent.py

Fix forgeAgent class

---

frontend/README.md

Update Readme Flutter

---

benchmark/agbenchmark/__main__.py
benchmark/agbenchmark/agent_api_interface.py
benchmark/agbenchmark/conftest.py
benchmark/agbenchmark/utils/challenge.py
benchmark/agbenchmark/utils/data_types.py
benchmark/agbenchmark_config/config.json

Fix API Mode

---

benchmark/agbenchmark/agent_api_interface.py
benchmark/agent_protocol_client/api/agent_api.py
benchmark/agent_protocol_client/models/__init__.py
benchmark/agent_protocol_client/models/artifacts.py
benchmark/agent_protocol_client/models/pagination.py

Fix SDK client

---

frontend/README.md

Update frontend readme

---

.github/workflows/autogpts-ci.yml
autogpts/forge/run
autogpts/forge/run_agent.sh

CI parameterized for all the autogpts in the autogpts folder

Autogpts ci unified for the hackathon

---

autogpts/forge/integrations/README.md

Add integrations to the forge

---

benchmark/agbenchmark/app.py

Fix CORS issue

---

autogpts/forge/run

Add command to reset environments

---

.github/workflows/benchmark_publish_package.yml

Update CI to release agbenchmark to pypi

---

.github/workflows/benchmark_publish_package.yml

Add working directory to agbenchmark pipy CI

---

benchmark/pyproject.toml

Update version to 0.0.10

---

.github/workflows/benchmark_publish_package.yml

Update CI pipy

---

.github/workflows/autogpts-ci.yml
.github/workflows/benchmark-ci.yml
autogpts/forge/README.md
autogpts/forge/run_benchmark.sh
benchmark/agbenchmark/README.md
benchmark/agbenchmark/__main__.py
benchmark/agbenchmark/challenges/CHALLENGE.md
docs/content/challenges/introduction.md

Remove start from agbenchmark

---

autogpts/forge/forge/__main__.py
autogpts/forge/forge/sdk/agent.py
cli.py
frontend/build.sh
frontend/lib/main.dart
frontend/lib/views/task/api_base_url_field.dart

To simplify the running process I'm building the flutter project then serving if using the forge's agent server
- added flutter build script
- added static directory to server the build frontend from the agent server
- moved the agent server api to be prefixed with /api/v1/
- updated the cli to run the build script before starting the agent
- updated the flutter project to take into account the new endpoints

Serving frontend from the forge agent server

---

QUICKSTART.md

Update quick start

---

frontend/lib/viewmodels/skill_tree_viewmodel.dart

The SkillTreeViewModel initially used a simple reversed node hierarchy list to guide the benchmarking process. To improve the robustness and maintainability of the code, a new data structure, `benchmarkStatusList`, is introduced. This structure will hold each node along with its benchmark status, allowing for more granular control and reporting of benchmark execution.
- Introduced `benchmarkStatusList`, a List of tuples containing a `SkillTreeNode` and a boolean flag indicating the success status of the benchmark associated with that node.
- Modified `runBenchmark` to populate and utilize `benchmarkStatusList` instead of the reversed node hierarchy list.
- Updated `runBenchmark` to read the "success" field from the `evaluationResponse` to update the benchmark status in …

Enhance SkillTreeViewModel to Manage Benchmark Status

---

autogpts/forge/run

Fix forge not being an autogpt anymore

---

frontend/build/web/flutter_service_worker.js
frontend/build/web/index.html

Update frontend build

---

benchmark/agbenchmark/challenges/verticals/scrape/2_book_price/data.json
benchmark/agbenchmark/utils/dependencies/graphs.py
benchmark/frontend/public/graph.json
benchmark/tests/test_get_roots.py
benchmark/tests/test_is_circular.py
frontend/assets/general_tree_structure.json
frontend/assets/tree_structure.json

Validate graph is not circular and the graph should have only one root.

Validate skill tree so the UI never breaks

---

arena/WeatherInformer.json

- **Agent Name:** WeatherInformer
- **Repository Link:** [colour-me-bibi/Auto-GPT](https://github.com/colour-me-bibi/Auto-GPT) …

WeatherInformer entering the arena

---

arena/QA_AGENT.json

- **Agent Name:** QA_AGENT
- **Repository Link:** [ada-lovecraft/Ada-GPT](https://github.com/ada-lovecraft/Ada-GPT) …

QA_AGENT entering the arena

---

arena/uply.json

- **Agent Name:** uply
- **Repository Link:** [uply23333/Uply-GPT](https://github.com/uply23333/Uply-GPT) …

uply entering the arena

---

arena/YoutubePost_agent.json

- **Agent Name:** YoutubePost_agent
- **Repository Link:** [ramirez3rg/Auto-GPT](https://github.com/ramirez3rg/Auto-GPT) …

YoutubePost_agent entering the arena

---

arena/Portalen.json

- **Agent Name:** Portalen
- **Repository Link:** [erlendjones/AutoGPT](https://github.com/erlendjones/AutoGPT) …

Portalen entering the arena

---

arena/Eduardo.json

Eduardo entering the arena

---

arena/webagent.json

webagent entering the arena

---

arena/Job_GPT.json

Job_GPT entering the arena

---

arena/evo.json

- **Agent Name:** evo
- **Team Members:** [@abdllahdev (Software Engineer), @Zanzofily (Software Engineer)]
- **Repository Link:** [abdllahdev/evo](https://github.com/abdllahdev/evo)
- **Starting Point:** We are building from scratch.
- **Why this Prize:** (We'd love to know why this prize feels like the right …

evo entering the arena

---

arena/AgGPT.json

- **Agent Name:** AgGPT
- **Repository Link:** [althaf004/AutoGPT](https://github.com/althaf004/AutoGPT) …

AgGPT entering the arena

---

ai_settings.yaml
arena/evlyn.json

- **Agent Name:** evlyn
- **Repository Link:** [TimothyZhang/AutoGPT](https://github.com/TimothyZhang/AutoGPT) …

evlyn entering the arena

---

arena/AskOpie.json

- **Agent Name:** AskOpie
- **Repository Link:** [arunqa/AutoGPT](https://github.com/arunqa/AutoGPT)
- …

AskOpie entering the arena

---

arena/northfork.json

- **Agent Name:** northfork
- **Repository Link:** [Sewen/AutoGPT](https://github.com/Sewen/AutoGPT)
- …

northfork entering the arena

---

arena/bot.json

- **Agent Name:** bot
- **Repository Link:** [Sampson2016/AutoGPT](https://github.com/Sampson2016/AutoGPT) …

bot entering the arena

---

arena/sql.json

- **Agent Name:** sql
- **Repository Link:** [monsterooo/AutoGPT](https://github.com/monsterooo/AutoGPT) …

sql entering the arena

---

arena/potato.json

potato entering the arena

---

arena/pipeline.json

- **Agent Name:** pipeline
- **Repository Link:** [geesugar/AutoGPT](https://github.com/geesugar/AutoGPT) …

pipeline entering the arena

---

arena/ghostcoder.json

- **Agent Name:** ghostcoder
- **Repository Link:** [aorwall/AutoGPT](https://github.com/aorwall/AutoGPT) …

ghostcoder entering the arena

---

arena/fuzz_gen.json

- **Agent Name:** fuzz_gen
- **Repository Link:** [stplaydog/AutoGPT](https://github.com/stplaydog/AutoGPT) …

fuzz_gen entering the arena

---

arena/tdev.json

tdev entering the arena

---

arena/JoshAgent1.json

- **Agent Name:** JoshAgent1
- **Repository Link:** [joshyorko/AutoGPT](https://github.com/joshyorko/AutoGPT) …

JoshAgent1 entering the arena

---

arena/EnglishTestpaperAgent.json

- **Agent Name:** EnglishTestpaperAgent
- **Repository Link:** [kyannai/AutoGPT](https://github.com/kyannai/AutoGPT) …

EnglishTestpaperAgent entering the arena

---

.gitignore
arena/Granger.json

- **Agent Name:** Granger
- **Repository Link:** [balloch/AutoGPTProblemSolver](https://github.com/balloch/AutoGPTProblemSolver) …

Granger entering the arena

---

arena/Stragegy_Steve.json

- **Agent Name:** Stragegy_Steve
- **Repository Link:** [talumo/AutoGPT](https://github.com/talumo/AutoGPT) …

Stragegy_Steve entering the arena

---

arena/RandomVampirePictureBot.json

- **Agent Name:** RandomVampirePictureBot
- **Repository Link:** [KleinerCodeDrago/AutoGPT](https://github.com/KleinerCodeDrago/AutoGPT)
- **Target Prize:** (Which prize caught your eye? …

RandomVampirePictureBot entering the arena

---

arena/monthly_summary.json

- **Agent Name:** monthly_summary
- **Repository Link:** [corpetty/AutoGPT](https://github.com/corpetty/AutoGPT) …

monthly_summary entering the arena

---

arena/gpt-eng-forge.json

- **Agent Name:** gpt-eng-forge
- **Repository Link:** [pbharrin/AutoGPT](https://github.com/pbharrin/AutoGPT) …

gpt-eng-forge entering the arena

---

QUICKSTART.md

Fix typo in QUICKSTART.md

---

arena/gen_fuzz.json

- **Agent Name:** gen_fuzz
- **Repository Link:** [stplaydog/AutoGPT](https://github.com/stplaydog/AutoGPT) …

gen_fuzz entering the arena

---

arena/SmartGPT.json

SmartGPT entering the arena

---

arena/Yutan_agent.json

- **Agent Name:** Yutan_agent
- **Team Members:** Yutan, Wei
- **Repository Link:** [zyt329/AutoGPT](https://github.com/zyt329/AutoGPT)
- **Starting Point:** Still trying to figure out!
- **Preliminary Ideas:** Building an agent that can take the .tex file that complies with a scientific journal and the template .tex file from a new journal (and perhaps also description from that new journal), then auto-convert the .tex file to be compliant with the format of the new journal.
- **Target Prize:** Just try …

Yutan_agent entering the arena

---

arena/DavidsAgent.json

- **Agent Name:** DavidsAgent
- **Repository Link:** [beisdog/AutoGPT](https://github.com/beisdog/AutoGPT) …

DavidsAgent entering the arena

---

arena/HekolcuAutoGPT.json

- **Agent Name:** HekolcuAutoGPT
- **Repository Link:** [hekolcu/AutoGPT](https://github.com/hekolcu/AutoGPT) …

HekolcuAutoGPT entering the arena

---

arena/ChadGPT.json

- **Agent Name:** ChadGPT
- **Repository Link:** [Ahmad-Alaziz/ChadGPT](https://github.com/Ahmad-Alaziz/ChadGPT) …

ChadGPT entering the arena

---

arena/MojoBurrito.json

- **Agent Name:** MojoBurrito
- **Repository Link:** [dawnkelly09/MojoBurrito](https://github.com/dawnkelly09/MojoBurrito) …

MojoBurrito entering the arena

---

arena/raindrop.json

- **Agent Name:** raindrop
- **Repository Link:** [tianbinraindrop/AutoGPT](https://github.com/tianbinraindrop/AutoGPT) …

raindrop entering the arena

---

arena/job_apply.json

- **Agent Name:** job_apply
- **Repository Link:** [tkbeili/AutoGPT](https://github.com/tkbeili/AutoGPT) …

job_apply entering the arena

---

arena/Light_Agent.json

- **Agent Name:** Light_Agent
- **Repository Link:** [mohammed-radha-LightRing/AutoGPT](https://github.com/mohammed-radha-LightRing/AutoGPT)
- **Target Prize:** (Which prize caught your …

Light_Agent entering the arena

---

arena/SouAgent.json

SouAgent entering the arena

---

arena/NoobSupreme.json

NoobSupreme entering the arena

---

arena/byl.json

- **Agent Name:** byl
- **Repository Link:** [yoonh12/byl](https://github.com/yoonh12/byl)
- **Why this …

byl entering the arena

---

arena/umiuni_agent.json

umiuni_agent entering the arena

---

arena/personal-al-website.json

- **Agent Name:** personal-al-website
- **Repository Link:** [Hazzari/AutoGPT](https://github.com/Hazzari/AutoGPT) …

personal-al-website entering the arena

---

arena/test.json

- **Agent Name:** test
- **Repository Link:** [Nivek92/AutoGPT](https://github.com/Nivek92/AutoGPT)
- …

test entering the arena

---

arena/hall_oto.json

hall_oto entering the arena

---

arena/Brillante-AI.json

- **Agent Name:** Brillante-AI
- **Repository Link:** [dabeer021/Brillante-AI](https://github.com/dabeer021/Brillante-AI) …

Brillante-AI entering the arena

---

benchmark/agbenchmark/challenges/verticals/code/6_battleship/artifacts_in/abstract_class.py
benchmark/agbenchmark/challenges/verticals/code/6_battleship/artifacts_out/abstract_class.py

Correct Battleship Challenge

---

arena/Maharathi.json

- **Agent Name:** Maharathi
- **Repository Link:** [sampatkalyan/AutoGPTHackathon](https://github.com/sampatkalyan/AutoGPTHackathon)
- **Target Prize:** (Which prize caught your eye? …

Maharathi entering the arena

---

arena/Baptiste.json

- **Agent Name:** Baptiste
- **Repository Link:** [Baptistecaille/AutoGPT](https://github.com/Baptistecaille/AutoGPT) …

Baptiste entering the arena

---

arena/proudgpt.json

- **Agent Name:** proudgpt
- **Repository Link:** [OmarHory/Star-Agent](https://github.com/OmarHory/Star-Agent) …

proudgpt entering the arena

---

arena/TheAgency.json

- **Agent Name:** TheAgency
- **Team Members:** [Vincent Castro, Lead Engineer/Founder](https://github.com/risingsunomi)
- **Repository Link:** [shamantechnology/TheAgency](https://github.com/shamantechnology/TheAgency)
- **Starting Point:** We are building from scratch with our knowledge from working with agents in langchain. Following the agent protocol flow and forge setup
- **Preliminary Ideas:** Currently looking to build an agent from the forge template focusing initially on general tasks
- **Target …

TheAgency entering the arena

---

arena/robita.json

- **Agent Name:** robita
- **Repository Link:** [atetsuka/AutoGPT](https://github.com/atetsuka/AutoGPT)
- …

robita entering the arena

---

benchmark/agbenchmark/challenges/verticals/scrape/3_revenue_retrieval/data.json
benchmark/agbenchmark/challenges/verticals/scrape/4_revenue_retrieval_2/data.json

Correct revenue retrieval challenge

---

arena/TestAgent.json

- **Agent Name:** TestAgent
- **Repository Link:** [AdrianSilaghi/AutoGPT](https://github.com/AdrianSilaghi/AutoGPT) …

TestAgent entering the arena

---

arena/DevOpsAgent.json

- **Agent Name:** DevOpsAgent
- **Repository Link:** [rahuldotar/AutoGPT](https://github.com/rahuldotar/AutoGPT) …

DevOpsAgent entering the arena

---

arena/misslu.json

- **Agent Name:** misslu
- **Repository Link:** [JasonZhang95/AutoGPT](https://github.com/JasonZhang95/AutoGPT) …

misslu entering the arena

---

arena/Miao.json

Miao entering the arena

---

arena/SaasWebDev.json

- **Agent Name:** SaasWebDev
- **Repository Link:** [giggei/AutoGPT](https://github.com/giggei/AutoGPT)
- …

SaasWebDev entering the arena

---

arena/hackathonishe.json

- **Agent Name:** hackathonishe
- **Repository Link:** [qwdqwqdwqd/autogpt](https://github.com/qwdqwqdwqd/autogpt) …

hackathonishe entering the arena

---

autogpts/forge/forge/__main__.py
autogpts/forge/forge/app.py
autogpts/forge/forge/sdk/agent.py
autogpts/forge/poetry.lock
autogpts/forge/pyproject.toml

Hot reload mode

---

.github/workflows/autogpts-ci.yml

Fix AutoGPTs-CI

---

.github/workflows/benchmark-ci.yml
benchmark/agbenchmark/__main__.py
benchmark/tests/test_benchmark_workflow.py

Fix benchmark ci

---

TROUBLESHOOTING.md

I had an issue regarding Pydantic, but it's simply that my db was old.

List tasks: inform of pydantic errors

---

autogpts/forge/poetry.lock
autogpts/forge/pyproject.toml

Add pycharm debug to dev dependencies

---

arena/gipity.json

- **Agent Name:** gipity
- **Repository Link:** [koad/gpt](https://github.com/koad/gpt)
- **Why this …

gipity entering the arena

---

arena/Alfred.json

- **Agent Name:** Alfred
- **Repository Link:** [Shadowless422/Alfred](https://github.com/Shadowless422/Alfred) …

Alfred entering the arena

---

arena/my_AutoGPT.json

my_AutoGPT entering the arena

---

arena/mrSabelotodo.json

Agent Name: mrSabelotodo
Team Members: Looking for more active members
Repository Link: https://github.com/joslangarica/AutoGPT
Starting Point: I am building from scratch 
Preliminary Ideas: SEO and content creator

mrSabelotodo entering the arena

---

arena/AppleGPT.json

- **Agent Name:** AppleGPT
- **Repository Link:** [Nimit3-droid/AutoGPT](https://github.com/Nimit3-droid/AutoGPT) …

AppleGPT entering the arena

---

arena/faran.json

- **Agent Name:** faran
- **Repository Link:** [faranbutt/AutoGPT](https://github.com/faranbutt/AutoGPT) …

faran entering the arena

---

benchmark/agbenchmark/app.py
benchmark/agbenchmark/utils/challenge.py

Fix custom_python not being copied

---

arena/MindwareGPT.json

MindwareGPT entering the arena

---

README.md

Just having a simple hyperlink is boring and hard to see in the maze of text. Using `invidget`, you can have a discord look-alike invite, which makes it clear what it is and the purpose.
Used [`SwitchbladeBot/invidget`](https://github.com/SwitchbladeBot/invidget) for a cleaner Discord invite

Update Discord invite

---

README.md

Put both a pretty image AND a basic link for the discord call to action

---

arena/EmbeddedAg.json

Agent Name: faran
Team Members: (Who are the amazing minds behind this team? Do list everyone along with their roles!)
Repository Link: [mdabir1203/AutoGPT](https://github.com/mdabir1203/AutoGPT)
Starting Point: Need some experiments
Preliminary Ideas: 
An Agent for Securing Embedded System security . Embedded system could be cars, smartwatch and etc. 
🏆 Prize Category
Target Prize: (Which prize caught your eye? Which …

EmbeddedAg entering the arena

---

arena/Bunny.json

- **Agent Name:** Bunny
- **Repository Link:** [razorhasbeen/AutoGPT](https://github.com/razorhasbeen/AutoGPT) …

Bunny entering the arena

---

arena/MEGATRON.json

- **Agent Name:** MEGATRON
- **Repository Link:** [razorhasbeen/AutoGPT](https://github.com/razorhasbeen/AutoGPT) …

MEGATRON entering the arena

---

arena/mljar-agent.json

- **Agent Name:** mljar-agent-1
- **Team Members:** @aplonska (manager, ideas) and @pplonski (developer)
- **Repository Link:** [mljar/mljar-agent](https://github.com/mljar/mljar-agent)
- **Starting Point:** From scratch, in the first iterations we would like to check how far can gpt-3.5 and gpt-4 go, without additional tricks
- **Preliminary Ideas:** We would like to check in-context learning
- **Target Prize:** data track
- **Why this Prize:** at [mljar](https://mljar.com) we work on outstanding data …

mljar-agent entering the arena

---

frontend/lib/viewmodels/skill_tree_viewmodel.dart
frontend/lib/views/task_queue/task_queue_view.dart
frontend/lib/views/task_queue/test_suite_button.dart

Initially, the application only allowed users to execute a single test and its dependencies. The UI did not provide options for executing different subsets of tests, and the logic handling the task execution was limited. The Test Suite Button was a `StatelessWidget`, and the task queue had an overlapping issue when the list got too long.
- **Functionality Addition:** Integrated new options for test execution, allowing users to either run a single test, the whole category of tests, or a test and its ancestors, enhancing flexibility and user control.
- **UI Update:** Refactored the Test Suite Button to include a dropdown menu, enabling users to easily select their preferred test execution option.
- **Old Implementation:** The Test Suite Button was a `StatelessWidget`.
- **New …

Enhanced Test Execution Flexibility

---

frontend/lib/utils/uri_utility.dart
frontend/lib/views/task_queue/leaderboard_submission_dialog.dart

Previously, the `LeaderboardSubmissionDialog` allowed users to input any URL for the repository field without checking if it was a valid GitHub repository. This could lead to incorrect or invalid submissions being made to the leaderboard.
This PR introduces a new validation method `isValidGitHubRepo` to the `UriUtility` class. This method checks if the provided repository URL is a valid GitHub repository by making a request to the GitHub API and validating the response. The `LeaderboardSubmissionDialog`’s `_validateAndSubmit` method has been updated to be asynchronous to incorporate this new validation. Now, when users attempt to submit their information, the dialog will not only check for the URL's format but also verify if it is a valid GitHub repository.
- `isValidGitHubRepo` method to …

Add GitHub Repository Validation to Leaderboard Submission Dialog

---

arena/AUTO_ENGINEER.json

- **Agent Name:** AUTO_ENGINEER
- **Repository Link:** [kaiomagalhaes/AutoGPT](https://github.com/kaiomagalhaes/AutoGPT) …

AUTO_ENGINEER entering the arena

---

arena/Pacific.json

- **Agent Name:** Pacific
- **Repository Link:** [yifeng-qiu/AutoGPTAgent](https://github.com/yifeng-qiu/AutoGPTAgent) …

Pacific entering the arena

---

arena/Bravo06.json

- **Agent Name:** Bravo06
- **Repository Link:** [jafar-albadarneh/Bravo06GPT](https://github.com/jafar-albadarneh/Bravo06GPT) …

Bravo06 entering the arena

---

arena/chenzo.json

- **Agent Name:** chenzo
- **Repository Link:** [chenzino/AutoGPT](https://github.com/chenzino/AutoGPT)
- …

chenzo entering the arena

---

arena/od_agent_1.json

- **Agent Name:** od_agent_1
- **Repository Link:** [mattsinnock/AutoGPT](https://github.com/mattsinnock/AutoGPT) …

od_agent_1 entering the arena

---

frontend/lib/services/auth_service.dart
frontend/lib/views/auth/firebase_auth_view.dart

Previously, our OAuth 2.0 implementation for signing in with Google and GitHub was based on redirecting users to the respective authentication pages. This approach was effective but had some limitations, especially when the application was run in dynamic environments like GitHub Codespaces. Users encountered a "400 Error: redirect URI mismatch" because the dynamic URLs generated by Codespaces were not registered in the Google Cloud Console or GitHub OAuth Apps.
We've enhanced the OAuth 2.0 implementation by dynamically setting the redirect URIs based on the environment where the application is running. The application now automatically detects the current hostname and sets the OAuth 2.0 redirect URI accordingly. This change ensures compatibility with dynamic environments, providing a …

Enhanced OAuth 2.0 Implementation with Dynamic Redirect URIs and Popup Authentication

---

frontend/lib/services/auth_service.dart

Swap out pop up auth for redirect

Swap out pop up auth for redirect

---

benchmark/agbenchmark/challenges/deprecated/code/1_password_generator/custom_python/test.py

Fix password generator

---

frontend/lib/models/artifact.dart
frontend/lib/models/chat.dart
frontend/lib/models/step.dart
frontend/lib/views/chat/chat_view.dart

Previously, artifacts were managed as a `List<dynamic>` containing maps. This approach lacked type safety and required additional processing to extract and utilize artifact data. With the growing need for robust and efficient data handling mechanisms, there was an imperative to refactor this approach and introduce a class representation for artifacts.
In this PR, we introduce the `Artifact` class, a well-structured, type-safe representation of artifact data, aligning with the provided JSON schema. This class facilitates efficient data handling, including easy deserialization from JSON received from the server.
- `Artifact` class with properties aligning with the artifact JSON schema.
- `fromJson` method for deserializing JSON data into an `Artifact` object.
- Updated data handling …

Implement Artifact Class for Enhanced Data Handling

---

arena/admariner.json

- **Agent Name:** admariner
- **Repository Link:** [admariner/AutoGPT](https://github.com/admariner/AutoGPT) …

admariner entering the arena

---

arena/ShiviBot.json

- **Agent Name:** ShiviBot
- **Repository Link:** [kshivang/DabblerGPT](https://github.com/kshivang/DabblerGPT) …

ShiviBot entering the arena

---

arena/LHRobot.json

- **Agent Name:** LHRobot
- **Repository Link:** [LH-Enterprise/AutoGPT](https://github.com/LH-Enterprise/AutoGPT) …

LHRobot entering the arena

---

arena/piGPT.json

- **Agent Name:** piGPT
- **Repository Link:** [pihanya/AutoGPT](https://github.com/pihanya/AutoGPT)
- …

piGPT entering the arena

---

arena/CurieAssistant.json

- **Agent Name:** CurieAssistant
- **Repository Link:** [HMDCrew/AutoGPT](https://github.com/HMDCrew/AutoGPT) …

CurieAssistant entering the arena

---

arena/RONNIN.json

- **Agent Name:** RONNIN
- **Repository Link:** [Huarada/AutoGPT](https://github.com/Huarada/AutoGPT)
- …

RONNIN entering the arena

---

arena/thebestagent.json

- **Agent Name:** thebestagent
- **Repository Link:** [hisandan/AutoGPT](https://github.com/hisandan/AutoGPT) …

thebestagent entering the arena

---

arena/Melang.json

Agent Name: Melang
Team Members: (Who are the amazing minds behind this team? Do list everyone along with their roles!)
Repository Link: [Brian-Mwangi-developer/AutoGPT](https://github.com/Brian-Mwangi-developer/AutoGPT)
Starting Point: (Are you building from scratch or starting with an existing agent? Do tell!)
Preliminary Ideas: (Share your initial ideas and what kind of project you are aiming to build. We are all …

Melang entering the arena

---

arena/jaxbob1.json

- **Agent Name:** jaxbob1
- **Repository Link:** [redthing1/AutoGPT](https://github.com/redthing1/AutoGPT) …

jaxbob1 entering the arena

---

arena/NumberOne.json

- **Agent Name:** NumberOne
- **Repository Link:** [micwin/AutoGPT](https://github.com/micwin/AutoGPT)
- …

NumberOne entering the arena

---

arena/evo-ninja.json

Agent Name: evo.ninja
Team Members: @nerfZael @dorgjelli @namesty @rihp @cbrzn
Repository Link: [polywrap/evo.ninja](https://github.com/polywrap/evo.ninja)
Starting Point: (Are you building from scratch or starting with an existing agent? Do tell!)
Preliminary Ideas: (Share your initial ideas and what kind of project you are aiming to build. We are all ears!)
🏆 Prize Category
Target Prize: (Which prize caught your eye? …

evo-ninja entering the arena

---

arena/caud.json

- **Agent Name:** caud
- **Repository Link:** [Swiftyos/CAUD](https://github.com/Swiftyos/CAUD)
- **Why …

caud entering the arena

---

arena/NASAssistant2.json

- **Agent Name:** NASAssistant2
- **Repository Link:** [IHIaadj/AutoGPT](https://github.com/IHIaadj/AutoGPT) …

NASAssistant2 entering the arena

---

arena/jarvis3.json

- **Agent Name:** jarvis3
- **Repository Link:** [MissingDLL/AutoGPT](https://github.com/MissingDLL/AutoGPT) …

jarvis3 entering the arena

---

arena/buddy.json

- **Agent Name:** buddy
- **Repository Link:** [danhamilt/AutoGPT](https://github.com/danhamilt/AutoGPT) …

buddy entering the arena

---

benchmark/agbenchmark/challenges/verticals/data/2_label_csv/artifacts_out/output.csv

fix label csv

---

arena/CISLERK.json

- **Agent Name:** CISLERK
- **Repository Link:** [cislerk/AutoGPT](https://github.com/cislerk/AutoGPT)
- …

CISLERK entering the arena

---

arena/smith.json

- **Agent Name:** smith
- **Repository Link:** [kevinboudot/AutoGPT](https://github.com/kevinboudot/AutoGPT) …

smith entering the arena

---

arena/Verkiezingsprogrammas.json

- **Agent Name:** Verkiezingsprogrammas
- **Repository Link:** [bergje0810/AutoGPT](https://github.com/bergje0810/AutoGPT) …

Verkiezingsprogrammas entering the arena

---

arena/Jarvis.json

- **Agent Name:** Jarvis
- **Repository Link:** [elynch303/AutoGPT](https://github.com/elynch303/AutoGPT) …

Jarvis entering the arena

---

arena/da-agent.json

- **Agent Name:** da-agent
- **Repository Link:** [rayzh-lab/AutoGPT](https://github.com/rayzh-lab/AutoGPT) …

da-agent entering the arena

---

arena/searchagent.json

- **Agent Name:** searchagent
- **Repository Link:** [sanjeevsaara/AutoGPT](https://github.com/sanjeevsaara/AutoGPT) …

searchagent entering the arena

---

arena/ExampleAgent.json

- **Agent Name:** ExampleAgent
- **Repository Link:** [janekdijkstra/AutoGPT](https://github.com/janekdijkstra/AutoGPT) …

ExampleAgent entering the arena

---

arena/Raslebot.json

Raslebot entering the arena

---

arena/Auto.json

- **Agent Name:** Auto
- **Repository Link:** [Nikhil8652/AutoGPT](https://github.com/Nikhil8652/AutoGPT) …

Auto entering the arena

---

arena/zze.json

- **Agent Name:** zze
- **Repository Link:** [quasimodo7614/AutoGPT](https://github.com/quasimodo7614/AutoGPT) …

zze entering the arena

---

arena/teacher.json

- **Agent Name:** teacher
- **Repository Link:** [miaowacao/AutoGPT1](https://github.com/miaowacao/AutoGPT1) …

teacher entering the arena

---

arena/TraceLLMAgent.json

- **Agent Name:** TraceLLMAgent
- **Repository Link:** [vmwsree/AutoGPT](https://github.com/vmwsree/AutoGPT) …

TraceLLMAgent entering the arena

---

arena/dda.json

- **Agent Name:** dda
- **Repository Link:** [aiherrera1/AutoGPT](https://github.com/aiherrera1/AutoGPT) …

dda entering the arena

---

arena/dev_agent.json

- **Agent Name:** dev_agent
- **Repository Link:** [pedrovvitor/AutoGPT](https://github.com/pedrovvitor/AutoGPT) …

dev_agent entering the arena

---

arena/robot.json
arena/roboticated.json

- **Agent Name:** robot
- **Repository Link:** [brisklad/AutoGPT](https://github.com/brisklad/AutoGPT)
- …

robot entering the arena

---

arena/testGPT.json

- **Agent Name:** testGPT
- **Repository Link:** [PZON2/testGPT](https://github.com/PZON2/testGPT)
- …

testGPT entering the arena

---

arena/AutoTestGenerator.json

- **Agent Name:** AutoTestGenerator
- **Repository Link:** [cagdasbas/AutoGPT](https://github.com/cagdasbas/AutoGPT) …

AutoTestGenerator entering the arena

---

arena/xt0m-GPT.json

- **Agent Name:** xt0m-GPT
- **Repository Link:** [jcartes/xt0m-GPT](https://github.com/jcartes/xt0m-GPT) …

xt0m-GPT entering the arena

---

arena/billy.json

- **Agent Name:** billy
- **Repository Link:** [khelil/AutoGPT](https://github.com/khelil/AutoGPT)
- …

billy entering the arena

---

arena/MyFirstAgent.json

- **Agent Name:** MyFirstAgent
- **Repository Link:** [smaxaddington/AutoGPT](https://github.com/smaxaddington/AutoGPT) …

MyFirstAgent entering the arena

---

arena/LinuzGPT.json

- **Agent Name:** LinuzGPT
- **Repository Link:** [linusaltacc/AutoGPT](https://github.com/linusaltacc/AutoGPT) …

LinuzGPT entering the arena

---

arena/AutoGPT2.json

- **Agent Name:** AutoGPT2
- **Repository Link:** [SarahGrevy/AutoGPT](https://github.com/SarahGrevy/AutoGPT) …

AutoGPT2 entering the arena

---

arena/Marx.json

- **Agent Name:** Marx
- **Repository Link:** [maxletemple/AutoGPT](https://github.com/maxletemple/AutoGPT) …

Marx entering the arena

---

arena/MyTestAgent.json

MyTestAgent entering the arena

---

arena/baby_agent.json

- **Agent Name:** baby_agent
- **Repository Link:** [keli-61/AutoK](https://github.com/keli-61/AutoK)
- …

baby_agent entering the arena

---

arena/shivi.json

- **Agent Name:** shivi
- **Repository Link:** [kshivang/DabblerGPT](https://github.com/kshivang/DabblerGPT) …

shivi entering the arena

---

arena/FynAgent.json

Agent Name: FynAgent
Team Members: Carlos J. Ramirez (a.k.a. @tomkat_cr)
Repository Link: [tomkat-cr/AutoGPT](https://github.com/tomkat-cr/AutoGPT)
Starting Point: (Are you building from scratch or starting with an existing agent? Do tell!)
Preliminary Ideas: (Share your initial ideas and what kind of project you are aiming to build. We are all ears!)
🏆 Prize Category
Target Prize: (Which prize caught your eye? Which one …

FynAgent entering the arena

---

arena/my_fx_agent.json

my_fx_agent entering the arena

---

arena/engineer.json

- **Agent Name:** engineer
- **Repository Link:** [bary12/AutoGPT](https://github.com/bary12/AutoGPT)
- …

engineer entering the arena

---

arena/martingpt.json

- **Agent Name:** martingpt
- **Repository Link:** [martinpeng/AutoGPT](https://github.com/martinpeng/AutoGPT) …

martingpt entering the arena

---

arena/JarvisAgent.json

- **Agent Name:** JarvisAgent
- **Repository Link:** [JadeCong/AutoGPT](https://github.com/JadeCong/AutoGPT) …

JarvisAgent entering the arena

---

arena/researchGPT2.json

- **Agent Name:** researchGPT2
- **Repository Link:** [gty3310/AutoGPT](https://github.com/gty3310/AutoGPT) …

researchGPT2 entering the arena

---

arena/GeorgeGPT.json

- **Agent Name:** GeorgeGPT
- **Repository Link:** [norn93/GeorgeGPT](https://github.com/norn93/GeorgeGPT) …

GeorgeGPT entering the arena

---

arena/Adtractive_Agent.json

- **Agent Name:** Adtractive_Agent
- **Repository Link:** [aivaras-mazylis/AutoGPT](https://github.com/aivaras-mazylis/AutoGPT) …

Adtractive_Agent entering the arena

---

arena/ZhaoJianAutoGPT.json

- **Agent Name:** ZhaoJianAutoGPT
- **Repository Link:** [zhaojianchn/AutoGPT](https://github.com/zhaojianchn/AutoGPT) …

ZhaoJianAutoGPT entering the arena

---

arena/eddy.json

- **Agent Name:** eddy
- **Repository Link:** [ltxctdbnn/AutoGPT](https://github.com/ltxctdbnn/AutoGPT)
- …

eddy entering the arena

---

arena/lcdegpt.json

- **Agent Name:** lcdegpt
- **Repository Link:** [tablc/lcdegpt](https://github.com/tablc/lcdegpt)
- …

lcdegpt entering the arena

---

arena/RosterAgent.json

- **Agent Name:** RosterAgent
- **Repository Link:** [ricowong0730/AutoGPT](https://github.com/ricowong0730/AutoGPT) …

RosterAgent entering the arena

---

arena/letst.json

- **Agent Name:** letst
- **Repository Link:** [jianhuanggo/AutoTestTest](https://github.com/jianhuanggo/AutoTestTest) …

letst entering the arena

---

arena/letstest.json

- **Agent Name:** letstest
- **Repository Link:** [jianhuanggo/AutoTestTest](https://github.com/jianhuanggo/AutoTestTest) …

letstest entering the arena

---

arena/assistant1.json

- **Agent Name:** assistant1
- **Repository Link:** [BarneyChambers/AutoGPT](https://github.com/BarneyChambers/AutoGPT) …

assistant1 entering the arena

---

arena/XXY.json

- **Agent Name:** XXY
- **Repository Link:** [xuxiangyang/AutoGPT](https://github.com/xuxiangyang/AutoGPT) …

XXY entering the arena

---

arena/date-buffer.json

- **Agent Name:** date-buffer
- **Repository Link:** [jackbullen/AutoGPT](https://github.com/jackbullen/AutoGPT) …

date-buffer entering the arena

---

arena/AgentKD.json

- **Agent Name:** AgentKD
- **Repository Link:** [kitdesai/AgentKD](https://github.com/kitdesai/AgentKD) …

AgentKD entering the arena

---

arena/TRAVIS.json

- **Agent Name:** TRAVIS
- **Repository Link:** [tskaggs/AutoGPT](https://github.com/tskaggs/AutoGPT)
- …

TRAVIS entering the arena

---

arena/han.json

- **Agent Name:** han
- **Repository Link:** [Hanhan0831/AutoGPT](https://github.com/Hanhan0831/AutoGPT) …

han entering the arena

---

arena/dive2code.json
arena/hackathonishe.json

hackathonishe.json renamed to dive2code.json

rename arena agent (hackathonishe -> dive2code)

---

arena/GameSoundGPT.json

- **Agent Name:** GameSoundGPT
- **Repository Link:** [mordvinov/AutoGPT](https://github.com/mordvinov/AutoGPT) …

GameSoundGPT entering the arena

---

arena/gpt-engineer.json

- **Agent Name:** gpt-engineer
- **Repository Link:** [ATheorell/AutoGPTArenaHack](https://github.com/ATheorell/AutoGPTArenaHack) …

gpt-engineer entering the arena

---

arena/MANU.json

- **Agent Name:** MANU
- **Repository Link:** [manuel-soria/AutoGPT](https://github.com/manuel-soria/AutoGPT) …

MANU entering the arena

---

arena/chappigpt.json

- [x ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ x] Have you changed or added a feature? &ensp; `-4 pts`
- [ x] Have you added/updated corresponding documentation? &ensp; `+4 pts`

chappigpt entering the arena

---

arena/Zeus.json

- **Agent Name:** Zeus
- **Repository Link:** [MerlimarCode/ZeusGPT](https://github.com/MerlimarCode/ZeusGPT) …

Zeus entering the arena

---

arena/CreaitorMarketing.json

- **Agent Name:** CreaitorMarketing
- **Repository Link:** [simonfunk/Auto-GPT](https://github.com/simonfunk/Auto-GPT) …

CreaitorMarketing entering the arena

---

arena/info-retrieval.json

- **Agent Name:** info-retrieval
- **Repository Link:** [paperMoose/AutoGPT](https://github.com/paperMoose/AutoGPT) …

info-retrieval entering the arena

---

arena/HACKATHON.json

- **Agent Name:** HACKATHON
- **Repository Link:** [manuel-soria/AutoGPT](https://github.com/manuel-soria/AutoGPT) …

HACKATHON entering the arena

---

arena/MOBILE.json

- **Agent Name:** MOBILE
- **Repository Link:** [nel349/AutoGPT](https://github.com/nel349/AutoGPT)
- …

MOBILE entering the arena

---

arena/Yui3.json

- **Agent Name:** Yui3
- **Repository Link:** [YuiChan04233/AutoGPT1](https://github.com/YuiChan04233/AutoGPT1) …

Yui3 entering the arena

---

arena/RAGOptimizer.json

- **Agent Name:** RAGOptimizer
- **Repository Link:** [nel349/AutoGPT](https://github.com/nel349/AutoGPT) …

RAGOptimizer entering the arena

---

arena/foobar.json

- **Agent Name:** foobar
- **Repository Link:** [sosthoff/AutoGPT](https://github.com/sosthoff/AutoGPT)
- …

foobar entering the arena

---

arena/theone.json

- **Agent Name:** theone
- **Repository Link:** [hisandan/AutoGPT](https://github.com/hisandan/AutoGPT)
- …

theone entering the arena

---

arena/RFPScanner.json

- **Agent Name:** RFPScanner
- **Repository Link:** [vidhatanand/AutoRFP](https://github.com/vidhatanand/AutoRFP) …

RFPScanner entering the arena

---

arena/autogbd.json

- **Agent Name:** autogbd
- **Repository Link:** [kylaro/AutoGBD](https://github.com/kylaro/AutoGBD)
- …

autogbd entering the arena
