Significant-Gravitas/AutoGPT

README.md

The docs say the command to add TTS is `speach-mode`, while it's `speak-mode`. Just a small mistake, but still caused some issues.

Fix mistake in docs

---

scripts/main.py

This PR fixes an issue in the `print_assistant_thoughts` function that caused a `UnboundLocalError` when `assistant_thoughts_reasoning` was referenced before assignment. 
To solve this, I have initialized all variables to `None` before trying to retrieve them from `assistant_reply_json`. This ensures that all variables are defined even if they are not included in the JSON response.

fix: UnboundLocalError: local variable 'assistant_thoughts_reasoning' referenced before assignment

---

scripts/main.py

This PR adds some handling on weird `assistant_thoughts` types:
```
Auto-GPT/scripts/main.py", line 59, in print_assistant_thoughts assistant_thoughts = assistant_reply_json.get("thoughts", {}) AttributeError: 'str' object has no attribute 'get'
Warning: Failed to parse AI output, attempting to fix.
```

fix assistant thoughts failure on string type

---

requirements.txt
scripts/speak.py

Adds the gTTS (Google Text-to-Speech) Python library as a fallback for text-to-speech conversion in the speak.py file. The changes were made to ensure that users can still convert text to speech even if the ElevenLabs API key is not set or if the API encounters an error. Additionally, the requirements.txt file has been updated to include the new gTTS dependency.

Added a default (free) library for text to speech

---

scripts/commands.py

This pull request introduces improvements to key validation and handling in the `overwrite_memory` and `message_agent` functions within the `scripts/commands.py` file.
Changes include:
-  Adding a new helper function `is_valid_int` to check if a value can be converted to an integer.
-  Updating the `overwrite_memory` function to handle both integer and string keys, and providing more informative error messages.
-  Updating the `message_agent` function to use the `is_valid_int` helper function for key validation and providing an informative error message for invalid keys.
These changes aim to make the code more robust and user-friendly, allowing for better handling of different key types and more informative error messages when invalid keys are encountered.

Improve Key Validation and Handling in Overwrite Memory and Message Agent Functions

---

.github/ISSUE_TEMPLATE/1.bug.yml
.github/ISSUE_TEMPLATE/2.feature.yml

I added issue templates to help organize the incoming issues. With these templates when someone creates a new issue they get to choose from these options:
----------
The bug report template looks like this:
--------------
The feature request template looks like this:

first draft of github issue templates

---

scripts/browse.py
scripts/config.py

Greetings,
I discovered that some sites are inaccessible due to the lack of user-agent headers. For instance, I tried to access 'https://etherscan.io/accounts' using the requests.get() method, but it returned a 403 error. Therefore, I added some fake user-agent headers to the request, which seemed to fix the issue.
To avoid adding more libraries to the project, I hard-coded the headers. However, I could implement a better solution by using the 'fake-useragent' library (or a similar one) if you prefer. That being said I believe the current solution is fine at least for now.

Added fake user-agent headers to browser request.

---

scripts/json_parser.py

The fix_json error is expected to return str.
In case of success, the function does a json.loads() and returns a JSON, which cause a "TypeError('the JSON object must be str, bytes or bytearray, not dict')" in the caller

fixing the "TypeError('the JSON object must be str, bytes or bytearray, not dict')" after a json_fix is successful

---

.env.template
README.md
scripts/config.py
scripts/llm_utils.py

Functionality is controlled through a switch in the .env configuration:
USE_AZURE=False
OPENAI_API_BASE=your-base-url-for-azure
OPENAI_API_VERSION=api-version-for-azure
OPENAI_DEPLOYMENT_ID=deployment-id-for-azure
Set USE_AZURE to True and fill in the appropriate values as detailed here: https://pypi.org/project/openai/ in the `Microsoft Azure Endpoints` section

Added functionality to allow the use of GPT on a Microsoft Azure instance

---

scripts/main.py

This PR addresses the issue of enabling users to run a custom number of continuous tasks in the interaction loop using the command `y -n`. By providing a number after the y - command, users can now specify how many continuous tasks they want the program to execute without user interaction.
To test this feature, follow these steps:
Run the program as you normally would.
When prompted for user input, type `y -n`, replacing `n` with the number of continuous tasks you want to execute. For example, to run 5 continuous tasks, type `y -5`.
Observe the output and verify that the specified number of tasks are executed without user interaction.
Additional Notes:
This pull request adds a new feature to the interaction loop by allowing users to specify a custom number of continuous tasks. The …

Implement custom continuous task count with 'y -n' command

---

README.md
scripts/main.py

- This PR provides fix to issue #433
- The issue is basically if you don't provide Pinecone API or Pinecone ENV then the main.py module raises an error.
- Therefore Pinecone is necessary for the main.py module to work.
- I added an exception in main.py before initializing the Pinecone Memory instance. The exception is raised if either pinecone_api_key or pinecone_region is not provided in env.
- Consequently, I also update the README.md as well to reflect the updated requirements.
No new tests were needed.

Pinecone API Key Bug Fix

---

scripts/ai_config.py

I was calling the script of the directory I cloned Auto-GPT, d:\src\Auto-GPT on my computer, and the settings were being saved on d:\src\ai_settings.yaml, while I expected them to be on d:\src\Auto-GPT\ai_settings.yaml

Settings were being saved and loaded in the wrong directory

---

.env.template
README.md
scripts/commands.py
scripts/config.py
scripts/data/prompt.txt
scripts/image_gen.py

Adds support for DALL-e (default) and Stable Diffusion. Image providers can be switched via the `IMAGE_PROVIDER` env var.
Adds a command for `generate_image` and a corresponding handler. 
Adds support for DALL-e and Stable Diffusion (via API).
Leverages the existing openAI API Key for DALL-e.
Tested against multiple prompts, was even able to get it to generate articles and include the generated images into the articles(!!) 
- [ x] I have considered potential risks and mitigations for my changes
I am not sure how to test python code in this project.

🖼 Image Generation: Adds DALL-e and Stable Diffusion support

---

README.md
requirements.txt
scripts/commands.py
scripts/config.py
scripts/main.py
scripts/memory/__init__.py
scripts/memory/base.py
scripts/memory/local.py
scripts/memory/pinecone.py
scripts/memory/redismem.py

Redis is a free and open source alternative to pinecone.
We had a dicussion here: https://discord.com/channels/1092243196446249134/1093713674679615638
The memory backend was given an abstract base class.
PineconeMemory now inherits from this ABC.
RedisMemory was added.
Configuration options were added to the Config class.
I had SuperMario in Discord verify I did not break pinecone, I tested redis locally.
I didn't see any existing tests for memory and will attempt to add some at a later point in time.

Implement Local Cache and Redis Memory backend

---

scripts/config.py
scripts/json_parser.py
scripts/main.py

using debug paramaters were hardcoded and needed to be taken from the arguments
store debug argument in cfg
use cfg.debug when calling chat.chat_with_ai and fix_json

put debug setting to cfg and use it in when calling chat.chat_with_ai and fix_json

---

.gitignore

Users frequently utilise python's venv module to isolate per-project dependencies.  
This change adds a .gitignore entry for default venv name 'venv' in the project root. 
- [ n/a] I have thouroughly tested my changes with multiple different prompts.

gitignore venv

---

scripts/call_ai_function.py

The function kwarg `model` default was storing gpt-4 value at import time, leading to yield a value of gpt-4. Even after setting gpt3only, because that happens later. By that time `gpt-4` is already stored in as the default value.
This PR fixes that for us folks still waiting to unlock gpt-4 usage.

🛠️ 🧰 Fix call_ai_function storing gpt-4 into kwarg model even when using gpt3only

---

scripts/data/prompt.txt

https://github.com/Torantulino/Auto-GPT/pull/575#discussion_r1161529687
Makes the `do_nothing` line in `prompt.txt` from my last pull request (#575) completely uniform with the rest of the commands list. 
Removed `; command name` from said line.
Already tested in #575.

[Quick fix] Make `do_nothing` line uniform

---

README.md

"$" was annoying when copy/pasting the command. And that was the only line with the character.

Patch readme "copy" command

---

README.md

Just adding the keys to .env is easier for most users. The current way confuses alot of people which causes lots of repetitive questions on github aswell as on discord.

Changed order of pinecone explaination too avoid confusion

---

README.md

Minor improvement in sentence clarity for Pinecone setup instructions.

Updated Pinecone API Key Setup instructions for clarity

---

scripts/ai_config.py
scripts/ai_functions.py
scripts/config.py
scripts/main.py
tests/test_browse_scrape_text.py

This is a new instance of #590. After many merged PR the trailing space creeped in again.
Only space characters at EOL were trimmed, and in the edited files the ending \r\n was added automaticall by vim (which is a good thing)
N/A
N/A

Remove trailing whitespace throughout

---

scripts/ai_config.py
scripts/browse.py
scripts/chat.py
scripts/json_parser.py
scripts/main.py

This is a part of a large movement to enable flake8 without breaking things.
Fix 2 flake 8 warnings: empty lines with whitespace and empty lines at the end of a file. There are not many fixes, so that it's easy to review and merge, and it isn't likely to break the existing PRs.
N/A
N/A

Fix flake8 W293 and W391

---

scripts/config.py
scripts/main.py

Another attempt to remove the duplicate set debug mode func in the current HEAD.
It has been hard to get removed because of multiple pull requests and conflicts.

Remove duplicates of set debug mode func

---

scripts/json_parser.py

This block was not running due to the above code not letting it, it now throws a value error if the index was not found.
Add additional exception `ValueError` to except statement.
None
None

Fix case where index throws value error.

---

scripts/main.py

There was no option that allowed the model to run in GPT-4 only mode.
Changed `main.py` module. `parse_argument` function was modified and the `gpt4only` argument was added to the parser. If `gpt4only` is provided by the user then fast_llm_model is set to smart_llm_model just like vice versa is happening in gpt3only mode.
No additional documentation was needed.

GPT-4 Only Option

---

.gitignore

Ignoring local IntelliJ project settings (e.g, Pycharm)
IntelliJ saves its project-specific settings into the .idea folder.
Git should ignore this folder, similar to VS Code settings.

Update .gitignore to ignore potential .idea folder

---

scripts/chat.py
scripts/json_parser.py
scripts/main.py

- Fixes issue #803, and its duplicates;
- #818
- #835
- #858
- #860
- #869
- #887
- Fix #803
- Brings back debug mode
- Replaces all callees from `cfg.debug` to `cfg.debug_mode` that was updated on 5b2d6010dc59bab1026d13bfcd75b37618e573b9
- Remove unnecessary config instance at main.py
I added a test placeholder for the unit test of local cache. I am wondering if we can have the git workflow hook to run basic unit test? @Torantulino

Bugfix for #803 - Debug mode

---

.gitignore

issue: #767
Changes line 10 in the .gitignore from `venv/*` to `*venv/*`
Such a simple change is self-explanatory, not worth the clutter of a comment line in the `.gitignore`. It would be better to add a section about venv in the `README`, these should be a different PR, not this one.
I tested this PR by naming my virtual environment `Auto-GPT-venv`, then pushed to a branch and confirmed the virtual environment directory was ignored.
Thanks, gn.

update gitignore venv/* to *venv/*

---

scripts/json_parser.py

I was receiving an `Invalid JSON` error on pretty much every prompt. Once it was received, it was very difficult to get out of it.
By not having correct_json(json_str) in the try/except, it was still easily possible to throw Invalid JSON errors.
When responses were received with no JSON at all, parsing would fail on attempting to locate the braces.
Tested by running a bunch of prompts. Sorry it's not more scientific than that. Each time I got a parsing error, I added a fix, and now it seems stable.

Fix various JSON input bugs

---

scripts/memory/base.py

Removed a redundant `cfg()` object creation in base.py of memory code section. Tested with a few prompts.

Removed redundant cfg object creation in base memory file

---

scripts/logger.py
scripts/memory/pinecone.py
scripts/memory/redismem.py

When AutoGPT attempts to connect to Redis or Pinecone, it doesn't check if the connection actually works. If it doesn't work a nasty exception is outputted, which can be annoying or overwhelming for new users.
Before performing any commands on Redis, Auto-GPT calls `redis.ping()` to verify the connection. If the connection doesn't work for whatever reason, Auto-GPT will log the following lines to the user:
```
FAILED TO CONNECT TO REDIS  Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
DOUBLE CHECK CONFIGURATION  Please ensure you have setup and configured Redis properly for use. You can check out https://github.com/Torantulino/Auto-GPT#redis-setup to ensure you've set up everything correctly.
```
For pinecone, Auto-GPT …

Improved logging on connection fail to a Memory Backend

---

scripts/file_operations.py

this errors can occur when setting goals in non English's language.

fix  Error: 'charmap' codec can't encode character '\u0142' in position 99: character maps to<undefined>

---

scripts/main.py

config.py is not used anymore to hardcode the OpenAI API key, This is now done in the .env file.  
Remove console output when OpenAI key is not set: "set in in config.py"

remove output to set OpenAI API key in config.py

---

README.md

Fixed twitter link to go to:
https://twitter.com/SigGravitas
Previously it was going to the icon image.

Fix twitter link: in README.md

---

scripts/ai_config.py

Errors may occur when inputting Chinese characters into `ai_setting.yaml` due to encoding issues.
>UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 14: illegal multibyte sequence
Read config files with UTF-8 encoding.
No need to document.
Tested locally & No need to add testcase.

Use UTF-8 encoding for reading config file.

---

docker-compose.yml

Add docker compose so that getting the app running with redis is one command:
```
docker-compose run auto-gpt
```
Introduced a `docker-compose.yml` configuration file that achieves the above
n/a
n/a

Add docker compose scheduling

---

scripts/ai_config.py

When I tested Auto-GPT with Chinese, the ai_settings.yaml configuration file was written in unicode, which was hard to understand. It looks like the following:
```yaml
ai_goals:
- "\u7814\u7A76chatgpt\u7684\u73B0\u72B6\u53CA\u5728\u5B89\u5168\u884C\u4E1A\u7684\
\u5E94\u7528"
- "\u786E\u5B9AChatGPT\u9886\u57DF\u7684\u9876\u7EA7\u4E13\u4E1A\u4EBA\u58EB\uFF0C\
\u7814\u7A76\u4ED6\u4EEC\u7684\u804C\u4E1A\u548C\u7ECF\u9A8C\u3002"
- "\u5236\u5B9A\u4E00\u4E2AChatGPT\u548C\u5B89\u5168\u7ED3\u5408\u8FDB\u884C\u521B\
\u4E1A\u7684\u8BA1\u5212"
ai_name: "\u5B89\u5168\u4E13\u5BB6"
ai_role: "\u4F60\u662F\u4E00\u540D\u5B89\u5168\u884C\u4E1A\u7684\u8F6F\u4EF6\u5DE5\
\u7A0B\u5E08\uFF0C\u4F60\u9047\u5230\u4E86ChatGPT\u7684\u8FDB\u5C55\u3002\u4F60\u9700\ …
```

Resolving Unicode encoding issues

---

Dockerfile

**Background**
The existing Dockerfile in the project can be improved by incorporating best practices and optimizations, such as using a non-root user, setting appropriate environment variables, and reducing image size by disabling caching. These changes will make the Dockerfile more secure, efficient, and compliant with best practices.
**Changes**
- Added environment variables to prevent Python from buffering the output and to disable writing `.pyc` files.
- Created a non-root user named `appuser` to follow the principle of least privilege and updated the ownership of files and folders accordingly.
- Added the `--no-cache-dir` flag to the `pip install` command to prevent caching and reduce the image size.
- Updated the `COPY` command to set the appropriate user and group ownership for …

Improve Dockerfile with best practices and optimizations

---

README.md

While following this guide to enable google search, this step was missing for me and the API calls to https://customsearch.googleapis.com/customsearch/v1?q= failed with: """
Custom Search API has not been used in project <PROJECT_ID> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/customsearch.googleapis.com/overview?project=<PROJECT_ID> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. """
Also, checked that merely https://console.developers.google.com/apis/api/customsearch.googleapis.com redirects to the active project used in the last session in GCP, so no need to provide the projectId parameter.

Enable Custom Search API in gcp project

---

.gitignore
scripts/logger.py

When run from the root of the project `python scripts/main.py` the logger was logging in a directory outside of the project directory (in the parent)
Make the log directory path (`../logs`) relative to the directory the logger file is in (ie. `./scripts/`). This puts the logs dir in the project directory.

More robust log dir path

---

autogpt/commands.py

fix commands.py

---

.env.template
autogpt/config/config.py

There are some unused azure environment variables left in the `env.template` as they are already moved to `azure.yaml.template`.
- Cleanup Azure related env from `env.template`.
- Remove unused azure parameters from `config.py`, also fix the yaml loader syntax with some preset values.
There are notes in `env.template` and the codes in `config.py` is clear enough.
Tested with azure configurations.

Cleanup azure parameters in env.template and remove unused env in config.py

---

.env.template

This is just a suggestion. I know it has pros and cons. But it appears like having 0 as the default would make the model more consistent.
We can wait to implement the benchmark to implement this, but we might be missing out a lot during that time.
People can still put 0 themselves, but new comers might be missing out without knowing.

make 0 the default temperature

---

autogpt/token_counter.py
tests/test_token_counter.py

A few days ago, we've added automated unit tests using Github workflow. This PR expands the coverage of the unit tests by covering the `token_counter.py` module.
- Add unit tests for `token_counter.py`
- Fix minor typo in `token_counter.py`
- N/A
- Unit tests should succeed
- (optional) Ask author(s) of `token_counter.py` and check if they agree

test: Write unit tests for token_counter

---

.env.template
autogpt/__main__.py
autogpt/args.py
autogpt/commands/web_selenium.py
autogpt/config/config.py

Continuation from #1566 since massive nuke merge #1537
In it's current implementation selenium browsing only works with Chrome. And nothing else. This is exclusionary to other users who don't want to or don't have chrome installed.
Additionally I would like to make some changes to allow the user to choose to use the old web-scraping functions.
Added support for 2 more browsers: Firefox and safari. Note that safari doesn't have a driver manager and there's some additional setup the user needs to do to get it working. See [this](https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari) article.
It might be smart to automate the setup (it seems to be a single shell command), so if someone could input if I should do that, that'd be greatly appreciated.
Set …

 Make browsing with Selenium Browser Agnostic 

---

Dockerfile
requirements-docker.txt

I was unable to build the Dockerfile on my M1 Mac. This is due to the sourcery dependency in Python, this is not compatible with aarch64 and also not used while using autogpt, only for pre-commit checks and CI. Therefore I created another requirements file which does not have that dependency, so it will build on multiple CPU architectures.
Created another requirements file which excluded sourcery because it is not compatible with all architectures and also not using in the application itself.

remove sourcery from docker build

---

tests.py
tests/test_prompt_generator.py

Add coverage report generation.
Adjust test_prompt_generator file.
- Remove unused imports.
- Add docstrings.
- Correct checking the presence of key-value pair of the command args dictionary in the generated prompt_string.
- Use setUpClass because we need one time execution of the setup function instead of setUp which is executed each time before each test function.
- Use covearge to load tests and adjust test location.
- Generate test report with missing tests to help in test integration.
Tests impacted are passed before opening the PR.

Adjust test_prompt_generator and add test report generation

---

tests/test_config.py

Clean the file by reducing duplications and add clear docstrings.
- Add Config instance creation to setUp function to reduce duplication.
- Separate defining tests from running them.
- Add function and class docstrings.
All impacted tests are passed

Adjust test_config file

---

autogpt/commands/execute_code.py

System: Command execute_shell returned: Error: 'in <string>' requires string as left operand, not PosixPath
recast variable as a string

Fix for 'requires string as left operand, not PosixPath'

---

autogpt/commands/file_operations.py

Error notation. In the split_file function, line 43, text->content.

Error notation in the split_file function in file_operations.py

---

autogpt/__main__.py
autogpt/app.py
autogpt/args.py
autogpt/commands/execute_code.py
autogpt/commands/git_operations.py
autogpt/commands/web_selenium.py
autogpt/config/config.py
autogpt/json_fixes/auto_fix.py
autogpt/memory/__init__.py
autogpt/memory/milvus.py
autogpt/prompt.py
scripts/check_requirements.py
tests/milvus_memory_test.py
tests/smoke_test.py
tests/test_token_counter.py

Quality update

---

autogpt/llm_utils.py
autogpt/memory/local.py
autogpt/memory/pinecone.py
autogpt/memory/redismem.py

The original embedding function will cause whole process crash when OpenAI or Azure API returns Error. It is necessary to try a few times.
1. move embedding function into llm_utils
2. add try feature within embedding function
It is an improvement for existing feature. I believe only the code review is necessary.
- [ x ] My pull request is atomic and focuses on a single change.
- [ x ] I have thoroughly tested my changes with multiple different prompts.
- [ x ] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x ] I have not snuck in any "extra" small tweaks changes 
I test

Embedding Improvement

---

scripts/json_parser.py

Fixes an issue where double quotes were not being escaped in JSON strings, causing parse errors.

Fix JSON string escaping issue

---

requirements.txt
tests/local_cache_test.py
tests/smoke_test.py
tests/unit/test_browse_scrape_links.py
tests/unit/test_browse_scrape_text.py
tests/unit/test_commands.py

Many approved PR lately. Broke 5 test files
1) Fixing the following tests files:
tests/local_cache_test.py
tests/smoke_test.py
tests/unit/test_browse_scrape_links.py
tests/unit/test_browse_scrape_text.py
tests/unit/test_commands.py
2) Adding pytest to requirements.txt
N/A
Added tests. Didn't change code. In any case, I've run some prompts

fixing tests to fit latest merges into master

---

.env.template
autogpt/app.py
autogpt/commands/audio_text.py
autogpt/config/config.py
autogpt/prompt.py

Background
Addition of a audio transcriber command that uses the huggingface inference API to call an audio to text model. 
Changes
Added a new python file called audio_text.py that contains the read_audio function, which call the huggingface API.
Made changes to prompt.py, the env template, config.py, and app.py to include the read_audio function and make it functional.
Documentation
The changes are implemented as just in code comments.
Test Plan
I tested the changes by added various audio samples to the working directory. Then I asked the agent to transcribe the audio samples and compare the transcribed stories to each other.

Transcribe audio using huggingface

---

requirements.txt

I opened an issue and wish to close #1790 and am making a pull request to resolve it related to module name being absent in requirements.txt
I have added the module tweepy in requirements.txt
I got the error `No Module named 'tweepy'` when I ran the command `python -m autogpt`.

resolved tweepy not in requirements.txt

---

README.md

Elaborates on the .env.template renaming process to reduce the number of questions on the discord server pertaining to API key setting and saving the .env file. I found 489 search results in the discord server for '.env'
```
5. Rename .env.template to .env and fill in your OPENAI_API_KEY. If you plan to use Speech Mode, fill in your ELEVENLABS_API_KEY as well.
```
to
```
5. Locate the file named '.env.template' in the 'Auto-GPT' folder.
Open the ".env" file in a text editor.
Find the line that says "OPENAI_API_KEY=".
After the "=", enter your unique OpenAI API Key (without any quotes or spaces).
Enter any other API keys or Tokens for services you'd like to utilize.
Rename this file to ".env" by removing the ".template" extension.
Use the 'Save as..' option and chose 'No Extension' from …
```

Update README.md .env.template instructions

---

autogpt/config/ai_config.py
autogpt/logs.py

I noticed the prompt had two joined words, so I fixed it by adding a space

Typo in prompt start - missing space resulted in joined words in the prompt

---

autogpt/json_fixes/bracket_termination.py

the logger statement is using '%' which does not convert to a variable
replace 
logger.error("Error: Invalid JSON: %s\n", json_string)
with
logger.error(f"Error: Invalid JSON: {json_string}")

Fix  update bracket_termination.py with f string

---

autogpt/chat.py

Local memory returns documents in descending order of scores, so relevant memory should be popped from right to fit token limit.
Pop relevant memory from right instead of left.
- [ .] My pull request is atomic and focuses on a single change.
- [ .] I have thoroughly tested my changes with multiple different prompts.
- [ .] I have considered potential risks and mitigations for my changes.
- [ .] I have documented my changes clearly and comprehensively.
- [ .] I have not snuck in any "extra" small tweaks changes

Remove least relevant items from memory first

---

autogpt/prompt.py

I think we should only append commands to the prompt which AutoGPT can execute since all configuration parameter is set. 
For example in this change the `Audio to text` command will be only appended to the prompt when the huggingface model is specified. 
Commented in the code
Should work, but I was unable to test.

Only add audio to text command to the prompt if model is set

---

autogpt/commands/file_operations.py

There is a new file logging capability that logs every file operation to file_logger.txt. However, the append operation creates another log line, which creates another append operation, etc.
Added a bool which controls whether the append operation should log.
Trivial
Ran unit tests and verified the file operations from autogpt no longer produce this:
- [x ] My pull request is atomic and focuses on a single change.
- [ x] I have thoroughly tested my changes with multiple different prompts.
- [x ] I have considered potential risks and mitigations for my changes.
- [n/a ] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes

Fix file logging infinite loop issue

---

autogpt/commands/audio_text.py
autogpt/commands/execute_code.py
autogpt/commands/file_operations.py
autogpt/commands/image_gen.py
autogpt/workspace.py

Currently, four commands use three different ways to resolve the workspace path and all implement it themselves. Also, workspace path resolution is broken for `execute_shell`.
PR #1903 also fixes the immediate failure of `execute_code.py` and `image_gen.py`, but does not address the unordered approach in other files.
* Consolidated workspace resolution functionality in `autogpt/workspace.py`
No changes for users, so no docs needed.
Tested by letting Auto-GPT read a file in the workspace, both directly and using `cat`.

Consolidate and fix workspace resolution

---

autogpt/agent/agent_manager.py
autogpt/commands/evaluate_code.py
autogpt/commands/file_operations.py
autogpt/commands/google_search.py
autogpt/commands/improve_code.py
autogpt/commands/web_playwright.py
autogpt/commands/web_requests.py
autogpt/commands/web_selenium.py
autogpt/commands/write_tests.py
autogpt/config/ai_config.py
autogpt/json_fixes/bracket_termination.py
autogpt/json_fixes/parsing.py
autogpt/llm_utils.py
autogpt/memory/local.py
autogpt/memory/no_memory.py
autogpt/memory/redismem.py
autogpt/processing/html.py
autogpt/promptgenerator.py
autogpt/token_counter.py
autogpt/workspace.py

there were some issues where some modules were using the future syntax without the annotations imported from `__future__`. This fixes that and ports all type annotations to future syntax and adds the `from __future__ import annotations` where this future syntax is used to maintain compatibility with older versions of python.
No functional changes other than removing typing imports in favor of the future syntax and adding the required import to do so on python versions < 3.10
No functional changes

unify annotations to future syntax

---

README.md

Add the subtitle in the README to match the Table of Contents

Add "Memory Backend Setup" subtitle

---

.github/workflows/benchmark.yml
.gitignore
autogpt/agent/agent.py
autogpt/app.py
autogpt/json_fixes/bracket_termination.py
autogpt/json_fixes/master_json_fix_method.py
autogpt/json_fixes/parsing.py
autogpt/json_schemas/llm_response_format_1.json
autogpt/json_validation/validate_json.py
autogpt/logs.py
benchmark/benchmark_entrepeneur_gpt_with_difficult_user.py
requirements.txt

we have a lot of issues with json parsing.
- Added benchmarks to measure json errors
- refactored json parsing so that it uses the right methods and has less if conditions
- used the right method to clean the json
- implemented json schema so that we have a clean AI input to work with => we need someone to work on feeding the json validations error back to the AI, so that it corrects its json itself (this is a different problem than JSON parsing)

benchmark json errors, clean json parsing code and implement json schema

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
autogpt/commands/web_selenium.py

Currently dev containers do not contain everything necessary to run AutoGPT, and between different environments installing these dependencies can be quite a mess.
This diff aims to give the containers everything necessary to just follow the readme and get going with auto-gpt in dev containers
- Update dockerfile to pull from know environment, the expectation is on apple silicon people will use rosetta to run this container, this change allows us to install chrome, sourcery and other standard things without much finangling
- Install Chrome, necessary to browse
- add options.add_argument("--no-sandbox") to Chrome startup so it can run in dev containers, this does have bad security implications https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/design/sandbox.md, and we …

Improve dev containers so autogpt can browse the web

---

autogpt/logs.py

Using characters (like “→”) not in cp1252 causes logger to throw error:
`UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 48: character maps to <undefined>`
Added 'utf-8' parameter to Logger's FileHandlers.

add utf-8 encoding to file handlers for logging

---

autogpt/commands/git_operations.py

closes #1971
closes #1734
closes #735 
This change simply wraps the intended clone path with the `path_in_workspace` helper function to ensure output is sent to the working directory

ensure git operations occur in the working directory

---

tests/milvus_memory_test.py

After minimall add pytest (#1859) merged. The test case is not worked. Try to fix it.
```
=================================== FAILURES ===================================
__________________________ TestMilvusMemory.test_add ___________________________
self = <tests.milvus_memory_test.TestMilvusMemory testMethod=test_add>
def setUp(self) -> None:
"""Set up the test environment"""
>       self.cfg = MockConfig()
E       NameError: name 'MockConfig' is not defined
```
call correct `mock_config()`, not `MockConfig()`
```
============================= test session starts ==============================
collecting ... collected 5 items
milvus_memory_test.py::TestMilvusMemory::test_add 
milvus_memory_test.py::TestMilvusMemory::test_clear 
milvus_memory_test.py::TestMilvusMemory::test_get …
```

Fix milvus test Error: 'NameError: name 'MockConfig' is not defined'

---

run_continuous.sh

This pull request aims to improve the usability of the `run_continuous.sh` script by ensuring that all command-line arguments are passed through to the `run.sh` script and the `autogpt` module. The original implementation did not properly pass additional command-line arguments, which could lead to confusion and limited flexibility for users.
- Modified `run_continuous.sh` to include the `--continuous` flag directly in the command:
- Removed the unused `argument` variable.
- Added the `--continuous` flag to the `./run.sh` command.
- Ensured all command-line arguments are passed through to `run.sh` and the `autogpt` module.
The changes made are documented [here](https://github.com/Significant-Gravitas/Auto-GPT/pull/1941#discussion_r1167977442)
1. Tested the `run_continuous.sh` script on a …

Fix: Update run_continuous.sh to correctly pass all command-line arguments

---

autogpt/memory/local.py

When first starting to use the tool, there's a minor formatting issue where there is no space between 2 sentences. This adds a space for better readability
Before 
```
Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.
```
After
```
Warning: The file 'AutoGpt.json' does not exist. Local memory would not be saved to a file.
```
Ran the change locally and observed the results.
No tests added because this is for aesthetic purposes only.

feat: (aesthetic) add space on warning message

---

autogpt/json_fixes/auto_fix.py

There is a noqa comment on `e` even though `e` is used and will not trigger QA. Other lines have `noqa` when it would be better to just not assign to a variable in the first place.
Removed the unused underscore variable assignments and unnecessary comments
I removed erroneous comments
I tested it a bit, but I can't conceive of any negative effects.    Removing assignment to an unused variable does nothing.  Removing an erroneous comment does nothing.

Remove irrelevant noqa comments

---

README.md

I swear one of the top issues users have is not actually having a paid open ai account when using auto-gpt. That or they buy ChatGPT Plus.
Moves probably one of the most important pieces of information in the readme to the top

Add the OpenAI API Keys Configuration to the top of the readme

---

.envrc
.gitignore

Add Nix flakes support through [direnv](https://github.com/nix-community/nix-direnv)
* Nix (https://nixos.org) is a reproducible build system. Having Nix support enables Nix users to develop and use Auto-GPT without having to deal with inner dependencies (such as PIP or any other future Auto-GPT dependency).
* To avoid Nix pollution to Auto-GPT repository, I have made Nix files a discrete repository:
- [github.com/superherointj/nix-auto-gpt](https://github.com/superherointj/nix-auto-gpt/)
* Note: This only affects nix / direnv users and direnv explicitly requests permission from user to enable this.
```
.envrc file is used by direnv (https://github.com/nix-community/nix-direnv)
When direnv is installed and configured, this script runs when openning directory.
It first checks for nix …
```

Add Nix flakes support through direnv

---

autogpt/commands/file_operations.py

Currently split_file will double count the last overlap# chars in a document due to the way we are consuming the chunks
Add logic to handle this case in the split_file function
Commented
Tested with new file_operation unit tests, which will be included in a following PR, and tested with a file operation prompt

Fix split file to handle edge case where overlap size > last chunk size

---

autogpt/speech/brian.py

Using USE_BRIAN_TTS=True, throws this exception:
```
Exception in thread Thread-1 (speak):
WelcomeTraceback (most recent call last):
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/lib/python3.10/threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "/home/gabriel/Auto-GPT/autogpt/speech/say.py", line 34, in speak
success = VOICE_ENGINE.say(text, voice_index)
File "/home/gabriel/Auto-GPT/autogpt/speech/base.py", line 33, in say
return self._speech(text, voice_index)
TypeError: BrianSpeech._speech() takes 2 positional arguments but 3 were given
```
Use the same arguments as used in _speech method from gtts.py as it doesn't need the third parameter "voice_index".
- [ ✓] My pull request is atomic and focuses on a single …

Fix BRIAN_TTS - Prevent TypeError exception in _speech method

---

.github/workflows/pr-label.yml

First we had too many concurrent runs, then the workflow broke.. This should be it.
Set concurrency group even if not triggered by a PR.

fix(pr-label): concurrency group cannot be empty

---

autogpt/llm_utils.py

This is a QoL update for a user facing issue that seems to be pretty common: users not setting up paid accounts and inevitably getting hit with a nasty exception vaguely telling them: "Failed to get response after x retries". This doesn't help anyone.
This PR just improves the logging for this common issue by outputting better logs and directing the user to possible causes for hitting the rate limit.
Added better logging in `llm_utils.py` in the `create_chat_completion` function.

Improve the error logging for OAI Issues

---

autogpt/commands/web_selenium.py

Users on Linux have reported issues with using selenium to open browsers. These fixes should help fix these issues.
Thanks to: timcperks#9664 for providing the flags.
Adds 3 flags when the detected system is linux:
* `--no-sandbox`
* `--disable-dev-shm-usage`
* `--remote-debugging-port=9222`

Add Fixes for Selenium Browsing On Linux

---

pyproject.toml

AutoGPT is now started with `python -m autogpt`, but that can fail if the user simply cloned the repository, and did not install it via pip. Usually, `pip install -e .` is enough to install the source code into PIP, but for that to work, the changes from this PR are necessary (mainly because pip finds other directories such as "output" and "log", and confuses it).
Simply added a `[tool.setuptools]` section to pyproject.toml. This is enough for `pip install -e .` to work properly.
This PR is the documentation.
Tested locally. It does not break things, yet works for the intended purpose.

Allow local Development without pip install using "pip install -e ."

---

autogpt/memory/weaviate.py
tests/integration/weaviate_memory_tests.py

It fixes an issue in the Weaviate integration whereby if a lowercase index name is specified in the MEMORY_INDEX environment variable it will raise a key error when processing Weaviate results
Added static function that replicates the converrsion from index name to classname that the Weaviate python client uses.
A note about the conversion is made in code comment form for the `format_classname` static method.
The current tests have been updated to reflect the conversion from indexname to classname.

fixes Weaviate index name to classname conversion

---

autogpt/app.py

In the process of `google` command, it convert `google_result` to `safe_message` by `encode('utf-8')`, then return it by just `str()`. This will cause the `google_result` becomes a series of hex escaped string, it's hard to read in the process (see `fig1`), and COULD cause exception due to the token size of hex-escaped string usually larger than unicode string (see `fig2`).
(`fig1`: the response of process is hard to read)
(`fig2`: InvalidRequestError: token oversize)
return unicode string (ex.: `宋江（演員）`) instead of hex-escaped sequence (ex.: `\xe5\xae\×8b\xe6\xb1\x9f`)
(`fig3`: expected output)

fix: unreadable text in console and potentially over the max token

---

autogpt/commands/execute_code.py

This change just adds a `str` return type hint to the `execute_python_file` and `execute_shell_popen` functions.

Added return type hint to execute_code.py file

---

.github/workflows/ci.yml

CI currently does not run automatically, instead needs manual execution.
Aims to make CI on PRs run automatically
Untested

Make Continuous Integration Automatic

---

.github/ISSUE_TEMPLATE/1.bug.yml

hotfix issues in template 
* made drop downs required
* formatting fixes

Hotfix bugs template

---

.gitignore
BULLETIN.md
autogpt/cli.py
autogpt/config/config.py
autogpt/configurator.py
autogpt/utils.py

Add the ability to read a file from the web (BULLETIN.md from our repo), and echo that to the user to keep them informed of community announcements, important news and new features, etc.  Especially useful for those not on Discord.
The file itself has information on how to suppress the output.

Added ability to output news/announcements on startup

---

.devcontainer/Dockerfile
.github/workflows/benchmark.yml
.github/workflows/ci.yml
.sourcery.yaml
Dockerfile

CI workflow was updated but now runs twice. Also runs with Python 3.8 which is inconsistent with README (#2342). Python version in other places is also inconsistent.
`pull_request_target` is both risky and unnecessary: CI will already run on `push` in the fork.
* Split `build` workflow into `lint` and `test` workflows
* Run all checks even if some fail
* Fix double PR runs
* Adopted #2343
* Adopted #2107

Move to Python 3.10 & improve CI workflow

---

autogpt/commands/execute_code.py

The first time Auto-GPT tried to run Python code, I didn't have Docker installed. I had to dig through the source code and ask ChatGPT before I got it working, but the issue was a very simple fix (I just had to install Docker). I added an extra `except` clause to the function which will intercept Docker errors and suggest to the users that they may need to install Docker if they haven't already.
The only change was to add an additional `except` clause in the `execute_python_file` function. The except clause prompts the user they may want to install Docker, then returns the error message.
This is a pretty simple addition, and the code is pretty reasonable, so I'd argue it's sufficient documentation in and of itself. (If not I'm happy to add comments)
I ran the function from an interactive …

fix(python-run): prompt users to install Docker when execute_python_file encounters a Docker error

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml

The requirements section of `README.md` says this project requires Python 3.8 _or higher_. Let's make sure that this is at least reflected in the CI.
- Added Python versions 3.9, 3.10 & 3.11 to the Python version matrix in `ci.yml`
The documentation already said the requirements are "Python 3.8 or higher", and this is now also reflected in `ci.yml`.
The CI should succeed for all configured Python versions.

Ensure Python 3.10 & 3.11 compatability

---

.env.template
autogpt/commands/image_gen.py
autogpt/config/config.py
tests/test_image_gen.py

[AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) exposes an API for generating images using it. This feature can be useful for cutting down costs for generating images and allowing flexibility and more power for tweaking image generation. 
By using the API exposed by [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui), we can generate images more efficiently and flexibly. This feature allows us to reduce the costs of image generation and to customize the image generation parameters for different models and settings.
- Added support for using [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) API as an image provider
- Renamed "sd" image provider to …

Image generation improvements

---

README.md

Fixes the Windows run conmmand to '.\run.bat' in the README.md and removes the word `start` in the instructions below
`./run.bat start' to '.\run.bat' and `start` to `./run.bat`

Update README.md Windows run.bat instructions

---

autogpt/processing/text.py

Fix Issue #1211 - gpt-3.5 chunk is  4096 but the default of the split is 8192
Add an option to set the chunk size using the configuration - BROWSE_CHUNK_MAX_LENGTH=4000
This way, we can avoid errors of exceeding chunk size when using gpt-3.5

Fix Issue #1211 - gpt-3.5 chunk is less than the default

---

autogpt/config/config.py

azure_model_to_deployment_id_map default type should be a dict, not list
azure_model_to_deployment_id_map default type chang to be a dict, not list

Update config.py fix: azure_model_to_deployment_id_map default type should be a dict, not list

---

autogpt/config/config.py
autogpt/llm_utils.py
azure.yaml.template

Fix azure config

---

autogpt/workspace.py

One-line fix to solve cases where the workspace is in a symlinked directory subtree

fix(workspace): resolve symlinks in workspace path before checking

---

README.md

Since master should not be used for installation as described in the readme, it would be better to checkout the stable branch immediately when cloning to prevent people from reporting issues that are not in the stable environment.
Documentation update, no tests needed.

doc: update git clone command to use stable branch

---

autogpt/config/config.py
autogpt/plugins.py
tests/unit/test_plugins.py

In an effort to promote more inclusive language within the codebase, this pull request addresses the usage of terms such as "blacklist" and "whitelist". The new terms, "denylist" and "allowlist", have been proposed as more neutral alternatives.
- All instances of the term "blacklist" have been renamed to "denylist".
- All instances of the term "whitelist" have been renamed to "allowlist".
- Ensured that the changes do not impact the functionality of the code.
The renaming of the variables is self-explanatory and does not require additional documentation. However, any external documentation referring to these terms should be updated accordingly.
1. Ensure that all instances of "blacklist" and "whitelist" have been properly replaced with "denylist" and "allowlist", respectively.
2. Run …

Use inclusive language: Rename 'blacklist' to 'denylist' and 'whitelist' to 'allowlist'

---

requirements.txt

As reported in the issue #2514, `browse_website` command fails (in particular, its parsing part) with an error `module 'collections' has no attribute 'Callable'`.
The issue appears on Python 3.10 (3.10.11) as well as 3.11 (3.11.3), and on the following Auto-GPT versions: `master`, `0.2.1`, `0.2.2`, and `0.2.2-test`.
The fix is simply to upgrade BeautifulSoup4 lib to the latest version (my previous version was 4.6.0):
```
pip install beautifulsoup4==4.12.2
```
which is then to be reflected in `requirements.txt` as `beautifulsoup4>=4.12.2`.
Note that this is easier and more elegant fix as the originally proposed in #2596
No in-code documentation needed.
Tested on:
- Python: `3.10`, and `3.11`
- Auto-GPT: `master`, `0.2.1`, `0.2.2`, and `0.2.2-test`.
After upgrading BeautifulSoup4 lib, the …

Pin BeautifulSoup version to fix `browse_website`

---

requirements.txt
scripts/check_requirements.py

* #2654
* Fix `requirements.txt` line splitting in `check_requirements.py`
* Install spacy language model as `en-core-web-sm` so it doesn't mismatch in `check_requirments.py`
* This works with the current config setup, e.g. `BROWSE_SPACY_LANGUAGE_MODEL=en_core_web_sm`
`docker-compose run --build --rm --entrypoint python auto-gpt -c 'import spacy; spacy.load("en_core_web_sm")'`

fix #2654 spacy language model installation

---

autogpt/json_utils/utilities.py

If running from any directory other than **Auto-GPT**,  the program will crash, giving the following error message:
```
File "AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "Auto-GPT\autogpt\cli.py", line 151, in main
agent.start_interaction_loop()
File "Auto-GPT\autogpt\agent\agent.py", line 86, in start_interaction_loop
validate_json(assistant_reply_json, "llm_response_format_1")
File "Auto-GPT\autogpt\json_utils\utilities.py", line 38, in validate_json
with open(f"autogpt/json_utils/{schema_name}.json", "r") as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: …
```

Fix `validate_json` file error when cwd != project root

---

autogpt/commands/image_gen.py

Size parameter was not used in required function parameter.
Adds size variable to functions parameters.

Add missing `size` param to generate_image_with_dalle

---

autogpt/commands/analyze_code.py
autogpt/commands/git_operations.py
autogpt/commands/improve_code.py

call_ai_function use correct python list (not List) would be better.
Fix a few mistakes:
1.  def analyze_code(code: str) -> List[str]:   
List change to correct python list, call_ai_function use correct python list (not List) would be better.
2.  def generate_improved_code(suggestions: List[str], code: str) -> str:  
List change to correct python list, call_ai_function use correct python list (not List) would be better.
3.  Change the spelling error of the function description "Clone Repositoryy" to "Clone Repository".

Fix typo's

---

autogpt/config/config.py

When `azure.yaml` can't be loaded, it now just continues silently even if `USE_AZURE` is set. Instead of breaking later on when the API calls start to fail, it should fail immediately and throw a `FileNotFoundError`.
* Remove `try` / `except` block in `load_azure_config`

Make `load_azure_config` throw if `azure.yaml` does not exist

---

README.md
docker-compose.yml

Since Dockerfile uses `/home/appuser` as workdir, the mounted volume should also be `/home/appuser`, or else we can't persist the written files.
https://github.com/Significant-Gravitas/Auto-GPT/blob/master/Dockerfile#L25
Tested locally.

Fix docker usage readme

---

.coveragerc
.github/workflows/ci.yml
.github/workflows/coverage.yml

Minor issue with CI failing due to push events trying to upload coverage

[Hotfix] Fix coverage tooling

---

autogpt/utils.py

On POSIX systems, the use of `input()` at `clean_input` falls a bit short, since it does not allow for the use of arrow keys to correct mistakes, nor Emacs-like shortcuts that are generally used in the shell (Ctrl-A, Ctrl-E...).
On line 8 of `utils.py`, the module `readline` is imported if available. This is the case for all POSIX systems I know, but not for Windows. Importing `readline` sort of monkeypatches the `input()` global function to make it more user-friendly.
In the future, `pyreadline` could be considered as an alternative for Windows, but this PR disregards it.
Even though I've added two lines, it seems appropriate to let the future readers know why that try-catch statement is there, so I've added a small comment.
1. Run the current version of Auto-GPT and check that arrow …

Use readline if available

---

autogpt/commands/google_search.py

Fixed a typo in `google_search.py` file
- [ x] My pull request is atomic and focuses on a single change.
- [x ] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes 
By submitting this, I agree that my pull request should be closed if I do not fill this out or follow the guidelines.

fixed typo

---

tests/test_config.py

Config values are currently being changed during testing, which effects later tests in the queue.
Example error this can cause:
`openai.error.InvalidRequestError: The model gpt-3.5-turbo-test does not exist`
This PR ensures all values changed during testing are reset after the test.
All code commented.
Tests are still passing on this file.

Fix(tests): restore config values after changing them in tests

---

CONTRIBUTING.md
codecov.yml

This helps ensure the quality of the code stays high. https://docs.codecov.com/docs/commit-status
Adds a coverage.yml file in the format specified by code cov
This is the test

Add CodeCov CI coverage requirements

---

requirements.txt

ModuleNotFoundError: No module named 'selenium.webdriver.safari.options when install <=4.1.3

ci: selenium safari bug fixed

---

autogpt/app.py

It's possible that the plugin args are not in the correct order, use ** instead.

Fix plugin command arg ordering issue.

---

autogpt/plugins.py
tests/unit/test_plugins.py

The current implementation of Auto-GPT supports loading only one plugin per zip file. However, the architecture of [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins) is designed to accommodate multiple plugins within a single Auto-GPT-Plugins.zip file. In order to enable this design, it is essential to update the codebase to enable the loading of multiple plugins from a single zip file.
This pull request introduces a modification to the `inspect_zip_for_module` function in `autogpt/plugins.py`. Instead of exiting early upon discovering a single plugin, the function now compiles a list of all modules found within the zip file. This adjustment enables the loading of multiple plugins from one zip file.
The modifications have been clearly documented through in-code …

Enable support for loading multiple plugins per zip file

---

docs/configuration/search.md

Documentation typo: serach -> search

---

autogpt/memory/milvus.py

https://github.com/Significant-Gravitas/Auto-GPT/pull/2127#discussion_r1174607373
fix module path.

Fix Milvus module config import

---

autogpt/plugins.py

There is a typo in the warning message when Auto-GPT tries to load a plugin which is not allowlisted.
Replace WARNNG to WARNING to be consistent with the other messages. 
N/A
I've checked if the application shows WARNING: instead of WARNNG when a not whitelisted plugin found.

Fix typo in warning message when non allowlisted plugins found

---

autogpt/cli.py

I introduced a regression when working on the LocalCache memory. This patch resolves that bug.  
The bug is caused by the sequencing of information in the global state. The configuration now needs to be initialized and have it's workspace attributes updated before we invoke anything related to the memory system as the memory indirectly depends on the workspace attributes stored in the config.  
Update config with workspace details before invoking memory creation
N/A
Manually reproduced error before the fix and checked error resolution after patch.

Resolve sequencing issue in global state management

---

autogpt/cli.py
autogpt/main.py

This is the first PR on the path to build a comprehensive error log that users can include it in their github issues for faster debugging. It simply adds a layer of indirection between the cli and the application main.  We can then wrap the main invocation easily in a try except block or similar to extract information about the error.
Add a layer of indirection between the cli and the application start
Module docstring, but otherwise no code changes to document.
This PR changes no logic.

Add indirection layer to entry point

---

autogpt/config/config.py

This fixes a simple bug in which one particular log statement emits the RED terminal color code sequence to start writing red text, but does not emit the matching RESET code to switch back to the default color, thus turning all text on the screen red.
The affected log statement is likely to be encountered by new users on first usage, but is unlikely to be seen by experienced users.
This PR properly resets the terminal, ensuring that the red text is red and the normal text remains unaffected, in this one log statement where `Fore.RESET` was previously missing.
N/A
To reproduce: `./run.sh` on a completely clean system with no `.env` file. Notice that all text is red.
- [*] My pull request is atomic and focuses on a single change.
- [*] I have thoroughly tested my changes with multiple …

Ensure Fore.RED is followed by Fore.RESET

---

autogpt/agent/agent.py

a recent merge (#3013 by ) added self-feedback functionality, however, it is trying to read the role from a file with a hardcoded name, which might not even exist causing a crash, and if it exists might not be the one running
this PR changes this from the hardcoded filename to be read from the config object.
Bugfix, no additional documentation

fix: use config instead of hardcoded filename

---

autogpt/api_manager.py
autogpt/commands/image_gen.py
autogpt/config/config.py
autogpt/llm_utils.py

We are currently relying on import time side-effects to make sure we're sending along the user's OpenAI api key.  This is incredibly fragile and has the pattern
```
import openai
openai.api_key = config.openai_api_key
```
proliferating about the codebase.
- Explicitly use the api key from the config when calling openai services.
- Cleanup import time side effects
N/A
CI is working, which covers most of what these import time side effects were meant to allow.  Manual application runs successful as well.

Use explicit API keys when querying OpenAI

---

autogpt/__init__.py
autogpt/commands/twitter.py
autogpt/config/config.py
tests/conftest.py

The .env file is currently loaded in a bunch of places, but canonically is loaded for the creation of the `Config` object.  Other entries have shown up because testing requires it or because some modules can get loaded out of context.  This PR ensures the .env is loaded at the very start of package import so it can happen once and work in all contexts.
- load .env at package import.
N/A
CI & manual application runs function normally.

Load .env in package init

---

.github/workflows/pr-label.yml

The bot is commenting 1000 lines when it should be commenting 200
Add a message with values 200
n/a
test in prod

Fix PR size autolabeler message

---

docs/installation.md

I want to say thank you for the incredible work the AutoGPT library creators have done. I encountered a broken link while reviewing the documentation for Auto-GPT installation at https://significant-gravitas.github.io/Auto-GPT/installation/. Upon further investigation, I can confirm that the issue is caused by a relative URL that leads to an incorrect destination, specifically https://significant-gravitas.github.io/Auto-GPT/README.md#-requirements.
To address this issue, I have taken the necessary steps to modify the requirements URL from a relative to an absolute link, in order to ensure that it points to the correct location. I considered adding the complete link https://github.com/Significant-Gravitas/Auto-GPT/blob/master/README.md#-requirements but considering the sustainability and …

Fix(docs) requirements link in installation guide

---

autogpt/memory/base.py
codecov.yml

Adding changes to codecov yaml, based on our chat with the team
Adding a "patch" coverage setup and instructions for how to setup flags and separate test coverage
https://docs.codecov.com/docs/codecovyml-reference
N/A
- [ x] My pull request is atomic and focuses on a single change.
- [ x] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes

Codecov - don't fail pipelines for project cov changes

---

tests/test_agent_manager.py

not much value calling openai in these unit tests.

mock openai in test agent manager

---

tests/test_image_gen.py

Working from @merwanehamadi 's changes to make these tests work correctly and remove some code duplication.
- Parameterize image size so all models are tested over several sizes.
- Extract a function to generate an image with a provider and validate the image size.
- Remove the `request` args from the funcs as they are not used and a holdover from a closed PR.
- Mark the SD WebUI as xfail because they fail for me.
N/A
All testing here.

Clean up image generation tests

---

autogpt/api_manager.py

The change just fixes a docstring.

fix set_total_budget docstring

---

autogpt/main.py
autogpt/prompts/prompt.py
tests/integration/agent_factory.py
tests/integration/agent_utils.py
tests/integration/goal_oriented/cassettes/test_browse_website/test_browse_website.yaml
tests/integration/goal_oriented/test_browse_website.py
tests/integration/goal_oriented/test_write_file.py
tests/utils.py

Browse website is a command that browses a url and answers a question using the content as an input. Very important for AutoGPT, it can't break
added regression test.

Browse Site Regression test

---

tests/conftest.py
tests/integration/agent_factory.py
tests/integration/agent_utils.py
tests/integration/goal_oriented/test_browse_website.py
tests/integration/goal_oriented/test_write_file.py

Addendum on #3387
* Fix `tests.vcr` imports
* Change `create_browse_agent` to `browse_agent` fixture, `create_write_agent` idem
* Clean up `test_write_file` and `test_browse_website`
See CI

Fix imports, type hints and fixtures for goal oriented tests

---

tests/integration/test_llm_utils.py

There are many open issues related to the maximum tokens allowed to be passed to the embedding.  This is a quick regression test to formally document the issue.
There are many related PRs and issues: 
- #3222 
- #2801 
- #2871
- #2906 
- #3244 
Add regression test for attempting to embed a string that's too long.
Comments in the test explaining what it's for.
This

Add a regression test for the embedding

---

autogpt/agent/agent.py
autogpt/json_utils/utilities.py
autogpt/llm/chat.py
autogpt/memory_management/store_memory.py
tests/integration/cassettes/test_memory_management/test_save_memory_trimmed_from_context_window.yaml
tests/integration/test_memory_management.py

Currently the memory is added at the cycle number 2. it doesn't make sense because we don't need memory if the context window is small.
add the memory only when the context window is full. We happen to have a while loop that does exactly that, so I just inserted the memory in there.
Also, we only want to add memory when we hit a json reply, not a command system or user input.
When we hit an assistant reply, we look at the message after it and we see if it's a user input or Command result.
We then append the assistant reply and user input or command result

Fix memory by adding it only when context window full

---

tests/integration/challenges/memory/cassettes/test_memory_challenge_b/test_memory_challenge_b.yaml
tests/integration/challenges/memory/test_memory_challenge_a.py
tests/integration/challenges/memory/test_memory_challenge_b.py
tests/integration/challenges/utils.py

Master only beats memory challenge B level 1. It fails at level 2.
By adding this challenge we can test the new summary implementation of Toran
- Put one task id per file
- put noise in the file to quickly consume all the context window.
Expected result: auto-gpt should remember all the ids.

Feature/challenge memory challenge B

---

tests/integration/test_git_commands.py

Git clone command was completely broken recently, to prevent it top happen again we need tests.
Added tests for clone_repository command.

added tests for clone_repository

---

autogpt/commands/file_operations.py
tests/unit/test_file_operations.py

rename search_files to list_files

---

autogpt/memory_management/summary_memory.py

An issue was caused by the update_running_summary function, which was directly modifying the new_events list passed as an argument. Since the new_events list is a part of the full_message_history, any modifications made to the new_events list would also affect the original full_message_history.
Create a copy of the new_events list: To avoid modifying the original new_events list and full_message_history, a copy of the new_events list was created using new_events.copy(), and the copy was named updated_new_events. Then added `updated_new_events` to the prompt.

Fix side effects on message history

---

autogpt/json_utils/utilities.py

validate_json is throwing error when used from tests
Set scheme patch to be relative to the .py file

Fix `validate_json` scheme path

---

autogpt/agent/agent.py

Large command outputs can currently cause a crash in the subsequent cycle, by overflowing the prompt of `update_running_summary`. Until we have a robust way to handle large amounts of data, this should at least prevent crashes on such instances.
* Added a check to the agent interaction loop that catches command outputs
* pass a warning to the LLM when this happens

Add warning for LLM to avoid context overflow

---

autogpt/core/configuration/base.py

Initial proposal for the abstract base class for the `Configuration` subsystem. Part of re-arch #3717. Discussion thread on [discord](https://discord.com/channels/1092243196446249134/1103540097384718438). Looking for feedback
- added accessors for other subsystem configs. open to suggestions for different name ideas.
- added `set_defaults` abstract method.
The expected use would be something like
```python
agent_system_classes = [
Workspace,
PluginManager,
Planner,
...
]
configuration.set_defaults(agent_system_classes)
```
A concrete implementation can choose a container (a dict) for example. Ideally the implementation defines something like a TypedDict for the return types of the accessors (or something static analysis-friendly).
Open to suggestions on this...

Proposed Configuration ABC

---

autogpt/core/planning/base.py

Update Planner Interface

---

docs/challenges/beat.md
docs/challenges/challenge_template.md
docs/challenges/introduction.md
docs/challenges/list.md
docs/challenges/memory/challenge_a.md
docs/challenges/memory/challenge_b.md
docs/challenges/memory/introduction.md
docs/challenges/submit.md
mkdocs.yml

We want to be able to give a link to people so they can :
- understand what challenges are
- browse  challenges
- create challenges
- run challenges and submit the solution

community challenges in the wiki

---

autogpt/core/configuration/base.py
autogpt/core/llm/base.py
autogpt/core/planning/base.py

This PR adds the base abstraction for the language model and adjusts some of the interface of the Planning model to create their communication contract.

Add language model base and work out interactions with planning manager

---

autogpt/core/messaging/base.py

Initial base.py for message broker agent-state-encapsulation

---

autogpt/core/command/base.py

- Added command and command registry as discussed in the re-arch meeting.
- Mainly a port of the existing interface 
- Added pre and post hooks
- Added command result data class. This will change a little bit on what to do with the result, however no change to any existing commands.
- The original method to execute commands was to have a function with the command register and command name ([code](https://github.com/Significant-Gravitas/Auto-GPT/blob/f2bef76368e792eeccf2309690da0da662690cc0/autogpt/app.py#L92)), in this function the command result is then added to memory by getting the memory module. This is separated out here for the sake of modularity and understandability - it feels like this is something that should happen in the acting section of the agent and be configurable there. …

Command Base Class Interface

---

autogpt/core/command/base.py
autogpt/core/messaging/base.py

Updates the abstract interface for the message broker as it starts to meet the real world in #3969

Revise message broker interface

---

.github/ISSUE_TEMPLATE/2.feature.yml
.github/workflows/ci.yml
.github/workflows/docker-ci.yml
requirements.txt

Our current testing suite takes a significant amount of time to execute, which slows down the development process and reduces the team's productivity. To address this issue, we have decided to integrate the pytest-xdist plugin into our project. This plugin enables parallel and concurrent testing, which will help speed up our test execution and provide faster feedback to developers.
- Added pytest-xdist to the project's requirements.txt file.
- Modified CI/CD pipeline configuration to include parallel testing options for pytest. The following files were modified in _.github_ folder:
1. _docker-ci.yml_ 
2. _ci.yml_
GitHub CI workflow.

Integrate pytest-xdist Plugin for Parallel and Concurrent Testing

---

autogpt/memory_management/summary_memory.py

Updated the update_running_summary to fix JSONDecodeError in your Python script. This error typically occurs when there is an issue with the JSON data being parsed. In this case, it seems like the JSON decoder is expecting a value at line 1 column 1 (char 0), but it doesn't find one.

Catch JSON error in summary_memory.py

---

Dockerfile

There is no way to install plugin dependencies with Docker 
Added the --install-plugin-deps arg to the Entrypoint.

Added --install-plugin-deps to Docker

---

autogpt/commands/command.py

Having a command with the same name overwrites the first one even if the second one is disabled.
Do not register a command if the command is disabled. Add warning if something is gonna overwrite a command.
https://github.com/Significant-Gravitas/Auto-GPT/issues/3904

Fix commands with same name overwriting

---

autogpt/prompts/prompt.py

trivial fix for people on github asking where the workspace is located, for instance:
- #2793
- #1930
- #3199
- #4060
- #874
- #1764
Should probably be extended to also suggest that people can put their files there for the agent to find them, e.g. to provide more in depth goals:
- #1930
- https://github.com/Significant-Gravitas/Auto-GPT/issues/3552#issuecomment-1530141766
- #1469

Show workspace during startup / fix for #2793

---

autogpt/agent/agent.py

Using self feedback was crashing Auto-GPT
See #4275 for more details
Fix the parameters being passed to the create_chat_completion within self feedback
N/A
Tested the relevant codepath manually

fix: completion was being called with wrong data types

---

docs/setup.md

Azure docs are unclear
Adds a note about the deployment name not being the deployment ID
Only Docs changes
Setup Azure

Improve Azure setup wording in docs

---

autogpt/commands/google_search.py
tests/integration/test_google_search.py

The new [duckduckgo_search](https://github.com/deedy5/duckduckgo_search) version deprecated the ddg function and max_result parameters. Users are seeing the following warning messages when auto-gpt executes google command.
*\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:20: UserWarning: ddg is deprecated. Use DDGS().text() generator warnings.warn("ddg is deprecated. Use DDGS().text() generator")
UserWarning: parameter max_results is deprecated, use DDGS().text() warnings.warn("parameter max_results is deprecated, use DDGS().text()")
This fixes #4376 
Migrate the search func to use the new function and use islice to limit the iterators up to max_results. Itertools.islice handles the iterators in an efficient way. Itertools is a module in python. …

Migrate google search to use DDGS.text function

---

.github/workflows/ci.yml
.github/workflows/docker-ci.yml

Added `timeout-minutes: 30` for the normal and docker tests.

Add 30 min timeout for tests

---

docs/setup.md

I'm trying to make the instructions in the setup doc more easy-to-follow. Users are confused with the current steps, e.g. whether to create the folder in the docker container or in the project folder. There's a recent question/feedback from a user in tech support channel.
https://discord.com/channels/1092243196446249134/1098744126461198447/1103984881526116432
Reordered the steps for docker compose so that it's more intuitive to follow. To avoid confusion, we should instruct users to complete the project directory creation and add relevant files in the folder first, before pulling the docker image and running docker compose.
```shell
black .
isort .
mypy
```

Improve the steps for running docker compose in the setup documentation

---

tests/integration/test_image_gen.py

Dalle wasn't using VCR
```shell
black .
isort .
mypy
```

add vcr to dalle

---

BULLETIN.md
requirements.txt
tests/integration/agent_factory.py
tests/integration/challenges/current_score.json
tests/integration/challenges/debug_code/data/two_sum.py
tests/integration/challenges/debug_code/data/two_sum_tests.py
tests/integration/challenges/debug_code/test_debug_code_challenge_a.py

- VCRPy currently breaks our flow as described here: https://github.com/Significant-Gravitas/Auto-GPT/pull/3926
- Moves the code to be executed and tests to their own files
-  Uses our self hosted fork of vcrpy
- Appears to work! (The first time)
-  In order to support this new fork, we have to remove vcrpy and install it as new urls do not trigger a re-install in requirements.txt and update/re-install flags do not work there. 
- Because of this bulletin update, I also added in the bulletin for @p-i- for version 0.3.1
- Code comments throughout.
- Bulletin update explaining the breaking challenge change.
- This is a test :)

Create "Debug Code Challenge"

---

.github/workflows/docker-ci.yml
.github/workflows/pr-label.yml

We push cassettes and the current score after a push event, there is no need to trigger the other workflows after this is pushed.
```shell
black .
isort .
mypy
```

Ignore cassettes and current score for all push events

---

.github/workflows/ci.yml

CI currently breaks quite easily because we use `pull_request_target`: https://github.com/Significant-Gravitas/Auto-GPT/actions/runs/5154842393/jobs/9287034366#logs
* Use `pull_request` instead of `pull_request_target` for internal pull requests
* Clean up CI workflow
* Fix git authentication set-up
See checks below: since this is an internal PR, the CI runs on `pull_request`. For PRs from forks, it should still run on `pull_request_target`.

Fix CI for internal PRs with CI changes

---

BULLETIN.md

Remove news about config
```shell
black .
isort .
mypy
```

remove news about config

---

.github/workflows/ci.yml
tests/integration/challenges/current_score.json
tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_b.py

Now python packages are cached in the ci pipeline.
```shell
black .
isort .
mypy
```

Cache Python Packages in the CI pipeline

---

tests/integration/test_web_selenium.py

The test needed the patched_api_requestor  from openai
```shell
black .
isort .
mypy
```

Fix `test_web_selenium`

---

tests/integration/challenges/current_score.json

Information retrieval challenge B and debug challenge A are flaky, they don't pass reliably.
We're going to skip them for now to not waste people's time, but we will put them back as soon as possible.
```shell
black .
isort .
mypy
```

Skip flaky challenges

---

BULLETIN.md

Sources:
* the draft release notes [here](https://pad.bitlair.nl/p/4VKUxQtt4amo0Wpdxg-x)
* [the release notes of v0.3.1](https://github.com/Significant-Gravitas/Auto-GPT/releases/tag/v0.3.1)
* https://github.com/Significant-Gravitas/Auto-GPT/milestone/5?closed=1

Add highlights for v0.4.0 release to BULLETIN.md

---

autogpt/commands/file_operations.py
tests/unit/test_file_operations.py

See #3643 
```shell
black .
isort .
mypy
```

Add `replace_in_file` command to change occurrences of text in a file

---

.github/workflows/ci.yml
tests/integration/challenges/basic_abilities/test_write_file.py
tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_a.py
tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_b.py
tests/integration/challenges/kubernetes/test_kubernetes_template_challenge_a.py
tests/integration/challenges/memory/test_memory_challenge_a.py
tests/integration/challenges/memory/test_memory_challenge_b.py
tests/integration/challenges/memory/test_memory_challenge_c.py

https://github.com/Significant-Gravitas/Auto-GPT/actions/runs/5181119242/jobs/9336197276?pr=4581
Update cassettes steps don't work. this is the fix.
- fix the update cassettes step
- removed some code and simplified the ci.yml
```shell
black .
isort .
mypy
```

Fix "update cassettes" step

---

autogpt/commands/execute_code.py
tests/integration/test_execute_code.py

- The logic for checking `deny_command` is inverted. Before this change `deny_command` didn't work as expected.
- Invert `deny_command` check so that it returns `False` if the command includes a `deny_command`
- Created a failing test and then fixed the code
```shell
black .
isort .
mypy
```

Fix inverted logic for deny_command

---

tests/challenges/utils/build_current_score.py

Master now needs to be in sync with this commit https://github.com/Significant-Gravitas/Auto-GPT-test-cassettes/commit/dbea803947475a53ee764aa4f74f304796f197fc
- updated submodule
- added a change with that, because otherwise the push event will be ignored, because of this line in the CI
```
name: Python CI
on:
push:
branches: [ master, ci-test* ]
paths-ignore:
- 'tests/Auto-GPT-test-cassettes'
- 'tests/challenges/current_score.json'
```
The change allows to get rid of useless commits. Sometimes we need to edit the current_score.json and it adds a new line, but when we create the current_score.json automatically the new line is not added, leading to stupid commits: 
```shell
black .
isort .
mypy
autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports autogpt tests …
```

Update cassette submodule

---

tests/challenges/basic_abilities/test_write_file.py
tests/challenges/current_score.json
tests/integration/agent_factory.py

- Now the test to write file uses the default commands, and gives less hints regarding what to do.
- the level asks to write 2 files in only 1 cycle, which will require AutoGPT's code to change.
```shell
black .
isort .
mypy
```

Make challenge "write file" harder + add level 2

---

.github/workflows/ci.yml

Upload logs as artifacts so we can see why some tests failed.
- added the github action
```shell
black .
isort .
mypy
```

Upload logs as artifact

---

autogpt/utils.py
docs/challenges/building_challenges.md
requirements.txt
tests/challenges/utils.py
tests/integration/test_setup.py

Keyboard arrow keys and shortcuts don't work in the CLI. We can use a library to help.
I saw #2838 but it's a super old branch so I started a new PR that has the smallest possible change.
This enables:
- Left/right arrow to go back/forwards on the current line.
- Keyboard shortcuts (e.g. to go back to the start of the line press `^a` on mac/linux)
- History (press up arrow to cycle through previous commands)
If we want in the future we can do autocomplete and stuff, but this is the smallest change with the biggest benefit.
- Use `prompt_toolkit` over `input`
No user change except it will be less annoying
- Updated the mock in challenges
- Tested manually on mac and linux (don't have a windows box but it's cross platform)
```shell
black .
isort .
mypy
autoflake --remove-all-unused-imports …
```

Use prompt_toolkit to enable keyboard navigation in CLI

---

autogpt/memory/message_history.py
tests/unit/test_message_history.py

Left some extra spaces in the summarization prompt when making the batch summarization change #4652
Removed the extra spaces
Reran the tests and succeeded
```shell
black .
isort .
mypy
```

Remove extra spaces in summarization prompt

---

autogpt/commands/file_operations.py
tests/unit/test_file_operations.py

`split_file` is not in use since #4208, see https://github.com/Significant-Gravitas/Auto-GPT/pull/3757#issuecomment-1586359778
* Remove `split_file` in file_operations.py
* Remove unit test for `split_file`
x
```shell
black .
isort .
mypy
```

Remove unused function `split_file` from file_operations.py

---

autogpt/log_cycle/log_cycle.py
autogpt/memory/message_history.py
tests/challenges/basic_abilities/test_browse_website.py
tests/challenges/basic_abilities/test_write_file.py
tests/challenges/challenge_decorator/challenge.py
tests/challenges/challenge_decorator/challenge_decorator.py
tests/challenges/conftest.py
tests/challenges/debug_code/test_debug_code_challenge_a.py
tests/challenges/information_retrieval/test_information_retrieval_challenge_a.py
tests/challenges/information_retrieval/test_information_retrieval_challenge_b.py
tests/challenges/kubernetes/test_kubernetes_template_challenge_a.py
tests/challenges/memory/test_memory_challenge_a.py
tests/challenges/memory/test_memory_challenge_b.py
tests/challenges/memory/test_memory_challenge_c.py
tests/challenges/memory/test_memory_challenge_d.py
tests/challenges/utils.py
tests/integration/test_web_selenium.py

When downloading logs from benchmarks.yml and ci.yml, we don't know the challenge being run.
- added challenge name and level to logs
- added back the fix for selenium tests
- removed whitespaces from summarize_batch method
```shell
black .
isort .
mypy
```

Add challenge identifiers to pytest

---

autogpt/log_cycle/log_cycle.py

Pointed out by user Saven in Discord VC: Auto-GPT will crash on Windows if the AI's name has a space as its 16th character:
* `create_outer_directory` -> `get_agent_short_name` truncates the AI name to 16 characters and uses it to create a folder
* space is stripped from the end of folder name -> created folder has no space at the end
* `create_inner_directory` fails because it expects the outer directory to have the space in the path
* Strip any whitespace from the end of the truncated AI name
x
x
```shell
black .
isort .
mypy
```

Strip spaces from the end of truncated ai_name in log_cycle.py

---

autogpt/memory/message_history.py

This PR addresses an oversight in my previous PR #4652, which introduced a new batch processing approach within the update_running_summary function. The goal of this approach is to prevent the total token count from exceeding the model's maximum limit when new events are being processed. While this method accounted for the token length of new events and the summarization prompt, it failed to consider the length of the current summary.
In the modified version, a summary_tlength variable has been introduced in the update_running_summary function. This variable holds the token length of the current summary, ensuring the total token count of three components: 1) the current summary, 2) the new events, and 3) the summarization prompt, does not surpass the maximum token limit imposed by the …

Incorporating current summary length in token count calculation for the update_running_summary function

---

.github/workflows/benchmarks.yml
tests/challenges/conftest.py
tests/vcr/__init__.py

Benchmarks retry tests once if they fail. If they use cassettes, the second test is doomed to fail as well.
- add --record-mode=all to benchmarks.yml so that we record interactions but without replaying them
```shell
black .
isort .
mypy
```

Make Benchmarks write cassettes without using them

---

autogpt/commands/file_operations.py
autogpt/main.py
autogpt/memory/vector/__init__.py
autogpt/memory/vector/memory_item.py
autogpt/memory/vector/providers/json_file.py
data_ingestion.py
tests/conftest.py
tests/integration/agent_factory.py
tests/integration/memory/test_json_file_memory.py

`JSONFileMemory` will write memories to a file, but can't yet load them back from a file. This PR fixes that.
* Implement loading `MemoryItem`s from JSON index file
* Remove `init` param from `get_memory()`, replace usages by `memory.clear()`
* Make token length calculation optional in `MemoryItem.dump()`
x
I added a test for `JSONFileMemory.load_index()`, so if CI is green we're good
```shell
black .
isort .
mypy
```

Implement loading `MemoryItem`s from file in `JSONFileMemory`

---

.gitignore
autogpt/llm/api_manager.py
autogpt/llm/utils/token_counter.py

we route each models to a tiktoken encoding model
```shell
black .
isort .
mypy
```

Count tokens with tiktoken

---

autogpt/plugins/__init__.py

Legacy zipped plugins don't load on 0.4.1, and instead emit a "plugin not configured" warning. The reason appears to be the move from class-based config keys to directory-based config keys.
This PR enables class-based config keys for zipped plugins, which allows legacy plugins to load.
Updated the code that checks whether a zipped plugin is configured to do so within the plugin load loop, where the class name is available, and updated the emitted debug and warning logs.
No change to docs as this is the legacy behavior.
```shell
black .
isort .
mypy
```

Improve plugin backward compatibility

---

autogpt/agent/agent.py
autogpt/app.py
tests/unit/test_execute_command.py

There was a regression introduced recently for plugins. Issue https://github.com/Significant-Gravitas/Auto-GPT-Plugins/issues/202
Fix the plugin issue by changing the args to the execute_command function
```shell
black .
isort .
mypy
```

Fix execute_command coming from plugins

---

autogpt/command_decorator.py

This piece of code is making a call to the config singleton and we want to get rid of this singleton.
This code is only useful to prevent use of a command if the AI decides to use it. But it's very unlikely it decides to use it because it's not even in the prompt, since this piece of code makes sure of it: 
autogpt/prompts/generator.py
```
if item_type == "command":
command_strings = []
if self.command_registry:
command_strings += [
str(item)
for item in self.command_registry.commands.values()
if item.enabled => HERE
]
command_strings += [self._generate_command_string(item) for item in items]
return "\n".join(f"{i+1}. {item}" for i, item in enumerate(command_strings))
```
- Remove the call to config() in command decorator.
```shell
black .
isort .
mypy
autoflake …
```

Remove config from command decorator

---

autogpt/commands/execute_code.py
autogpt/json_utils/utilities.py

Issue reported on Discord. This is due to garbage that the AI sends back when a response includes code. Functions will fix this. In the meantime:
- Fix argument name in `execute_python_code`
- Lower level of response parse errors
- Add debug message so it's easier to see what was messed up
```shell
black .
isort .
mypy
```

Fix issues with execute_python_code responses

---

autogpt/llm/utils/__init__.py

https://github.com/Significant-Gravitas/Auto-GPT/pull/4744
it needs to be an internal PR
```shell
black .
isort .
mypy
```

Retry 503 OpenAI errors

---

autogpt/config/config.py
docs/challenges/building_challenges.md
requirements.txt
tests/challenges/challenge_decorator/challenge_decorator.py
tests/conftest.py
tests/integration/agent_factory.py
tests/integration/memory/test_json_file_memory.py
tests/integration/test_image_gen.py
tests/integration/test_setup.py
tests/integration/test_web_selenium.py
tests/utils.py

There were a few more calls to config() in the codebase.
- removed remaining calls to config()
- removed config being a singleton. This means it's not allowed to call it initialize it twice in the autogpt folder. (we still initialize it once in pytest.
- removed flaky because it's slowing down the pipeline: a flaky challenge should be discarded from the pipeline anyway, there is no point keeping it.
- the service unavailable 503 error is a new error OpenAI has been giving recently, we want to retry that so it's been added to the retry_api decorator.
```shell
black .
isort .
mypy
```

Remove config singleton

---

autogpt/json_utils/utilities.py

The JSON invalid error is a giant red error everyone sees even witout the debug flag
Make JSON errors more silent by using debug instead of error.
```shell
black .
isort .
mypy
```

Make JSON errors more silent

---

autogpt/commands/execute_code.py
tests/integration/test_execute_code.py

```shell
black .
isort .
mypy
```

Fix up Python execution commands

---

benchmarks.py
tests/challenges/basic_abilities/test_browse_website.py
tests/challenges/basic_abilities/test_write_file.py
tests/challenges/debug_code/test_debug_code_challenge_a.py
tests/challenges/information_retrieval/test_information_retrieval_challenge_a.py
tests/challenges/information_retrieval/test_information_retrieval_challenge_b.py
tests/challenges/kubernetes/test_kubernetes_template_challenge_a.py
tests/challenges/memory/test_memory_challenge_a.py
tests/challenges/memory/test_memory_challenge_b.py
tests/challenges/memory/test_memory_challenge_c.py
tests/challenges/memory/test_memory_challenge_d.py
tests/challenges/utils.py
tests/integration/agent_factory.py

Currently there is only one challenge linked to the benchmarks.py file. We need all the challenges linked to this benchmarks.py
- Changed the test to use the run_task method
```shell
black .
isort .
mypy
```

Link all challenges to benchmark python hook

---

autogpt/llm/providers/openai.py
tests/unit/test_retry_provider_openai.py

This is the PR for retrying when a `ServiceUnavailableError` occurs. 
This is an improved version of #4744 .
The code has been modified to perform a retry operation when a `ServiceUnavailableError` (503 error) occurs.
[The original code](https://github.com/Significant-Gravitas/Auto-GPT/blob/de97097db15c7a10eadaece9ad01bc5d760f5c13/autogpt/llm/providers/openai.py#L194) handles specific exceptions such as `APIError` and `Timeout` that occur when calling the OpenAI API. When one of the two exceptions occurs, Auto-GPT checks if the HTTP status code of that exception is 429, 502, 503, or if the default number of retry attempts (num_attempts) has been reached. If so, it rethrows (raises) the exception.
However, when specific exceptions such as `APIError` and `Timeout` occur, the HTTP status …

Retry ServiceUnavailableError

---

autogpt/config/config.py
autogpt/configurator.py
autogpt/core/configuration/schema.py
autogpt/main.py
autogpt/plugins/__init__.py
benchmarks.py
data_ingestion.py
tests/conftest.py
tests/integration/agent_factory.py
tests/integration/memory/utils.py
tests/unit/test_config.py
tests/unit/test_plugins.py

We can start integrating some of the elements of the rearch in master. Thanks @collijk !
- Add the new Configuration class along with other methods and classes coming straight from the rearch
- integrated the config with these new objects.
- clearly separate default values from the rest of the logic.
- clearly separate what comes from the env from the rest of the logic (so that we can build a config without an env file.
- Code cleanup
```shell
black .
isort .
mypy
```

Use Configuration of rearch

---

autogpt/agent/agent.py
autogpt/config/config.py
autogpt/configurator.py
autogpt/core/configuration/schema.py
autogpt/llm/providers/openai.py
autogpt/logs.py
autogpt/main.py
autogpt/plugins/__init__.py
benchmarks.py
data_ingestion.py
tests/conftest.py
tests/integration/agent_factory.py
tests/integration/memory/utils.py
tests/unit/test_config.py
tests/unit/test_plugins.py
tests/unit/test_retry_provider_openai.py

https://github.com/Significant-Gravitas/Auto-GPT/pull/4810 but for release-branch.

Filtering out ANSI escape codes in printed assistant thoughts

---

autogpt/main.py

This commit changes the `run_auto_gpt` function in `main.py`
to unregister commands which are ultimately incompatible
with the config and would be disabled when the config was injected.
This way, the LLM and only ever sees commands that can run.

Unregister commands incompatible with current config.

---

autogpt/processing/text.py

`summarize_text` is currently broken, because it calls itself with the wrong args (missing `config`).

fix for #4813

---

autogpt/config/config.py
autogpt/main.py

As per https://github.com/pydantic/pydantic/issues/1729#issuecomment-1300576214, the implementation of `model_post_init()` is postponed until Pydantic v2. As a result, the initialization of PluginConfig is being skipped.
This fix calls `plugin.model_post_init()` explicitly.
The recency of the Pydantic v2 release means that some of the other extensions we use do not support it yet. Specifically, extensions such as spacy and openapi-python-client are currently limited to Pydantic versions that are less than 2.0. There may be other extensions that have the same limitation as well.

Hotfix - call model_post_init explicitly until pydantic 2.0

---

autogpt/plugins/__init__.py
autogpt/plugins/plugins_config.py

Simplified plugin log messages to make plugin debugging easier

Simplified plugin log messages

---

tests/challenges/basic_abilities/test_write_file.py
tests/challenges/memory/test_memory_challenge_a.py

This PR is intended to fix the errors at the following URL.
https://github.com/Significant-Gravitas/Auto-GPT/actions/runs/5461866933
As can be seen in the URL below, an error occurs during the `__init__` process of the `api_requestor` in the openai library, within `original_init` in `tests/vcr/__init__.py`.
https://github.com/Significant-Gravitas/Auto-GPT/actions/runs/5461866933/jobs/9940430084#step:7:202
This seems to be because `config` defined as a pytest.fixture in the `tests/conftest.py` is not being called during the execution of the pytest, causing `os.environ["OPENAI_API_KEY"]` to become `None`. So, modifying files, as shown below, will resolve this issue.
```python
@challenge()
def test_write_file(
+   config: Config,  # or agent: Agent
patched_api_requestor: None,
monkeypatch: …
```

Fix errors in Mandatory Tasks of Benchmarks

---

.env.template
autogpt/agent/agent.py
autogpt/config/config.py
autogpt/configurator.py
autogpt/llm/chat.py
autogpt/llm/utils/__init__.py
autogpt/memory/message_history.py
autogpt/processing/text.py
autogpt/setup.py
azure.yaml.template
docs/configuration/options.md
docs/setup.md
docs/usage.md
tests/unit/test_agent_manager.py
tests/unit/test_config.py
tests/unit/test_message_history.py

- Use GPT-4 as default smart LLM in Agent
- Rename (smart|fast)_llm_model to (smart|fast)_llm everywhere
OpenAI just announced GPT-4 general availability: https://openai.com/blog/gpt-4-api-general-availability
UPDATE: "general availability" only applies to existing developers "with a history of successful payments" for now. :(
> **Warning**
> While testing manually, I experienced a one-time anomaly where it told me `openai.error.InvalidRequestError: The model: 'gpt-4' does not exist`. Subsequent attempts were successful.
* Set GPT-4 as the default Smart LLM
* Use the Smart LLM in the main Agent loop
* Rename `smart_llm_model` to `smart_llm` and `fast_llm_model` to `fast_llm` everywhere (with backwards compatibility)
yes
CI
```shell
black .
isort .
mypy
autoflake …
```

Use GPT-4 in Agent loop by default

---

autogpt/agent/agent.py
autogpt/logs.py
autogpt/main.py
autogpt/speech/base.py
autogpt/speech/gtts.py
autogpt/speech/macos_tts.py
autogpt/speech/say.py
autogpt/speech/stream_elements_speech.py

Tss is broken (see #4794).
* Fixed the interfaces for the tts classes.
* Fixed the usage of the say_text() command.
* Made a hack in logger for the config.
Manually tested on win10 gtts. There is currently sound playing.
- [ * ] My pull request is atomic and focuses on a single change.
- [ * ] I have thoroughly tested my changes with multiple different prompts.
- [ * ] I have considered potential risks and mitigations for my changes.
- [ * ] I have not snuck in any "extra" small tweaks changes. 
- [ * ] I have run the following commands against my code to ensure it passes our linters:
```shell
black .
isort .
mypy
```

Bugfix fixtts

---

autogpt/logs.py
autogpt/main.py
tests/conftest.py

`PLAIN_OUTPUT` only works when combined with a monkeypatch applied by a pytest fixture.
* Remove the `patch_emit` fixture
* Patch the output handler in `Logger` when `config.plain_output` is `True`
x
* Tested manually
* CI
```shell
black .
isort .
mypy
```

Fix PLAIN_OUTPUT for normal execution

---

autogpt/core/README.md
autogpt/core/ability/schema.py
autogpt/core/agent/simple.py
autogpt/core/planning/strategies/next_ability.py
autogpt/core/runner/cli_app/cli.py
autogpt/core/runner/cli_app/main.py
requirements.txt

I made several changes to merge the re-arch to master.  I left a couple of mistakes.
- Add a missing requirement (`inflection`)
- Remove a defunct command (`status`)
- Remove a leftover configuration option.
- Fix bad instructions in the readme.
```shell
black .
isort .
mypy
```

Fix bugs running the core cli-app

---

autogpt/config/config.py

The config args are listed as a big disorganized blob.  This is just some organization ahead of some logic cleanup.
- Organize the config args into groups with headings.
- Reduce duplication by setting the defaults on the config class.
Headings for config groups.
CI.  This pr has no logic changes.
- [] I have thoroughly tested my changes with multiple different prompts.
```shell
black .
isort .
mypy
```

Organize the configuration args

---

autogpt/agent/agent.py
autogpt/app.py
autogpt/command_decorator.py
autogpt/commands/file_operations.py
autogpt/commands/web_search.py
autogpt/configurator.py
autogpt/core/README.md
autogpt/core/ability/schema.py
autogpt/core/agent/simple.py
autogpt/core/planning/strategies/next_ability.py
autogpt/core/runner/cli_app/cli.py
autogpt/core/runner/cli_app/main.py
autogpt/llm/api_manager.py
autogpt/llm/utils/__init__.py
autogpt/logs.py
autogpt/main.py
autogpt/memory/vector/__init__.py
autogpt/memory/vector/memory_item.py
autogpt/models/command.py
autogpt/models/command_registry.py
autogpt/processing/text.py
autogpt/prompts/generator.py
requirements.txt
tests/conftest.py
tests/unit/test_commands.py
tests/unit/test_execute_command.py
tests/unit/test_prompt_generator.py

Some identified bugs/regressions have been fixed:
- Issues affecting azure config (PR #4912)
- Bugs running the core cli app (PR #4905)
The following recent merges into master are also being pulled into v0.4.4:
- Fix PLAIN_OUTPUT for normal execution (#4904)
- Fix summarize_text usages and self-calls (#4863) 
- Add docstring to function get_memory() in autogpt.memory.vector (#1296)

Syncing bugfixes and newer commits from master to release-v0.4.4

---

autogpt/memory/vector/providers/base.py
autogpt/speech/base.py
tests/integration/memory/test_json_file_memory.py

Singletons are bad and we don't need them
- Remove the abstract singleton parent class from the vector memory
N/A
CI
- [] I have thoroughly tested my changes with multiple different prompts.
```shell
black .
isort .
mypy
```

Drop AbstractSingleton as a parent class of the vector memory

---

autogpt/config/config.py
autogpt/llm/utils/__init__.py
autogpt/memory/vector/utils.py
tests/unit/test_config.py

Repeat of #4932 
Restores #2594

Fix regression where we lost the api base and organization

---

.github/workflows/ci.yml

* CI fails to make API calls via the proxy, gets 400 Bad Request: https://github.com/Significant-Gravitas/Auto-GPT/actions/runs/5533011279/jobs/10096906731
* Taking the proxy out of the equation lets CI pass: https://github.com/Significant-Gravitas/Auto-GPT/actions/runs/5532961197/jobs/10095778254?pr=4799#logs
Pass `OPENAI_API_TOKEN` instead of using `PROXY` on internal PRs (so from a branch in the repo to another branch in the repo).
x
CI

Disable proxy for internal pull requests

---

autogpt/core/README.md

The existing readme lack references to other documentation resources and people have been having issues with the run instructions.
- Add an overview with links to relevant github issues.
- Add more clarity about installing autogpt and where to do it from (this was a user testing issue)
- Add more clarity about where a users home directory is on different platforms (this was a user testing issue)
- Add more clarity about what isn't being worked on (the cli web app) as this caused some user confusion.
All Docs
X
```shell
black .
isort .
mypy
```

Add links to github issues in the README and clarify run instructions

---

autogpt/agents/agent.py
autogpt/agents/base.py
autogpt/main.py
benchmarks.py

We have a ton of application code in the Agent (getting/parsing user input, displaying non-logging messages to the UI, running UI context managers, signal handling).  This distracts from the core operations of the Agent. This is a first pass to try to at least crudely separate application concerns from the agent logic.
- Lift getting/parsing user input out of the agent
- Lift all calls to logger.typewriter_log (UI updates) out of the agent
- Lift user signal handling out of the agent
- Lift the Spinner UI context manager out of the agent
- Add a `run_interaction_loop` function to `main.py` that does all of the above.
Since the agent now has no method to run forever, it's step is split along boundaries where we either want to start some UI element or we want to interact with the user.
- …

Extract application code from the agent

---

autogpt/config/config.py

📷 @NeonN3mesis 
* Do `PluginsConfig.load_config` *after* determining `config.plugins_config_file`
x
CI
```shell
black .
isort .
mypy
```

Fix loading the plugins config

---

autogpt/commands/execute_code.py

Please see #4975
```shell
black .
isort .
mypy
```

Fix `execute_python_file` workspace mount & Windows path formatting

---

autogpt/config/config.py

`TEXT_TO_SPEECH_PROVIDER` is bulldozed in `ConfigBuilder.build_config_from_env()`:
* https://github.com/Significant-Gravitas/Auto-GPT/pull/4931#issuecomment-1638962278
* https://github.com/Significant-Gravitas/Auto-GPT/blob/a758acef2cf12b206d7172b47880dd876f8ad4bc/autogpt/config/config.py#L289
* Enclose the offending piece of code in an `if not config_dict["text_to_speech_provider"]`
* Get config values from `config_dict` instead of repeatedly calling `os.getenv` for the same variable
x
CI
```shell
black .
isort .
mypy
```

Fix configuring TTS engine

---

autogpt/core/runner/cli_app/main.py
autogpt/core/runner/client_lib/parser.py

As there are plan to build a web-app , and add modularity to the code, it would be beneficial to set the parser as a library.
Move the parser in a separate file
Run.
```shell
black .
isort .
mypy
```

runner.cli parsers set as a library

---

.gitignore
autogpt/cli.py
autogpt/commands/execute_code.py
autogpt/commands/image_gen.py
autogpt/config/ai_config.py
autogpt/config/config.py
autogpt/logs/handlers.py
autogpt/logs/log_cycle.py
autogpt/logs/logger.py
autogpt/main.py
autogpt/memory/vector/providers/json_file.py
autogpt/plugins/__init__.py
autogpt/plugins/plugins_config.py
autogpt/prompts/prompt.py
autogpt/workspace/workspace.py
benchmarks.py
docs/configuration/memory.md
docs/setup.md
tests/conftest.py
tests/unit/test_config.py
tests/unit/test_plugins.py

We continue to have issues where a piece of code containing a relative path reference is moved and suddenly the `logs` folder or the workspace folder isn't in the right place anymore.
- Fix and clean up path processing in logs module
- Move `logs/` back to project root after it was misplaced in #4921
- Fix path processing throughout the project
- Move workspace folder to `./auto_gpt_workspace` after it was misplaced in #4778 (see [this comment](https://github.com/Significant-Gravitas/Auto-GPT/pull/4778/files#r1270674542))
- Change `Config.workspace_path` type to `Path`
Auto-GPT runs fine, tests pass
```shell
black .
isort .
mypy
```

Fix path processing

---

autogpt/core/runner/client_lib/parser.py

The + symbol is forgotten in parse_ability_result(...) func inside parser.py.
Puts back the + symbol in its place.
NA
NA
```shell
black .
isort .
mypy
```

fix the forgotten + symbol in parse_ability_result(...) in parser.py

---

mkdocs.yml

We get many support requests about things that are configurable, but aren't in the docs. The options.md file that describes the .env options exists but isn't linked from mkdocs.yaml, so it doesn't show up in the online docs at agpt.co/docs
Added options.md to mkdocs.yaml
This is a documentation change
I ran mkdocs locally and confirmed the change.
```shell
black .
isort .
mypy
```

Add config options to documentation site

---

autogpt/core/runner/cli_web_app/cli.py
autogpt/core/runner/cli_web_app/server/api.py

I found a runtime error in the API mainly caused by a wrong variable access.
The changes I made are in the `cli_web_app` directory - I fixed the error and updated the files  to work with some changes to the other parts of AutoGPT.
_I need to document the changes and the new functionality._
_I still need to thoroughly test these changes._
```shell
black .
isort .
mypy
```

Fix runtime error in the API

---

agbenchmark/config.json

```shell
black .
isort .
mypy
```

Change workspace location

---

autogpt/agents/base.py
autogpt/commands/file_operations.py
autogpt/core/planning/templates.py
tests/unit/test_file_operations.py

How many user experiences got ruined because of this command ?
And what does it bring ? Yeah it can be useful, but come on, it's not critical.
Without this command Auto-GPT becomes way more reliable at doing tasks without deleting them.
- remove delete_file command 
```shell
black .
isort .
mypy
```

Remove delete file

---

autogpt/agents/agent.py
autogpt/agents/base.py
autogpt/app/setup.py
autogpt/config/ai_config.py
autogpt/config/prompt_config.py
autogpt/llm/utils/__init__.py
autogpt/prompts/generator.py
autogpt/prompts/prompt.py
prompt_settings.yaml
tests/unit/test_prompt_config.py
tests/unit/test_prompt_generator.py

Supporting infrastructure for #5077
- Clean up prompt generation
- Add debug logging to AIConfig autogeneration
- Clarify prompting and add support for multiple thought processes to Agent
* Tested manually ✅
* CI
```shell
black .
isort .
mypy
```

Improve prompting and prompt generation infrastructure

---

agbenchmark/benchmarks.py
autogpt/commands/file_operations.py
autogpt/config/config.py
autogpt/llm/utils/__init__.py
tests/unit/test_config.py

Not very useful command, write_to_file is more reliable.
```shell
black .
isort .
mypy
```

Remove append to file

---

agbenchmark/benchmarks.py
autogpt/app/main.py
autogpt/commands/__init__.py
autogpt/commands/execute_code.py
autogpt/commands/file_operations.py
autogpt/commands/git_operations.py
autogpt/commands/image_gen.py
autogpt/commands/system.py
autogpt/commands/web_search.py
autogpt/commands/web_selenium.py
autogpt/core/runner/cli_web_app/server/api.py
autogpt/models/command_registry.py
tests/mocks/mock_commands.py
tests/unit/test_commands.py

In order to build better prompts and make agents with access to different sets of abilities, the CommandRegistry needs extension to accommodate categories of commands.
* Add `categories` attribute to `CommandRegistry` class
* Move command loading code from main.py into `CommandRegistry`
* Add name and title attributes to command modules
No changes needed
CI
```shell
black .
isort .
mypy
```

Add categories to command registry

---

autogpt/app/main.py
tests/integration/test_update_user.py

`update_user()` in `app/main.py` only checks for command errors if the `command_name` is `None`, which causes a `NoneType` error.
Refactor the logic to check for `command_name` errors within the "command_name is not None" block.
Added a test to confirm
```shell
black .
isort .
mypy
```

fix: Nonetype error from command_name.startswith()

---

autogpt/commands/__init__.py

Enabling image_gen commands to support IMAGE_PROVIDER in the .env.
```shell
black .
isort .
mypy
```

Update __init__.py to support image_gen commands

---

docs/content/setup.md

auto-gpt keys were mis-nested under auto-gpt section of the docker-compose.yml after modern material improvements in 7cd407b7b4a9f4395761e772335e859e40e8c3d3 part of PR #5035.

Fix docs: sample docker-compose.yml broken indents

---

.github/workflows/benchmark-ci.yml
benchmark/agents_to_benchmark.json

- fix report not being generated in correct path
- allow to pin specific commit version
- ability test sending push to report on ci-test-* branches

Benchmark agents without submodule + ability to pin a specific commit.

---

frontend/lib/main.dart
frontend/lib/models/skill_tree/ground.dart
frontend/lib/models/skill_tree/info.dart
frontend/lib/models/skill_tree/skill_node_data.dart
frontend/lib/models/skill_tree/skill_tree_edge.dart
frontend/lib/models/skill_tree/skill_tree_node.dart
frontend/lib/viewmodels/skill_tree_viewmodel.dart
frontend/lib/views/main_layout.dart
frontend/lib/views/skill_tree/skill_tree_view.dart
frontend/lib/views/skill_tree/tree_node_view.dart
frontend/pubspec.lock
frontend/pubspec.yaml

The main application has been relying on placeholder views and data models for the Skill Tree functionality. As the Skill Tree feature set becomes more mature, there is a need to integrate these new implementations into the main application layout and data flow. This integration aims to replace placeholders with functional components and to set up proper interactions with the SkillTreeViewModel.
1. **New Data Models**: Introduced new data models (Ground, Info, SkillNodeData, SkillTreeEdge, and SkillTreeNode) that represent the skill tree's structure and metadata.
2. **Updated SkillTreeViewModel**:
- Added a _selectedNode property to manage single node selection.
- Introduced initializeSkillTree and toggleNodeSelection methods for tree initialization and node selection, respectively.
3. …

Integrate Skill Tree Functionality into Main Application

---

autogpts/autogpt/autogpt/app/main.py

This PR was created to introduce a small change in the console input formatting line to improve readability. It adds a space following the colon in console input prompt, enhancing its visual appearance and ease of input.
- Added a space after "Input:" in the console input line.
Given the atomic nature of this PR, it does not address a GitHub issue, add/change a feature, or alter the behavior of Auto-GPT hence, no score in these areas. The change was small and strictly focusing on improvement in console prompt readability.

Adding Space After Colon in Console Input Prompt

---

.github/workflows/benchmark-ci.yml
autogpts/forge/advanced_commands/README.md
autogpts/forge/advanced_commands/run_benchmark_dev
autogpts/forge/forge/__main__.py
autogpts/forge/run_benchmark
benchmark/agbenchmark/__main__.py
benchmark/agbenchmark/agent_interface.py
benchmark/agbenchmark/app.py
benchmark/agbenchmark/challenges/deprecated/content_gen/2_plan/data.json
benchmark/agbenchmark/execute_sub_process.py
benchmark/agbenchmark/generate_test.py
benchmark/agbenchmark/reports/ReportManager.py
benchmark/agbenchmark/reports/agent_benchmark_config.py
benchmark/agbenchmark/reports/reports.py
benchmark/tests/test_web_server.py

To save the reports in the correct folder, we use a class that is currently saved between API requests.
So by making it a singleton we're aware our application is stateful and
The other alternative was to pass the benchmark start time accross the app. But it blows up the scope.

Implement old polling mechanism

---

frontend/lib/viewmodels/skill_tree_viewmodel.dart

The `runBenchmark` method in `SkillTreeViewModel` currently iterates through all the nodes in the skill tree to run benchmarks. However, it lacks a mechanism to halt the entire benchmarking process if a particular node's benchmark fails.
- Added a conditional statement in the `runBenchmark` method to check the `successStatus` of each node's benchmark.
- If `successStatus` is false, the benchmarking process will terminate early, and a message will be printed to the console indicating which node caused the termination.
This change enhances the efficiency of the benchmarking process and provides immediate feedback when a benchmark fails.

Add Early Termination to runBenchmark on Benchmark Failure

---

frontend/lib/viewmodels/skill_tree_viewmodel.dart
frontend/lib/views/task_queue/task_queue_view.dart

The `runBenchmark` method in `SkillTreeViewModel` runs benchmarks for various skill tree nodes. To better track and manage these benchmarks, it's beneficial to group them into test suites, especially when multiple benchmarks are run in succession.
- At the start of the `runBenchmark` method, a new `TestSuite` object is created with the current timestamp.
- Each new `Task` object created during the benchmarking process is added to the `TestSuite`.
- Once the benchmarking process completes, the `TestSuite` object is added to the `TaskViewModel` using its `addTestSuite` method.
This enhancement provides a structured way to group benchmarks and facilitates better tracking and reporting of benchmark runs.

Enhance runBenchmark with TestSuite Tracking

---

autogpts/forge/forge/sdk/agent.py
autogpts/forge/forge/sdk/forge_log.py

Changed response type to StreamResponse to drop the need to temporarily write the file out.

change to stream respsonse

---

autogpts/autogpt/autogpt/agents/agent.py

prompt instructions were stacking making the agent eventually return an error because the prompt was full of repeating instructions
in agent.py build_prompt resets extra_messages eliminating stacking instructions similar to the fix @Pwuts  implemented here https://github.com/Significant-Gravitas/AutoGPT/commit/563df6ca3a4bc1ad11ff921a37fc3fcb624c666d

Fixed stacking prompt instructions

---

frontend/lib/models/test_option.dart
frontend/lib/viewmodels/skill_tree_viewmodel.dart
frontend/lib/views/task_queue/task_queue_view.dart
frontend/lib/views/task_queue/test_suite_button.dart

In the skill tree view of our application, users have the option to select among various test execution strategies, such as running a single test, a suite of tests, or all tests in a category. Previously, these options were represented and managed using strings, leading to potential issues with type safety, code readability, and maintenance. There was a need to enforce a more structured and type-safe approach to handle these test options.
In this pull request, we introduce a new `TestOption` enum to represent the different test execution options in a more structured and type-safe manner. We have also updated the relevant parts of the code where these test options are used, enhancing the clarity and maintainability of the code.
- `TestOption` enum with values representing the distinct test …

Introduce TestOption Enum for Enhanced Test Selection Clarity

---

autogpts/forge/forge/sdk/db.py
autogpts/forge/forge/sdk/schema.py

- The `output` of a `Step` is an essential attribute to properly inform the user/frontend
- The `output` attribute is present on the `Step` model, but not the corresponding DB entity `StepModel`
- Add output fields to `StepModel` and `AgentDB.update_step`
- Fix `AgentDB.get_step` parameter types

Forge: add output fields to DB StepModel

---

autogpts/autogpt/autogpt/agents/utils/exceptions.py

Fix typo in exceptions.py

---

autogpts/forge/forge/sdk/abilities/registry.py

Fixing a typo in an error message displayed to users.
Fixed the misspelling of the word "actually"
- [✅] Have you used the PR description template? &ensp; `+2 pts`
- [✅] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [NA] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [✅] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [❎] Have you changed or added a feature? &ensp; `-4 pts`
- [NA] Have you added/updated corresponding documentation? &ensp; `+4 pts`
- [NA] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [❎] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
- [NA] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 …

Fixed typo in registry.py

---

cli.py

The improved regex was introduced with: https://github.com/Significant-Gravitas/AutoGPT/pull/6096
However, there seems to be an issue with the updated regex. 
The uppercase meta-character `\W` only matches non-word characters, i.e. everything that is NOT `[A-Za-z0-9_]`.
This leads to issues when choosing an agent name, where basically all names get rejected. Example: https://github.com/Significant-Gravitas/AutoGPT/issues/6106
What you actually want is to use the lowercase `\w` character.
Change regex to use `\w` instead of `\W` meta-character.

Fix for agent_name regex

---

autogpts/autogpt/autogpt/agent_factory/profile_generator.py
autogpts/autogpt/autogpt/agents/prompt_strategies/one_shot.py
autogpts/autogpt/autogpt/config/config.py
autogpts/autogpt/autogpt/core/planning/prompt_strategies/initial_plan.py
autogpts/autogpt/autogpt/core/planning/prompt_strategies/name_and_goals.py
autogpts/autogpt/autogpt/core/planning/prompt_strategies/next_ability.py
autogpts/autogpt/autogpt/core/resource/model_providers/openai.py
autogpts/autogpt/autogpt/core/resource/model_providers/schema.py

- Updated the `OpenAIModelName` enum to include new GPT-3.5 Turbo and GPT-4 models
- Added support for the `GPT3_v3` and `GPT4_v3` models in the `OPEN_AI_CHAT_MODELS` dictionary
- Modified the `OpenAIProvider` class to handle the new models and features
- Updated the schema definitions in the `schema.py` module to include `AssistantToolCall` and `AssistantToolCallDict` models
- Updated the `AssistantChatMessage` and `AssistantChatMessageDict` models to include the `tool_calls` field
- Refactored the code in various modules to handle the new tool calls and function arguments
Added support for the new models and features introduced with OpenAI's latest update. This commit allows the system to utilize the `GPT3_v3` and `GPT4_v3` models and includes all necessary modifications to the codebase …

feat: Add support for new models and features from OpenAI's November 6 update

---

cli.py

Solving #6215 
Fixing an issue where regular expression caused a SyntaxWarning. Replacing the regular expression "\w*$" with a raw string (r"\w*$") to ensure proper handling of the regular expression in cli.py.

Fix regex warning

---

docs/content/AutoGPT/Setups/nogit-setup.md

Without that step, I got this error:
```
"ModuleNotFoundError: No module named
'auto_gpt_plugin_template'"
```
Updated the `setup.md` instructions file to include the `poetry install` command in dockerless setup. Also removed a couple of stray whitespaces on that page.

Include poetry install step in dockerless setup instructions

---

autogpts/autogpt/poetry.lock
autogpts/autogpt/pyproject.toml
autogpts/forge/poetry.lock
autogpts/forge/pyproject.toml

Changing agbenchmark dependency as git reference instead of folder reference.
When building the autogpt docker image, then only the autogpts/autogpt folder is copied into the Docker image.
So, when `poetry install --root` tries to install the dependencies in the image, it will not work, because the `benchmark` folder is not in the image. As  [JulianBroudy's commented the logs](https://github.com/Significant-Gravitas/AutoGPT/issues/5253#issuecomment-1774068760) under #5253. So, I changed the dependency to a git reference which makes the agbenchmark accessible from the Docker image.
Related issues:
* #6191
* #5253
* Updated autogpts/autogpt/pyproject.toml. Changed agbenchmark from folder to git reference and run `poetry update agbencmark` to update the `poetry.lock` file.
* Updated …

Fix docker build. Changing agbenchmark dependency as git reference instead of folder reference.

---

autogpts/forge/tutorials/003_crafting_agent_logic.md

[Using and Creating Abilities](https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/forge/tutorials/003_crafting_agent_logic.md#using-and-creating-abilities) is referring to `@ability` decorator for creating custom abilities. This needs to be updated to use the `@action` decorator and corresponding classes.
Update the documentation to use the `ActionRegister` class and `@action` annotation
closes #6652
- [x ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts` (https://github.com/Significant-Gravitas/AutoGPT/issues/6652)
- [x ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`

[Documentation Update] Updating Using and Creating Abilities to use Action Annotations

---

autogpts/forge/forge/__main__.py

When executing `port = os.getenv("PORT", 8000)` if the port is being fetched from a `.env` file it is fetched as a string.
This causes an error: `TypeError: 'str' object cannot be interpreted as an integer`
The port is casted to int before passed to uvicorn

fix: cast port to int

---

autogpts/autogpt/autogpt/commands/web_selenium.py
autogpts/autogpt/autogpt/processing/text.py

While browsing, the agent may try to access websites that have cookie walls, banners, or other popups, bloating or obstructing access to the page content. This impedes the agent's ability to retrieve information from these websites.
Luckily, there are browser extensions to deal with UX pollution. These can be sideloaded through Selenium and solve the problem for us.
* Add `_sideload_chrome_extensions` subroutine to `open_page_in_browser` in web_selenium.py
* Sideloads uBlock Origin and I Still Don't Care About Cookies, downloading them if necessary
* Add 2-second delay to `open_page_in_browser` to allow time for handling cookie walls

feat(agent/web): Add browser extensions to deal with cookie walls and ads

---

frontend/lib/views/chat/chat_input_field.dart

This has not yet been tested due to an issue with compiling on wsl. This was the fix suggested by Pwuts.
Add a few lines based on Pwuts suggestion.

Adding support to allow for sending a message with the enter key

---

autogpts/autogpt/autogpt/commands/execute_code.py

Fix
- Disable `execute_python_code` and `execute_python_file` if running outside Docker and Docker is unavailable.

fix(agent/execute_code): Disable code execution commands when Docker is unavailable

---

autogpts/autogpt/autogpt/app/main.py

When trying to load non existing agent in AutoGPT CLI, an exception was thrown.
Skip loading non-existing agent, create a new one and inform the user.

OPEN-133: Fix trying to load non-existing agent

---

autogpts/autogpt/autogpt/agents/agent.py
autogpts/autogpt/autogpt/models/action_history.py

Raise in `parse_and_process_response` inside `agent.py` if agent tries to execute the same command twice in a row.

OPEN-165: Improvement - check for duplicate command

---

autogpts/autogpt/autogpt/file_storage/gcs.py
autogpts/autogpt/autogpt/file_storage/s3.py

Make GCS and S3 FileStorage root path absolute if it isn't in `__init__`.

fix(autogpt): Fix GCS and S3 root path issue

---

autogpts/autogpt/autogpt/app/main.py

Fix: OPEN-118
This fixes exception in CLI when user entered an empty task. Now it'll prompt user again until task is non-empty.
Server has no such issue.

fix(autogpt/cli): Loop until non-empty task is provided by the user

---

docs/mkdocs.yml

`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since the acquisition, numerous issues have emerged (https://github.com/polyfillpolyfill/polyfill-service/issues/2835, …

docs: replace `polyfill.io`

---

autogpts/autogpt/tests/vcr/__init__.py
autogpts/autogpt/tests/vcr/vcr_filter.py

- Move filtering logic from tests/vcr/__init__.py to tests/vcr/vcr_filter.py
- Ignore all `X-Stainless-*` headers for cassette matching, e.g. `X-Stainless-OS` and `X-Stainless-Runtime-Version`
- Remove deprecated OpenAI proxy logic
- Reorder methods in vcr_filter.py for readability
CI for PRs from forks works on Linux but fails on macOS and Windows:
This is because the OpenAI library includes platform- and version-specific headers in requests:
```
x-stainless-arch:
- x64
x-stainless-async:
- 'false'
x-stainless-lang:
- python
x-stainless-os:
- Linux
x-stainless-package-version:
- 1.8.0
x-stainless-runtime:
- CPython
x-stainless-runtime-version:
- 3.10.13
```
We can fix this by ignoring (= filtering out) those headers before saving/retrieving the request to/from a cassette.

test(agent): Fix VCRpy request filter for cross-platform use

---

.github/workflows/autogpt-ci.yml

- Add `macos-arm64` to `platform-os` matrix, and map it to `macos-14` runner
When it comes to testing, macOS != macOS on M1 because it requires different distributions of platform-specific packages.

ci(agent): Add macOS ARM64 to AutoGPT Python CI matrix

---

autogpts/autogpt/autogpt/agent_factory/profile_generator.py
autogpts/autogpt/autogpt/agents/prompt_strategies/one_shot.py
autogpts/autogpt/autogpt/core/planning/prompt_strategies/initial_plan.py
autogpts/autogpt/autogpt/core/planning/prompt_strategies/name_and_goals.py
autogpts/autogpt/autogpt/core/planning/prompt_strategies/next_ability.py
autogpts/autogpt/autogpt/core/resource/model_providers/openai.py
autogpts/autogpt/autogpt/core/resource/model_providers/schema.py
autogpts/autogpt/autogpt/core/utils/json_utils.py

- **feat(agent/utils): Improve conditions and errors in `json_loads`**
- **refactor(agent/core): Rearrange and split up `OpenAIProvider.create_chat_completion`**
- **fix(agent): Handle decoding of function call arguments in `create_chat_completion`**

refactor(agent): Refactor & improve `create_chat_completion`

---

autogpt/autogpt/app/configurator.py
autogpt/tests/unit/test_config.py
forge/forge/llm/providers/_openai_base.py
forge/forge/llm/providers/anthropic.py
forge/forge/llm/providers/groq.py
forge/forge/llm/providers/multi.py
forge/forge/llm/providers/openai.py
forge/forge/llm/providers/schema.py

It seems to be a trend for new LLM providers to mimic the OpenAI API. The same goes for Llamafile. We can leverage this and create a common base class that implements most of the functionality for providers with OpenAI-like interfaces. This has the additional benefit of increasing maintainability and making it easier to add support for more such providers in the future.
This PR also paves the way for a clean integration of #7091.
- Add `_BaseOpenAIProvider`, `BaseOpenAIChatProvider`, and `BaseOpenAIEmbeddingProvider`
- (Re)move as much code as possible from `GroqProvider` and `OpenAIProvider`
Also:
- Rename `get_available_models()` to `get_available_chat_models()` on `BaseChatModelProvider`
- Add `get_available_models()` to `BaseModelProvider`
- Add `get_available_embedding_models()` to …

refactor(forge/llm): Create `BaseOpenAIProvider` -> deduplicate `GroqProvider` & `OpenAIProvider`

---

.github/ISSUE_TEMPLATE/1.bug.yml
autogpt/README.md
autogpt/autogpt/app/cli.py
autogpt/autogpt/app/configurator.py
autogpt/autogpt/app/main.py
autogpt/tests/unit/test_config.py
docs/content/AutoGPT/setup/docker.md
docs/content/AutoGPT/setup/index.md

* Update instructions to set up OpenAI / GPT-4 access
* Add instructions to set up Anthropic access
* Add instructions to set up Groq access
* Remove GPT-specific `--gpt3only`, `--gpt4only` CLI flags and related logic
* Remove duplicate config instructions from the docker setup page, replace by a link to the regular setup instructions
Blocks #7091

docs+fix(agent): Update LLM setup instructions & remove GPT-specific flags

---

docs/content/AutoGPT/configuration/options.md

There was a dead link to components
- Fixes the dead link
___
Documentation
___
- Fixed a dead link in the `options.md` file to the built-in components configuration.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>options.md</strong><dd><code>Fix dead link in configuration options documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/content/AutoGPT/configuration/options.md
- Fixed a dead link to the built-in components configuration.
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7207/files#diff-a10f9a59c1af5f7ead65832ae0702369adf9f601f094ae20ddb3638f7ba608f1">+1/-1</a>&nbsp; &nbsp; &nbsp; </td> …

fix(docs): bad link from Options to built in components config

---

rnd/autogpt_server/autogpt_server/data/block.py
rnd/autogpt_server/autogpt_server/executor/executor.py
rnd/autogpt_server/schema.prisma

This is a follow-up of:
https://github.com/Significant-Gravitas/AutoGPT/pull/7194
https://github.com/Significant-Gravitas/AutoGPT/pull/7195
Some code were missing during the work and this PR fixes it.
* PEP8 linting fix
* Revert db schema
* next node checking for execution

feat(rnd): Add missing code on execution logic for AutoGPT Server

---

autogpt/autogpt/app/main.py
forge/forge/config/__init__.py
forge/forge/config/config.py

The application currently checks whether a valid OpenAI API key is set, even if `SMART_LLM` and `FAST_LLM` are set to models from other providers.
The check needs to support other providers as well, and shouldn't break the app if someone tries to use a different provider.
Related:
- #25
- #7214
* Rename `assert_config_has_openai_api_key` to `assert_config_has_required_llm_api_keys`
* Make OpenAI credential check conditional (only if an OpenAI model is selected in the config)
* Implement checks for Groq and Anthropic credentials
* Use API calls for Groq and OpenAI credential checks to make sure the keys are valid

fix(agent, forge): Make LLM API key check provider-agnostic

---

rnd/autogpt_server/autogpt_server/data/graph.py
rnd/autogpt_server/schema.prisma

AgentServer node will require additional metadata for the UI related purpose.
The scope of this change is introducing a generic metadata field for the Node.
Add `metadata` field on AgentNode.

feat(rnd): Add node metadata on Agent Server Node object

---

rnd/autogpt_server/autogpt_server/app.py
rnd/autogpt_server/autogpt_server/data/schedule.py
rnd/autogpt_server/autogpt_server/executor/manager.py
rnd/autogpt_server/autogpt_server/executor/scheduler.py
rnd/autogpt_server/autogpt_server/server/server.py
rnd/autogpt_server/autogpt_server/util/service.py
rnd/autogpt_server/poetry.lock
rnd/autogpt_server/pyproject.toml
rnd/autogpt_server/schema.prisma
rnd/autogpt_server/test/executor/test_manager.py
rnd/autogpt_server/test/executor/test_scheduler.py
rnd/autogpt_server/test/util/test_service.py

Agent execution should be able to be triggered in a recurring manner.
This PR introduced an ExecutionScheduling service, a process responsible for managing the execution schedule and triggering its execution based on a predefined cron expression.
* Added `scheduler.py` / `ExecutionScheduler` implementation.
* Added scheduler test.
* Added `AgentExecutionSchedule` table and its logical model & prisma queries.
* Moved `add_execution` from API server to `execution_manager`

feat(rnd): Add AutoGPT server scheduling service

---

rnd/autogpt_server/autogpt_server/data/block.py
rnd/autogpt_server/autogpt_server/data/execution.py
rnd/autogpt_server/autogpt_server/data/graph.py
rnd/autogpt_server/autogpt_server/data/schedule.py
rnd/autogpt_server/autogpt_server/executor/manager.py
rnd/autogpt_server/autogpt_server/executor/scheduler.py
rnd/autogpt_server/autogpt_server/server/server.py
rnd/autogpt_server/autogpt_server/util/service.py
rnd/autogpt_server/schema.prisma
rnd/autogpt_server/test/executor/test_manager.py

The current implementation of AgentServer doesn't allow for a single pin to be connected to multiple nodes, this will be problematic when you have a single output node that needs to be propagated into many nodes. Or multiple nodes that possibly feed the data into a single pin (first come first serve).
This infra change is also part of the preparation for changing the `block` interface to return a stream of output instead of a single output.  Treating blocks as streams requires this capability.
* Update block run interface from returning `(output_name, output_data)` to `Generator[(output_name, output_data)]`
* Removed `agent` term in the API, replace it with `graph` for consistency.
* Reintroduced `AgentNodeExecutionInputOutput`. `AgentNodeExecution` input & output will be a list of …

feat(rnd): Refactor AgentServer Node Input/Output Relation & Block output interface

---

rnd/autogpt_server/.gitignore
rnd/autogpt_server/autogpt_server/app.py
rnd/autogpt_server/autogpt_server/server/server.py
rnd/autogpt_server/autogpt_server/util/data.py
rnd/autogpt_server/autogpt_server/util/settings.py
rnd/autogpt_server/config.default.json
rnd/autogpt_server/poetry.lock
rnd/autogpt_server/pyproject.toml

We need a way to configure the agent server for two types of things: 
- configurations
- secrets
The typical way we configure is to use a `.env,` but this is difficult for users to handle.
Generally, we need to keep defaults that are overridden at runtime, and this can be pretty confusing for users. It is also difficult for them to share their configurations with us as we require them to mix their secrets with their other config settings. In the past, this has led to leaked API keys and more.
- Add support for Pydantic Settings
- Add a `config.default.json` to keep the default settings (can be deleted in favor of keeping them in code, but I think the JSON files will be useful long term for defaults at different install levels like single user, server, etc and environments like staging, …

feat(server): Add settings with secrets and configuration with API updating and Saving to file

---

rnd/autogpt_server/autogpt_server/data/block.py
rnd/autogpt_server/autogpt_server/data/execution.py
rnd/autogpt_server/autogpt_server/executor/manager.py
rnd/autogpt_server/test/executor/test_manager.py

On AgentServer, To create a `Block` like `StringFormatterBlock` or `LllmCallBlock`, we need some way to dynamically link input pins and aggregate them into a single list input. This will give a better experience for the user to construct an input and link it from the output of the other nodes. The scope of this change is adding support for that in the least intrusive way.
*Proposal*
To differentiate the input list name and its singular entry we are using the `$_<index>` prefix. For example:
For the input `items`: `list[int]`, you can set a pin `items` with values like `[1,2,3,4]`. But you can also add input pins like `items_$_0` or `items_$_4` with values `1` or `2`, which will be appended to the `items` input in alphabetical order.
The execution engine will guarantee to wait for the …

feat(rnd): Add support for dynamic input as list for AgentServer Block

---

autogpt/poetry.lock
autogpt/pyproject.toml

* Fixes #7297
The `cx-freeze` dependency was changed to a git dependency in #7271. This requires `python3-dev` to be installed locally to build the `cx-freeze` package when you run `poetry install`.
* Create (optional) `build` dependency group
* Move `cx-freeze` dependency to `build` dependency group
To include this group when installing dependencies, run `poetry install` with the `--with=build` option.

fix(agent): Make build dependencies optional to unbreak install

---

autogpt/poetry.lock
forge/forge/components/web/search.py
forge/poetry.lock
forge/pyproject.toml

* Fixes #7284
- Add `google-api-python-client-stubs` dev dependency
- Add version specification to `google-api-python-client` dependency
- Fix type error (by ignoring it) in forge/components/web/search.py

fix(forge): Add `google-api-python-client-stubs` and fix type error

---

rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/lib/autogpt_server_api.ts
rnd/autogpt_builder/src/lib/types.ts

API logic is currently scattered throughout `Flow.tsx` and only partially implemented. This is a first shot at a simple API client with fully typed inputs and outputs, to make all our lives a bit easier :)
* Resolves #7327
- feat(autogpt_builder): Add `AutoGPTServerAPI` client
- Migrate API calls in `Flow.tsx` to new API client

feat(autogpt_builder): Add simple `AutoGPTServerAPI` client

---

rnd/autogpt_builder/src/components/Flow.tsx

We want to clearly show the user the progress of each node as the agent is running. I have added visual elements to ensure it is clear (Green for completed, Yellow for Running etc). Previously this animation was not hooked up to the live data. This PR changes that, and links the animation to the actual progress of the node from the backend
Map backend node id to frontend node id.
___
Enhancement
___
- Added a mapping from backend node IDs to frontend node IDs to synchronize the frontend with the backend.
- Updated the frontend node IDs and positions based on the backend response to ensure accurate tracking of execution progress.
- Included logging for execution data to aid in debugging and monitoring.
- Modified the logic to update nodes with execution data, reflecting the real-time …

feat(autogpt_builder) Hook up execution progress animation to live execution data

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/ModalComponent.tsx

Fix issue with node input modal showing data from other inputs
small changes to the way the value was passed, this is to fix [7352](https://github.com/Significant-Gravitas/AutoGPT/issues/7352)

Fix issue with node inputs

---

rnd/autogpt_builder/next.config.js
rnd/autogpt_builder/package.json
rnd/autogpt_builder/src/components/Flow.tsx

The project now reads the AGPT_SERVER_URL thats setup in the .env and uses that
This fixes #7324 
Make sure to run ``npm install dotenv`` just incase you dont have it

Reads data from .env

---

rnd/autogpt_builder/src/components/Flow.tsx

Add the ability to just save an agent without running it.
___
Enhancement
___
- Introduced a new `saveAgent` function to allow saving an agent without executing it.
- Modified the existing `runAgent` function to call `saveAgent` first and then execute the agent.
- Updated the UI to include two separate buttons: one for saving the agent and another for saving and running the agent.
- Improved code formatting and readability.
___
<tr>
<td>
<details>
<summary><strong>Flow.tsx</strong><dd><code>Add functionality to save an agent without running it</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_builder/src/components/Flow.tsx
<li>Added …

feat(builder) Add save Agent functionality 

---

rnd/autogpt_builder/src/components/Flow.tsx

When opening an existing flow with `<FlowEditor flowID={flowID} />`, it doesn't load the preset input values:
(📸 @aarushik93)
- Assign `node.input_default` to `hardcodedValues` in `FlowEditor:loadFlow(..)`

fix(autogpt_builder): Restore node input presets when loading a flow

---

rnd/autogpt_builder/src/components/Flow.tsx

Bug fix, when disconnecting two nodes, the sink node's input field wasn't reappearing. This PR fixes that
Added a callback to handle disconnection
https://github.com/user-attachments/assets/c175229c-1730-4460-bde5-96980526fa18
___
Bug fix
___
- Added a new `onEdgesDelete` callback function to handle the deletion of edges in the flow editor.
- Updated the node state to filter out connections related to the deleted edges, ensuring the sink node's input field reappears correctly.
- Integrated the `onEdgesDelete` callback with the Flow component to ensure it is called when edges are deleted.
___
<tr>
<td>
<details>
<summary><strong>Flow.tsx</strong><dd><code>Add …

feat(autogpt_builder) Add logic for node disconnection

---

rnd/autogpt_builder/src/components/Flow.tsx

We shouldn't be saving the execution data into the input_default when connecting nodes. Just input data on the backend is fine for it to be saved when running. 
Removed the logic that was saving the output data from source node into the sink node when saving.
___
Enhancement
___
- Removed the logic that saved the output data from the source node into the sink node when saving.
- Simplified the input data handling by removing the merging of execution data from connected nodes.
___
<tr>
<td>
<details>
<summary><strong>Flow.tsx</strong><dd><code>Remove saving of execution data into sink node</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat(autogpt_builder) Remove saving of execution data into sink node

---

autogpt/autogpt/agent_factory/profile_generator.py
autogpt/autogpt/agents/agent.py
autogpt/autogpt/agents/prompt_strategies/one_shot.py
docs/content/forge/components/built-in-components.md
forge/forge/components/README.md
forge/forge/components/action_history/action_history.py
forge/forge/components/web/selenium.py
forge/forge/llm/prompting/base.py
forge/forge/llm/providers/_openai_base.py
forge/forge/llm/providers/anthropic.py
forge/forge/llm/providers/schema.py

After [updating to Pydantic v2](https://github.com/Significant-Gravitas/AutoGPT/pull/7280) Pydantic complains about model fields with `model_` prefix as it's a Pydantic protected namespace:
```
UserWarning: Field "model_info" has conflict with protected namespace "model_".
```
To silence this warning fields need to be renamed or namespace need to be removed from `protected_namespaces`.
This PR renames `model_*` fields to `llm_*` in affected models.

fix(agent, forge): Silence Pydantic v2 protected namespace `model_` warning

---

.github/workflows/autogpt-server-ci.yml

___
___
- Added a new step in the GitHub Actions workflow to set the maximum open files limit on macOS runners.
- This change uses `ulimit -n unlimited` to remove the limit on the number of open files, which helps in preventing issues related to open file handle limits during CI runs.
___
<tr>
<td>
<details>
<summary><strong>autogpt-server-ci.yml</strong><dd><code>Set max open files limit in CI workflow for macOS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/autogpt-server-ci.yml
<li>Added a step to set the maximum open files limit on macOS runners.<br> …

feat: push the limit for open handles

---

docs/mkdocs.yml

documentation
___
- Added a new prominent link to "The AutoGPT Server" in the documentation navbar.
- Removed the old "Server" link from the navbar to avoid redundancy.
___
<tr>
<td>
<details>
<summary><strong>mkdocs.yml</strong><dd><code>Make "The AutoGPT Server" link more prominent in docs navbar</code></dd></summary>
<hr>
docs/mkdocs.yml
<li>Added a new prominent link to "The AutoGPT Server" in the docs navbar.<br> <li> Removed the old "Server" link from the navbar.<br>
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7402/files#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2df">+3/-3</a>&nbsp; …

tweak(docs): Make link to The AutoGPT Server more prominant in docs navbar.

---

rnd/autogpt_builder/next.config.js
rnd/autogpt_builder/next.config.mjs

The changes made here are to fix the things i broke in #7357 in this https://github.com/Significant-Gravitas/AutoGPT/pull/7357#issuecomment-2227111627
I moved everything inside the original .mjs file and it seems to all work and / redirects to /build like it should, the env file is still read

feat(autogpt_builder): Fix Read API base URL from `.env`

---

rnd/autogpt_builder/src/app/build/page.tsx

Removed excess tailwind from page.tsx which seems to be causing the issue, now no-matter the screen size, everything should stay the same size, If there is a better way to go about this/if there where a reason for having LG screen size set please let me know, but this seems to work better
Also updated "node" to "block"
Addresses: https://github.com/Significant-Gravitas/AutoGPT/issues/7417
Screen size < LG
Screen size > LG

feat(builder): Fix message covering navbar on < lg screen size

---

rnd/autogpt_builder/.vscode/launch.json
rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_server/autogpt_server/data/model.py

If you screenshot or record the builder, your API keys will be leaked. This change is designed to ensure that does not happen.
- Adds a launch.json for debugging the frontend
- Adds a parameter to the API to mark something secret
- Adds a toggle to the frontend to show something is secret
___
Enhancement, Tests
___
- Added `secret` parameter to `SchemaField` and `SecretField` functions in the backend to mark fields as secret.
- Modified the `CustomNode` component in the frontend to handle and display secret fields as masked.
- Added a `launch.json` configuration file for debugging Next.js applications, including server-side, client-side, and full-stack debugging options.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</stro …

feat(builder, server): hide secrets from the UI and mark them as secrets in the api

---

rnd/autogpt_builder/src/components/Flow.tsx

Deleting nodes is currently unclear. This is a stopgap to allow deletion using the Delete key present on many keyboards
Specifies that Backspace and delete are both valid options to delete nodes and edges
___
Enhancement
___
- Added support for the 'Delete' key to delete nodes and edges in the Flow editor.
- Updated the `deleteKeyCode` property to accept both 'Backspace' and 'Delete' keys.
___
<tr>
<td>
<details>
<summary><strong>Flow.tsx</strong><dd><code>Allow deletion of nodes and edges using 'Delete' key</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_builder/src/components/Flow.tsx
<li>Added support for 'Delete' key to …

feat(builder): allow deletion of nodes and edges via del key

---

rnd/autogpt_server/autogpt_server/blocks/create_medium_post.py
rnd/autogpt_server/autogpt_server/util/settings.py

Adds a block that uses the Medium API to post a blog post. 
Resulting Post:
https://autoblogs.medium.com/openai-launches-gpt-4o-mini-d7266cb28305

feat(blocks): Add Medium Post block

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/customnode.css

"Toggle Properties" button in builder should say "Toggle Output".
This PR fixes that, as well as replacing erroneous mentions of the word "properties" elsewhere in the codebase.

tweak(builder): Replace erroneous mentions of "Properties" to "Output"

---

rnd/autogpt_builder/src/components/ui/tooltip.tsx

I have made the blocks tooltip open in 10ms 
https://github.com/user-attachments/assets/e249a73f-2fd3-4c67-b305-ba68514a7221
Addresses: https://github.com/Significant-Gravitas/AutoGPT/issues/7473

Feat(Builder): Decrease the delay before a tooltip opens

---

rnd/autogpt_builder/src/components/flow.css

My latest change broke the scroll so this should updated the sidebar to now properly scroll down all the way to show all the blocks 
Currently this happens, i cant scroll down any more
With this fix now we can

feat(builder): fix sidebar scroll issue

---

rnd/autogpt_server/autogpt_server/blocks/__init__.py
rnd/autogpt_server/autogpt_server/data/block.py
rnd/autogpt_server/autogpt_server/data/execution.py
rnd/autogpt_server/autogpt_server/data/graph.py
rnd/autogpt_server/autogpt_server/data/schedule.py
rnd/autogpt_server/autogpt_server/executor/manager.py
rnd/autogpt_server/autogpt_server/executor/scheduler.py
rnd/autogpt_server/autogpt_server/server/server.py
rnd/autogpt_server/test/conftest.py
rnd/autogpt_server/test/executor/test_manager.py
rnd/autogpt_server/test/executor/test_scheduler.py

Input from the input pin is consumed only once, and the default input can always be used. So when you have an input pin overriding the default input, the value will be used only once and the following run will always fall back to the default input. This can mislead the user.
Expected behaviour: the node should NOT RUN, making connected pins only use their connection(s) for sources of data.
* Make pin connection the mandatory source of input and not falling back to default value.
* Fix the type flakiness on block input & output. Unify the typing for BlockInput & BlockOutput using the right alias to avoid wrong typing.
* Add comment on alias
* automated test on the new behaviour.

fix(rnd): Make Agent Server's pin connections become the mandatory source of input

---

rnd/autogpt_server/autogpt_server/blocks/maths.py

feat(Blocks): Add Blocks Providing Basic Arithmetic Operations

---

rnd/autogpt_builder/src/components/Flow.tsx

@Torantulino found a bug where if you copy and paste a block, when you edit the pasted block's hard coded input it updates the original blocks input, this is to fix it
https://github.com/user-attachments/assets/f2962349-dcd2-4510-9cab-52df983ee6fe
https://github.com/user-attachments/assets/6fe9991c-fe31-4dd7-be5e-7071564c7fc6
made sure it makes a brand new copy of the block with its own ID so the edits are seperated

fix(Builder): fixes to copy and pasted blocks

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx

- #7392
- Set `node.data.connections` based on `graph.links` in `loadGraph(..)`
- Use reactflow's built-in `useNodesState`, `useEdgesState` to replace some boilerplate functions that do exactly the same

fix(builder): Correctly load node connections

---

.vscode/all-projects.code-workspace
autogpt/.vscode/settings.json
benchmark/.vscode/settings.json
forge/.vscode/settings.json
rnd/autogpt_server/.vscode/settings.json

After talking to Craig (@Swiftyos) yesterday, I realized our Python type checking issues may be aggravated because we haven't set the type checking mode for the repo.
- Set `python.analysis.typeCheckingMode` to `basic` in all subprojects' `.vscode/settings.json` + `all-projects.code-workspace`

dx: Set Python type checking mode to "basic" for all subprojects

---

rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/lib/autogpt-server-api/client.ts

- Resolves #7602
- Fix type signatures of `sendWebSocketMessage(..)`, `onWebSocketMessage(..)`, `runGraph(..)` in `autogpt-server-api/client`
- Add `WebsocketMessageTypeMap`
- Fix type signature of `updateNodesWithExecutionData` in `FlowEditor`

fix(builder/api): Fix websocket client types

---

rnd/autogpt_server/postgres/migrations/20240726131311_node_input_unique_constraint/migration.sql
rnd/autogpt_server/postgres/schema.prisma

We made DB schema changes here: https://github.com/Significant-Gravitas/AutoGPT/commit/d2a5bb286f615f00f47a1d497b7296c3de4d3e83 and added SQLite migrations, but not PG (we support both dbs). 
This PR adds those migrations
___
___
- Added a unique constraint on columns `referencedByInputExecId`, `referencedByOutputExecId`, and `name` in the `AgentNodeExecutionInputOutput` table to ensure data integrity.
- Created a unique index `AgentNodeExecutionInputOutput_referencedByInputExecId_refer_key` in the PostgreSQL migration script.
- Updated the Prisma schema to reflect the new unique constraint on the `AgentNodeExecutionInputOutput` model.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><ta …

fix(server): Add missing PG migrations

---

rnd/autogpt_server/autogpt_server/executor/manager.py
rnd/autogpt_server/autogpt_server/server/server.py
rnd/autogpt_server/autogpt_server/util/service.py

Currently we are running two 2 threads within the API process:
1. pyro thread
2. fast API
The latest change makes it both thread requires prisma connection, while prisma is not multi threaded and should be handled within only a single event loop. 
In the scope: the fix is to revert the change that makes pyro requires prima.
Out of scope: Fix the Prisma usage in AppServer by making pyro & fast API shares the same event loop.

fix(rnd): Fix broken server execution update due to split prisma connection to different loops

---

rnd/autogpt_builder/src/app/globals.css
rnd/autogpt_builder/src/app/layout.tsx
rnd/autogpt_builder/src/app/providers.tsx
rnd/autogpt_builder/tailwind.config.ts

**User description**
The current implementation of the ShadCn components is in need of a theme standardization. When developing front-end solutions it is essential that we stay in alignment on styles, themes, and ux. 
By implementing this change we can allow developers to use class names such as "bg-background", "bg-accent", etc. This will remove complexity and drive easy development of new additions to the solution. 
The only other change was a consolidation of providers. This will keep our root layout clean and robust. Allowing for the focus of the layout.tsx to be components and not to be overflowing with providers as the frontend continues to scale. 
With these small changes we can better support our developer's experience and drive a better development experience. 
- Addition of a …

feat(builder): Apply standard theming for shadCn and centralize providers

---

rnd/autogpt_server/autogpt_server/data/execution.py
rnd/autogpt_server/autogpt_server/data/graph.py
rnd/autogpt_server/autogpt_server/executor/manager.py
rnd/autogpt_server/autogpt_server/server/server.py
rnd/autogpt_server/migrations/20240729051155_static_input_link/migration.sql
rnd/autogpt_server/postgres/migrations/20240729061216_static_input_link/migration.sql
rnd/autogpt_server/postgres/schema.prisma
rnd/autogpt_server/schema.prisma
rnd/autogpt_server/test/executor/test_manager.py

Input from the input pin is consumed only once. While this is required in most of the use cases, there are some cases where the input can only be produced once, and that input needs to be re-used just like an input default value, that is passively providing input data, without triggering any execution. The scope of this change is providing that functionality in the link level, this property will be called **`static link`** in this system.
Provides a static link feature with the following behaviours:
* A link can be marked `static` to become a static link.
* Once a node produces an output it will persist the output data and propagate the output to the other nodes through the link, for a static link, instead of making the data queued in the input pin, it will override the default value.
* …

feat(rnd): Add freezed/static input link feature for retaining input data to be re-used in multiple node executions

---

rnd/autogpt_server/linter.py
rnd/autogpt_server/postgres/schema.prisma
rnd/autogpt_server/pyproject.toml
rnd/autogpt_server/schema.prisma

Migration not being synced has caused issues and CI is not catching this yet.
* Added schema check in both sqlite & postgres prisma.schema on linting step.
* Introduced `poetry run schema` for syncing prisma.schema + generating migration in both files.

feat(rnd): Add postgres schema check on linting step + auto gen migration and schema sync command (poetry run schema)

---

rnd/autogpt_builder/src/components/CustomNode.tsx

fix beautifyString duplicated import, this was breaking the build page

Fix(Builder): beautifyString duplicated import

---

rnd/autogpt_server/autogpt_server/blocks/time_blocks.py
rnd/autogpt_server/autogpt_server/util/test.py

CurrentDateAndTimeBlock would fail if the test is not complete within 1-second wall-time.
In the case a test started at the second 00:00:01:59:59, it becomes flaky.
We can change the test to only assert the type. But this is also a good chance to add more assertion options for Block: a custom function.
Change assertion for the time block using an additional margin of error.

fix(rnd): Fix flaky CurrentDateAndTimeBlock test

---

rnd/autogpt_builder/src/components/CustomNode.tsx

- Resolves #7598
- Always show connected optional pins on node
- Refactor `hasOptionalFields()` to a constant `hasOptionalFields`

fix(builder): Always show connected optional pins on node

---

rnd/autogpt_builder/src/components/Flow.tsx

Resolves: [Add "Pan to Center" for the view on Build Screen/#7627](https://github.com/Significant-Gravitas/AutoGPT/issues/7627)
Users can lose track of their agents if they move the view too far away on the build screen, disrupting their workflow. To enhance usability, a feature is needed to quickly reorient the view to center on the agents, allowing users to regain focus efficiently.
- Introduced the < Controls /> component to the build screen.
- Added buttons for zooming in, zooming out, fitting the view to center on all agents, and locking the viewport.
- Ensured smooth transitions for fitting the view, enhancing user experience and usability.
___
Enhancement
___
- Introduced the `<Controls />` component to the Flow editor in the build screen.
- Added buttons for zooming in, zooming …

fix(builder): Added option to pan view to center agents on build screen

---

rnd/autogpt_server/autogpt_server/data/schedule.py
rnd/autogpt_server/test/executor/test_scheduler.py

___
Bug fix, Tests
___
- Added `userId` field to the schedule creation data to ensure it is never None.
- Uncommented and updated the test for agent schedule to include `user_id` in schedule update and retrieval.
___
<tr>
<td>
<details>
<summary><strong>schedule.py</strong><dd><code>Ensure `userId` is included in schedule creation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/data/schedule.py
- Added `userId` field to the schedule creation data.
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7749/files#diff-ede26f9fd5df807a42873b67234428b3febdbbe31 …

fix(tests): Ensure user ID is not None on schedule in tests

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/customnode.css

- Enhanced the styling of the `CustomNode` component by moving some styles to Tailwind CSS classes.
- Added `overflow-hidden`, `border-4`, and `rounded-xl` classes to the main container.
- Updated padding and background color for better visual hierarchy.
- Adjusted CSS properties to maintain consistency with the new Tailwind styles.
___
Enhancement
___
- Enhanced the styling of the `CustomNode` component by moving some styles to Tailwind CSS classes.
- Added `overflow-hidden`, `border-4`, and `rounded-xl` classes to the main container.
- Updated padding and background color for better visual hierarchy.
- Adjusted CSS properties to maintain consistency with the new Tailwind styles.
___
<table><thead><tr><th></th><th align="left">Relevant …

fix(builder): Added header background and moved some styling to tailwind

---

rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx
rnd/autogpt_builder/src/components/ui/input.tsx

___
Enhancement
___
- Enhanced the `BlocksControl` component by increasing the width of the popover content and updating the styling of the `Card` and `Label` components for better visual hierarchy and user experience.
- Adjusted the focus-visible ring color for input fields to improve accessibility and visual consistency.
___
<tr>
<td>
<details>
<summary><strong>BlocksControl.tsx</strong><dd><code>Update BlocksControl component styling for better UI</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx
<li>Increased width of the popover content.<br> <li> Updated <code>Card</code> …

tweak(builder) block control styling

---

rnd/autogpt_server/graph_templates/Discord Chatbot with History_v145.json

Adds a new example agent, this time an Advanced LLM Chatbot with full conversation History.
The content window in this example is not managed, so will grow indefinitely.
The Chatbot is hooked up to Discord as an interface for easy testing.

Add Advanced Chatbot with History using Discord

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/NodeHandle.tsx

___
Enhancement
___
- Increased the background transparency of the node container from `.8` to `.9` for better visibility.
- Changed the title background transparency to `.7` and updated the title font weight to `font-semibold` and font family to `font-roboto`.
- Modified the border color of the node handle when not connected from `border-gray-600` to `border-gray-300`.
___
<tr>
<td>
<details>
<summary><strong>CustomNode.tsx</strong><dd><code>Adjust node container and title styles for better visibility</code></dd></summary>
<hr>
rnd/autogpt_builder/src/components/CustomNode.tsx
<li>Increased background transparency of the node container.<br> <li> Changed …

tweak(builder) Changes to transparency, connector color and title boldness

---

rnd/autogpt_server/autogpt_server/blocks/http.py

If a string request body is passed on the HTTP block, it must be parsed as JSON.
If a string request body is passed on the HTTP block, it must be parsed as JSON.

fix(rnd): Fix unparsed string on HTTP block

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/NodeHandle.tsx
rnd/autogpt_builder/src/components/SchemaTooltip.tsx
rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx

Added tooltips to blocks and the blocks controller
___
Enhancement
___
- Added `SchemaTooltip` component to display block descriptions as tooltips.
- Updated `CustomNode`, `FlowEditor`, `NodeHandle`, and `BlocksControl` components to integrate `SchemaTooltip`.
- Modified `SchemaTooltip` to accept a `description` prop instead of `schema`.
___
<tr>
<td>
<details>
<summary><strong>CustomNode.tsx</strong><dd><code>Add tooltips to CustomNode component for block descriptions</code></dd></summary>
<hr>
rnd/autogpt_builder/src/components/CustomNode.tsx
<li>Imported <code>SchemaTooltip</code> component.<br> <li> Added <code>description</code> field to …

Added tooltips for blocks

---

rnd/autogpt_server/autogpt_server/blocks/basic.py
rnd/autogpt_server/autogpt_server/data/block.py
rnd/autogpt_server/autogpt_server/data/graph.py

We need some way to distinguish blocks that should have a static link on their output (currently ValueBlock).
Add a static output field to the `GET /blocks` API.
Update ValueBlock description, make ValueBlock as staticOutput == true.

feat(rnd): Add staticOutput field on block API

---

rnd/autogpt_builder/src/components/Flow.tsx

This makes it so the blocks spawn at the center of the screen instead of at 0,0 / off the screen
https://github.com/user-attachments/assets/85f13a65-ac3f-47d0-a3fc-0c1e7ed1002e
Had to add ``useViewport`` and updated the add node to use the current useViewport and half it to get the center!

Feat(Builder): Make blocks spawn in the center of the screen not at 0,0

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/lib/autogpt-server-api/types.ts

Make static connections correctly displayed on newly connected edges. Previously, static connection were only correctly displayed when loading an existing graph. This is currently relevant only to `ValueBlock` output.

fix(builder): Correctly display static links on new edges

---

rnd/autogpt_server/autogpt_server/executor/manager.py

We don't have an ordering guarantee on the node execution.
Let's say we have a node that has to execute different data A, B, and C.
The current implementation limits the execution to 1 execution at a time, but there is no guarantee that A, B, and C will be executed in order.
The initial implementation did not have any restrictions, so it used to be A, B, and C executed in parallel
In the current implementation with the per-node constraint, it's A, B, C are executed serially but with no guarantee of ordering.
The scope of this PR is to guarantee that order.
Guaranteeing the execution per node ordering by avoiding any re-enqueue mechanism. If there are two executions run in the same node, the first one will be executed and the other will block. The blocking mechanism is indeed sub-optimal, …

fix(rnd): Guarantee execution ordering per node by waiting the node completion

---

rnd/autogpt_builder/src/lib/autogpt-server-api/client.ts

Websocket connection retry has no backoff period which causes event-loop freeze.
Add backoff period on retry.

fix(rnd): Fix JS event-loop freeze caused by websocket connection retry

---

rnd/autogpt_builder/src/components/node-input-components.tsx

We where having a issue when editing the input of a block because it did not have a default value, by adding a empty default it fixes it
This is a fix for https://github.com/Significant-Gravitas/AutoGPT/issues/7908 the original video of the bug is also in the same issue 
https://github.com/user-attachments/assets/c0216a22-966b-479e-bd15-181bea36a293
Simply set value to be ``value = "",``

fix(builder): Set default `value` in `NodeStringInput` to silence uncontrolled input warning

---

rnd/autogpt_builder/src/components/Flow.tsx

When we delete a block undoing it would not bring it back, this is to fix that. we where not properly adding the deleted block to history so it was not logged
https://github.com/user-attachments/assets/8ab8096f-65b9-44a3-9853-407cde0cb159

Feat(Builder): Fix delete block is non-undoable

---

rnd/autogpt_builder/src/components/customedge.css

Normally edges are always drawn below nodes, so sometimes if may be hard to see how they connect and impossible to delete on mobile devices.
- Draw selected edges above nodes

feat(builder): Draw selected edges above nodes

---

rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx
rnd/autogpt_builder/src/components/ui/card.tsx

This fixes the block menu width as for the tutorial this happens
now with the fix it properly highlights the area
Inside of ``rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx`` I updated the width
```diff
-- className="w-96 p-0"
++ className="w-[30rem] p-0"
```
and then i had to remove ``min-w-fit`` from ``rnd/autogpt_builder/src/components/ui/card.tsx``

Feat(Builder): Fix block menu width

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/InputModalComponent.tsx

Long text in input modals is hard to read. Ticket: https://github.com/Significant-Gravitas/AutoGPT/issues/7833
- Add minimize/maximize button in the corner of modal to make it significantly larger and centered
- Add copy button to copy all text
- Add optional `title` to display as a modal header
Maximized:
___
enhancement
___
- Enhanced the `InputModalComponent` to include maximize/minimize functionality, allowing users to resize the modal.
- Added a copy button to the `InputModalComponent` to enable copying of text to the clipboard.
- Introduced an optional `title` prop to display a header in the modal.
- Updated the `CustomNode` component to pass the new `title` and `initialValue` props to the `InputModalComponent`.
___
<table><thead><tr><th></th><th align="left">Relevant …

feat(builder): Resizable input modal

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/lib/autogpt-server-api/types.ts
rnd/autogpt_server/autogpt_server/data/model.py

Currently all non-required inputs are considered advanced and hidden by default but sometimes it's desirable to always show a non-required input.
- Add `advanced` to `SchemaField` and pass it to `json_extra`
- Add `advanced` to `BlockIOSubSchemaMeta` type
- Update `CustomNode`, so that:
- non-required advanced inputs are hidden
- non-advanced and required inputs are always shown

feat(builder, server): Add advanced block inputs

---

rnd/autogpt_server/autogpt_server/blocks/__init__.py
rnd/autogpt_server/autogpt_server/blocks/basic.py
rnd/autogpt_server/autogpt_server/blocks/medium.py
rnd/autogpt_server/autogpt_server/blocks/time_blocks.py
rnd/autogpt_server/autogpt_server/usecases/sample.py
rnd/autogpt_server/test/executor/test_manager.py

This happens here because both the input and the output pins have the same name: Value.
Avoid duplicating pin-names.
___
Bug fix
___
- Added a check to prevent duplicate field names in `input_schema` and `output_schema` in blocks, raising a `ValueError` if duplicates are found.
- Renamed fields in `InputOutputBlockOutput` and `CountdownTimerBlock` to avoid duplication and improve clarity.
- Removed `author_id` from the Medium block output schema.
- Updated test cases and graph links to reflect the changes in field names.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Prevent duplicate field names in block schemas</code>&nbsp; &nbsp; …

fix(rnd): avoid duplicating name on input/output pin for blocks

---

rnd/autogpt_server/autogpt_server/data/execution.py
rnd/autogpt_server/autogpt_server/executor/manager.py

- Resolves #8009
- Handle JSON-encoding inside `.data.execution.upsert_execution_output(..)` to ensure it is always encoded the same
- Amend `.executor.manager.execute_node(..)` to pass unencoded data into `upsert_execution_output(..)`

fix(server): Always JSON-encode `AgentNodeExecutionInputOutput` data

---

rnd/autogpt_server/autogpt_server/util/decorator.py

Fix type hinting created by the function decorator.
Fixed type hinting for `@time_measured` and `@error_logged`.

fix(rnd): Fix decorator function type hint

---

rnd/autogpt_builder/.gitignore
rnd/autogpt_builder/next.config.mjs
rnd/autogpt_builder/package.json
rnd/autogpt_builder/sentry.client.config.ts
rnd/autogpt_builder/sentry.edge.config.ts
rnd/autogpt_builder/sentry.server.config.ts
rnd/autogpt_builder/src/app/global-error.tsx
rnd/autogpt_builder/src/app/login/actions.ts
rnd/autogpt_builder/src/components/admin/marketplace/AdminFeaturedAgentsControl.tsx
rnd/autogpt_builder/src/components/admin/marketplace/actions.ts
rnd/autogpt_builder/src/components/marketplace/actions.ts
rnd/autogpt_builder/src/instrumentation.ts
rnd/autogpt_builder/src/lib/supabase/client.ts
rnd/autogpt_builder/src/lib/withRoleAccess.ts
rnd/autogpt_builder/yarn.lock

We want to track errors in the frontend
Adds sentry and configures a few of its more straightforward settings to meet our goals. The main one I changed was the actions to work
(note 90%+ of this was scaffolded by the sentry wizard 🧙 )

feat(builder): sentry integration

---

rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/edit/control/ControlPanel.tsx
rnd/autogpt_builder/src/components/node-input-components.tsx
rnd/autogpt_builder/src/components/ui/input.tsx
rnd/autogpt_builder/src/hooks/useAgentGraph.ts
rnd/autogpt_builder/src/lib/utils.ts
rnd/autogpt_server/autogpt_server/executor/manager.py

https://github.com/Significant-Gravitas/AutoGPT/pull/8052#discussion_r1759764573
Introduced a new execution bug in which the node that hasn't been saved is unable to execute.
The change reverts the change introduced in the mentioned PR and does it differently to avoid impacting the saved node id.
And fix the behaviour of running an agent that is not saved yet by disabling it.

fix(rnd): Fix execution error on non-saved agent

---

rnd/autogpt_builder/src/lib/autogpt-server-api/baseClient.ts
rnd/autogpt_builder/src/lib/autogpt-server-api/client.ts
rnd/autogpt_builder/src/lib/autogpt-server-api/clientServer.ts
rnd/autogpt_server/.env.example

This PR changes the default hardcoded ports on the frontend for _server_ because I changed the port to 8006 to support supabase which runs kong on 8000
replaced hardcoded instances of "http://localhost:8000/api" ---> "http://localhost:8006/api"

tweak(rnd): Update server and postgres ports

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/executor/manager.py

We are still missing important log information & the llm failure doesn't propagate the error.
Fix both issues.
> [!NOTE] 

fix(platform): Fix logging incomplete information & LLM missing error

---

.github/workflows/platform-backend-ci.yml
autogpt_platform/frontend/package.json
autogpt_platform/frontend/sentry.client.config.ts

Remove sentry popup
add run option to run with sentry disabled
> [!NOTE] 

fix(frontend): Remove Sentry Pop-up and add run options

---

autogpt_platform/backend/.env.example

BACKEND_CORS_ALLOW_ORIGINS as introduced in #8140 should be a list
> [!NOTE] 

fix(platform): Update Backend .env.example BACKEND_CORS_ALLOW_ORIGINS to be a list

---

autogpt_platform/infra/helm/autogpt-builder/templates/frontendconfig.yaml
autogpt_platform/infra/helm/autogpt-builder/values.dev.yaml

Not all browsers automatically redirect to https. Adding a frontend config to force a redirect at the ingress level
Created frontend config
Added annotation to ingress
> [!NOTE] 

tweak(platform) Add frontendconfig for redirect

---

autogpt_platform/backend/.env.example

Adding yet another missing mandatory environment variable.
Added:
SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY
SUPABASE_JWT_SECRET
> [!NOTE] 

fix(platform): Add missing mandatory environment variable

---

autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx

When you close the blocks panel, the filter does not reset. This PR fixes that
https://github.com/user-attachments/assets/fa7c6c29-16bf-49a3-b798-ea8395909b2d
> [!NOTE] 

fix(platform): Reset Block Control filters on popover close

---

autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/components/PrimaryActionButton.tsx

Recent UI change on the Run/Stop removes the UI notion of a disabled button on the unsaved agent.
It also replaces the disabled button with an intrusive browser alert, many browser users block this alert (and the browser auto blocks it after several alerts).
* Reduce button opacity on an unsaved agent.
* Replace browser alert with auto-disappearing toast.
https://github.com/user-attachments/assets/f76f03b6-0d1c-431f-b7e4-5d1f4e302110
> [!NOTE] 
- Edit an agent from monitor, and confirm it …

fix(platform): UI fixes; Fix disabled Run/Stop button

---

autogpt_platform/backend/backend/blocks/basic.py
autogpt_platform/backend/backend/data/block.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/DataTable.tsx
autogpt_platform/frontend/src/components/RunnerUIWrapper.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.ts

Expected:
When it's executed:
* Re-purposed backend BlockUIType to generic BlockType.
* Avoid note block to be executed by the backend.
* Fix UI bug showing note block as a normal block.
* Prettify JSON output 
> [!NOTE] 

fix(platform): UI fixes; Fix block note UI displayed as normal block;Json-prettify execution output

---

autogpt_platform/backend/backend/blocks/llm.py

This was requested by a couple of users and I've felt the need two when building agents.
The AITextSummarizerBlock in the autogpt_platform/backend/backend/blocks/llm.py file has been enhanced to include the following changes:
- Added a new enum class, SummaryStyle, with options for `concise`, `detailed`, `bullet points`, and `numbered list` styles.
- Added a new input parameter, `focus`, to specify the topic of the summary.
- Modified the _summarize_chunk method to include the style and focus in the prompt.
- Modified the _combine_summaries method to include the style and focus in the prompt.
These changes allow users to customize the style and focus of the generated summaries, providing more flexibility and control.

Feat(Builder): Enhance AITextSummarizerBlock with configurable summary style and focus

---

autogpt_platform/docker-compose.yml

Now that we've added supabase, we have soo many services, many that we dont use. Unpick and remove the ones we don't need.
Removed realtime, storage, imgproxy, meta, functions
> [!NOTE] 

tweak(platform): Remove unused supabase services in docker compose

---

autogpt_platform/frontend/src/components/DataTable.tsx
autogpt_platform/frontend/src/components/ui/render.tsx

We want to be able to previous images and videos in the Builder.
This change checks if an output url points to an image or a video, and renders it in the output table rather than displaying the url.
This works for raw video urls and YouTube urls.
https://github.com/user-attachments/assets/7ecf4e77-cbf9-4475-859e-e8417ce8d728

Feat(Builder): Add Video and Image Rendering to Block outputs

---

autogpt_platform/frontend/src/app/auth/callback/route.ts
autogpt_platform/frontend/src/app/build/page.tsx
autogpt_platform/frontend/src/app/layout.tsx
autogpt_platform/frontend/src/app/login/actions.ts
autogpt_platform/frontend/src/app/login/page.tsx
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/components/NavBar.tsx
autogpt_platform/frontend/src/components/NavBarButtons.tsx
autogpt_platform/frontend/src/components/PrimaryActionButton.tsx
autogpt_platform/frontend/src/components/TallyPopup.tsx
autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx
autogpt_platform/frontend/src/components/edit/control/ControlPanel.tsx
autogpt_platform/frontend/src/components/flow.css
autogpt_platform/frontend/src/components/ui/button.tsx

Design reference: https://www.figma.com/design/Oeu3UE3k134biyWQL2UL9B/Simple-updates-to-UI-before-beta?node-id=35-1060&node-type=canvas&t=LHPSt1U9Nu0dVWbu-0)](https://www.figma.com/design/Oeu3UE3k134biyWQL2UL9B/Simple-updates-to-UI-before-beta?node-id=35-1060&node-type=canvas&t=LHPSt1U9Nu0dVWbu-0
This PR brings the current UI one step closer to the design.
Navigation
* Avoid redirecting to unimplemented /profile, redirect to home `/` instead.
* Fix broken zoom-in zoom-out due to the run button covering it.
Layout
* Make flow-editor full-screen: Remove border and make the whole screen an editor
* On block listing: top border for scrolling is added, and vertical padding is removed.
Text
* Add `credits` text back.
Navbar
* Align styling, and reduce excessive shadow & radius.
* Add button …

feat(platform): Sync on new UI design

---

autogpt_platform/backend/backend/blocks/llm.py

I've found in my agent creation that I often need LLMs to generate lists. This block simplifies the process for users, allowing them to generate Python list objects without having to repeatedly figure out prompting and parsing. The new `AIListGeneratorBlock` allows users to efficiently generate lists based on a focus or provided source data.
[AI List Generator Test_v11.json](https://github.com/user-attachments/files/17180159/AI.List.Generator.Test_v11.json) 📁
- Added a new block `AIListGeneratorBlock` that generates Python lists using an LLM.
- Input fields include `focus`, `source_data`, LLM `model`, and retry attempts.
- Integrated a method to call an LLM and convert the response string into a valid Python list.
- Implemented error handling and retry logic for up to 5 attempts.
- …

feat(blocks): Add AI List Generator block

---

autogpt_platform/backend/backend/blocks/iteration.py

The ListIteratorBlock is currently very hard to work with, as it constructs and returns dictionaries (iirc - or it could be Tuples?) with an added index.
For most use-cases this makes the outputs very cumbersome to work with, requiring subsequent data processing blocks.
The block should be simplified to just output the list items.
https://github.com/user-attachments/assets/cf5fe2a3-4cba-47b3-b491-51d5ba6f7913

tweak(blocks): Simplify iteration block to output list items

---

.github/labeler.yml

Automatically apply the `platform/blocks` label to PRs that change files in `backend/blocks/`

dx: Auto-label block PRs

---

docs/content/server/new_blocks.md

This is to prevent issue with hand-made and too similar UUIDs: https://github.com/Significant-Gravitas/AutoGPT/issues/8223
- Add `important` admonition in `new_blocks.md` with instruction to use online UUID generator or python snippet
- Add comment for AI, so it doesn't make up UUID
> [!NOTE] 

docs(server): Request to use UUID generators for new block ids

---

autogpt_platform/market/market/db.py

@aarushik93 requested this change for debugging marketplace issues
swaps from a prisma raw query to a structured prisma query
> [!NOTE] 

feat(market): swap to prisma direct query

---

autogpt_platform/frontend/src/app/login/page.tsx

This pull request addresses a broken link in the frontend for the terms of use. The broken link has been updated to ensure users can access the terms of use page correctly.
- Fixed the broken link to the terms of use in `autogpt_platform/frontend/src/app/login/page.tsx`
Please review the changes and confirm that the link is now functional.

tweak(frontend): Fix broken terms of use link

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/manager.py

Current graph execution is always in the completed status, the notion of failing only happens in the node execution.
But there is a possibility the graph executor has a buggy code and the graph execution is failed.
Add execution failure and exception on graph execution persisted to the DB.
> [!NOTE] 

feat(platform): Add Graph Execution error data & status

---

autogpt_platform/infra/helm/autogpt-builder/templates/configmap.yaml
autogpt_platform/infra/helm/autogpt-builder/templates/frontendconfig.yaml
autogpt_platform/infra/helm/autogpt-builder/templates/managedcert.yaml
autogpt_platform/infra/helm/autogpt-builder/values.dev.yaml
autogpt_platform/infra/helm/autogpt-builder/values.prod.yaml
autogpt_platform/infra/helm/autogpt-websocket-server/templates/backendconfig.yaml
autogpt_platform/infra/helm/autogpt-websocket-server/templates/frontendconfig.yaml
autogpt_platform/infra/helm/autogpt-websocket-server/templates/service.yaml
autogpt_platform/infra/helm/autogpt-websocket-server/values.prod.yaml

We have our prod environment now, adding the prod values for builder and ws. 
Doing some small clean ups and removing unused values, adding updated values such as to support www.
- Added prod values for builder and ws.
- Updated Cors values
- Updated managed cert / ingress to handle www
Has been deployed and fully tested in prod in the past week.
> [!NOTE] 

feat(infra,prod): Add prod values builder and ws

---

autogpt_platform/frontend/src/components/customedge.css

`x` button to delete edges was rendered below nodes, even when edge was selected and shown above nodes. This was because edge button element was a sibling of edge, not its descendant.
- Modify `customedge.css` to make edge label render above nodes
> [!NOTE] 

fix(builder): Make edge delete button render above nodes

---

autogpt_platform/frontend/src/lib/autogpt-server-api/baseClient.ts

fixed issue #8101 
the main change to the BaseAutoGPTServerAPI class was the removal of the async keyword from 23 methods that don't use await internally. These methods now return Promises directly, which is more efficient and cleaner. The async keyword was retained for 4 methods that do use await. No changes were made to private methods or WebSocket-related functions. These modifications address the issue of unnecessary async functions while maintaining the same functionality, improving code efficiency without altering the class's behavior.

refactor(frontend): Remove unnecessary keywords in `BaseAutoGPTServerAPI`

---

autogpt_platform/backend/backend/data/graph.py

We don't want to show templates downloaded from the marketplace to all users. Only to the user who downloaded it.
Updated the get_graphs_meta function to always filter by user_id.
Made user_id not optional
> [!NOTE] 

fix(platform): Always filter on user id

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/rest_api.py
autogpt_platform/frontend/src/app/marketplace/submit/page.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/baseClient.ts

Marketplace wasn't implemented with secret hiding. It downloads the agent as is and then submits it as is, with secrets in cleartext. 
Made the graph endpoint hideable. Added query param to hide secrets, which should hide the input data in the nodes when fetching
> [!NOTE] 

fix(platform): Fix marketplace leaking secrets

---

autogpt_platform/backend/backend/data/graph.py

The delete from the review was added here: https://github.com/Significant-Gravitas/AutoGPT/pull/8281#discussion_r1791958040. This should not have been an inplace operation. 
Made it so we track the keys to delete 
> [!NOTE] 

fix(platform): Update deletion of secret values to not do it in place

---

autogpt_platform/backend/.env.example
autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/server/rest_api.py
autogpt_platform/backend/backend/server/ws_api.py
autogpt_platform/backend/backend/util/logging.py
autogpt_platform/backend/backend/util/settings.py

We dont offer ollama instance so we need to remove it from the LLM options. 
We can use ~~one of the cloud flags we have now~~ *these didn't actually do what we thought* to turn it on and off
Adds 
- BehaveAs as an environment variable
- Adds a metaclass to the LLM Model
- Updates various issues with how AppEnv was used 
- Updates Logging to correctly follow cloud pathway in cloud
> [!NOTE] 

feat(backend): add the capibility to disable llm models in the cloud env

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/rest_api.py

This was designed for local use/installs. We don't support this anymore and all users are exepcted to have a user and download agents from the marketplace
Removed the import_packaged_templates function and references
> [!NOTE] 

tweak(platform): Remove importing templates from local dir

---

autogpt_platform/backend/backend/blocks/__init__.py
autogpt_platform/backend/backend/blocks/ai_shortform_video_block.py
autogpt_platform/backend/backend/blocks/basic.py
autogpt_platform/backend/backend/blocks/block.py
autogpt_platform/backend/backend/blocks/decoder_block.py
autogpt_platform/backend/backend/blocks/email_block.py
autogpt_platform/backend/backend/blocks/github/issues.py
autogpt_platform/backend/backend/blocks/github/pull_requests.py
autogpt_platform/backend/backend/blocks/github/repo.py
autogpt_platform/backend/backend/blocks/google/gmail.py
autogpt_platform/backend/backend/blocks/google/sheets.py
autogpt_platform/backend/backend/blocks/google_maps.py
autogpt_platform/backend/backend/blocks/ideogram.py
autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/blocks/medium.py
autogpt_platform/backend/backend/blocks/replicate_flux_advanced.py
autogpt_platform/backend/backend/blocks/search.py
autogpt_platform/backend/backend/blocks/talking_head.py
autogpt_platform/backend/backend/blocks/text_to_speech_block.py
autogpt_platform/backend/backend/blocks/youtube.py
autogpt_platform/backend/backend/data/block.py
docs/content/server/new_blocks.md

https://github.com/Significant-Gravitas/AutoGPT/pull/8267 revealed the inconsistency of the way we throw an error in the block implementation:
* Yielding `error` and abort
* Yielding `error` without aborting
* Raise an error
Any error happening in the block has already been yielding an `error`. So the simplest approach to produce an error is by simply raising it. This will mark the execution as failed. Manually yielding `error` without using an exception will be interpreted as a fully handled & completed execution.
* Remove all try-catch yield "error" in block implementation.
* Remove if output == "error": raise error logic on the block implementation.
* Add check to ensure all block `error` pin is a string, this will be used to expose execution error to other nodes, if needed.
> [!NOTE] …

fix(platform): Remove blind try-except for yielding error on block

---

autogpt_platform/frontend/src/app/login/page.tsx

This simply comments out the buttons for logging in with Google/GitHub/Discord for now
> [!NOTE] 

refactor(frontend/login): Hide sign in with Google/GitHub/Discord for now

---

autogpt_platform/frontend/src/app/globals.css
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/components/ui/input.tsx
autogpt_platform/frontend/src/components/ui/select.tsx
autogpt_platform/frontend/src/components/ui/textarea.tsx

- Resolves #8333
Before/after:
<p>
</p>
- **remove `rounded-xl` from node input components**
- **apply consistent border coloring and shadows to `Input`, `Select`, and `Textarea`**
- **add `whitespace-nowrap` to `CustomNode` header category tags**

fix(frontend): Fix styling inconsistencies in input elements

---

autogpt_platform/infra/helm/autogpt-builder/templates/deployment.yaml

We were using .env.local previously. this won't work in ci and we shouldn't be using it anyways. 
Added configmap to deployment
> [!NOTE] 

feat(builder): Use configmap for builder

---

autogpt_platform/infra/helm/autogpt-builder/templates/sealed-secrets.yaml
autogpt_platform/infra/helm/autogpt-market/templates/sealed-secrets.yaml
autogpt_platform/infra/helm/autogpt-server/templates/sealed-secrets.yaml
autogpt_platform/infra/helm/autogpt-websocket-server/templates/sealed-secrets.yaml

Names for market and builder were incorrectly annotated
Fixed the name and annotation
> [!NOTE] 

fix(infra): Fix sealed secret names 

---

autogpt_platform/infra/helm/autogpt-server/values.dev.yaml
autogpt_platform/infra/helm/autogpt-server/values.prod.yaml

Removed docs endpoint. Should now use health endpoint
Changed /docs > /health in values.dev and values.prod for server
> [!NOTE] 

fix(infra): Update backend server health check endpoint

---

autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/hooks/useCopyPaste.ts

This allows copy and pasting of blocks between flows + it cleans up and moves all of the copy and paste related code to its own file to prevent adding a bunch more code to the main ``Flow.tsx``
Made a new ``useCopyPaste.ts`` file inside of the ``hooks`` folder, this now holds everything related to copy and pasting of blocks + the new code to allow copy and pasting between flows.
Here i show me copy and pasting a section of connected blocks from one flow to another and running it, everything works as intended + i show that we can still normally copy and paste a single block.
https://github.com/user-attachments/assets/7759f4b3-c97a-4b8b-a9b1-efb50b7ba591

feat(frontend): Allow copy and pasting of blocks between flows

---

.github/workflows/repo-pr-enforce-base-branch.yml

We want to keep `master` as the default branch for easy and safe cloning, but `dev` as the target for all pull requests.
- ci: Add a workflow that automatically changes PRs' target branch from `master` to `dev` unless the head branch is `dev` or `hotfix/*`

ci: Enforce `dev` as base branch for development

---

autogpt_platform/infra/helm/autogpt-server/values.dev.yaml
autogpt_platform/infra/helm/autogpt-server/values.prod.yaml

fix spelling mistake

---

autogpt_platform/infra/helm/autogpt-server/values.prod.yaml

Liveness probe needs the right endpoint or it failes
Fix typo heath in autogpt_server/values.prod.yaml to health
> [!NOTE] 

 fix(platform/infra): Fix liveness probe 

---

autogpt_platform/frontend/src/components/NodeOutputs.tsx

This just fixes the output as before it looked like this where the divider bar is in the wrong place
this simply fixes it so it now looks like

feat(blocks): fix output divider bar being in the wrong place

---

autogpt_platform/docker-compose.yml

We removed a bunch of supabase services https://github.com/Significant-Gravitas/AutoGPT/pull/8178/files?diff=split&w=0#diff-c0568dde0d708d2b1345af548966c8eaa96fec5d35016f1c173944f577af6085
but this seems to break more than fix. 
Put them all back in
> [!NOTE] 

fix(platform/dockercompose): Put removed services back in

---

.github/workflows/platform-autogpt-deploy.yaml
autogpt_platform/infra/helm/autogpt-builder/values.dev.yaml
autogpt_platform/infra/helm/autogpt-server/values.dev.yaml
autogpt_platform/infra/helm/autogpt-server/values.prod.yaml
autogpt_platform/infra/helm/autogpt-websocket-server/values.dev.yaml
autogpt_platform/infra/terraform/environments/dev.tfvars
autogpt_platform/infra/terraform/main.tf
autogpt_platform/infra/terraform/modules/iam/main.tf
autogpt_platform/infra/terraform/modules/iam/outputs.tf
autogpt_platform/infra/terraform/modules/iam/variables.tf
autogpt_platform/infra/terraform/variables.tf

Automatic deploys from dev branch to dev environment
Set up gha iam account
Set up workload identity pools so we can use an IAM without keys
Set up CI pipeline to build, push docker images to artifact registery
Set up CI pipeline to do a helm upgrade on all services
> [!NOTE] 

feat(platform/ci) Set up deploys from dev

---

autogpt_platform/frontend/src/components/edit/control/SaveControl.tsx

This update stops the browser from showing its usual save page pop-up when you press Ctrl/Cmd + S. Instead, it now saves your work in the application, making it easier and quicker to use.
1. Now,pressing Ctrl/Cmd + S saves changes directly in the app instead of triggering the browser’s save page dialog.
2. A toast notification confirms successful saves,

Implement custom save shortcut in SaveControl component

---

autogpt_platform/infra/helm/autogpt-server/templates/deployment-executor.yaml
autogpt_platform/infra/helm/autogpt-server/templates/service-executor.yaml
autogpt_platform/infra/helm/autogpt-server/values.dev.yaml
autogpt_platform/infra/helm/autogpt-server/values.prod.yaml

A change was made so that the rest server now uses the DB Manager inside of executor. So we have to expose that port for use
Expose port 8005 on the deployment and service
> [!NOTE] 

fix(platform): Expose DB Manager Port

---

autogpt_platform/frontend/next.config.mjs

dontenv loads environment variables only from environment variable files and it's messing with docker and k8s environments when not adding these files dynamically
Remove dotenv and let nextjs handle environment variabels. This still loads from .env* files locally and in different environments but also from system environment when needed. You can read here: https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#environment-variable-load-order
> [!NOTE] 
- Edit …

feat(platform/frontend) Remove dotenv

---

autogpt_platform/frontend/src/components/agptui/PublishAgentAwaitingReview.stories.tsx
autogpt_platform/frontend/src/components/agptui/PublishAgentAwaitingReview.tsx
autogpt_platform/frontend/src/components/agptui/PublishAgentSelect.stories.tsx
autogpt_platform/frontend/src/components/agptui/PublishAgentSelect.tsx
autogpt_platform/frontend/src/components/agptui/PublishAgentSelectInfo.stories.tsx
autogpt_platform/frontend/src/components/agptui/PublishAgentSelectInfo.tsx
autogpt_platform/frontend/src/components/ui/icons.tsx

feat(platform): Add Publish agent flow section 

---

autogpt_platform/frontend/src/components/marketplace/AgentDetailContent.tsx

Currently clicking "Save to Templates" on a template page provides no visual feedback and doesn't do anything.
- Create and redirect to a new agent instance when clicking on the `Save to Templates` button
- Show toast as a visual feedback when clicking button and on error
> [!NOTE] 
> [!NOTE] 
If you're making configuration or infrastructure changes, please remember …

feat(frontend): Make `Save to Templates` Marketplace button create and redirect to a new agent

---

autogpt_platform/frontend/src/lib/utils.ts
autogpt_platform/frontend/src/tests/util.spec.ts

To be filled later
To be filled later
> [!NOTE] 
> [!NOTE] 
- Secrets or …

fix(frontend): object pollution problem

---

.pre-commit-config.yaml
autogpt_platform/backend/backend/usecases/block_autogen.py

Add detect secrets
> [!NOTE] 
> [!NOTE] 
- Secrets or environment variable …

feat(pre-commit): Detect secrets

---

autogpt_platform/README.md

Update the frontend instructions to specify copying of `.env.example` to `.env.local` 
> [!NOTE] 
> [!NOTE] 
- Adding new services that need …

docs(platform): Update frontend instructions

---

autogpt_platform/docker-compose.yml

This PR adopted https://github.com/Significant-Gravitas/AutoGPT/pull/8561 changes for the local mode to reduce the number of services being run for local development.
Removed these supabase services on local app out-of-docker mode:
- studio
- rest
- realtime
- storage
- imgproxy
- meta
- functions
> [!NOTE] 
> [!NOTE] 
If you're making configuration or …

feat(backend): Reduce number of services on the local mode

---

autogpt_platform/frontend/package.json
autogpt_platform/frontend/yarn.lock

> [!NOTE] 
> [!NOTE] 
- New or …

fix: update cookie

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.ts

A few errors are being fixed here:
* https://github.com/Significant-Gravitas/AutoGPT/pull/8252 re-introduced bug on dynamic-pin to not populate links on the field with empty values.
* `Run` execution error is not propagated to the user.
* Agent Output & Agent Input validation is now checked during creation (as opposed to execution), but the input_link validation is buggy on the non-created graph.
Fixed the above issues (and display a short id on the node): 
> [!NOTE] 
- Edit an agent from …

fix(frontend): Broken UI caused by lack of error propagation on Run

---

autogpt_platform/backend/backend/blocks/helpers/http.py
autogpt_platform/backend/backend/blocks/jina/_auth.py
autogpt_platform/backend/backend/blocks/jina/search.py
autogpt_platform/backend/backend/blocks/search.py
autogpt_platform/backend/backend/data/credit.py

Jina needs an API key now
Update to use credentials and move into jina folder
https://github.com/user-attachments/assets/1e026909-3d8b-43b6-b6dc-7744531cf233
> [!NOTE] 
> [!NOTE] 
Examples of such …

fix(searchtheweb): Fix the Jina Search Block

---

.github/workflows/platform-autgpt-deploy-prod.yml
.github/workflows/platform-autogpt-deploy-dev.yaml
.github/workflows/platform-autogpt-deploy.yaml
autogpt_platform/README.md

We made the decision to move most things to a private repo, related to cloud deployment. Running this pipeline through the private repo then
Removed build and deploy steps to instead triggger a workflow in infra repo
> [!NOTE] 
> [!NOTE] 
If you're making configuration or infrastructure changes, please remember to check you've updated the related infrastructure code …

ci(platform): Update pipelines to run from infra repo

---

autogpt_platform/autogpt_libs/autogpt_libs/supabase_integration_credentials_store/store.py
autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/util/settings.py

We want to provide jina by default on our platform
Added Jina credentials to all the default settings in store.py. 
Added a jina cost filter in credit.py
<details>
</details>
<details>
</details>

feat(blocks/jina): Add default credentials for Jina

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/data/block_cost_config.py
autogpt_platform/backend/backend/data/cost.py
autogpt_platform/backend/backend/data/credit.py

Currently, the cost for LLM blocks is defined separately (in `llm.py`) from the rest of the block cost (in `credit.py`).
We need a single place to configure these.
* Moved blockcost-related models to `cost.py`.
* Merged LLM cost and the rest of the block cost to `block_cost_config.py`. 
<details>
</details>
<details>
</details>

refactor(backend): Centralize Block Cost into a Single File

---

autogpt_platform/backend/backend/data/model.py
autogpt_platform/frontend/package.json
autogpt_platform/frontend/src/hooks/useCredentials.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

- Patch for breakage from #8524
- Resolves #8635
- fix(frontend): Fix type mismatch of `CredentialsField` schema between frontend and backend
- Fix usages of `credentialsSchema.credentials_provider`
- refactor(backend): Create `CredentialsFieldSchemaExtra` model in backend so it can be mirrored directly in frontend
- Add check to enforce multi-provider `CredentialsField` always has `discriminator`
- dx: Add type checking shortcut `yarn type-check` / `npm run type-check` for frontend
<details>
</details>

fix(frontend): Unbreak credentials input on single-provider blocks

---

autogpt_platform/autogpt_libs/autogpt_libs/supabase_integration_credentials_store/store.py
autogpt_platform/backend/backend/data/block_cost_config.py
autogpt_platform/backend/backend/util/settings.py

This PR updates block cost configuration.
**Key Changes:**
1. **Credentials Store:** 
- Added `unreal_credentials` to manage Unreal Speech API keys.
- Updated `DEFAULT_CREDENTIALS` and `get_all_creds` methods to include Unreal Speech credentials if available.
- Defined `unreal_speech_api_key` in `Secrets` to handle Unreal Speech API keys.
2. **Block Cost Configuration:**
- Added `UnrealTextToSpeechBlock` with a cost of 5 credits, referencing Unreal Speech API credentials.
- Updated block costs for `IdeogramModelBlock` and `AIShortformVideoCreatorBlock`.
- Introduced new block costs: `AIMusicGeneratorBlock`, `JinaEmbeddingBlock`, and `AIListGeneratorBlock` with specific cost configurations.
These changes enable us to provide Unreal Speech API support and expand the platform's capabilities …

tweak(backend): Update all block costs

---

autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.ts

AgentExecutorBlock stores the input data in the `data` field of the hardcoded value.
Currently, the AgentExecutorBlock is validating the metadata instead of the actual data.
* Fixed the false-negative validation error on the agent block executor.
* Propagated the error of the validation error to the user instead of throwing a blanket `Invalid credentials or inputs` error.
* Added open agent context menu item on the `agent block executor`.
<details>
</details>
<details>
</details>

fix(frontend): Fix client-side validation for Agent Executor Block

---

classic/README.md
docs/content/classic/index.md

We need to clearly state that the classic AutoGPT is unsupported for security reasons.
Adds a readme for classic autogpt to show that we won't update
<details>
<summary>Test Plan</summary>
</details>

fix(classic): update docs for security deprecation 

---

autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/lib/utils.ts

There are three different issues:
* https://github.com/Significant-Gravitas/AutoGPT/issues/8626 where setting empty string from input box won't visually update the input field.
* https://github.com/Significant-Gravitas/AutoGPT/pull/8524/files#diff-69de95e19acaba021b2e4c08cada30293eb4d8bd451f93aa56cfecb91a5c5f97R235 seems to be a conflict resolving issue which causes the AgentExecutorBlock default value not being populated.
* Setting any nested input field will give a false-negative error UI (which makes the block red) due to the nested field being treated as a non-null error message.
Fixed the mentioned issues above.
<details>
</details>
<details>
- Adding new services that need to …

fix(frontend): Fix input-field update on empty & default value

---

autogpt_platform/frontend/src/components/tutorial.ts

Some recent updates caused the tutorial to break, this simply fixes it :)
Just had to update some of the var names in the tutorial so it knows that to reference 
https://github.com/user-attachments/assets/55c22459-46f5-4b80-89b7-8216ea21c0b3

Feat(Builder/tutorial): Updates to fix tutorial 

---

autogpt_platform/backend/backend/data/user.py
autogpt_platform/backend/backend/server/rest_api.py

Reverts Significant-Gravitas/AutoGPT#8646
The problem analysis that led to #8646 contained some errors, so the migration removed in the PR doesn't seem to have been the cause of the problem we were hunting. Also, this migration is an essential part of the security improvement that we made 2 weeks ago.

Revert "fix(platform): Remove migrate and encrypt function"

---

autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/components/ui/input.tsx

This fixes https://github.com/Significant-Gravitas/AutoGPT/issues/8625
Due to the input values are globally managed and asynchronous, the `onBlur` event was used instead of `onChange` to avoid the [jumping caret problem](https://dev.to/kwirke/solving-caret-jumping-in-react-inputs-36ic).
However, this causes issues when there could be some re-render events that still keep the input box focused, making the `onBlur` not triggered, but the input was reset. One such scenario is the scrolling (zoom-in & zoom-out of the node editor).
Introduce & use `LocalValuedInput`. Instead of using onBlur as a trigger, the component maintains its local state value to be displayed on the input box, but also calls the `onChange` update on the globally managed value state, while syncing its value from the …

fix(frontend): Newly typed text in Input fields vanishes on scroll

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/rest_api.py
autogpt_platform/backend/migrations/20241115170707_fix_llm_provider_credentials/migration.sql

In #8524, the `"llm"` credentials provider was replaced. There are still entries with `"provider": "llm"` in the system though, and those break if not migrated.
- SQL migration to fix the obvious ones where we know the provider from `credentials.id`
- Non-SQL migration to fix the rest
<details>
</details>

fix(backend): Add migrations to fix credentials inputs

---

autogpt_platform/docker-compose.platform.yml

When running in local docker-mode, the executor is unable to access the pyro server of the execution manager with this error:
`Node execution failed with error cannot connect to ('localhost', 8002): [Errno 111] Connection refused`.
Define executionmanager hostname for local docker-mode
<details>
</details>
<details>
</details>

fix(backend): Define executionmanager hostname for local docker-mode

---

autogpt_platform/frontend/src/components/node-input-components.tsx

https://github.com/Significant-Gravitas/AutoGPT/pull/8657 introduces state change on each input `onChange` event.  This causes the NodeKeyValueInput to get re-rendered on each value change making the input unfocussed.
Use a numbered index as the DOM key instead of an actual input key to avoid React's dirty check and re-render the component as a different DOM, which causes the input to un-focus.
<details>
</details>
<details>
</details>

fix(frontend): Typing in the NodeKeyValueInput field causes the field to un-focus

---

autogpt_platform/frontend/src/components/monitor/FlowInfo.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunInfo.tsx

Edit button in Monitor is currently just an icon of a pencil.
- Make edit buttons for both agent and particular run in a `default` style with `Open in Builder` text
- Add `Export` text to json export button

refactor(frontend): Update buttons to edit agents in Monitor

---

autogpt_platform/autogpt_libs/autogpt_libs/auth/depends.py
autogpt_platform/autogpt_libs/autogpt_libs/auth/models.py
autogpt_platform/backend/backend/data/user.py
autogpt_platform/backend/backend/server/utils.py
autogpt_platform/backend/backend/server/ws_api.py

https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpt_platform/autogpt_libs/autogpt_libs/auth/depends.py#L18-L20
This code falls back to the default admin user when the payload is empty, which definite is not intentional.
Refactor DEFAULT_USER_ID fallback logic into a single location, and add config check for fallback.
<details>
</details>
<details>
</details>

fix(backend): Avoid falling back to default user unless ENABLED_AUTH is set to False

---

autogpt_platform/backend/backend/server/routers/v1.py

Add the lower cap of the user credits to zero.
<details>
</details>
<details>
</details>

fix(backend): Add the lower cap of the user credits to zero

---

autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx

Avoid displaying long description text for block
<details>
</details>
<details>
</details>

fix(frontend): avoid displaying long description text for block

---

.pre-commit-config.yaml
autogpt_platform/backend/pyproject.toml

Extracted from #8358 because of https://github.com/Significant-Gravitas/AutoGPT/pull/8358#discussion_r1848785855
`isort` doesn't detect first-party packages correctly and applies its own styling which is incompatible with `black`.
- Set `tool.isort.profile = "black"`
- Explicitly pass the first-party package name in the `isort` jobs in the `pre-commit` config

dx(backend): Fix `pre-commit` `isort` step

---

autogpt_platform/backend/backend/blocks/ai_music_generator.py

The field model_version in the ai music generator project conflicted with pydantic internals. This fixes that.
<details>
</details>
<details>
</details>
This pull request includes several changes to the `autogpt_platform/backend/backend/blocks/ai_music_generator.py` file, focusing on renaming a variable for consistency across the codebase. The variable `model_version` has been renamed to `music_gen_model_version`.
Variable renaming for consistency:
* Renamed `model_version` to `music_gen_model_version` in the `Input` class …

fix(block): Updated model_version to prevent conflicts with pydantic naming

---

README.md

'Read this guide' link uri was 404
change 'server' to 'platform' in uri

docs(platform): Fix url in `README.md`

---

docs/content/platform/advanced_setup.md
docs/content/platform/getting-started.md

User had [issue](https://discord.com/channels/1092243196446249134/1092275629602394184/1310501283400257587) with outdated backend despite updating to the latest version through git.
- Add `--build` to `docker compose up` instructions

docs(backend): Add `--build` to docker command in Getting Started guide

---

autogpt_platform/backend/backend/server/integrations/router.py
autogpt_platform/frontend/src/components/integrations/credentials-provider.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/baseClient.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

- Resolves #8770
- Resolves (hopefully) #8613
- Add `/integrations/credentials` endpoint which lists all credentials for the authenticated user
- Amend credential fetching logic in front end to fetch all at once instead of per provider
<details>
</details>

refactor(platform): Combine per-provider credentials API calls

---

autogpt_platform/frontend/src/app/[lang]/store/search/page.tsx

This make it so the search page can deal with no results / showing only agents and only creators depending on what the search results

feat(platform): Tweaks to Search page 

---

autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx

Blocks should be easy to search, the name is sometimes not straightforward, but the description does.
Make the block description searchable.
<details>
</details>
<details>
</details>

feat(frontend): Make Block description searchable on Block list palette

---

autogpt_platform/backend/backend/blocks/jina/search.py
autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/blocks/search.py
autogpt_platform/backend/backend/data/block_cost_config.py
autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/test/data/test_credit.py
autogpt_platform/frontend/src/components/CustomNode.tsx

We've started enabling cost based on the *partial value* of the `credentials` field. And this logic has never been supported. 
* Add partial object matching on the input data filter for evaluating the block cost.
* Add missing credentials for `ExtractWebsiteContentBlock`
* Removed fallback cost on LLM blocks.
<details>
</details>
<details>
</details>

fix(backend): Fix `credentials` cost filter not able to filter the block cost

---

autogpt_platform/backend/backend/data/credit.py

When calculating the next month, we are not rolling the month number causing an error on credits.
Add modulo while calculating next month.
<details>
</details>
<details>
</details>

hotfix(backend): Fix month credit calculation on December

---

autogpt_platform/frontend/src/app/[lang]/store/agent/[creator]/[slug]/page.tsx
autogpt_platform/frontend/src/components/agptui/RatingCard.stories.tsx
autogpt_platform/frontend/src/components/agptui/RatingCard.tsx

This adds the rating card, currently i just make it show in every agent page till we have better logic for it + we want to make it show on the block builder when we are looking at some one else's agent from the marketplace, this is to be implemented soon
The Tutorial and ? buttons will also be hidden on the market place pages so ignore them showing for now

feat(platform): Adds rating card

---

.github/dependabot.yml

Dependabot's commit messages are bulky and don't use our commit message scopes. Although not fully customizable, this partially fixes it.
- Fix dependabot commit message scopes

dx: Fix dependabot PR/commit titles

---

autogpt_platform/frontend/src/tests/build.spec.ts
autogpt_platform/frontend/src/tests/pages/build.page.ts

In the block tests we didn't have ``connectBlockOutputToBlockInput`` implemented, this PR adds it and adds a test to add two blocks, connect them, saves the graph then runs it to make sure it all works
implements ``connectBlockOutputToBlockInput`` and adds test 
https://github.com/user-attachments/assets/4aed4f5d-8d52-47bc-bd62-9e45e0782c0f

feat(frontend): add block connecting test

---

SECURITY.md

Huntr isn't offering a security bounty for autogpt at the moment so remove it in favor of github security adviosories
comments out huntr line in case they decide to offer it again in the future

docs: huntr no longer is offering a security bounty so remove it

---

autogpt_platform/autogpt_libs/autogpt_libs/feature_flag/client.py
autogpt_platform/autogpt_libs/autogpt_libs/logging/config.py
autogpt_platform/autogpt_libs/autogpt_libs/logging/test_utils.py
autogpt_platform/autogpt_libs/autogpt_libs/rate_limit/config.py
autogpt_platform/autogpt_libs/autogpt_libs/rate_limit/limiter.py
autogpt_platform/autogpt_libs/autogpt_libs/rate_limit/middleware.py

Once we release api key feature, we will want to be able to rate limit as well. This is the foundation for that.
For now it is a blanket rate limit, later we will be able to add tiered rate limits
Added new middleware libary in autogpt_libs which contains the logic for getting the api key, storing it's details in redis and checking how many requests it's done, how many are left and what the reset time is.

feat(libs): Add API key rate limit middleware

---

autogpt_platform/autogpt_libs/autogpt_libs/rate_limit/limiter.py
autogpt_platform/backend/backend/blocks/fal/ai_video_generator.py

Replace Dict with dict
Replace Dict with dict
<details>
</details>
<details>
</details>

chore(blocks/fal): Use dict instead of Dict

---

autogpt_platform/backend/backend/blocks/github/triggers.py

On windows this file load kept crashing stuff on startup so I specified the encoding

fix: specify encoding for file with emoji in it so it loads on windows

---

.github/workflows/platform-backend-ci.yml
.pre-commit-config.yaml
autogpt_platform/autogpt_libs/autogpt_libs/feature_flag/client.py
autogpt_platform/autogpt_libs/autogpt_libs/logging/config.py
autogpt_platform/autogpt_libs/autogpt_libs/logging/test_utils.py
autogpt_platform/backend/linter.py

- Resolves #8859
- Follow-up to #8751
- Add `autogpt_libs` to the backend CI path filter
- Add `ruff format` step for `autogpt_libs` to `linter.py` and `pre-commit` config
- Run `poetry run format` with the new setup

dx(backend): Fix linting & formatting for `autogpt_libs`

---

autogpt_platform/backend/backend/data/model.py

- resolve #8739
I don't think so that this is a frontend issue [might be wrong] , because if we are not classifying that a particular input is `advanced = true/false`. Then we automatically get `advanced = True`.

fix(frontend): advanced-toggle-default

---

autogpt_platform/frontend/src/tests/build.spec.ts
autogpt_platform/frontend/src/tests/pages/profile.page.ts
classic/forge/forge/components/README.md
docs/content/classic/index.md
docs/content/classic/setup/docker.md
docs/content/classic/setup/index.md
docs/content/forge/components/built-in-components.md
docs/content/forge/get-started.md
docs/content/platform/contributing/tests.md
docs/mkdocs.yml

Nick wants others to be able to write tests besides Nick
- Fixes various import errors across the docs to fix dead links
- Adds Docs for making and debugging your own tests

docs: add docs for writing playwright tests

---

autogpt_platform/backend/backend/server/rest_api.py

We aren't using Launch Darkly locally and so it's not set up but it was still attempting to shut down LaunchDarkly when the app shutdown, causing errors on shutdown. This PR fixes that issue by entirely disabling LD on local machines.
Added a contextmanager to handle LaunchDarkly start up and shutdown
Added a check for local environment in said context manager
<details>
</details>
<details>
</details>

fix(platform): Stop the start up & shutdown of LaunchDarkly on local envs

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/data/block_cost_config.py

**Summary:**
This PR removes the `GEMINI_FLASH_1_5_EXP` model (due to inference on OpenRouter not working) and introduces several new models to the `LlmModel` enum. Corresponding updates have been made to the metadata configurations and block cost settings to reflect the changes.
**Key Changes:**
1. **Removed Models:**
- `GEMINI_FLASH_1_5_EXP`
2. **Added New Models:**
- `QWEN_QWQ_32B_PREVIEW`
- `NOUSRESEARCH_HERMES_3_LLAMA_3_1_405B`
- `NOUSRESEARCH_HERMES_3_LLAMA_3_1_70B`
- `AMAZON_NOVA_LITE_V1`
- `AMAZON_NOVA_MICRO_V1`
- `AMAZON_NOVA_PRO_V1`
- `MICROSOFT_WIZARDLM_2_8X22B`
- `GRYPHE_MYTHOMAX_L2_13B`
3. **Metadata Updates:**
- Added metadata entries for the new models with a max output tokens of 4,000 tokens.
4. **Cost Configuration Updates:**
- Defined block costs for the newly added …

feat(blocks): Add new openrouter models

---

autogpt_platform/frontend/src/components/CustomEdge.tsx
autogpt_platform/frontend/src/components/NodeHandle.tsx

Recently pins were made slightly bigger and misaligned needlessly. The problem in the linked issue was to fix connection area, not make them bigger.
- https://github.com/Significant-Gravitas/AutoGPT/issues/8913
- Revert pins size to smaller
- Fix hover area and highlight for input pins
<details>
</details>
<details>
</details>

fix(frontend): Make pins smaller and fix hover area and highlight for input pins

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/server/rest_api.py
autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/backend/backend/util/test.py
autogpt_platform/backend/test/executor/test_scheduler.py
autogpt_platform/frontend/src/app/page.tsx
autogpt_platform/frontend/src/components/feature-flag/with-feature-flag.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/baseClient.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

This is a follow-up of https://github.com/Significant-Gravitas/AutoGPT/pull/8752
There are several APIs and functions related to graph execution that are unused now.
There is also confusion about the name of `GraphExecution` that exists in graph.py & execution.py.
* Renamed `GraphExecution` in `execution.py` to `GraphExecutionEntry`, this is only used as a queue entry for execution.
* Removed unused `get_graph_execution` & `list_executions` in `execution.py`.
* Removed `with_run` option on `get_graph` function in `graph.py`.
* Removed `GraphMetaWithRuns`
* Removed exposed functions only for testing.
* Removed `executions` fields in Graph model.
<details>
</details>
<details>
- Adding …

chore(platform):Refactor GraphExecution naming clash and remove unused Graph Execution functions

---

autogpt_platform/frontend/src/components/node-input-components.tsx

- Resolve #8928 
Currently, the frontend renders a string input for an optional integer. I have now corrected it.

fix(frontend) : Optional number input

---

autogpt_platform/frontend/src/components/tutorial.ts

This is to fix [Tutorial highlight causes bottom buttons to move up #8942](https://github.com/Significant-Gravitas/AutoGPT/issues/8942)
Updates the tutorial to add a short delay before moving onto the next step which prevents the UI from lifting up in a weird way (skip to 14 seconds in the video below to see this being fixed)
Updates to some of the positioning of the steps
Video to show latest run through whole tutorial 
https://github.com/user-attachments/assets/4cf09a2f-8ed2-45bd-9909-aa92540af845

feat(frontend): Update and fix tutorial

---

autogpt_platform/backend/backend/server/routers/v1.py

- Resolves #8945
- Call `on_graph_deactivate` on current active version in `DELETE /api/graphs/{graph_id}` endpoint

fix(backend): Deactivate graph on delete

---

.github/workflows/platform-frontend-ci.yml

- Resolves #8948
- Parallelize frontend test job into a per-browser matrix
- Speed up "Free Disk Space" step by disabling removal of large system packages

ci(frontend): Speed up test jobs

---

autogpt_platform/backend/backend/server/v2/store/model.py
docs/content/platform/new_blocks.md

feat: default for is featured

---

autogpt_platform/frontend/src/components/agptui/PublishAgentSelect.tsx

Fixes #9059 
- Changed agent selection from keying on agent name to keying on agent id

fix(store): Uploading to store selects two agents

---

autogpt_platform/frontend/src/app/store/agent/[creator]/[slug]/page.tsx

Fixes #9054 
- add the video link to the start of the images array

fix(store): Youtube link not showing video on agent page

---

autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/model.py
autogpt_platform/frontend/src/components/agptui/PublishAgentSelectInfo.tsx
autogpt_platform/frontend/src/components/agptui/composite/PublishAgentPopout.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

- added description to my agents response
- auto populate the publish agent info form
https://github.com/user-attachments/assets/68cd5d33-0f67-4875-80e9-5a7115b847e7

feat(store): Auto-populate the agent submission form

---

autogpt_platform/frontend/src/components/agent-import-form.tsx
autogpt_platform/frontend/src/lib/utils.ts

This is for [Credential ID Exports into Agent JSON #8919 ](https://github.com/Significant-Gravitas/AutoGPT/issues/8919)
I have added a new function ``removeCredentials`` into [``utils.ts``](https://github.com/Significant-Gravitas/AutoGPT/compare/dev...bently/open-2153-credential-id-exports-into-agent-json?expand=1#diff-db26a69e6fb7546dc621634f3c8ee6efa3639e72e02837f753af18b2fdddf7be) which will go through and look for any "credentials" that are in the JSON during a agent export, this will then remove them and let the user download the file.
I have also added the same function to the importing of agents for old agents that where exported that still contain the credentials, this means that old agents can be imported with out breaking/causing issues. 
When I say it looks for credentials I …

feat(frontend) Remove "credentials" from export & import of agents

---

autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/components/edit/control/SaveControl.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.ts

Now agent can be saved multiple times.
Disable agent save button when saving or running.
<details>
</details>
<details>
</details>

fix(frontend): Disable agent save button when saving or running

---

autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/routes.py
autogpt_platform/frontend/src/app/store/agent/[creator]/[slug]/page.tsx
autogpt_platform/frontend/src/app/store/creator/[creator]/page.tsx

Username was case sensitive, made username case insensitive

fix(store): Make username case insensitive

---

autogpt_platform/frontend/src/components/agptui/PublishAgentSelectInfo.tsx

Introduced when making sure initialData was inferred from the agent object. This has been fixed now

fix(store): "Publish an Agent" flow has a missing default image

---

autogpt_platform/backend/backend/server/v2/store/image_gen.py
autogpt_platform/backend/backend/server/v2/store/media.py
autogpt_platform/backend/backend/server/v2/store/routes.py
autogpt_platform/frontend/src/components/agptui/PublishAgentSelectInfo.tsx
autogpt_platform/frontend/src/components/agptui/composite/PublishAgentPopout.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts

Allow generating ai images for store submissions

feat(store): Generate AI images for store submissions

---

autogpt_platform/frontend/src/components/agptui/AgentTableRow.tsx

swaps context menu for dropdown menu
<details>
</details>
<details>
</details>

feat: swap context menu for dropdown to fix three dots doing nothing

---

autogpt_platform/frontend/next.config.mjs
autogpt_platform/frontend/src/app/layout.tsx
autogpt_platform/frontend/src/app/store/agent/[creator]/[slug]/page.tsx
autogpt_platform/frontend/src/app/store/creator/[creator]/page.tsx
autogpt_platform/frontend/src/components/agptui/AgentImageItem.tsx
autogpt_platform/frontend/src/components/agptui/AgentImages.tsx
autogpt_platform/frontend/src/components/agptui/AgentInfo.tsx
autogpt_platform/frontend/src/components/agptui/BecomeACreator.tsx
autogpt_platform/frontend/src/components/agptui/BreadCrumbs.tsx
autogpt_platform/frontend/src/components/agptui/CreatorInfoCard.tsx
autogpt_platform/frontend/src/components/agptui/Navbar.tsx
autogpt_platform/frontend/src/components/agptui/StoreCard.tsx
autogpt_platform/frontend/src/components/agptui/composite/AgentsSection.tsx
autogpt_platform/frontend/src/components/ui/icons.tsx

Add small ui changes on marketplace 
Fix
- #9035
- #9034 
- #9033
- #9031 
- #9029
- #9028
- #9027 
- #9026 
- #9025 
- #9021 
- #9020 
- #9004 
- #9003 
- #9002 
- #9001 
- #8999  
- #8998 
- #8997 
- #8996 
- #8995 
- #8994 
- #8993
- #8991   
- #8990 
- #8989

feat(store) : Small UI changes on marketplace

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/v2/library/routes.py

Do a deep copy of the store agent so the new agent is under the current users id
⚠️  Hacky fix!!

fix(store): Fixing add agent to library

---

autogpt_platform/backend/backend/server/v2/store/db.py

fix(store): username not lowered when its updated breaking access to any of there users pages in the store

fix(store): username not lowered when its updated

---

autogpt_platform/backend/backend/server/v2/library/routes_test.py
autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/routes.py
autogpt_platform/backend/migrations/20241230102007_update_store_agent_view/migration.sql
autogpt_platform/frontend/src/app/marketplace/page.tsx
autogpt_platform/frontend/src/app/store/agent/[creator]/[slug]/page.tsx
autogpt_platform/frontend/src/components/agptui/composite/AgentsSection.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/utils.ts

- Redirect to the marketplace.
- Ensure that the store agent uses agent graph data instead of store listing data.
- Don’t export agent input values.
- URL sanitization: We can’t open an agent if it has a colon in its name.
- Show all top agents.
<details>
</details>
<details>
</details>

Hotfix new year

---

autogpt_platform/frontend/src/app/login/actions.ts
autogpt_platform/frontend/src/app/login/page.tsx
autogpt_platform/frontend/src/app/reset_password/actions.ts
autogpt_platform/frontend/src/app/reset_password/page.tsx
autogpt_platform/frontend/src/app/signup/actions.ts
autogpt_platform/frontend/src/app/signup/page.tsx
autogpt_platform/frontend/src/components/auth/AuthBottomText.tsx
autogpt_platform/frontend/src/components/auth/AuthButton.tsx
autogpt_platform/frontend/src/components/auth/AuthCard.tsx
autogpt_platform/frontend/src/components/auth/AuthFeedback.tsx
autogpt_platform/frontend/src/components/auth/AuthHeader.tsx
autogpt_platform/frontend/src/components/auth/PasswordInput.tsx
autogpt_platform/frontend/src/components/auth/index.ts
autogpt_platform/frontend/src/hooks/useSupabase.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts
autogpt_platform/frontend/src/tests/pages/login.page.ts
autogpt_platform/frontend/src/types/auth.ts
autogpt_platform/frontend/yarn.lock

There are UX and design issues with current auth pages; `login`, `signup` and `reset_password` (including change password).
*Missing `s` on the login's password error is fixed.
Important changes in bold.
- **Split `/login` into `/signup`**
- UI Redesign that adheres to Figma designs
- General code cleanup and improvements
- Fix feedback: it's now shown when needed and clear (e.g. "~~String~~ Password must be...")
- All action functions use `Sentry.withServerActionInstrumentation`
- `PasswordInput` "eye button" shows password only when mouse button is hold and doesn't capture tab
- **Removed agree to terms checkbox** (it's only on signup now)
- Move provider login function to `actions.ts`
- **Requires to type password twice**
- Shows waitlist information on *any* database error
- …

refactor(frontend): Auth pages update

---

autogpt_platform/autogpt_libs/autogpt_libs/utils/synchronize.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/integrations/creds_manager.py

Exception:
```
nid:ce829f66-14b0-4bd3-b748-791e46666cb6|-] Failed node execution ce829f66-14b0-4bd3-b748-791e46666cb6: Cannot release an unlocked lock {}\u001b[0m",
Traceback (most recent call last):\n  File \"/app/autogpt_platform/backend/backend/integrations/creds_manager.py\", line 145, in _locked\n    yield\n  File \"/app/autogpt_platform/backend/backend/integrations/creds_manager.py\", line 115, in acquire\n    lock = self._acquire_lock(user_id, credentials_id)",
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
File \"/app/autogpt_platform/backend/backend/integrations/creds_manager.py\", line 139, in _acquire_lock",
return self._locks.acquire(key)",
^^^^^^^^^^^^^^^^^^^^^^^^",
File \"/app/autogpt_platform/autogpt_libs/autogpt_libs/utils/synchronize.py\", line 44, in acquire", …
```

fix(backend): Added locking status check before releasing to avoid releasing timing out lock

---

autogpt_platform/backend/backend/data/block.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/data/model.py
autogpt_platform/backend/test/data/test_graph.py

https://github.com/Significant-Gravitas/AutoGPT/issues/8739 causes input fields that are supposed to be an advanced field end up being a mandatory field:
*See the retry count field here.
Set the `advanced` field on each input field, and set the default value using this logic:
* If it has a default value, set it to True.
* otherwise, False.
<details>
</details>
<details>
</details>

fix(platform): Fields with default value are not set to advanced by default

---

autogpt_platform/backend/backend/util/request.py

Addresses: https://github.com/Significant-Gravitas/AutoGPT/security/advisories/GHSA-4c8v-hwxc-2356
Currently, no IPv6 is used by default on this system. However, the lack of block HTTP access prevention to internal systems with IPv6 could be a potential SSRF.
Prevent internal IPv6 address access on HTTP request blocks.
<details>
</details>
<details>
</details>

fix(backend): Prevent HTTP requests access to internal IPV6 addresses for Agent Blocks

---

autogpt_platform/backend/backend/blocks/github/pull_requests.py

This adds 2 blocks, a Github Create File Block (GithubCreateFileBlock) and Github Update File Block (GithubUpdateFileBlock)
These allow you to create files and update files on github, i used it to make all the files that are on my repo here https://github.com/Bentlybro/AGPT-Testing/commits/main/

feat(blocks): Add github create file block

---

autogpt_platform/backend/backend/util/request.py

Previously, `http://` would be converted to `http://http` and pass the no-hostname check that way. It eventually fails validation, but only at hostname lookup which times out -> takes very long.
- Fix URL canonicalization logic
- Merge `_canonicalize_url` into `validate_url`

fix(backend): Fix validation of hostname-less URLs

---

autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/NodeHandle.tsx
autogpt_platform/frontend/src/components/customnode.css
autogpt_platform/frontend/src/components/node-input-components.tsx

There are a few hardcoded margins and padding in the block input layout, causing the input to sometimes overflow or be used inconsistently.
* Make padding consistent between left & right, top & bottom.
* Remove hard-coded margins.
* Match the hardcode negative margin for the right node handle to the left node handle.
* Make the input box take the full width.
<details>
</details>
<details>
</details>

fix(frontend): Make input layout & padding consistent

---

autogpt_platform/backend/backend/integrations/webhooks/utils.py

Webhooks are broken
Swaps the way we fill webhooks into strings

Fix Provider name enum being used instead of value

---

autogpt_platform/backend/backend/blocks/nvidia/_auth.py
autogpt_platform/backend/backend/blocks/nvidia/deepfake.py
autogpt_platform/backend/backend/data/block.py
autogpt_platform/backend/backend/data/model.py
autogpt_platform/backend/backend/integrations/providers.py
autogpt_platform/frontend/src/components/flow.css
autogpt_platform/frontend/src/components/integrations/credentials-input.tsx
autogpt_platform/frontend/src/components/integrations/credentials-provider.tsx
autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/components/ui/render.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

Adding a block to allow users to detect deepfakes in their workflows. 
This block takes in an image as input and returns the probability of it being a deepfake as well as the bounding boxes around the image.
- Added NvidiaDeepfakeDetectBlock
- Added the ability to upload images on the frontend
- Added the ability to render base64 encoded images on the frontend
<details>
</details>
<details>
</details>

feat(blocks/nvidia): Add Nvidia deepfake detection block

---

autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/frontend/src/app/store/(user)/api_keys/page.tsx
autogpt_platform/frontend/src/app/store/(user)/layout.tsx
autogpt_platform/frontend/src/components/agptui/Sidebar.tsx
autogpt_platform/frontend/src/components/agptui/composite/APIKeySection.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

Allow users to create API keys for the AutoGPT platform. The backend is already set up, and here I’ve added the frontend for it.
1. Fix the `response-model` of the API keys endpoints.  
2. Add a new page `/store/api_keys`.  
3. Add an `APIKeySection` component to create, delete, and view all your API keys.

feat(platform) : Add api key generation frontend

---

autogpt_platform/backend/backend/blocks/http.py

This is to improve how we deal with plain text in the send web request block.
-	Plain text stays as plain text (regardless of JSON toggle)
-	Valid JSON with JSON toggle enabled sends as JSON
-	JSON-like data with JSON toggle disabled sends as form data

fix(blocks): improve handling of plain text in send web request block

---

autogpt_platform/backend/.env.example
autogpt_platform/backend/backend/integrations/credentials_store.py
autogpt_platform/backend/backend/util/settings.py

We want to provide certain providers by default on our platform. These three were not added previously, so fixing that.
If api keys for Fal Exa or E2B exist in environment variables, load them by default as credentials that are usable by our users. 
<details>
</details>
<details>
</details>

fix(backend): Add default credentials for Fal, Exa, E2B

---

autogpt_platform/frontend/src/hooks/useAgentGraph.ts

- Resolves #9253
- Update state when an error occurs on save, to re-enable the save button
- Try to save an agent with missing required fields -> should give an error
- Fill out the required fields and try saving again -> should work

fix(frontend): Unbreak save button after save error

---

autogpt_platform/backend/backend/executor/manager.py

There should be no possibly failing code between graph exec creation and the actual queueing.
It could risk the graph execution being stuck on the QUEUED status.
Moved the node exec creation and status update to be inside the graph execution logic.
<details>
</details>
<details>
</details>

feat(backend): Minimize the non caught error logic between graph exec creation and queueing

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/test/data/test_credit.py

To maintain the transaction running-balance integrity, the monthly top-up balance has to adjust the top-up amount to maintain the balance of the user to be at least X amount, instead of top-up the user balance with a fixed X amount.
* Add an additional query to sum the remaining un-snapshotted balance (if any).
* Monthly top-up transaction set the amount target_amount - current_balance instead of fixed target_amount.
<details>
</details>
<details>
</details>

fix(backend): Make monthly top-up adjust the target balance instead of top-up the target amount

---

autogpt_platform/backend/backend/blocks/linear/comment.py
autogpt_platform/backend/backend/blocks/linear/issues.py
autogpt_platform/backend/backend/blocks/linear/projects.py

Linear blocks show up even if oauth isn't configured
disables the linear blocks if oauth isn't configured

fix: check if linear is enabled before showing blocks

---

.github/workflows/repo-close-stale-issues.yml

We are making issues stale that aren’t. With the additions of more careful project management this has become a hindrance rather than help. 
- increases days until stale from 50 to 100

ci(repo): Update repo-close-stale-issues.yml

---

autogpt_platform/backend/backend/blocks/llm.py

In the AI Conversation block it uses ``AIStructuredResponseGeneratorBlock.input`` for the input but it is missing ollama_host, this means that if i try to use ollama with this block, ollama_host is not passed, this PR fixes that by simply adding ``ollama_host=input_data.ollama_host`` to the ``class AIConversationBlock(AIBlockBase):``
```diff
AIStructuredResponseGeneratorBlock.Input(
prompt="",
credentials=input_data.credentials,
model=input_data.model,
conversation_history=input_data.messages,
max_tokens=input_data.max_tokens,
expected_format={},
++  ollama_host=input_data.ollama_host,
),
```

fix(blocks): add ollama_host to AIConversationBlock

---

autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/util/service.py

Block execution that cost credit can fail, the scope of this fix is making this error as part of the node execution instead of a system error.
<details>
</details>
<details>
</details>

fix(backend): Make spend credit failure as part of block execution failure

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/server/routers/v1.py

Make set_auto_top_up accepts AutoTopUpConfig & eliminate hardcoding of json value.
<details>
</details>
<details>
</details>

fix(backend): Remove hardcoded auto-top-up config definition on set_auto_top_up

---

autogpt_platform/frontend/src/app/signup/actions.ts
autogpt_platform/frontend/src/app/signup/page.tsx

Currently if user tries to sign in with an email that is already associated with a user they are redirected to login without any feedback.
- Show feedback: "User with this email already exists" on signup when user already registered
- Beta user waitlist message is shown otherwise as previously
<details>
</details>
<details>
</details>

fix(frontend): Show feedback if user exists on sign up

---

autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

Type system complains about this entry as impossible but this code path is possible and without it some blocks are broken (e.g. `Step Through Items`)
- Restore `case "object"` in `NodeGenericInputField` 
- Update `BlockIOKVSubSchema` type, so ts type checking doesn't complain
<details>
</details>
<details>
</details>

fix(frontend): Fix typing for `dict`/`dict[Any, Any]` `SchemaField`

---

autogpt_platform/backend/backend/server/v2/store/db.py

We oops'd and didn't return the agent as a downloadable
- attaches agent object

fix(backend): fix missing agent object requirement

---

autogpt_platform/backend/backend/executor/manager.py

https://github.com/Significant-Gravitas/AutoGPT/pull/9340/files#diff-1b278ebf10a9da0fb5030010222b3a6df2b05a5463cad428cd6c38a1541b0f73R210-R219 introduced a bug where the spend_credit and update_execution is called inside the loop instead of by the end of the execution.
Untabbed the `spend_credit` and `update_execution` code outside the loop.
<details>
</details>
<details>
</details>

fix(backend): Fix doubly reported produced output

---

autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/frontend/src/app/marketplace/(user)/credits/page.tsx

Make the auto top-up wordings clearer: 
es 🏗️
<details>
</details>
<details>
</details>

feat(frontend): Fix wordings for auto top-up feature

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/executor/manager.py

Instead of letting the user to execution the block then break it post-execution.
We can charge the user first and execute it afterward.
The trade-offs:
* We can't charge a block that is charged based on the execution time.
* We will also charge failed block executions.
<details>
</details>
<details>
</details>

fix(backend): Charge user credits before its block execution

---

autogpt_platform/frontend/src/components/CustomEdge.tsx
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/NodeHandle.tsx

1. Remove isHovered / onMouseEnter / onMouseLeave state updates
2. Wrap Custom Node in React.memo
3. Avoid re-renders for context menus

platform(fix): Improve performance of builder

---

autogpt_platform/frontend/src/hooks/useAgentGraph.tsx

Array output, e.g. `Item` in Step Through Items block doesn't output correct number of beads, this PR fixes this issue.

fix(frontend): Fix beads when output is array

---

autogpt_platform/backend/.env.example
autogpt_platform/docker-compose.platform.yml
autogpt_platform/docker-compose.yml

We want to use RabbitMQ for email (and executor in the future) to ensure message delivery -- something we currently lack with Redis. This PR is adding RabbitMQ to the docker-compose and setup details with defaults so that when we start bringing services up, they have the backing to do so.
- Adds rabbitmq container (with exposed API and mgmt ports)
- Adds .env.example config for the backend
- Adds dockercompose config for the backend, and passes the variables around as needed

feat(infra): add rabbitmq to docker compose

---

autogpt_platform/README.md
docs/content/platform/getting-started.md

Added `--progress` to the submodule update, so that cloning progress can be tracked and does not appear to hang.
<details>
</details>
<details>
<summary> Provide feedback when cloning submodules </summary>
-  now updating submodules shows the cloning repo's progress
</details>

docs: Provide feedback when cloning submodules

---

autogpt_platform/backend/backend/blocks/text.py

Introduced `matched_result` & `matched_count` as a batch matched result list and its count for the block execution of ExtractTextInformationBlock.
<details>
</details>
<details>
</details>

feat(block): Add batch matched result and its count on ExtractTextInformationBlock

---

autogpt_platform/frontend/src/components/agptui/composite/PublishAgentPopout.tsx

Updates the PublishAgentAwaitingReview router.push path, it was going to ``/marketplace/dashboard`` it should be ``/profile/dashboard``
https://github.com/Significant-Gravitas/AutoGPT/blob/8181ee8cd1f71bd351a3e0ad66356a0313877db2/autogpt_platform/frontend/src/components/agptui/composite/PublishAgentPopout.tsx#L265-L267
to be
```tsx
onViewProgress={() => {
router.push("/profile/dashboard");
handleClose();
}}
```

fix(frontend) update PublishAgentAwaitingReview router push path

---

autogpt_platform/backend/backend/notifications/email.py

I made a mistake in how we check if postmark exists
- adds a more explicit setting of postmark to none and extra checking to prevent its use if it isn’t set

fix(backend): correctly check if email service is set up

---

autogpt_platform/backend/migrations/20250218135013_create_library_agents_for_existing_graphs/migration.sql
autogpt_platform/frontend/src/app/build/page.tsx
autogpt_platform/frontend/src/app/monitoring/page.tsx
autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/components/monitor/AgentFlowList.tsx
autogpt_platform/frontend/src/components/monitor/FlowInfo.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunInfo.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunsList.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunsStatus.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunsTimeline.tsx
autogpt_platform/frontend/src/components/monitor/scheduleTable.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

- Follow-up to #9258
The front end is fetching `/library/agents` -> `LibraryAgent[]` but using the result as `GraphMeta[]`. This breaks a bunch of things.
Frontend:
- Add `LibraryAgent` type for `api.listLibraryAgents()`
- Amend all broken usages of `LibraryAgent` objects
- Introduce branded typing for `LibraryAgent.id` and `GraphMeta.id` to disallow mixing them. This prevents incorrect use in the future, and reduces the chance of this frontend issue accumulating interest on existing open PRs.
Backend:
- Add a migration to create `LibraryAgent` objects for all existing `AgentGraphs`

fix(frontend): Fix return type and usage of `api.listLibraryAgents()`

---

autogpt_platform/backend/backend/notifications/notifications.py

When we fail to process something, we don't want to keep retrying forever. We should store those and process them later
- Fix the type of the failed exchange from Direct to Topic to allow filtering based on name (allows us later to do more advanced handling of queue types)
- abstract processing the messages in a queue a bit to reduce repeated code
- abstract how we check if a user wants a notification so that its a bit easier to process
- Handle errors better
- Abstract model parsing
<details>
</details>

feat(backend): move failed messages into a dead letter queue

---

autogpt_platform/backend/backend/util/settings.py

- Follow-up to #9508 
HTTP-based RPC has not been fully tested and should be disabled by default.
- Disable HTTP-based RPC and use Pyro by default

fix(backend): Use Pyro for RPC by default

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/util/service.py
autogpt_platform/backend/backend/util/settings.py

HttpResponse error introduced by RPC is buggy since we are returning the exception as is instead of the string version of it.
Also `RUNNING` status on the graph execution is missing.
* Refactored & fixed the exception return handling on RPC failure.
* Add `RUNNING` status update during the graph execution.
<details>
</details>
<details>
</details>

fix(backend): Fix exception response on RPC error & Missing Graph `Running` Status

---

autogpt_platform/backend/backend/util/service.py

Exception can contain more than message, so we propagate the whole args as long as it is serializable.
<details>
</details>
<details>
</details>

feat(backend): Propagate error arguments on RPC exceptions

---

autogpt_platform/backend/backend/util/service.py

We allow tuples to be returned from exceptions, but pydantic restricts their size to 1 b/c the typehint. This fixes that
- Adds `, ...` to the tuple type hint

fix(backend): allow more than one arg on the tuple

---

autogpt_platform/backend/backend/blocks/smart_decision_maker.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/test/executor/test_tool_use.py
autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx

Now that the MVP for Smar Decision Block is available, we need to add this info in the block output:
Messages (list) - The messages list sent to the LLM plus its generated response as the latest assistant entry. This is a single list of dictionaries in standard LLM API format).
* Add `conversations` output pin that populates the update `conversation_history` input pin with the assistant response.
* Refactored `Smart Decision Block` to avoid downloading the whole graph on each execution, remove code duplication, declutter data fetching.
* Minor UI issue on the smart decision block entry in the search bar. 
<details>
</details>
<details>
- Adding new services that need to communicate …

feat(backend): Add conversation history as Smart Decision Block output

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/blocks/smart_decision_maker.py

Instead of parsing an LlmMessage by ourselves, we use raw content from the LLM as conversation history and accept any format it introduces.
Example output:
```
[
{
"role": "system",
"content": "Thinking carefully step by step decide which function to call. Always choose a function call from the list of function signatures. The test graph is basically an all knowing answer machine you can use it to get an answer"
},
{
"role": "user",
"content": "Hey how's the weather today"
},
{
"role": "assistant",
"audio": null,
"content": null,
"refusal": null,
"tool_calls": [
{
"id": "call_Z7CKKIkldylmfWJdE6ZnDxjr",
"type": "function",
"function": {
"name": "storevalueblock",
"arguments": "{\"input\":\"I don't have context for your location. Could you provide one?\"}"
}
}
],
"function_call": null
}
] …
```

fix(backend): Use raw content from the LLM as conversation history

---

autogpt_platform/backend/backend/blocks/agent.py
autogpt_platform/backend/backend/blocks/smart_decision_maker.py
autogpt_platform/backend/backend/data/block.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/executor/manager.py

**Proposal / Request For Comments** 
The tool calling provided by the LLM provider requires an output generated by the tool to be looped back as part of the conversation history. The scope of this PR is trying to address the need to fulfill the feature expectation.
* `Last Tool Output` is introduced to loop back the output of the tool back to Smart Decision Block.
* Smart Decision Block execution will be pending unless the `Last Tool Output` us provided where a pending tool call is present in the conversation history.
* **Known hack**: The last tool output will prefill all the pending tool calls from the conversation history.
* A few tweaks were required to allow a blocking loop to be executed without awaiting on all the inbound links.
<details> …

feat(backend): Add tool execution response on Smart Decision Block

---

autogpt_platform/backend/backend/server/v2/library/db.py
autogpt_platform/backend/backend/server/v2/library/db_test.py
autogpt_platform/backend/backend/server/v2/library/model.py
autogpt_platform/backend/backend/server/v2/library/routes/agents.py
autogpt_platform/frontend/src/app/library/agents/[id]/page.tsx
autogpt_platform/frontend/src/components/agents/agent-delete-confirm-dialog.tsx
autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/agents/agent-run-draft-view.tsx
autogpt_platform/frontend/src/components/agents/agent-runs-selector-list.tsx
autogpt_platform/frontend/src/components/agents/agent-schedule-details-view.tsx
autogpt_platform/frontend/src/components/agptui/types.ts
autogpt_platform/frontend/src/components/library/library-agent-card.tsx
autogpt_platform/frontend/src/components/monitor/FlowInfo.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts

- Resolves #9545
- fix(platform): Make "Delete" button on `/monitoring` soft-delete the `LibraryAgent` instead of hard-deleting the corresponding `AgentGraph`
- feat(frontend): Add "Delete agent" button on `/library/agents/[id]`
Technical:
- fix(backend): Accept partial input on `update_library_agent` endpoint
- feat(backend): Add `GET /api/library/agents/{library_agent_id}` endpoint
- refactor(frontend): Replace use of `GraphMeta` by `LibraryAgent` where possible on `/library/agents/[id]`
Also, out of scope but important:
- fix(frontend): Hide buttons that require direct graph access depending on `agent.can_access_graph`
- Go to the Library and select an agent
- Save this URL for later (especially the ID)!
- Click "Delete agent" on `/library/agents/[id]`
- Click "Delete" to confirm
- …

feat(platform): Library Agent "Delete" functionality

---

autogpt_platform/frontend/src/app/error.tsx
autogpt_platform/frontend/src/app/globals.css
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/PrimaryActionButton.tsx
autogpt_platform/frontend/src/components/TallyPopup.tsx
autogpt_platform/frontend/src/components/agptui/BecomeACreator.tsx
autogpt_platform/frontend/src/components/agptui/ProfileInfoForm.tsx
autogpt_platform/frontend/src/components/auth/AuthButton.tsx
autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx
autogpt_platform/frontend/src/components/edit/control/ControlPanel.tsx
autogpt_platform/frontend/src/components/edit/control/SaveControl.tsx
autogpt_platform/frontend/src/components/profile/settings/SettingsForm.tsx
autogpt_platform/frontend/src/components/ui/button.stories.tsx
autogpt_platform/frontend/src/components/ui/button.tsx

Our application currently uses multiple inconsistent button implementations across the codebase. 
This PR standardizes buttons to use our base Button component that leverages ShadcN, improving UI consistency, maintainability, and accessibility.
Resolves: #9567 
- Replaced custom button implementations in various components with our base Button component and greatly reduced redundant overlapping styles. 
- Paired with our designer to streamline our `globals.css` to match the desired approach.  
- Added button variant documentation in Storybook
- Deprecated the obsolete 'primary' class  and marked it.
<details>
<summary>Button Consolidation Test Plan</summary>
Visual Verification
Functional Testing
Responsive Testing
</details>

fix(frontend): Consolidate Application Buttons to ShadcN Base Button Component

---

autogpt_platform/frontend/src/app/library/page.tsx

This PR fixes the layout of the Library page. It properly anchors the 'old experience' message to the bottom of the viewport and improves the overall page structure using semantic HTML and Tailwind best practices.
Resolves: #9524 
- Restructured the LibraryPage component to use proper semantic HTML with a `<main>` element
- Added a fixed Alert component at the bottom of the viewport with 8px margin
- Used ShadcN Alert component for the 'old experience' message for UI consistency
- Implemented responsive behavior to hide the alert on mobile screens
- Optimized Tailwind classes by using the `container` utility and removing redundant styles
- Improved accessibility and UX by using appropriate semantic elements
<details>
<summary>Alert Message at Bottom of Library Page</summary>
</details>

fix(library): Anchor message to bottom of page 

---

autogpt_platform/backend/backend/util/service.py

Increase the logging threshold to WARNING to avoid chatty RPC service request logs.
Before:

fix(backend): Increase logging level threshold of RPC service to WARNING

---

autogpt_platform/backend/backend/blocks/github/checks.py
autogpt_platform/backend/backend/blocks/github/statuses.py

Trying to run the GitHub Status blocks results in a serialization error
- Serializes the checks and blocks data objects correctly

fix(backend): serialize the pydantic objects correctly for github checks and statuses

---

autogpt_platform/backend/backend/data/includes.py
autogpt_platform/backend/backend/server/v2/library/db.py
autogpt_platform/frontend/src/components/agptui/AgentInfo.tsx

- Fixes #9577
- Add the required include statements to `LibraryAgent` queries
- Make a `library_agent_include(user_id)` utility in `backend.data.includes`
- Go to an agent in the Marketplace; click "Add To Library"

fix(backend): Unbreak `add_marketplace_agent_to_library`

---

autogpt_platform/backend/backend/blocks/exa/contents.py

The Exa Block has a missing error pin which prevents error handling, this adds that.

fix(block): Add missing error pin to Exa Contents Block

---

autogpt_platform/backend/backend/blocks/basic.py

Creating a self-loop of the AddToListBlock requires a boilerplate of adding a dummy block to trigger its execution.
If the only inbound link on an input pin comes from the same block, we don't wait for that pin on the first execution (as it's never going to come).
<details>
</details>
<details>
</details>

feat(block): Allow undefined self-loop link to `list` input pin on `AddToListBlock`

---

autogpt_platform/backend/backend/server/v2/library/db.py
autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/image_gen.py
autogpt_platform/backend/backend/server/v2/store/model.py
autogpt_platform/frontend/src/components/agptui/PublishAgentSelect.tsx
autogpt_platform/frontend/src/components/agptui/composite/PublishAgentPopout.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

We've been auto-generating the thumbnail image for the agent in the library, this PR is propagating that image as an initial image for the store listing. This PR also removes the fetch all query for getting the count for paginating library agent.

fix(platform): Make LibraryAgent image as initial StoreListing image

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/rest_api.py
autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/backend/backend/server/v2/library/db_test.py
autogpt_platform/backend/backend/server/v2/library/model_test.py
autogpt_platform/backend/backend/server/v2/library/routes_test.py
autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/db_test.py
autogpt_platform/backend/backend/server/v2/store/routes.py
autogpt_platform/backend/migrations/20250316095525_remove_graph_template/migration.sql
autogpt_platform/backend/schema.prisma
autogpt_platform/backend/test/data/test_graph.py
autogpt_platform/backend/test/test_data_creator.py
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts

Agents using Agent blocks should be seamlessly downloaded from the marketplace to a file and imported from a file.
Requirements:
* A recursive export process that exports all the required agents to a single file, no matter how many layers deep (taking care of potential loops).
* An import process that expects and extracts several agents from a single file into your library at once.
Considerations:
We need to ensure the reference IDs in the Agent Blocks match/are updated to match the imported sub-agent ids to prevent broken references.
* Add sub_graphs field on Graph model 
* Improve graph creation query to support inserting graph + subgraphs in batch
* Deprecate graph template & remove its column
* Update on marketplace download agent (unified the used method, with more secure cleanup & …

feat(backend): Support sub-agent on export/import agent feature

---

autogpt_platform/db/docker/docker-compose.yml
autogpt_platform/docker-compose.yml

The change in https://github.com/Significant-Gravitas/AutoGPT/pull/9620 introduces a breaking change in the database volume content; however, the database's volume location does not change, making switching between two versions clash.
Renamed db-config named volume to supabase-config.

fix(platform): Fix possible db-config permission denied when running two different Supabase versions

---

autogpt_platform/frontend/src/components/agents/agent-run-draft-view.tsx
autogpt_platform/frontend/src/components/agptui/Button.tsx

- Resolves #9622
- Add pop-out button + modal to input fields in Agent Run Draft view on `/library/agents/[id]`
- Fix `icon`-variant button styling
- Go to an agent's page -> click "+ New run"
- Enter a value in one of the inputs; click the pop-out button on that input
- Edit the value & click "Save"

feat(frontend/library): Make agent input fields expandable

---

autogpt_platform/frontend/src/components/library/library-agent-card.tsx
autogpt_platform/frontend/src/components/library/library-agent-list.tsx

- Resolves #9631
- Truncate library agent card title (2 lines) and description (3 lines)
- Make "See runs" and "Open in builder" stick to bottom of card regardless of other content
- Reduce number of grid columns (4 -> 3) in `lg` layout on `/library` to give items more horizontal space

fix(frontend/library): Truncate agent card title and description

---

autogpt_platform/backend/backend/exec.py
autogpt_platform/docker-compose.platform.yml

DB Manager uses DB connections, and multiple instances of it hog the very limited Database connection quota. We need this service to be a unified place to control the limited db connection.
Connect all the database manager usage in a single place, currently running on the rest service.
<details>
</details>
<details>
</details>

feat(platform): Use a single DB manager across the system

---

autogpt_platform/frontend/src/hooks/useAgentGraph.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts

The current execution update is unreliable, once you lose WebSocket connection, you will receive no updates.
Fix web socket re-connection logic.

fix(frontend): Fix unreliable websocket connection for node execution update

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/manager.py

Having the starting nodes of the execution marked as incomplete misled the users.
Mark the starting nodes during the executions as QUEUED instead of INCOMPLETE.

feat(backend): Mark starting nodes as QUEUED instead of INCOMPLETE during the initial execution

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/data/includes.py
autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/server/routers/v1.py

A graph that processes tens of thousands of nodes will cripple the system since the API tries to load all of them and dump them into the browser. The scope of this change is to avoid such an issue by only returning the last 1000 node executions.
* Return only 1000 node executions from `AgentNodeExecutions` reference.
* Unify the include clause for fetching `AgentNodeExecutions` in one place and its format.
* Fix & optimize `cancel_execution` logic to always set both the graph & node execution status in batch.

feat(backend): Avoid loading all node executions on large continuos agent

---

autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/hooks/useCredentials.ts

Defaults need to be handled as special cases every time there's no `hardcodedValues` in node data. This causes multiple issues such as `useCredentials` not taking into account default model and requiring user to manually switch model back and forth.
- Set default values from `inputSchema` to `hardcodedValues` when new node is placed.

fix(frontend): Fill defaults from schema to `hardcodedValues` at node creation

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/data/model.py
autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/executor/utils.py
autogpt_platform/backend/backend/util/settings.py
autogpt_platform/backend/test/data/test_credit.py

Blocks that are not defined in the block cost are pretty much free. The lack of cost control makes it hard to control its quota. The scope of this change is providing a way to charge any executions based on the number of block being executed in real-time.
* Add execution charge logic based on the number of blocks executed, controlled by these two configurations:
* `execution_cost_count_threshold`: We will charge the execution based on the multiple of this number.
* `execution_cost_per_threshold`: The amount we are charging on its threshold multiple.  
* Make charging logic on the graph execution logic (as opposed to node level) so it's being done serially and insufficient fund error is guaranteed to stop the graph execution.
* Moved cost calculation logic into backend/executor/util.py

feat(backend): Add capability to charge based on block execution count

---

autogpt_platform/backend/backend/blocks/io.py
autogpt_platform/backend/backend/util/settings.py

Agent Input Block subtypes do not have a proper input UI yet on the library & run input page.
Provide a toggle to enable these blocks and set it to False by default.
<details>
</details>
<details>
</details>

fix(blocks): Disable and provide toggle for Agent Input Block subtypes

---

autogpt_platform/backend/backend/util/request.py
autogpt_platform/backend/test/util/test_request.py

The current block web requests utility has a logic to avoid the system firing into blocklisted IPs.
However, the current logic is still prone to a few security issues:
* DNS rebinding attack: due to the lack of guarantee on the used IP not being changed during the IP checking and firing step.
* Open redirect: due to the request sensitive request headers are still being propagated throughout the web redirect.
* Uses IP pinning to request the web.
* Strip `Authorization`, `Proxy-Authorization`,  `Cookie` upon web redirects.

fix(backend): Increase block request security; Prevent DNS rebinding & open redirect attack

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/manager.py

When we are cancelling a running graph execution, it's possible that the graph is already terminated.
We need to allow this process to proceed and update the rest of its node execution to terminate.
Instead of erroring out the graph execution status update, we proceed on updating the node execution status.

fix(backend): Skip updating status of already terminated graph

---

autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/routes.py

This PR publicly exposes all the agents listed in the store to the internet.
Remove the auth requirement for an agent to download the agent.

feat(backend): Make agent store data to be publicly accessible by non authenticated user

---

autogpt_platform/backend/.env.example
autogpt_platform/backend/docker-compose.test.yaml
autogpt_platform/backend/linter.py
autogpt_platform/backend/pyproject.toml
autogpt_platform/backend/run_tests.py

This pull request includes several changes to improve the backend functionality and configuration of the `autogpt_platform`. The most important changes involve adding a RabbitMQ service for testing, enhancing logging configuration, updating the linter script to handle errors gracefully, and modifying test configurations.
Backend configuration improvements:
* [`autogpt_platform/backend/docker-compose.test.yaml`](diffhunk://#diff-f6a211ff1c6d96d19adb5641ee287258a6af8d72a99e33dafb4a334094205a43R29-R43): Added RabbitMQ service configuration for testing, including health checks and environment variables.
* [`autogpt_platform/backend/.env.example`](diffhunk://#diff-62020caf1b9a15e0e3b9b3b1b69d5f6464bf7643f62354cbbaabf755d57b6064R191-R192): Added a section delimiter for optional API keys for use …

fix(platform): Fixs to allow formatting and tests to work from sub command

---

autogpt_platform/frontend/src/app/library/page.tsx

- fix #9705 
Adding extra padding so the banner doesn’t cut below the cards.

fix(frontend): Add extra padding bottom on library agent page

---

autogpt_platform/frontend/src/components/ui/carousel.tsx

- fix #8958 
Currently, the arrow button and carousel have a 16px margin, and the button is placed 12px below the top of the container. This makes the spacing appear to be 28px. Therefore, place the button and indicator at the top of the container.

fix(marketplace): Fix margin between arrows and carousel

---

autogpt_platform/frontend/src/app/marketplace/creator/[creator]/page.tsx

- fix #9000 
Currently, we have a 32px bottom padding on the Creator’s page on larger screen. I have added an extra 58px to make it 90px.

fix(marketplace): Add 58px bottom padding to creator page agents section on large screens

---

autogpt_platform/frontend/src/components/agent-import-form.tsx
autogpt_platform/frontend/src/components/library/library-upload-agent-dialog.tsx
autogpt_platform/frontend/src/components/monitor/FlowInfo.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/utils.ts
autogpt_platform/frontend/src/lib/utils.ts

- Resolves #9716
- Builds on the work done in #9627
- Remove `safeCopyGraph`; export directly from backend instead
- Explicitly name sanitization functions for *importing* graphs; move to `@/lib/autogpt-server-api/utils`
- Amend `BackendAPI.getGraph(..)` to delete `.user_id` if `for_export == true`
Out-of-scope improvements:
- Add missing `user_id` to frontend `Graph` types
- Add `UserID` branded type for `User.id` + all `user_id` properties
- Create and configure an agent with the Publish To Medium block, a block that uses credentials, and a webhook trigger
- Go to `/monitoring` and click the agent you just created

refactor(frontend): Clean up graph import & export logic

---

README.md
docs/content/platform/getting-started.md

This is to remove the out dated tutorial video from docs & readme and add a direct link to the docs in the readme
Remove video link from readme.md
Remove video link from https://github.com/Significant-Gravitas/AutoGPT/blob/dev/docs/content/platform/getting-started.md
Add direct link to docs in readme.me

update(docs): Remove out dated tutorial video from docs & readme

---

autogpt_platform/frontend/src/app/library/agents/[id]/page.tsx
autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/agents/agent-run-draft-view.tsx
autogpt_platform/frontend/src/components/agents/agent-schedule-details-view.tsx
autogpt_platform/frontend/src/components/agptui/action-button-group.tsx
autogpt_platform/frontend/src/components/agptui/types.ts

- Resolves #9730
- feat: Add "Open in builder" run action
- refactor: Add `ActionButtonGroup` to replace boilerplate code in `AgentRunDetailsView`, `AgentRunDraftView`, `AgentScheduleDetailsView`
- feat: Add link support to `ActionButtonGroup`, `ButtonAction`
- Go to `/library/agents/[id]`

feat(frontend/library): Add "Open in builder" run action

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/data/block_cost_config.py

This PR is to add the new [Meta: Llama 4 Maverick](https://openrouter.ai/meta-llama/llama-4-maverick) and [Meta: Llama 4 Scout](https://openrouter.ai/meta-llama/llama-4-scout) models via [OpenRouter](https://openrouter.ai/)
Added the model names to ``llm.py``
```
META_LLAMA_4_SCOUT = "meta-llama/llama-4-scout"
META_LLAMA_4_MAVERICK = "meta-llama/llama-4-maverick"
```
and the modela metadata
```
LlmModel.META_LLAMA_4_SCOUT: ModelMetadata("open_router", 131072, 131072),
LlmModel.META_LLAMA_4_MAVERICK: ModelMetadata("open_router", 1048576, 1000000),
```
and i have added the model price to ``block_cost_config.py``
```
LlmModel.META_LLAMA_4_SCOUT: 1,
LlmModel.META_LLAMA_4_MAVERICK: 1,
```

feat(backend): Add new llama 4 maverick & scout models

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/data/includes.py
autogpt_platform/backend/backend/data/onboarding.py
autogpt_platform/backend/backend/data/user.py
autogpt_platform/backend/backend/server/v2/library/db.py
autogpt_platform/backend/backend/server/v2/library/db_test.py
autogpt_platform/backend/backend/server/v2/library/model.py
autogpt_platform/backend/backend/server/v2/library/model_test.py
autogpt_platform/backend/backend/server/v2/library/routes_test.py
autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/db_test.py
autogpt_platform/backend/backend/util/type.py
autogpt_platform/backend/migrations/20250227140210_fix_library_presets_relations/migration.sql
autogpt_platform/backend/migrations/20250407181043_refactor_store_relations/migration.sql
autogpt_platform/backend/schema.prisma
autogpt_platform/backend/test/executor/test_manager.py
autogpt_platform/frontend/src/app/library/agents/[id]/page.tsx
autogpt_platform/frontend/src/app/monitoring/page.tsx
autogpt_platform/frontend/src/components/agents/agent-runs-selector-list.tsx
autogpt_platform/frontend/src/components/library/library-agent-card.tsx
autogpt_platform/frontend/src/components/monitor/AgentFlowList.tsx
autogpt_platform/frontend/src/components/monitor/FlowInfo.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunInfo.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunsList.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunsTimeline.tsx
autogpt_platform/frontend/src/components/monitor/scheduleTable.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

Distilled from #9541 to reduce the scope of that PR.
- Part of #9307
- ❗ Blocks #9786
- ❗ Blocks #9541
- Fix `LibraryAgent` schema (for #9786)
- Fix relationships between `LibraryAgent`, `AgentGraph`, and `AgentPreset`
- Add uniqueness constraint on `LibraryAgent`
- Rename things that are called `agent` that actually refer to a `graph`/`agentGraph`
- Fix singular/plural forms in DB schema
- Simplify reference names of closely related objects (e.g. `AgentGraph.AgentGraphExecutions` -> `AgentGraph.Executions`)
- Eliminate use of `# type: ignore` in DB statements
- Add `typed` and `typed_cast` utilities to `backend.util.type`

refactor(backend): Clean up Library & Store DB schema

---

autogpt_platform/frontend/src/app/marketplace/agent/[creator]/[slug]/page.tsx
autogpt_platform/frontend/src/app/marketplace/page.tsx
autogpt_platform/frontend/src/components/agptui/BecomeACreator.tsx
autogpt_platform/frontend/src/components/agptui/CreatorInfoCard.tsx
autogpt_platform/frontend/src/components/agptui/composite/AgentsSection.tsx
autogpt_platform/frontend/src/components/agptui/composite/FeaturedCreators.tsx
autogpt_platform/frontend/src/components/agptui/composite/FeaturedSection.tsx
autogpt_platform/frontend/src/components/ui/avatar.tsx

- fix #9003 
- fix - #8969 
- fix #8970 
Adding correct margins in between headers, divider and content.
- Remove any vertical padding or margin from the section.
- Add top and bottom margins to the separator, so the spacing between sections is handled only by the separator.
- Also, add a size prop in AvatarFallback because its size is currently broken. It’s not able to extract the size properly from the className.

fix(marketplace): Fixing margins between headers, divider and content

---

autogpt_platform/frontend/src/components/agptui/AgentInfo.tsx

- fix #9177 
Add `whitespace-pre-line` tailwind property to allow newline rendering in marketplace description text

fix(marketplace): Render newline in marketplace description text

---

autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/agents/agent-schedule-details-view.tsx

Fix this broken behaviors:
Input data mix-up caused by running two different executions of the same agent with the same input.

fix(frontend): Fix Input value mixup on Library page 

---

autogpt_platform/autogpt_libs/autogpt_libs/utils/cache.py
autogpt_platform/backend/backend/server/routers/v1.py

The recent change to the execution cancelation fix turns out to only work on the first request.
This PR change fixes it by reworking how the thread_cached work on async functions.

fix(backend): Fix cancel_execution can only work once

---

autogpt_platform/frontend/src/components/node-input-components.tsx

- Resolves #9823 
The key-value pairs input, like those used in CreateDictionaryBlock, are assumed to be either a numeric or a string type.
When it has `any` type, it was randomly assumed to be a numeric type. 
Only convert to number when it's explicitly defined to do so on key-value pair input.

fix(frontend/builder): Fix key-value pair input for any non-string types

---

autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/util/settings.py

We have seen instances where the executor gets stuck in a failing message-consuming loop due to the upstream RabbitMQ being down. The current message-consuming pattern is not optimal for handling this.
* Add a retry limit to the execution loop limit.
* Use `basic_consume` instead of `basic_get` for handling message consumption.

fix(backend): Fix execution manager message consuming pattern

---

autogpt_platform/backend/backend/executor/manager.py

This change simply changes the logging level of node inputs and outputs to debug level. This change is needed because currently logging all node data causes logs that are too large for the logger to prevent nodes from running.
<details>
</details>
<details>
</details>

fix(logging): Change node data logging to debug level from info

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/blocks/smart_decision_maker.py

SmartDecisionBlock sometimes tried to be smart by calling multiple tool calls and our platform does not support this yet.
Disable parallel tool calls for OpenAI & OpenRouter LLM provider LLM blocks.

fix(block): Disable LLM blocks parallel tool calls

---

autogpt_platform/frontend/src/app/library/agents/[id]/page.tsx

If the websocket doesn't disconnect when the user switches to viewing a different agent, they aren't unsubscribed. If execution updates *from a different agent* are adopted into the page state, that can cause crashes.
- Filter incoming execution updates by `graph_id`
- Go to an agent and initiate a run that will take a while (long enough to navigate to a different agent)
- Navigate: Library -> [another agent]

fix(frontend/library): Prevent execution updates mixing between library agents

---

autogpt_platform/backend/migrations/20250416140000_make_arrays_not_null/migration.sql

Array fields in `schema.prisma` are non-nullable, but generated migrations don’t add `NOT NULL` constraints. This causes existing rows to get `NULL` values when new array columns are added, breaking schema expectations and leading to bugs.
- Backfill all `NULL` rows on non-nullable array columns to empty arrays
- Set `NOT NULL` constraint on all array columns

fix(backend): Fix array types in database

---

autogpt_platform/frontend/src/components/onboarding/WalletTaskGroups.tsx

This redesigns how the task group is displayed when finished for both expanded and folded state.
- Folded state now displays `Done` badge and hides tasks
- Expanded state shows only task names and hides details and video
Screenshot:
1. Expanded unfinished group
2. Expanded finished group
3. Folded finished group

feat(frontend): Update completed task group design in Wallet

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/rest_api.py

https://github.com/Significant-Gravitas/AutoGPT/pull/9452 was throwing `operator does not exist: text ? unknown` on deployed dev and so the function call was commented as a hotfix.
This PR fixes and re-enables the llm model migration function.
- Uncomment and fix `migrate_llm_models` function

fix((backend): Fix migrate llm models in existing agents

---

autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx

Replacing credits with cents (100 credits = 1$).
I haven’t touched anything internally, just changed the UI.
Everything is working great.
On the frontend, there’s no other place where we use credits instead of dollars.

fix(library/run): Replace credits to cents

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/data/block_cost_config.py

This PR adds the following models:
OpenAI's O3: https://platform.openai.com/docs/models/o3
OpenAI's GPT 4.1: https://platform.openai.com/docs/models/gpt-4.1
Anthropics Claude 3.7: https://www.anthropic.com/news/claude-3-7-sonnet
Googles gemini 2.5 pro: https://openrouter.ai/google/gemini-2.5-pro-preview-03-25

feat(backend): Adds latest llm models

---

autogpt_platform/backend/backend/integrations/credentials_store.py

Setting the Google Maps API through the API has never worked on the platform.
Set the default api key from the environment variable.

fix(platform): Fix Google Maps API Key setting through env

---

autogpt_platform/frontend/src/app/(platform)/profile/(user)/integrations/page.tsx

Hide Google Maps system id key on the frontend UI.

fix(frontend): Hide Google Maps Key ID filter

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/util/retry.py

Executor process initialization can fail and cause this error:
```
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
```
Add retry to reduce the chance of the initialization error to happen.

feat(backend): Add retry on executor process initialization

---

autogpt_platform/backend/backend/util/process.py

Set process starting mode to forkserver instead of spawn, if possible, for performance benefits.

feat(backend): Use forkserver on process creation if possible

---

autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/page.tsx
autogpt_platform/frontend/src/components/agptui/action-button-group.tsx
autogpt_platform/frontend/src/components/agptui/types.ts

Update "Edit a copy" modal text when copying marketplace agent in Library. Update agent action buttons to reflect the design accurately.
- Update modal text
- Disable copying owned agents (only marketplace allowed)
- `Open in Builder` -> `Customize agent`
- Disabled `Customize agent` instead of hiding
- Change `Delete agent` to non-destructive design

feat(frontend): Update "Edit a copy" modal and buttons

---

autogpt_platform/autogpt_libs/autogpt_libs/utils/synchronize.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/integrations/creds_manager.py

There are instances of node executions that were failed and end up stuck in the RUNNING status due to the execution failed to release the lock:
```
2025-04-24 20:53:31,573 INFO  [ExecutionManager|uid:25eba2d1-e9c1-44bc-88c7-43e0f4fbad5a|gid:01f8c315-c163-4dd1-a8a0-d396477c5a9f|nid:f8bf84ae-b1f0-4434-8f04-80f43852bc30]|geid:2e1b35c6-0d2f-4e97-adea-f6fe0d9965d0|neid:590b29ea-63ee-4e24-a429-de5a3e191e72|-] Failed node execution 590b29ea-63ee-4e24-a429-de5a3e191e72: Cannot release a lock that's no longer owned
```
Check the ownership of the lock before releasing.

fix(backend): Avoid releasing lock that is no longer owned by the current thread

---

autogpt_platform/backend/backend/data/credit.py

The transaction with zero payment amount will not generate a payment ID, so the checkout failed for this scenario.
Don't use payment id as transaction key on top-up with zero payment amount.

fix(backend):  Fix top-up with zero transaction flow

---

autogpt_platform/frontend/src/components/node-input-components.tsx

- fix #9882 
we’re currently using optional multi select, and it’s working great. We’re able to correctly determine the data type for it. However, there’s a small issue. We’re not using the correct subSchema that is inside anyOf on the multi select input. This is why we’re getting the problem on the Twitter block. It’s the only one that’s using this type of input, so it’s the only one that’s affected.

fix(frontend): Add support to optional multiselect

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/v2/admin/store_admin_routes.py
autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/frontend/src/app/(platform)/admin/marketplace/actions.ts
autogpt_platform/frontend/src/components/admin/marketplace/download-agent-button.tsx
autogpt_platform/frontend/src/components/admin/marketplace/expandable-row.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts

for admins to approve agents for the marketplace, we need to be able to run them. this is a quick workaround for downloading them so you can put them in your marketplace to check
- clones various endpoints related to downloading into an admin side with logging, and admin checks
- adds download button and removes open in builder action

feat: allow admins to download agents for review

---

autogpt_platform/frontend/src/app/(platform)/marketplace/agent/[creator]/[slug]/page.tsx

we oopsed and used the wrong attribute for short desc
Uses sub heading instead now

fix: use subheading for agent info not description

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/util/settings.py

When an executor dies, an ongoing execution will not be retried and will just stuck in the running status.
This change avoids such a scenario by allowing an execution of an entry that is not in QUEUED status with the low-probability risk of double execution.
* Allow non-QUEUED status to be re-executed.
* Improve cleanup of node & graph executor.
* Make a cancellation request consumption a separate thread to avoid being blocked by other messages.
* Remove unused retry loop on the execution manager.

feat(backend): Improve cancel execution reliability

---

autogpt_platform/backend/backend/server/v2/library/model_test.py

```
FAILED test/model_test.py::test_agent_preset_from_db - pydantic_core._pydantic_core.ValidationError: 1 validation error for AgentNodeExecutionInputOutput
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for AgentNodeExecutionInputOutput
E       data
E         JSON input should be string, bytes or bytearray [type=json_type, input_value=Json, input_type=Json]
E           For further information visit https://errors.pydantic.dev/2.11/v/json_type
```
Manually creating a Prisma model often breaks, and we have such an instance in the test.
This PR fixes the test to make the new Pydantic happy.

fix(backend): Failing test on a new Pydantic version

---

autogpt_platform/frontend/src/components/admin/spending/add-money-button.tsx

Fixes the admin add dollars, in the ``add-money-button.tsx`` file, in the handleApproveSubmit action it was trying to use formatCredits for the value which is wrong, this fix changes it
```diff
<form action={handleApproveSubmit}>
<input type="hidden" name="id" value={userId} />
<input
type="hidden"
name="amount"
-    value={formatCredits(Number(dollarAmount))}
+    value={Math.round(parseFloat(dollarAmount) * 100)}
/>
```
i was able to add $1, $0.10 and $0.01

feat(frontend): fix admin add dollars

---

autogpt_platform/backend/backend/app.py
autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/server/external/routes/v1.py
autogpt_platform/backend/backend/server/routers/v1.py

Currently, the agent/graph execution engine is consuming the execution queue and acknowledges the message after fully completing its execution or failing it. 
However, in the case of the agent executor failing due to a hardware/resource issue, or the executor did not manage to acknowledge the execution message. Another agent executor will pick it up and start the execution again from the beginning. 
The scope of this PR is to make the next executor pick up the next work to continue the pre-existing execution instead of starting it all over from the beginning. 
* Removed `start_node_execs` from `GraphExecutionEntry`
* Populate the starting graph node from the DB query instead (fetching Running & Queued node executions).
* Removed `get_incomplete_node_executions` from DB manager.
* Use …

feat(backend): Continue instead of retrying aborted/broken agent execution

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/backend/executor/scheduler.py
autogpt_platform/backend/backend/notifications/notifications.py
autogpt_platform/backend/backend/util/metrics.py
autogpt_platform/backend/backend/util/settings.py
autogpt_platform/backend/backend/util/test.py
autogpt_platform/backend/migrations/20250507025350_execution_created_at_index/migration.sql
autogpt_platform/backend/schema.prisma

Introduce a late execution check scheduled job. The late threshold duration is configurable.
This initial version only reports the error to Sentry.
* Added late execution check scheduled job
* Move the registration weekly notification processing job out of API call and calling it directly from the scheduler service.

feat(backend): Introduce late execution check scheduled job

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

If a node has a multi-credentials input (e.g. AI Text Generator block) but the discriminator value (e.g. model choice) is missing, the input can't be discriminated into a single-provider input. Discrimination into a single-provider input is necessary to make a graph-level credentials input for use in the Library.
- feat(backend): Require discriminator fields to always have a value
- dx(frontend): Improve typing of discriminator stuff
- dx(frontend): Fix typing in `NodeOneOfDiscriminatorField` component
- Note: We don't have any blocks with a discriminator that doesn't have a default value, so currently I don't think it's possible to produce a case where this mechanism would be triggered.

feat(backend): Require discriminator value on graph save

---

autogpt_platform/backend/backend/executor/scheduler.py
autogpt_platform/backend/backend/server/routers/v1.py

- Resolves #9918
- Follow-up fix for #9914
- In `get_graph_execution_schedules`, skip jobs when their kwargs can't be parsed as `GraphExecutionJobArgs`
- Rename methods of `Scheduler` to clarify their scope (scheduled *graph* executions)
- Go to `/library/agents/[id]` (which calls `GET /api/schedules`)

fix(backend/scheduler): Unbreak `Scheduler.get_execution_schedules`

---

autogpt_platform/frontend/src/app/(platform)/marketplace/agent/[creator]/[slug]/page.tsx

Listing page throws exception on deployment because of supabase auth issue.
Catch the exception when getting library agent. This reverts the behavior of listing page and it'll always show "Add to Library" when user is logged in.

fix(frontend): Catch exception on agent listing page

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

This is a follow-up to https://github.com/Significant-Gravitas/AutoGPT/pull/9903
The continued graph execution restarted all the execution stats from zero, making the execution stats misleading.
Continue the execution stats when continuing the graph execution.

fix(backend): Continue stats accounting on aborted or broken executions

---

autogpt_platform/backend/backend/blocks/__init__.py

```
2025-05-09 11:54:15,171 ERROR  Error executing graph 954e6fc8-9c90-46fa-be5b-4063eb519ec7: Block ID AIMusicGeneratorBlock error: 44f6c8ad-d75c-4ae1-8209-aad1c0326928 is already in use
```
This PR avoids the use of global variables messing up with the way `load_all_blocks` is cached.

fix(blocks): Fix load_all_blocks in concurrent calls

---

autogpt_platform/backend/migrations/20250512104735_rename_agent_executor_node_input/migration.sql

- Follow-up fix for #9862
- Rename the stored `data` input field to `inputs` on all Agent Executor nodes in the DB

fix(backend): Unbreak existing Agent Executor nodes

---

autogpt_platform/backend/backend/server/v2/store/db.py

This pull request includes a small change to the `get_my_agents` function in `autogpt_platform/backend/backend/server/v2/store/db.py`. The change updates the sorting order for retrieving library agents to use the `updatedAt` field instead of `agentGraphVersion`.
This aligns with the later sorting that is applied to the fetched page in the frontend.
<details>
</details>
<details>
</details>

fix(backend): Change library agents fetch sort from version to updatedAt

---

autogpt_platform/frontend/src/app/(platform)/login/page.tsx
autogpt_platform/frontend/src/app/(platform)/reset_password/page.tsx
autogpt_platform/frontend/src/app/(platform)/signup/page.tsx
autogpt_platform/frontend/src/components/auth/AuthFeedback.tsx
autogpt_platform/frontend/src/components/auth/help-item.tsx

Currently both login and signup page show the same feedback on error on cloud (join the waitlist).
Update login&signup feedback for cloud.
- Use cards for login and signup feedback instead of html list
- Make login page show prompt to redirect user to signup

feat(frontend): Update login and signup feedback

---

autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/page.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts

- Resolves #9929
- Implement `BackendAPI.onWebSocketConnect(..)`
- Improve reliability and reactivity of `/library/agents/[id]`:
- Refresh page data and (re)subscribe and on WebSocket (re)connect
- Break up multi-action hooks into smaller parts to reduce unnecessary re-renders and requests
- Reduce duplicate requests
- Use `onWebSocketConnect` in `useAgentGraph` as well
- Tidy up `autogpt-server-api/client.ts` a bit
- Go to `/library/agents/[id]`
- Run the agent
- Suspend your computer, or restart the backend (or WS server) to break the connection
- DO NOT REFRESH THE TAB ITSELF
- Run the agent again

fix(frontend): Re-subscribe on WebSocket re-connect

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/notifications/notifications.py
autogpt_platform/backend/backend/util/logging.py

> Log entry with size 865.8K exceeds maximum size of 256.0K
Some logs are just too large.
Truncate logging on NotificationManager and LLMBlocks

feat(backend): Truncate logging on NotificationManager and LLMBlocks

---

.vscode/launch.json
autogpt_platform/backend/backend/util/request.py

Github Blocks use an URL transformer passed to `Requests` to convert web URLs to the API URLs. This doesn't always work with the anti-SSRF URL pinning mechanism that was implemented in #8531.
In `Requests.request(..)`:
- Apply `validate_url` *after* `extra_url_validator`, to prevent mismatch between `pinned_url` and `original_hostname`
- Simplify logic & add clarifying comments

fix(backend): Make URL pinning work with `extra_url_validator`

---

autogpt_platform/autogpt_libs/autogpt_libs/auth/middleware.py
classic/benchmark/agbenchmark/challenges/webarena.py

This small PR resolves the deprecation warnings of the `logger` library:
```
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

fix: Resolve `logger.warn(..)` deprecration warnings

---

autogpt_platform/backend/backend/blocks/google/gmail.py
docs/content/platform/blocks/google/gmail.md

- drop obsolete includeSpamTrash option from Gmail thread block
- update Gmail block docs
- `ruff check autogpt_platform/backend/backend/blocks/google/gmail.py`

Remove Gmail thread includeSpamTrash

---

autogpt_platform/backend/backend/blocks/google/gmail.py
docs/content/platform/blocks/google/gmail.md

- handle gmail metadata scope in Gmail read
- handle metadata scope in Gmail get thread
- avoid missing payload when scope is metadata
- mention metadata scope limitation in documentation
- `poetry run black backend/blocks/google/gmail.py`
- `poetry run isort backend/blocks/google/gmail.py`
- `poetry run ruff format backend/blocks/google/gmail.py`
- `poetry run format` *(fails: pyright errors)*

Fix Gmail blocks query error

---

autogpt_platform/frontend/src/app/layout.tsx
autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/components/OttoChatWidget.tsx
autogpt_platform/frontend/src/components/PrimaryActionButton.tsx
autogpt_platform/frontend/src/components/TallyPopup.tsx

- Resolves #9950
- Move `<OttoChatWidget>` from root layout into `FlowEditor`
- Pass graph info directly into `OttoChatWidget` instead of using `useAgentGraph`
- Rearrange z-indices of elements in the builder
- Go to `/build`
- Open the widget and ask Otto something
- Add a few blocks and save the graph
- Click "Include graph data" and ask Otto something about your graph

refactor(frontend): Move `OttoChatWidget` out of root layout

---

autogpt_platform/backend/backend/blocks/github/_api.py
autogpt_platform/backend/backend/util/request.py
autogpt_platform/backend/test/util/test_request.py

- Resolves #9987
- Split `pin_url(..)` out of `validate_url(..)` and call `extra_url_validator` in between

fix(backend): Unbreak URL handling for GitHub blocks

---

autogpt_platform/backend/backend/data/model.py
autogpt_platform/backend/backend/data/user.py

Makes all optional fields on `Credentials` models actually optional, and sets `exclude_none=True` on the corresponding `model_dump`.
This is a hotfix: after running the `aryshare-revid` branch on the dev deployment, there is some data in the DB that isn't valid for the `UserIntegrations` model on the `dev` branch (see [here](https://github.com/Significant-Gravitas/AutoGPT/pull/9946#discussion_r2098428575)).

fix(backend): Unbreak `UserIntegrations` parsing for missing `None` values

---

autogpt_platform/backend/backend/util/request.py

Keep the original URL when an HTTP error occurs in `SendWebRequestBlock`.

fix(blocks): Error messages from SendWebRequestBlock use the requested translated IP instead of the orignal URL

---

autogpt_platform/backend/backend/blocks/mem0.py

This pull request refines the handling of `input_data.content` and improves error message formatting in the `run` method of `mem0.py`. The changes enhance robustness and clarity in the code.
* Updated the `run` method to handle `Content` objects explicitly, ensuring proper formatting of messages when `input_data.content` is of type `Content`. Additionally, non-standard types are now converted to strings for consistent handling. (`[autogpt_platform/backend/backend/blocks/mem0.pyR127-R130](diffhunk://#diff-d7abf8c3299388129480b6a9be78438fe7e0fbe239da630ebb486ad99c80dd24R127-R130)`)
* Simplified the error message formatting by removing the unnecessary `object=` keyword in the `str()` conversion of exceptions. (`[autogpt_platform/backend/backend/blocks/mem0.pyL155-R157](diffhunk://#diff-d7abf8 …

Fix AddMemoryBlock JSON serialization error

---

autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/page.tsx
autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/agents/agent-schedule-details-view.tsx

- Resolves #9992
- Use `<LoadingBox>` instead of "Loading..." on `/library/agents/[id]`

feat(frontend/library): Replace "Loading..." by loading spinners

---

autogpt_platform/frontend/src/components/agptui/PublishAgentSelect.tsx
autogpt_platform/frontend/src/components/agptui/composite/PublishAgentPopout.tsx

- add scroll handler prop to `PublishAgentSelect` so the publish popout can detect scroll position
- hook up infinite scroll handler in the publish popout and prevent page scrolling
- `yarn lint`
- `yarn type-check`
- `yarn test` *(fails: Process from config.webServer exited early)*

fix(frontend): Implement infinite scroll for publish agent popout

---

autogpt_platform/backend/backend/blocks/exa/contents.py
autogpt_platform/backend/backend/blocks/exa/search.py
autogpt_platform/backend/backend/blocks/exa/similar.py

Exa blocks currently just return an empty list when they fail.
- Add `error` output field where missing on Exa blocks
- Don't yield empty results when a request fails
- `ruff check autogpt_platform/backend/backend/blocks/exa/search.py autogpt_platform/backend/backend/blocks/exa/contents.py autogpt_platform/backend/backend/blocks/exa/similar.py --fix`
- `black autogpt_platform/backend/backend/blocks/exa/search.py autogpt_platform/backend/backend/blocks/exa/contents.py autogpt_platform/backend/backend/blocks/exa/similar.py`
- `isort autogpt_platform/backend/backend/blocks/exa/search.py autogpt_platform/backend/backend/blocks/exa/contents.py autogpt_platform/backend/backend/blocks/exa/similar.py`
- `pre-commit run --files autogpt_platform/backend/backend/blocks/exa/search.py …

feat(blocks/exa): Fix Exa blocks error reporting

---

autogpt_platform/frontend/src/app/(platform)/login/page.tsx
autogpt_platform/frontend/src/app/(platform)/reset_password/page.tsx
autogpt_platform/frontend/src/app/(platform)/signup/page.tsx
autogpt_platform/frontend/src/components/auth/Turnstile.tsx
autogpt_platform/frontend/src/hooks/useTurnstile.ts

Users were unable to retry login attempts after a failed authentication because the Turnstile CAPTCHA widget was not properly resetting. This forced users to refresh the entire page to attempt login again, creating a terrible user experience.
Root Cause: The useTurnstile hook had several critical issues:
- The reset() function only cleared state when shouldRender was true and widget existed
- Widget ID tracking was unreliable due to intercepting window.turnstile.render
- Token wasn't being cleared on verification failures
- State wasn't being reset consistently across error scenarios
Changes 🏗️
- Fixed useTurnstile hook reset logic: Modified the reset() function to always clear all state (token, verified, verifying, error) regardless of shouldRender condition
- Improved widget ID …

fix(platform): Turnstile CAPTCHA reset after failed login attempts

---

autogpt_platform/frontend/src/app/(platform)/reset_password/page.tsx
autogpt_platform/frontend/src/app/(platform)/signup/page.tsx

CASA requires a length of 12 passwords, which we did update. When testing in dev, I realized I missed a few.
updates a missed prompt

fix(frontend): missed a password prompt

---

autogpt_platform/backend/backend/blocks/flux_kontext.py
autogpt_platform/backend/backend/data/block_cost_config.py
docs/content/platform/blocks/blocks.md
docs/content/platform/blocks/flux_kontext.md

This PR adds a new internal block, **AI Image Editor**, which enables **text-based image editing** via BlackForest Labs’ Flux Kontext models on Replicate. This block allows users to input a prompt and optionally a reference image, and returns a transformed image URL. It supports two model variants (Pro and Max), with different cost tiers. This functionality will enhance multimedia capabilities across internal agent workflows and support richer AI-powered image manipulation.
---
* Added `FluxKontextBlock` in `backend/blocks/flux_kontext.py`
* Uses `ReplicateClient` to call Flux Kontext Pro or Max models
* Supports inputs for `prompt`, `input_image`, `aspect_ratio`, `seed`, and `model`
* Outputs transformed image URL or error
* Added credit pricing logic for Flux Kontext models to …

feat(platform/blocks): add AI Image Editor Block powered by flux kontext

---

.github/dependabot.yml

- Fixes #10098
Tells dependabot to ignore poetry
N/A

chore(backend): Tell Dependabot not to update Poetry

---

autogpt_platform/backend/backend/data/graph.py

Currently, the get_graph function, with no graph version specifier will try to fetch the latest version, and when the graph is not owned and the latest version is not available for listing, it will return `None` instead of picking the latest graph version available on the store.
Instead of using the latest graph.version to fetch the store listing, don't provide any version filter at all and pick up whatever available version in the store.

fix(backend): Fix graph fetching of non-owned marketplace agent

---

autogpt_platform/frontend/.env.example
autogpt_platform/frontend/src/hooks/useTurnstile.ts
autogpt_platform/frontend/src/lib/turnstile.ts

This simply adds a env to hide turnstile for dev deploys
if this env ``NEXT_PUBLIC_DISABLE_TURNSTILE`` is set to false which it is by default, it will show turnstile, if the env is set to "true" it will hide the turnstile

update(turnstile): Add env to hide turnstile for dev deploy

---

autogpt_platform/frontend/.env.example
autogpt_platform/frontend/src/hooks/useTurnstile.ts
autogpt_platform/frontend/src/lib/turnstile.ts

change ``NEXT_PUBLIC_DISABLE_TURNSTILE`` to ``NEXT_PUBLIC_TURNSTILE``  and set turnstile captcha to be hidden by default 
if ``NEXT_PUBLIC_TURNSTILE=enabled`` is set, captcha will work and show on the frontend login/signup/password reset pages
if ``NEXT_PUBLIC_TURNSTILE=disabled`` is set, captcha will be hidden from the frontend and is not needed to login/signup/password reset
if ``NEXT_PUBLIC_TURNSTILE`` is not set captcha will be hidden from the frontend and is not needed to login/signup/password reset
This means users who setup AutoGPT locally will not need to deal with changing the env to hide captcha

fix(turnstile): Disable turnstile by default and rename its env

---

autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/customnode.css
autogpt_platform/frontend/src/components/node-input-components.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

There are a few UI bugs on the builder that this PR addresses.
Fix these UI issues:
* (screenshot attached above) Key-value input width was unintentionally maxed out due to a stale CSS rule.
* When multiple executions within the same node are running, we pick the latest status, making one running and one completed execution displayed as completed.
* No balance errors were executed, only displayed while at least one node execution was triggered, while this can be done directly when the execution request is triggered.
* Run & Stop button glitch: it's still showing as stopped when the graph is still running, this is due to way the UI code tracks execution in the node-level, instead of graph level.

fix(frontend): Fix builder UI glitch

---

autogpt_platform/frontend/instrumentation-client.ts
autogpt_platform/frontend/package.json
autogpt_platform/frontend/pnpm-lock.yaml
autogpt_platform/frontend/sentry.edge.config.ts
autogpt_platform/frontend/sentry.server.config.ts

We were getting the following warnings in the console when running the local server:
```
⚠ ./node_modules/.pnpm/@sentry+node@9.26.0/node_modules/@sentry/node/build/cjs/sdk
Package import-in-the-middle can't be external
The request import-in-the-middle matches serverExternalPackages (or the default list).
The request could not be resolved by Node.js from the project directory.
Packages that should be external need to be installed in the project directory, so they can be resolved from the output files.
Try to install it into the project directory by running npm install import-in-the-middle from the project directory.
```
The Sentry SDK for Next.js tries to hook into Node.js internals using packages like `import-in-the-middle` and `require-in-the-middle`. When Sentry is imported at the top …

fix(frontend): avoid Sentry initialisation and warnings on local dev

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/executor/utils.py

Allowing depth-first execution will unlock faster processing latency and a better sense of progress.
* Prioritize adding a new execution over processing execution output
* Make sure to enqueue each node once when processing output instead of draining a single node and move on.

feat(executor): Improve execution ordering to allow depth-first execution

---

autogpt_platform/backend/backend/blocks/fal/ai_video_generator.py

This simply adds "fal-ai/veo3" to the ``FalModel`` in the ``ai_video_generator.py`` file
Oh i also set it so veo3 also always generates videos with audio so ``generate_audio=True`` is set to true if veo3 is selected

feat(blocks): add veo3 to ai video generator

---

autogpt_platform/frontend/src/stories/border-radius.stories.tsx

Document border radius tokens, which follow Tailwind default theme radius scale ✅

docs(frontend): document border radius tokens

---

autogpt_platform/backend/backend/server/routers/v1.py

Added the `graph_id` parameter to the stop execution endpoint path (`/graphs/{graph_id}/executions/{graph_exec_id}/stop`) to fix client generation from Openapi spec error.
The client generation was failing due to missing path parameter definition for `graph_id` in the stop execution endpoint.
Added `graph_id` as a path parameter while maintaining the existing functionality.

fix(backend): Add graph_id path parameter to fix automatic client generation from OpenAPI spec 

---

autogpt_platform/backend/backend/server/rest_api.py

This PR introduces a custom function for generating unique operation IDs for OpenAPI specifications to improve auto-generated client code quality.
**Better Auto-Generated Clients**: Default FastAPI operation IDs create unclear method names in generated clients. Our custom generator produces clean, readable operation IDs that translate to intuitive method names.
- **Before**: `get_items_api_v1_items_get` → unclear generated methods
- **After**: `get_users_list` → clean, descriptive method names
- ✨ **Added**: `custom_generate_unique_id` utility function
- Generates IDs using pattern: `{method}_{tag}_{summary}`
- Ensures uniqueness and readability
- 🔧 **Updated**: FastAPI app configuration to use custom generator

feat(backend): add custom openapi generator

---

autogpt_platform/backend/backend/blocks/basic.py
autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/executor/utils.py

Since auto conversion is applied before merging nested input in the block, it breaks the auto conversion break.
* Enabling auto-type conversion on block input schema mismatch for nested input
* Add batching feature for `CreateListBlock`
* Increase default max_token size for LLM call

feat(blocks): Enabling auto type conversion on block input schema mismatch for nested input

---

autogpt_platform/backend/.env.example
autogpt_platform/docker-compose.platform.yml
autogpt_platform/frontend/.env.example
autogpt_platform/frontend/src/app/(platform)/reset-password/actions.ts

We need to `FRONTEND_BASE_URL` to → `NEXT_PUBLIC_FRONTEND_BASE_URL` given is needed on the new API client on the Front-end to make requests. The `NEXT_PUBLIC` prefix is important so that it is available on the client.

fix(frontend): migrate to `NEXT_PUBLIC_FRONTEND_BASE_URL`

---

autogpt_platform/frontend/src/app/api/proxy/[...path]/route.ts

A new undocumented env var, `NEXT_PUBLIC_AGPT_SERVER_BASE_URL`, was added to the proxy route for it to work with the new `react-query` mutator. 
I removed it and used the existing `NEXT_PUBLIC_AGPT_SERVER_URL`, so we have fewer environment variables to manage ( _and this one is already added to all environments_ ).

fix(frontend): use `NEXT_PUBLIC_AGPT_SERVER_URL` on proxy route

---

.github/workflows/platform-frontend-ci.yml

- **Before**: Each job separately installs dependencies (~4 redundant installations)
Each job repeats these SAME 4 steps:
- Checkout repository
- Set up Node.js (version 21) 
- Enable corepack
- Install dependencies (pnpm install --frozen-lockfile)
This happens 4+ times across different jobs:
-  lint job
- type-check job
- chromatic job
- test job (runs 2x due to matrix strategy)
No caching strategy - downloads packages fresh every time
- Every workflow run downloads all packages from scratch
- No benefit from previous runs, even with identical pnpm-lock.yaml
- **After**: Dependencies installed once in setup job, cached and reused
This optimization maintains all existing CI functionality while significantly improving pipeline efficiency.
A workflow run example is dispatched: …

feat: optimize frontend CI with shared setup job 

---

autogpt_platform/frontend/src/app/api/proxy/[...path]/route.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/helpers.ts

Requests to the Backend happen now on the server, given we moved to server-side cookies 🍪 ... however the client proxy is not exposing the API errors to the client correctly. This aim to fix that.

fix(frontend): do not swallow errors on the proxy

---

autogpt_platform/frontend/src/app/api/proxy/[...path]/route.ts
autogpt_platform/frontend/src/components/integrations/credentials-input.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts
autogpt_platform/frontend/src/lib/autogpt-server-api/helpers.ts

We noticed that in some pages ( `/build` _mainly_ ), where a lot of API calls are fired in parallel using the old `BackendAPI`( _running many agent executions_ ) the performance became worse. That is because the `BackendAPI` was proxied via [server actions](https://nextjs.org/docs/14/app/building-your-application/data-fetching/server-actions-and-mutations) ( _to make calls to our Backend on the Next.js server_ ). 
Looks like server actions don't run in parallel, and their performance is also subpar, given that we are not hosted on Vercel (they don't utilise the edge middleware). 
These changes cause all `BackendAPI` calls to be proxied via the Next.js `/api/` route when executed on the browser; when executed on the server, they bypass the proxy and directly access the API. Hopefully we …

fix(frontend): proxy via API route no actions

---

autogpt_platform/CLAUDE.md
autogpt_platform/backend/backend/blocks/google/sheets.py
autogpt_platform/backend/backend/blocks/mem0.py

The block library was missing two key capabilities that keep coming up in real-world agent flows:
1. **Granular Mem0 filtering.**  Agents often work side-by-side for the same user, so memories must be scoped to a specific run or agent to avoid crosstalk.  
2. **First-class Google Sheets support.**  Many community projects (e.g., data-collection, lightweight dashboards, no-code workflows) rely on Sheets, but we only had a brittle REST call block.  
This PR adds fine-grained filters to every Mem0 retrieval block and introduces a complete, OAuth-ready Google Sheets suite so agents can create, read, write, format, and manage spreadsheets safely. :contentReference[oaicite:0]{index=0}
---
* Added `categories_filter`, `metadata_filter`, `limit_memory_to_run`, and `limit_memory_to_agent` inputs …

feat(block): Enhance Mem0 blocks filetering & add more GoogleSheets blocks

---

autogpt_platform/backend/backend/server/v2/library/db.py
autogpt_platform/backend/backend/server/v2/library/model.py

- Resolves #10300
- Follow-up fix to #10167
- Include sub-graphs in `get_library_agent` endpoint

fix(backend/library): Include subgraphs in `get_library_agent`

---

autogpt_platform/frontend/src/app/(no-navbar)/onboarding/5-run/page.tsx
autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/agents/agent-run-draft-view.tsx
autogpt_platform/frontend/src/components/agents/agent-schedule-details-view.tsx

Looking at the generated types, it looks like `input_schema` for the agent can be anything:
- [libraryAgent](https://github.com/Significant-Gravitas/AutoGPT/blob/dev/autogpt_platform/frontend/src/app/api/__generated__/models/libraryAgent.ts#L18-L38)
- [libraryAgentInputSchema](https://github.com/Significant-Gravitas/AutoGPT/blob/dev/autogpt_platform/frontend/src/app/api/__generated__/models/libraryAgentInputSchema.ts#L9)
But the Front-end is reading it optimistically through the hardcoded types on Backend API:
- [GraphIOSchema](https://github.com/Significant-Gravitas/AutoGPT/blob/443995d79a90486fd287f7e15272fe56a19d36f0/autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts#L324-L329)
No configuration changes.

fix(frontend): make reading `input_schema` way more defensive

---

autogpt_platform/backend/backend/util/type.py
autogpt_platform/backend/backend/util/type_test.py
autogpt_platform/frontend/src/components/agents/agent-run-draft-view.tsx

Auto type conversion doesn't work on optional type.
To reproduce:
Use the AgentNumberInput block and try to pass a string value to the sub-agent that uses it.
Added optional type auto conversation support.

fix(backend;frontend): Add auto-type convertion support for optional types

---

autogpt_platform/frontend/src/app/(platform)/library/components/LibraryAgentList/LibraryAgentList.tsx
autogpt_platform/frontend/src/app/(platform)/library/components/LibraryAgentList/useLibraryAgentList.ts

Currently, my agents count is showing the initial agent count loads on the library and then adding more agents after pagination.
- I’ve used `total_items` inside the pagination response and shown the correct result.
https://github.com/user-attachments/assets/b9a2cf18-c9fc-42f8-b0d4-3f8a7ad3cbc5

fix(frontend): fix my agent count in the library

---

autogpt_platform/frontend/src/components/layout/Navbar/data.ts
autogpt_platform/frontend/src/tests/signin.spec.ts

When redoing the navigation bar, I moved the profile query to be executed on the server using the new [react-query](https://tanstack.com/query/latest) generated hooks. 
The README [states the new hooks can be called on the server](https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpt_platform/frontend/README.md#server-side-prefetching), but when looking deeply into the implementation of [`custom-mutator.ts`](https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpt_platform/frontend/src/app/api/mutators/custom-mutator.ts), it turns out they can not ( yet ) as `custom-mutator` calls the proxy API ( _which can't be called from a RSC_ 😅 ).
For now, I changed the call to be made through the old `BackendAPI`, which can be called client and server side ✅  ( _I did that …

fix(frontend): navbar profile query not working

---

autogpt_platform/frontend/playwright.config.ts
autogpt_platform/frontend/src/components/layout/Navbar/components/NavbarMainPage.tsx
autogpt_platform/frontend/src/components/layout/Navbar/data.ts
autogpt_platform/frontend/src/tests/build.spec.ts
autogpt_platform/frontend/src/tests/signin.spec.ts

In this recent PR https://github.com/Significant-Gravitas/AutoGPT/pull/10394/  the navigation bar disappeared when logged out. A change was introduced where the navigation bar does not show up if we don't have profile data ( _which we won't have when logged out_ ). This solves it + adds tests covering the navigation bar in the logged out state.
None

fix(frontend): navbar missing

---

autogpt_platform/backend/backend/blocks/agent.py
autogpt_platform/backend/backend/executor/scheduler.py
autogpt_platform/backend/backend/executor/utils.py
autogpt_platform/backend/backend/integrations/credentials_store.py

This PR reduces the dependency of the API layer on the database manager service by avoiding using DatabaseManager for credentials fetch when a direct query is possible from the API layer
* If Prisma is available, use the direct query.
* Otherwise, utilize the database manager.

feat(backend): avoid using DatabaseManager when direct query is possible from the API layer

---

autogpt_platform/backend/backend/integrations/webhooks/graph_lifecycle_hooks.py
autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/backend/backend/server/v2/library/db.py
autogpt_platform/backend/backend/server/v2/store/image_gen.py
autogpt_platform/backend/test/e2e_test_data.py

Currently, we only create a library entry of the top-most graph when importing the graph from an exported file.
This can cause some complications, as there is no way to remove the library entry of it.
Create the library entry for all the subgraphs during the import process.

feat(backend): Register agent subgraphs as library entries during agent import

---

autogpt_platform/frontend/src/components/layout/Navbar/components/AccountMenu/AccountMenu.tsx
autogpt_platform/frontend/src/services/feature-flags/feature-flag-provider.tsx
autogpt_platform/frontend/src/tests/signin.spec.ts

Launch Darkly is not being initialised in production, despite on paper all env variables being well set 🧐 
I tried doing production builds locally, and I noticed this provider needs to be initialised on the client because Launch Darkly flags are designed to work on the client side, where they can access user context and browser environment.
None

fix(frontend): init LD on the client

---

autogpt_platform/backend/backend/rest.py
autogpt_platform/backend/backend/scheduler.py

Rest-Api service is a vital service where we should minimize the amount of external resources impacting it.
And the NotificationManager service is running as a singleton in nature (similar to the scheduler service), so it makes sense to put it in a single pod.
Move the NotificationManager service from rest-api pod to the scheduler pod

feat(platform): Move NotificationManager service from rest-api pod to scheduler pod

---

autogpt_platform/backend/backend/data/rabbitmq.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/executor/utils.py

When we run multiple instances of the executor, some of the executors can oversubscribe the messages and end up queuing the agent execution request instead of letting another executor handle the job. This change solves the problem.
* Reject execution request when the executor is full.
* Improve `active_graph_runs` tracking for better horizontal scaling heuristics.

feat(backend): Avoid executor over-consuming messages when it's fully occupied

---

autogpt_platform/autogpt_libs/autogpt_libs/utils/cache_test.py
autogpt_platform/backend/backend/monitoring/late_execution_monitor.py
autogpt_platform/backend/backend/util/service.py
autogpt_platform/backend/backend/util/service_test.py

HTTP requests can fail when the DNS is messed up. Sometimes this kind of issue requires a client reset.
Introduce HTTP client refresh on repeated error

feat(backend): Introduce http client refresh on repeated error

---

autogpt_platform/backend/backend/blocks/google/gmail.py
autogpt_platform/backend/test/blocks/test_gmail.py

Need: The Gmail integration had several parsing issues that were causing data loss and
workflow incompatibilities:
1. Email recipient parsing only captured the first recipient, losing CC/BCC and multiple TO
recipients
2. Email body parsing was inconsistent between blocks, sometimes showing "This email does
not contain a readable body" for valid emails
3. Type mismatches between blocks caused serialization issues when connecting them in
workflows (lists being converted to string representations like "[\"email@example.com\"]")
1. Enhanced Email Model:
- Added cc and bcc fields to capture all recipients
- Changed to field from string to list for consistency
- Now captures all recipients instead of just the first one
2. Improved Email Parsing:
- Updated GmailReadBlock and GmailGetThreadBlock …

feat(backend): add getting user profile, drafts, update send email to use mulitple to, cc, bcc

---

autogpt_platform/backend/backend/blocks/ayrshare/post_to_youtube.py
autogpt_platform/backend/backend/server/integrations/router.py

- Enabled the YouTube posting block that was previously disabled
- The block provides comprehensive YouTube-specific posting options including titles, visibility settings, thumbnails, playlists, tags, and more
- Removed `disabled=True` from YouTube posting block to enable functionality  
- Added full YouTube API integration with all supported options:
- Video title and description
- Visibility settings (private/public/unlisted)
- Thumbnail support
- Playlist management
- Video tags and categories
- YouTube Shorts support
- Subtitle/caption support
- Country-based targeting
- Synthetic media disclosure
https://github.com/user-attachments/assets/d4459f15-fe57-47bf-8459-f06f1af45ad6

feat(backend): Enable Ayrshare YouTube support

---

autogpt_platform/backend/backend/blocks/ayrshare/post_to_instagram.py
autogpt_platform/backend/backend/server/integrations/router.py

- Enabled the Instagram posting block that was previously disabled
- The block provides comprehensive Instagram-specific posting options including stories, reels, posts, user tagging, and location tagging
- Improved parameter types and validation for better user experience
- Removed `disabled=True` from Instagram posting block to enable functionality
- Updated parameter types from required to optional with proper None defaults for better flexibility
- Added validation for Instagram reel options to ensure all required fields are provided together
- Improved user tag validation with better error messages
- Added support for:
- Instagram Stories (24-hour expiration)
- Instagram Reels with audio, thumbnails, and feed sharing options
- Alt text for accessibility
- Location tagging via Facebook …

feat(backend): Enable Ayrshare Instagram support

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/data/block_cost_config.py

In my last PR https://github.com/Significant-Gravitas/AutoGPT/pull/10508 i forgot to remove the Grok-beta LLM, it  has been deprecated so needs removing from the platform.

chore(backend): Remove grok-beta llm

---

autogpt_platform/backend/backend/blocks/ayrshare/_util.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_bluesky.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_facebook.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_gmb.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_instagram.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_linkedin.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_pinterest.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_reddit.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_snapchat.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_telegram.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_threads.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_tiktok.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_x.py
autogpt_platform/backend/backend/blocks/ayrshare/post_to_youtube.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/integrations/credentials_store.py
autogpt_platform/backend/backend/server/integrations/router.py

This PR refactors the Ayrshare integration to remove the centralized `get_ayrshare_profile_key` function from the credentials store and instead retrieve the profile key directly within each Ayrshare block. This change improves code organization by keeping Ayrshare-specific logic within the Ayrshare module.
- **Refactored Ayrshare profile key retrieval**: Moved profile key fetching logic from the credentials store into the Ayrshare blocks
- **Added `get_profile_key` helper function** in `autogpt_platform/backend/backend/blocks/ayrshare/_util.py` to fetch the profile key from user integrations
- **Updated all 15 Ayrshare social media blocks** to use `user_id` instead of `profile_key` parameter and fetch the profile key internally
- **Removed `get_ayrshare_profile_key` method** from …

refactor(backend): remove Ayrshare from execution & credentials manager

---

autogpt_platform/backend/backend/blocks/agent.py
autogpt_platform/backend/backend/executor/manager.py

The node execution status can be done before the output persistence, making the output be persisted when the node execution status is already completed.
* Re-order the node execution status & output persistence logic.
* Make agent.py avoid yielding the same node_exec_id twice (that can be caused by the above issue).

fix(backend/executor): Fix node execution status and output persistence ordering

---

autogpt_platform/frontend/src/app/(platform)/login/page.tsx
autogpt_platform/frontend/src/app/(platform)/login/useLoginPage.ts
autogpt_platform/frontend/src/app/(platform)/signup/page.tsx
autogpt_platform/frontend/src/app/(platform)/signup/useSignupPage.ts

Updated login and signup pages to display the Turnstile CAPTCHA and require verification only when running in a cloud environment. This prevents unnecessary CAPTCHA prompts in local or non-cloud deployments.
Locally when you try to login with the wrong password, and you update and login again, you get a warning about captcha which is wrong, so this fix makes it so the captcha will only when running in a cloud

feat(frontend): Show CAPTCHA only in cloud environments

---

autogpt_platform/backend/backend/data/rabbitmq.py
autogpt_platform/backend/backend/executor/manager.py

The RabbitMQ connection is unreliable (fixing it is a separate issue) and sometimes get restarted. The scope of this PR is to avoid the operation break due to executing on a stale, broken connection.
Fix executor running RabbitMQ operations on closed/closing connection

fix(backend): Fix executor running RabbitMQ operations on closed/closing connection

---

autogpt_platform/backend/backend/executor/scheduler.py
autogpt_platform/backend/backend/executor/utils.py

This PR addresses the recurring job validation failures by adding graph validation before scheduling jobs. Previously, validation errors only occurred at runtime during job execution, making it difficult to communicate errors to users for scheduled recurring jobs.
- **Extract validation logic**: Created `validate_and_construct_node_execution_input` wrapper function that centralizes graph fetching, credential mapping, and validation logic
- **Add pre-scheduling validation**: Modified `add_graph_execution_schedule` to validate graphs before creating scheduled jobs
- **Make construct function private**: Renamed `construct_node_execution_input` to `_construct_node_execution_input` to prevent direct usage and encourage use of the wrapper
- **Reduce code duplication**: Eliminated duplicate …

fix(backend): add graph validation before scheduling recurring jobs

---

autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/backend/executor/scheduler.py
autogpt_platform/backend/backend/notifications/notifications.py
autogpt_platform/backend/backend/server/rest_api.py
autogpt_platform/backend/backend/util/service.py

This PR standardizes health check error handling across all services by introducing and using a consistent `UnhealthyServiceError` exception type. This improves monitoring, debugging, and service reliability by providing uniform error reporting when services are unhealthy.
- **Added `UnhealthyServiceError` class** in `backend/util/service.py`:
- Custom exception for unhealthy service states
- Includes service name in error message
- Added to `EXCEPTION_MAPPING` for proper serialization
- **Updated health checks across services** to use `UnhealthyServiceError`:
- **Database service** (`backend/executor/database.py`): Replace `RuntimeError` with `UnhealthyServiceError` for database connection failures
- **Scheduler service** (`backend/executor/scheduler.py`): Replace `RuntimeError` with …

feat(backend): standardize service health checks with UnhealthyServiceError

---

autogpt_platform/backend/backend/blocks/llm.py

Corrects the context window for GPT5_CHAT, fixes provider for CLAUDE_4_1_OPUS from 'openai' to 'anthropic', and adds a 600s timeout to the Anthropic client call in llm_call.
- changed gpt5's context limit to be smaller, 16k
- changed claude's provider from openai to anthropic
- Adding a 600s timeout to the Anthropic client call

fix(backend): correct LLM configurations

---

autogpt_platform/backend/backend/blocks/smart_decision_maker.py

We're forcing this note to the end of the system prompt SDM block: 
Only provide EXACTLY one function call; multiple tool calls are strictly prohibited., this is being interpreted by GPT5 as "Only call one tool per task," which is resulting in many agent runs that only use a tool once (i.e., useless low low-effort answers)
Remove parallel tool-call system prompting entirely.

feat(block): Remove paralel tool-call system prompting

---

autogpt_platform/frontend/src/app/(platform)/marketplace/components/MainMarketplacePage/MainMarketplacePage.tsx

Use a skeleton for the martkeplace loading state, representing visually how the place should looks. Looks a bit more stylish than the previous `Loading...` text.
None

fix(marketplace): loading state

---

autogpt_platform/backend/backend/server/v2/AutoMod/manager.py

Calls to the moderation API now strip whitespace from the API key before including it in the 'X-API-Key' header, preventing authentication issues due to accidental leading or trailing spaces.

fix(backend/AM): Fix AutoMod api key issue

---

autogpt_platform/frontend/src/components/molecules/TabsLine/TabsLine.stories.tsx
autogpt_platform/frontend/src/components/molecules/TabsLine/TabsLine.tsx

https://github.com/user-attachments/assets/4a83ed59-068e-46e0-8e76-4f34ed9dd976
- Needed for the new Agent Runs views ( [designs](https://www.figma.com/design/14jjs3hH3Hmkq4hGqxZWco/agent-runs-unification?node-id=187-8653&t=3BV5fF6NDXN7BlI8-1) ) 
- Took **shadcn** tabs as a base and applied styles on top
None

feat(frontend): add Line Tabs component

---

autogpt_platform/backend/backend/server/routers/v1.py

Some API key endpoints have the Launch Darkly feature flag enabled, while others don’t. To ensure consistency and remove the API key flag from the Launch Darkly dashboard, I’m also removing it from the left endpoints.

chore(api): remove launch darkly feature flags from api key endpoints

---

autogpt_platform/frontend/src/app/(platform)/library/components/LibraryUploadAgentDialog/LibraryUploadAgentDialog.tsx
autogpt_platform/frontend/src/app/(platform)/library/components/LibraryUploadAgentDialog/useLibraryUploadAgentDialog.ts

With this PR, when a user removes the agent file, the agent name and description will also be removed if they haven’t been changed. However, if the user has modified either of them, they will remain.

fix(frontend): clear agent name and description on agent file removal

---

autogpt_platform/backend/.env.default
autogpt_platform/backend/backend/blocks/discord/_api.py
autogpt_platform/backend/backend/blocks/discord/_auth.py
autogpt_platform/backend/backend/blocks/discord/bot_blocks.py
autogpt_platform/backend/backend/blocks/discord/oauth_blocks.py
autogpt_platform/backend/backend/integrations/oauth/__init__.py
autogpt_platform/backend/backend/integrations/oauth/discord.py
autogpt_platform/backend/backend/util/metrics.py
autogpt_platform/backend/backend/util/settings.py

We want a way to get the user's id from discord without them having to enable dev mode so this is a way -- oauth login
- Created DiscordOAuthHandler for managing OAuth2 flow, including login URL generation, token exchange, and revocation.
- Implemented support for PKCE in the OAuth2 flow.
- Enhanced error handling for user info retrieval and token management.
- Add discord block for getting the logged in user
- Add new client secret field to .env.default

feat(backend): DiscordGetCurrentUserBlock to fetch authenticated user details via OAuth2

---

autogpt_platform/backend/backend/server/v2/AutoMod/manager.py
autogpt_platform/backend/backend/server/v2/AutoMod/models.py
autogpt_platform/backend/backend/util/exceptions.py

AutoModManager now captures and propagates the content_id from the moderation API for both input and output moderation. AutoModResponse and ModerationError are updated to include content_id, allowing better traceability of moderation actions and error reporting, with this the error message will now show ``Failed due to content moderation (Moderation ID: uuid-here)``
This is good for if a user is having a issue with automod and its falsely flagging there runs we can use the moderation ID to look at automod to see whats going on
Just some updates to receive the content_id from AutoMod and then show it in the "Failed due to content moderation" message

feat(AutoMod): add ``moderation id`` to moderation message

---

autogpt_platform/frontend/src/tests/pages/library.page.ts

A test in one of my pr is failing something like… 
That’s why I fixed it.

test(frontend): fix library flaky e2e test

---

autogpt_platform/frontend/src/lib/utils.ts

Date values were being rejected as "empty" by the run input form.
- Specifically handle `Date` type values in `isEmpty`
- Specifically handle `NaN` values in `isEmpty`

fix(frontend): Fix checking of `Date` and `NaN` input values

---

autogpt_platform/db/docker/docker-compose.yml
autogpt_platform/docker-compose.platform.yml

Supabase `db/docker/docker-compose.yml` overrides env vars set in `autogpt_platform/.env` file. This PR fixes that and simplifies the compose files further.
`autogpt_platform/docker-compose.platform.yml`:
- Move hardcoded `DATABASE_URL` and `DIRECT_URL` to `x-backend-env` on top as it repeats for most services.
- Remove `RABBITMQ_DEFAULT_USER` and `RABBITMQ_DEFAULT_PASS` from `rabbitmq` service and use env files instead
`autogpt_platform/db/docker/docker-compose.yml`:
- Remove hardcoded env vars from `x-supabase-env` - these are already defined in `.env`
- Remove env vars from services that are already defined in `.env` files
*Changes to db compose file only affect self-hosted Supabase*

feat(backend/infra): Cleanup platform and db docker compose files

---

autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/AgentRunsView/AgentRunsView.tsx
autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/AgentRunsView/components/EmptyAgentRuns/EmptyAgentRuns.tsx
autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/AgentRunsView/components/RunDetailCard/RunDetailCard.tsx
autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/AgentRunsView/components/RunDetails/useRunDetails.ts
autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/AgentRunsView/components/RunsSidebar/RunsSidebar.tsx
autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/AgentRunsView/components/RunsSidebar/useRunsSidebar.ts
autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/AgentRunsView/useAgentRunsView.ts
autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/page.tsx

- Make a nicer empty state and display it when there are no runs/schedules
- Rename search param to `executionId` to mirror what was on the old page
- Reduce polling when execution is happening to 1.5s ( 3.s is too slow maybe... )
- Make sure the run details page also updates when a run is happening
None
<details>
</details>

feat(frontend): smol improvements on new run view

---

autogpt_platform/backend/backend/util/metrics.py
autogpt_platform/backend/backend/util/process.py

Adds error reporting to Sentry for exceptions (excluding KeyboardInterrupt and SystemExit) before executing process cleanup. Silently ignores failures if Sentry is unavailable.
Adds cleanup for sentry
Adds disabling for sentry

fix(backend): Report process errors to Sentry before cleanup

---

autogpt_platform/backend/backend/blocks/github/pull_requests.py

Reverts Significant-Gravitas/AutoGPT#10317
The changes omit the hostname from the "prepared" URL, breaking some GitHub blocks.

Revert "fix(backend): Improve GitHub PR URL validation and API URL generation"

---

autogpt_platform/backend/backend/blocks/airtable/_api.py
autogpt_platform/backend/backend/blocks/airtable/bases.py
autogpt_platform/backend/backend/blocks/airtable/records.py

Fixes critical issue with Airtable API where empty/false fields are completely omitted from responses, causing inconsistent data structures. Also improves the create base block to prevent duplicate bases.
The Airtable API has a problematic behavior where it omits fields with "empty" values from responses:
- Unchecked checkboxes are missing entirely instead of returning `false`
- Empty number fields are missing instead of returning `0`
- This makes it impossible to distinguish between "field doesn't exist" and "field is false/empty"
- Users were getting inconsistent record structures that broke their workflows
- New `get_table_schema()` function to fetch table field definitions
- New `get_empty_value_for_field()` to determine appropriate empty values per field type
- New …

fix(backend): Add Airtable record normalization + find/create base

---

autogpt_platform/backend/migrations/20250910161617_fix_store_materialized_views_refresh_job/migration.sql

- Resolves #10898
- Fix and re-create `refresh_store_materialized_views` DB function and its pg_cron job

fix(backend/db): Unbreak store materialized views refresh job

---

autogpt_platform/backend/backend/executor/activity_status_generator.py
autogpt_platform/backend/backend/executor/activity_status_generator_test.py
autogpt_platform/backend/backend/util/settings.py

Separate the API key for internal usage (smart agent execution summary) and block usage.

feat: Separate OpenAI key for smart agent execution summary and other internal AI calls

---

autogpt_platform/backend/backend/server/v2/store/db.py
autogpt_platform/backend/backend/server/v2/store/db_test.py

This PR enhances the agent retrieval logic in the store database to ensure accurate fetching of the latest approved agent versions. The changes address scenarios where agents may have multiple versions with different approval statuses.
- **Active Version Priority**: Added logic to prioritize fetching agents based on the `activeVersionId` when available
- **Fallback to Latest Approved**: When no active version is set, the system now falls back to the latest approved version (sorted by version number descending)
- **Improved Accuracy**: Ensures users always see the most relevant agent version based on the current store listing state
- **Enhanced Store Listing Filter**: Modified the filter to only include store listings that have at least one available version
- **Nested Version Check**: …

feat(backend): enhance agent retrieval logic in store agent page

---

autogpt_platform/frontend/src/app/(platform)/marketplace/page.tsx

When building on Vercel:
```
at Object.start (.next/server/chunks/2744.js:1:312830) {
description: "Route /marketplace couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
digest: 'DYNAMIC_SERVER_USAGE'
}
Failed to get server auth token: Error: Dynamic server usage: Route /marketplace couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
at r (.next/server/chunks/8450.js:22:7298)
at n (.next/server/chunks/4735.js:1:37020)
at g (.next/server/chunks/555.js:1:31925)
at m (.next/server/chunks/555.js:1:87056)
at h (.next/server/chunks/555.js:1:932)
at k (.next/server/chunks/555.js:1:25195)
at queryFn …
```

fix(frontend): force dynamic rendering on marketplace 

---

autogpt_platform/backend/backend/data/graph.py

Restore `include=AGENT_GRAPH_INCLUDE` that is needed to build schema from the nodes.

hotfix: Fix Agent node missing inputs and outputs

---

autogpt_platform/backend/backend/blocks/io.py
autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/blocks/text.py
autogpt_platform/backend/backend/util/text.py

- Resolves #10954
Unnecessary escaping distorts content and so should be disabled wherever the output isn't used in HTML.
- Disable HTML escaping on prompt value insertion in AI blocks
- Make HTML escaping optional in text formatting and output blocks

fix(blocks): Default disable HTML escaping in all blocks with templating features

---

autogpt_platform/backend/backend/blocks/smart_decision_maker.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/integrations/creds_manager.py

Fix two production issues causing agent execution failures that occurred this morning:
1. **AsyncRedisLock Release Error** (ExecutionID: 08b2c251-ee27-45de-b88d-1792823ca3ee)
- Error: "Cannot release a lock that's no longer owned" 
- Root cause: Race condition where lock expires during long database operations
- Location: backend/executor/manager.py synchronized context manager
2. **Tool Call Parameter Validation** (ExecutionID: 766fd9a0-5f22-4a77-96e8-14c9d02f3292)
- Issue: LLM used typo'd parameter 'maximum_keyword_difficulty' instead of 'max_keyword_difficulty'
- SmartDecisionMakerBlock silently accepted typo, setting correct parameter to null
- Result: Downstream blocks received null values causing execution failures
- Add try-catch blocks around AsyncRedisLock.release() calls in …

fix(backend): resolve two critical long-running agent execution failures

---

autogpt_platform/backend/backend/blocks/smart_decision_maker.py
autogpt_platform/backend/backend/blocks/test/test_smart_decision_maker.py
autogpt_platform/backend/backend/blocks/test/test_smart_decision_maker_dict.py
autogpt_platform/backend/backend/blocks/test/test_smart_decision_maker_dynamic_fields.py
autogpt_platform/backend/backend/data/dynamic_fields.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/executor/utils.py
autogpt_platform/backend/backend/executor/utils_test.py
autogpt_platform/backend/backend/util/dynamic_fields.py
autogpt_platform/backend/backend/util/dynamic_fields_test.py

- Centralize dynamic field delimiters and helpers in backend/data/dynamic_fields.py.
- Refactor SmartDecisionMaker: build function signatures with dynamic-field mapping and re-map tool outputs back to original dynamic names.
- Deterministic retry loop with retry-only feedback to avoid polluting final conversation history.
- Update executor/utils.py and data/graph.py to use centralized utilities.
- Update and extend tests: dynamic-field E2E flow, mapping verification, output yielding, and retry validation; switch mocked llm_call to AsyncMock; align tool-name expectations.
- Add a single-tool fallback in schema lookup to support mocked scenarios.
- Full backend test suite: 1125 passed, 88 skipped, 53 warnings (local).
- Backend lint/format pass.
- Minimal and localized to SmartDecisionMaker …

fix(backend): Add dynamic input pin support for Smart Decision Maker Block

---

autogpt_platform/frontend/instrumentation-client.ts
autogpt_platform/frontend/src/services/feature-flags/feature-flag-provider.tsx

We struggle to identify where issues are coming from feature flags and which are from normal use. This adds that split on the frontend.
Include sentry in the LD initialization

feat(frontend): launchdarkly tracking on frontend browser
