arena/JackGPT.json

- **Agent Name:** JackGPT
- **Repository Link:** [JackDance/AutoGPT](https://github.com/JackDance/AutoGPT) …

JackGPT entering the arena

---

arena/HMD2.json

- **Agent Name:** HMD2
- **Repository Link:** [HMDCrew/AutoGPT](https://github.com/HMDCrew/AutoGPT)
- …

HMD2 entering the arena

---

arena/aiwowo.json

- **Agent Name:** aiwowo
- **Repository Link:** [jeffxtang/AutoGPT](https://github.com/jeffxtang/AutoGPT) …

aiwowo entering the arena

---

arena/autogpt_hackathon.json

- **Agent Name:** autogpt_hackathon
- **Repository Link:** [ThisisHubert/AutoGPT-hackathon](https://github.com/ThisisHubert/AutoGPT-hackathon)
- **Target Prize:** (Which prize caught …

autogpt_hackathon entering the arena

---

arena/operationAgent.json

- **Agent Name:** operationAgent
- **Repository Link:** [KMing-L/AutoGPT](https://github.com/KMing-L/AutoGPT) …

operationAgent entering the arena

---

arena/rachael.json

rachael entering the arena

---

arena/TLGPT.json

- **Agent Name:** TLGPT
- **Repository Link:** [TheoLawrence86/AutoGPT](https://github.com/TheoLawrence86/AutoGPT) …

TLGPT entering the arena

---

arena/momo.json

- **Agent Name:** momo
- **Repository Link:** [UICJohn/AutoGPT](https://github.com/UICJohn/AutoGPT)
- …

momo entering the arena

---

arena/webgeek.json

webgeek entering the arena

---

arena/dndagent.json

- **Agent Name:** dndagent
- **Repository Link:** [xSudoNymx/AutoGPT](https://github.com/xSudoNymx/AutoGPT) …

dndagent entering the arena

---

arena/autoai.json

- **Agent Name:** autoai
- **Repository Link:** [maanvithag/AutoGPT](https://github.com/maanvithag/AutoGPT) …

autoai entering the arena

---

arena/CYNO_AGENT.json

- **Agent Name:** CYNO_AGENT
- **Repository Link:** [dr1yl/AutoGPT](https://github.com/dr1yl/AutoGPT)
- …

CYNO_AGENT entering the arena

---

arena/researchGPT.json

- **Agent Name:** researchGPT
- **Repository Link:** [gty3310/AutoGPT](https://github.com/gty3310/AutoGPT) …

researchGPT entering the arena

---

arena/chatgpt_taller.json

- **Agent Name:** chatgpt_taller
- **Repository Link:** [leobusar/AutoGPT](https://github.com/leobusar/AutoGPT) …

chatgpt_taller entering the arena

---

arena/AUTO_GPT_JON001.json

- **Agent Name:** AUTO_GPT_JON001
- **Repository Link:** [Jonobinsoftware/AutoGPT-Tutorial](https://github.com/Jonobinsoftware/AutoGPT-Tutorial)
- **Target Prize:** (Which prize caught …

AUTO_GPT_JON001 entering the arena

---

arena/fst.json

- **Agent Name:** fst
- **Repository Link:** [onewesong/AutoGPT](https://github.com/onewesong/AutoGPT)
- …

fst entering the arena

---

arena/newAgent.json

- **Agent Name:** newAgent
- **Repository Link:** [alexsoshnikov/AutoGPT](https://github.com/alexsoshnikov/AutoGPT) …

newAgent entering the arena

---

arena/cislerk2.json

- **Agent Name:** cislerk2
- **Repository Link:** [cislerk/AutoGPT](https://github.com/cislerk/AutoGPT)
- …

cislerk2 entering the arena

---

arena/aWOL.json

- **Agent Name:** aWOL
- **Repository Link:** [aodrasa/aWOL](https://github.com/aodrasa/aWOL)
- **Why …

aWOL entering the arena

---

arena/xmly.json

- **Agent Name:** xmly
- **Repository Link:** [dongdaoguang/AutoGPT](https://github.com/dongdaoguang/AutoGPT) …

xmly entering the arena

---

arena/babe_perphorator_.json

babe_perphorator_ entering the arena

---

arena/AndersLensway.json

- **Agent Name:** AndersLensway
- **Repository Link:** [4nd3rs/AutoGPT](https://github.com/4nd3rs/AutoGPT) …

AndersLensway entering the arena

---

arena/AutoTDD.json

- **Agent Name:** AutoTDD
- **Repository Link:** [vshneer/AutoTDD](https://github.com/vshneer/AutoTDD)
- …

AutoTDD entering the arena

---

arena/bot01.json

- **Agent Name:** bot01
- **Repository Link:** [Arthur-Heng/AutoGPT](https://github.com/Arthur-Heng/AutoGPT) …

bot01 entering the arena

---

arena/aiaudit.json

aiaudit entering the arena

---

arena/Lab49Agent.json

- **Agent Name:** Lab49Agent
- **Repository Link:** [FutureProofTechnology/AutoGPT](https://github.com/FutureProofTechnology/AutoGPT)
- **Target Prize:** (Which prize caught your eye? …

Lab49Agent entering the arena

---

arena/Lirum.json

- **Agent Name:** Lirum
- **Repository Link:** [rogerioth/AutoGPT](https://github.com/rogerioth/AutoGPT) …

Lirum entering the arena

---

arena/icode.json

- **Agent Name:** icode
- **Repository Link:** [krishnaji/AutoGPT](https://github.com/krishnaji/AutoGPT) …

icode entering the arena

---

arena/ASSISTANT.json

- **Agent Name:** ASSISTANT
- **Repository Link:** [hongzzz/AutoGPT](https://github.com/hongzzz/AutoGPT) …

ASSISTANT entering the arena

---

arena/stockAgent.json

- **Agent Name:** stockAgent
- **Repository Link:** [SnowYoung/StockAgent](https://github.com/SnowYoung/StockAgent) …

stockAgent entering the arena

---

arena/Heisenberg.json

typo Heisenberg.json

---

QUICKSTART.md

I was trying to set up the project and saw a typo. Thought I'd fix it. :)
fixed a typo in QUICKSTART.md

docs: fix typo in QUICKSTART.md

---

QUICKSTART.md

This commit introduces enhancements to the project's documentation, specifically targeted at Windows users who may encounter issues post installing WSL. The added content aims to facilitate a smoother setup experience by providing clear and concise solutions to common problems encountered during the installation process.
These changes are derived from personal experiences and are intended to prevent Windows users from spending additional time troubleshooting issues already resolved, allowing them to have a more consistent development environment setup.
- Instructions on updating WSL for resolving initial setup issues.
- Solutions to fix ‘FileNotFoundError’ or ‘No such file or directory’ errors by addressing line-ending discrepancies between Windows and Unix/Linux systems.
- …

Improved Documentation for Windows Users

---

arena/Pumu2_agent.json

Pumu2_agent entering the arena

---

arena/hello.json

- **Agent Name:** hello
- **Repository Link:** [ldnvnbl/AutoGPT](https://github.com/ldnvnbl/AutoGPT)
- …

hello entering the arena

---

arena/Bagi_agent.json

Bagi_agent entering the arena

---

arena/devagent.json

- **Agent Name:** devagent
- **Repository Link:** [w6m6/kkgpt](https://github.com/w6m6/kkgpt)
- **Why …

devagent entering the arena

---

arena/WYC.json

- **Agent Name:** WYC
- **Repository Link:** [131250208/AutoGPT_YC](https://github.com/131250208/AutoGPT_YC) …

WYC entering the arena

---

arena/UGYUJI.json

- **Agent Name:** UGYUJI
- **Repository Link:** [ugyuji/AutoGPT](https://github.com/ugyuji/AutoGPT)
- …

UGYUJI entering the arena

---

arena/ZJgpt.json

- **Agent Name:** ZJgpt
- **Repository Link:** [jiezhangGt/AutoGPT](https://github.com/jiezhangGt/AutoGPT) …

ZJgpt entering the arena

---

arena/YoudaoAutoGPT.json

- **Agent Name:** YoudaoAutoGPT
- **Repository Link:** [jiezhangGt/AutoGPT](https://github.com/jiezhangGt/AutoGPT) …

YoudaoAutoGPT entering the arena

---

arena/AwareAgent.json

AwareAgent entering the arena

---

arena/MyExample.json

- **Agent Name:** MyExample
- **Repository Link:** [gabenitez/AutoGPT](https://github.com/gabenitez/AutoGPT) …

MyExample entering the arena

---

arena/UniAgent.json

- **Agent Name:** UniAgent
- **Repository Link:** [JovanKanevche/AutoGPT](https://github.com/JovanKanevche/AutoGPT) …

UniAgent entering the arena

---

arena/LAWYER_EMAD.json

LAWYER_EMAD entering the arena

---

arena/woohoo_agent.json

- **Agent Name:** woohoo_agent
- **Repository Link:** [FIresInWind/AutoGPT](https://github.com/FIresInWind/AutoGPT) …

woohoo_agent entering the arena

---

arena/analystgpt.json

- **Agent Name:** analystgpt
- **Repository Link:** [vleonidas/AutoGPT](https://github.com/vleonidas/AutoGPT) …

analystgpt entering the arena

---

arena/kingmitch.json

kingmitch entering the arena

---

arena/akela.json

- **Agent Name:** akela
- **Repository Link:** [SarahGrevy/AutoGPT](https://github.com/SarahGrevy/AutoGPT) …

akela entering the arena

---

arena/stefan.json

- **Agent Name:** stefan
- **Repository Link:** [sutefu23/AutoGPT](https://github.com/sutefu23/AutoGPT)
- …

stefan entering the arena

---

arena/easn.json

- **Agent Name:** easn
- **Repository Link:** [qazwsxdshb/AutoGPT](https://github.com/qazwsxdshb/AutoGPT) …

easn entering the arena

---

arena/AlphaCISO.json

- **Agent Name:** AlphaCISO
- **Repository Link:** [alphaciso/AutoGPT](https://github.com/alphaciso/AutoGPT) …

AlphaCISO entering the arena

---

arena/CCAgent.json

- **Agent Name:** CCAgent
- **Repository Link:** [ccsnow127/AutoGPT](https://github.com/ccsnow127/AutoGPT) …

CCAgent entering the arena

---

arena/business.json

- **Agent Name:** business
- **Repository Link:** [danielfebrero/AutoGPT](https://github.com/danielfebrero/AutoGPT) …

business entering the arena

---

arena/AutoGPT-ariel.json

- **Agent Name:** AutoGPT-ariel
- **Repository Link:** [RedTachyon/AutoGPT](https://github.com/RedTachyon/AutoGPT) …

AutoGPT-ariel entering the arena

---

arena/gaby_agent.json

gaby_agent entering the arena

---

arena/480bot.json

- **Agent Name:** 480bot
- **Repository Link:** [480/AutoGPT](https://github.com/480/AutoGPT)
- **Why …

480bot entering the arena

---

arena/autogpt_hackathon1.json

- **Agent Name:** autogpt_hackathon1
- **Repository Link:** [ThisisHubert/AutoGPT-hackathon](https://github.com/ThisisHubert/AutoGPT-hackathon)
- **Target Prize:** (Which prize caught …

autogpt_hackathon1 entering the arena

---

arena/career-agent.json

- **Agent Name:** career-agent
- **Repository Link:** [asifdotpy/CareerGPT](https://github.com/asifdotpy/CareerGPT) …

career-agent entering the arena

---

arena/autogpt-hackathon2.json

- **Agent Name:** autogpt-hackathon2
- **Repository Link:** [ThisisHubert/AutoGPT-hackathon](https://github.com/ThisisHubert/AutoGPT-hackathon)
- **Target Prize:** (Which prize caught …

autogpt-hackathon2 entering the arena

---

arena/first-agent.json

first-agent entering the arena

---

arena/zaheer.json

- **Agent Name:** zaheer
- **Repository Link:** [zaheerahmad33/AutoGPT](https://github.com/zaheerahmad33/AutoGPT) …

zaheer entering the arena

---

arena/metware.json

- **Agent Name:** metware
- **Repository Link:** [chenxuya/AutoGPT](https://github.com/chenxuya/AutoGPT) …

metware entering the arena

---

arena/miniAgent.json

- **Agent Name:** miniAgent
- **Repository Link:** [bigzz/AutoGPT](https://github.com/bigzz/AutoGPT)
- …

miniAgent entering the arena

---

arena/ccace.json

- **Agent Name:** ccace
- **Repository Link:** [ccsnow127/AutoGPT](https://github.com/ccsnow127/AutoGPT) …

ccace entering the arena

---

arena/MangoAgent-3.json

- **Agent Name:** MangoAgent-3
- **Repository Link:** [stargatejy/MangoAI](https://github.com/stargatejy/MangoAI) …

MangoAgent-3 entering the arena

---

arena/illynet.json

illynet entering the arena

---

arena/chengshu.json

- **Agent Name:** chengshu
- **Repository Link:** [skadai/AutoGPT](https://github.com/skadai/AutoGPT)
- …

chengshu entering the arena

---

arena/ag1.json

- **Agent Name:** ag1
- **Repository Link:** [gensy421/AutoGensy](https://github.com/gensy421/AutoGensy) …

ag1 entering the arena

---

arena/lawk.json

- **Agent Name:** lawk
- **Repository Link:** [xiaolongtuan-yuan/AutoGPT](https://github.com/xiaolongtuan-yuan/AutoGPT) …

lawk entering the arena

---

arena/PAgentAI.json

- **Agent Name:** PAgentAI
- **Repository Link:** [plopez10/GPT](https://github.com/plopez10/GPT)
- **Why …

PAgentAI entering the arena

---

arena/Mira.json

- **Agent Name:** Mira
- **Repository Link:** [enricofranke/EnricoAssistant](https://github.com/enricofranke/EnricoAssistant) …

Mira entering the arena

---

arena/MyExampleAgent.json

- **Agent Name:** MyExampleAgent
- **Repository Link:** [moizsajid/AutoGPT](https://github.com/moizsajid/AutoGPT) …

MyExampleAgent entering the arena

---

arena/MyAgent.json

- **Agent Name:** MyAgent
- **Repository Link:** [AgentService/AutoGPT](https://github.com/AgentService/AutoGPT) …

MyAgent entering the arena

---

arena/SmartAgent.json

- **Agent Name:** SmartAgent
- **Repository Link:** [AgentService/AutoGPT](https://github.com/AgentService/AutoGPT) …

SmartAgent entering the arena

---

arena/zlipknot_test_agent_4.json

zlipknot_test_agent_4 entering the arena

---

arena/zlipknot_1.json

zlipknot_1 entering the arena

---

arena/IncredibubbleTea.json

- **Agent Name:** IncredibubbleTea
- **Repository Link:** [mariepop13/AutoGPT](https://github.com/mariepop13/AutoGPT) …

IncredibubbleTea entering the arena

---

arena/actor_tester.json

- **Agent Name:** actor_tester
- **Repository Link:** [calmglow/mbtiagent](https://github.com/calmglow/mbtiagent) …

actor_tester entering the arena

---

arena/minister_agent.json

- **Agent Name:** minister_agent
- **Repository Link:** [miandai/AutoGPT](https://github.com/miandai/AutoGPT) …

minister_agent entering the arena

---

arena/justwondering.json

- **Agent Name:** justwondering
- **Repository Link:** [tbxy09/JustWondering](https://github.com/tbxy09/JustWondering) …

justwondering entering the arena

---

arena/ZoeyGPT.json

- **Agent Name:** ZoeyGPT
- **Repository Link:** [carylaw/FatGPT](https://github.com/carylaw/FatGPT)
- …

ZoeyGPT entering the arena

---

arena/FcsummerGPT.json

- **Agent Name:** FcsummerGPT
- **Repository Link:** [fbk111/FcsummerGPT](https://github.com/fbk111/FcsummerGPT) …

FcsummerGPT entering the arena

---

arena/zcb.json

- **Agent Name:** zcb
- **Repository Link:** [asasasheshou/AutoGPT](https://github.com/asasasheshou/AutoGPT) …

zcb entering the arena

---

arena/MoTS.json

MoTS entering the arena

---

arena/ltzAgent.json

- **Agent Name:** ltzAgent
- **Repository Link:** [ltzmaxwell/AutoGPT](https://github.com/ltzmaxwell/AutoGPT) …

ltzAgent entering the arena

---

arena/beyond.json

- **Agent Name:** beyond
- **Repository Link:** [sn0wdown/AutoGPT](https://github.com/sn0wdown/AutoGPT)
- …

beyond entering the arena

---

arena/LegalAgent.json

- **Agent Name:** LegalAgent
- **Repository Link:** [gengrui1983/LegalGPT](https://github.com/gengrui1983/LegalGPT) …

LegalAgent entering the arena

---

arena/mygent.json

- **Agent Name:** mygent
- **Repository Link:** [prashanthi-instalily/AutoGPT](https://github.com/prashanthi-instalily/AutoGPT) …

mygent entering the arena

---

arena/linggong.json

- **Agent Name:** linggong
- **Repository Link:** [linggong2023/AutoGPT](https://github.com/linggong2023/AutoGPT) …

linggong entering the arena

---

arena/xq_agent.json

- **Agent Name:** xq_agent
- **Repository Link:** [emptykid/AutoGPT](https://github.com/emptykid/AutoGPT) …

xq_agent entering the arena

---

arena/liuzh.json

- **Agent Name:** liuzh
- **Repository Link:** [Hanzhang-lang/AutoGPT_zh](https://github.com/Hanzhang-lang/AutoGPT_zh) …

liuzh entering the arena

---

arena/MangoAI.json

- **Agent Name:** MangoAI
- **Repository Link:** [stargatejy/MangoAI](https://github.com/stargatejy/MangoAI) …

MangoAI entering the arena

---

arena/project_review.json

- **Agent Name:** project_review
- **Repository Link:** [oneforce/AutoGPT](https://github.com/oneforce/AutoGPT) …

project_review entering the arena

---

arena/Zoidberg.json

- **Agent Name:** Zoidberg
- **Repository Link:** [KapitanFernand/Zoidberg](https://github.com/KapitanFernand/Zoidberg) …

Zoidberg entering the arena

---

arena/agentgpt.json

agentgpt entering the arena

---

arena/avengaGPT.json

- **Agent Name:** avengaGPT
- **Repository Link:** [sebabetz/AutoGPT](https://github.com/sebabetz/AutoGPT) …

avengaGPT entering the arena

---

arena/set.json

- **Agent Name:** set
- **Repository Link:** [victorrica/AutoGPT](https://github.com/victorrica/AutoGPT) …

set entering the arena

---

arena/cssupdater.json

- **Agent Name:** cssupdater
- **Repository Link:** [mplummeridge/AutoGPT](https://github.com/mplummeridge/AutoGPT) …

cssupdater entering the arena

---

arena/test1.json

- **Agent Name:** test1
- **Repository Link:** [mplummeridge/AutoGPT](https://github.com/mplummeridge/AutoGPT) …

test1 entering the arena

---

arena/victor2-0.json

- **Agent Name:** victor2-0
- **Repository Link:** [victorleduc/AutoGPT](https://github.com/victorleduc/AutoGPT) …

victor2-0 entering the arena

---

arena/Pelle.json

- **Agent Name:** Pelle
- **Repository Link:** [pilotniq/AutoGPT](https://github.com/pilotniq/AutoGPT)
- …

Pelle entering the arena

---

arena/QuantumQuill.json

- **Agent Name:** QuantumQuill
- **Repository Link:** [dleidisch/AutoAgent](https://github.com/dleidisch/AutoAgent) …

QuantumQuill entering the arena

---

arena/ra1.json

- **Agent Name:** ra1
- **Repository Link:** [aramfaghfouri/AutoGPT](https://github.com/aramfaghfouri/AutoGPT) …

ra1 entering the arena

---

arena/ra.json

- **Agent Name:** ra
- **Repository Link:** [aramfaghfouri/AutoGPT](https://github.com/aramfaghfouri/AutoGPT) …

ra entering the arena

---

arena/research_analyst.json

- **Agent Name:** research_analyst
- **Repository Link:** [aramfaghfouri/AutoGPT](https://github.com/aramfaghfouri/AutoGPT) …

research_analyst entering the arena

---

arena/DE.json

- **Agent Name:** DE
- **Repository Link:** [wic0144/AutoGPT](https://github.com/wic0144/AutoGPT)
- **Why …

DE entering the arena

---

arena/ai_assistant.json

- **Agent Name:** ai_assistant
- **Repository Link:** [xhjxhj001/AutoGPT](https://github.com/xhjxhj001/AutoGPT) …

ai_assistant entering the arena

---

arena/Mary.json

Add Mary.json

---

arena/zczc.json

- **Agent Name:** zczc
- **Repository Link:** [Howard-Cheung/AutoGPT](https://github.com/Howard-Cheung/AutoGPT) …

zczc entering the arena

---

arena/illyx1.json

illyx1 entering the arena

---

arena/illynetV2.json

illynetV2 entering the arena

---

arena/AutoGenius.json

- **Agent Name:** AutoGenius
- **Repository Link:** [JasonDRZ/AutoGPT](https://github.com/JasonDRZ/AutoGPT) …

AutoGenius entering the arena

---

arena/WRITER.json

- **Agent Name:** WRITER
- **Repository Link:** [ezirmusitua/AutoGPT](https://github.com/ezirmusitua/AutoGPT) …

WRITER entering the arena

---

arena/aixiaoxin.json

- **Agent Name:** aixiaoxin
- **Repository Link:** [aixiaoxin123/AutoGPT](https://github.com/aixiaoxin123/AutoGPT) …

aixiaoxin entering the arena

---

arena/Drench.json

- **Agent Name:** Drench
- **Repository Link:** [MohamedBasueny/AutoGPT-Drench](https://github.com/MohamedBasueny/AutoGPT-Drench) …

Drench entering the arena

---

arena/autogpt_warlock.json

- **Agent Name:** autogpt_warlock
- **Repository Link:** [warlockee/AutoGPT-wl](https://github.com/warlockee/AutoGPT-wl) …

autogpt_warlock entering the arena

---

arena/AwareAgent.json

Arena submission aware agent

---

arena/test-tpk.json

- **Agent Name:** test-tpk
- **Repository Link:** [seeseesky/AutoGPT](https://github.com/seeseesky/AutoGPT) …

test-tpk entering the arena

---

arena/hodri.json

- **Agent Name:** hodri
- **Repository Link:** [bilisim1995/AutoGPT](https://github.com/bilisim1995/AutoGPT) …

hodri entering the arena

---

arena/gpt_for_beans.json

gpt_for_beans entering the arena

---

arena/CONNECTBOT.json

CONNECTBOT entering the arena

---

arena/wyjagent.json

- **Agent Name:** wyjagent
- **Repository Link:** [wangyijunlyy/AutoGPT](https://github.com/wangyijunlyy/AutoGPT) …

wyjagent entering the arena

---

arena/happy_guy.json

- **Agent Name:** happy_guy
- **Repository Link:** [jianglonghui/AutoGPT](https://github.com/jianglonghui/AutoGPT) …

happy_guy entering the arena

---

arena/bait.json

- **Agent Name:** bait
- **Repository Link:** [a0balaton/AutoGPT](https://github.com/a0balaton/AutoGPT)
- …

bait entering the arena

---

arena/TeslaBot.json

- **Agent Name:** TeslaBot
- **Repository Link:** [momokrunic/AutoGPT](https://github.com/momokrunic/AutoGPT) …

TeslaBot entering the arena

---

arena/GPTTest.json

GPTTest entering the arena

---

arena/MyFistAgent.json

- **Agent Name:** MyFistAgent
- **Repository Link:** [eslam-fakhry/AutoGPT](https://github.com/eslam-fakhry/AutoGPT) …

MyFistAgent entering the arena

---

arena/sgpt.json

- **Agent Name:** sgpt
- **Repository Link:** [ya5has/sgpt](https://github.com/ya5has/sgpt)
- **Why this …

sgpt entering the arena

---

cli.py

Improvement of the regular expression for more clear code
Changes in the regular expression pattern

Improvement of the regular expression

---

arena/AGENT_GORDON.json

- **Agent Name:** AGENT_GORDON
- **Repository Link:** [filipjakubowski/AutoGPT](https://github.com/filipjakubowski/AutoGPT) …

AGENT_GORDON entering the arena

---

arena/AI.json

- **Agent Name:** AI
- **Repository Link:** [QingquanBao/AutoGPT](https://github.com/QingquanBao/AutoGPT) …

AI entering the arena

---

arena/AKBAgent.json

Add AKBAgent.json for benchmarking

---

arena/medical-agent.json

- **Agent Name:** medical-agent
- **Repository Link:** [daviddhc20120601/AutoGPT](https://github.com/daviddhc20120601/AutoGPT) …

medical-agent entering the arena

---

arena/CodeAutoGPT.json

- **Agent Name:** CodeAutoGPT
- **Repository Link:** [hugomastromauro/AutoGPT](https://github.com/hugomastromauro/AutoGPT) …

CodeAutoGPT entering the arena

---

arena/davidtest1.json

- **Agent Name:** davidtest1
- **Repository Link:** [ningzero/AutoGPTTest](https://github.com/ningzero/AutoGPTTest) …

davidtest1 entering the arena

---

arena/MarketResearcherEduRob.json

- **Agent Name:** MarketResearcherEduRob
- **Repository Link:** [fzoric8/AutoGPT](https://github.com/fzoric8/AutoGPT) …

MarketResearcherEduRob entering the arena

---

arena/my_gpt.json

- **Agent Name:** my_gpt
- **Repository Link:** [dawnchen123/AutoGPT](https://github.com/dawnchen123/AutoGPT) …

my_gpt entering the arena

---

arena/tiffGPT.json

- **Agent Name:** tiffGPT
- **Repository Link:** [darkcyber-ninja/AutoGPT](https://github.com/darkcyber-ninja/AutoGPT) …

tiffGPT entering the arena

---

arena/ChrisGPT.json

- **Agent Name:** ChrisGPT
- **Repository Link:** [darkcyber-ninja/AutoGPT](https://github.com/darkcyber-ninja/AutoGPT) …

ChrisGPT entering the arena

---

arena/xtest.json

- **Agent Name:** xtest
- **Repository Link:** [popperxu/AutoGPT](https://github.com/popperxu/AutoGPT)
- …

xtest entering the arena

---

arena/TEST_TPK.json

- **Agent Name:** TEST_TPK
- **Repository Link:** [seeseesky/AutoGPT](https://github.com/seeseesky/AutoGPT) …

TEST_TPK entering the arena

---

arena/TestLbAgent.json

- **Agent Name:** TestLbAgent
- **Repository Link:** [BiaoLiu2017/AutoGPT](https://github.com/BiaoLiu2017/AutoGPT) …

TestLbAgent entering the arena

---

arena/TheAgent.json

- **Agent Name:** TheAgent
- **Repository Link:** [BiaoLiu2017/AutoGPT](https://github.com/BiaoLiu2017/AutoGPT) …

TheAgent entering the arena

---

arena/FLASH.json

- **Agent Name:** FLASH
- **Repository Link:** [flashdumper/AutoGPT](https://github.com/flashdumper/AutoGPT) …

FLASH entering the arena

---

arena/project_assitant.json
arena/project_master.json
arena/project_master2.json

Arena submission project master2

---

arena/Derpmaster.json

- **Agent Name:** Derpmaster
- **Repository Link:** [schumacher-m/Derpmaster](https://github.com/schumacher-m/Derpmaster) …

Derpmaster entering the arena

---

arena/SkorkobaniecAgent.json

- **Agent Name:** SkorkobaniecAgent
- **Repository Link:** [RafalSkorka/AutoGPT](https://github.com/RafalSkorka/AutoGPT) …

SkorkobaniecAgent entering the arena

---

arena/NanAutoGPT.json

- **Agent Name:** NanAutoGPT
- **Repository Link:** [open-nan/NanAutoGPT](https://github.com/open-nan/NanAutoGPT) …

NanAutoGPT entering the arena

---

arena/LbAgent.json

- **Agent Name:** LbAgent
- **Repository Link:** [BiaoLiu2017/AutoGPT](https://github.com/BiaoLiu2017/AutoGPT) …

LbAgent entering the arena

---

arena/Jean-Michel.json

- **Agent Name:** Jean-Michel
- **Repository Link:** [Yanniswein/Jean-Michel](https://github.com/Yanniswein/Jean-Michel) …

Jean-Michel entering the arena

---

arena/houxe.json

- **Agent Name:** houxe
- **Repository Link:** [jiarung/AutoGPTTest](https://github.com/jiarung/AutoGPTTest) …

houxe entering the arena

---

arena/CES-GPT.json

- **Agent Name:** CES-GPT
- **Repository Link:** [ces-sonnguyen/CES-GPT](https://github.com/ces-sonnguyen/CES-GPT) …

CES-GPT entering the arena

---

arena/autocoder.json

- **Agent Name:** autocoder
- **Repository Link:** [mtx-light/AutoGPT](https://github.com/mtx-light/AutoGPT) …

autocoder entering the arena

---

arena/coder_first.json

- **Agent Name:** coder_first
- **Repository Link:** [mtx-light/AutoGPT](https://github.com/mtx-light/AutoGPT) …

coder_first entering the arena

---

arena/ArtistManagerGPT.json

- **Agent Name:** ArtistManagerGPT
- **Repository Link:** [AmahAjavon/AutoGPT](https://github.com/AmahAjavon/AutoGPT) …

ArtistManagerGPT entering the arena

---

arena/agentSmith.json

- **Agent Name:** agentSmith
- **Repository Link:** [Nameless8243/AgentSmith](https://github.com/Nameless8243/AgentSmith) …

agentSmith entering the arena

---

arena/agent2.json

- **Agent Name:** agent2
- **Repository Link:** [lukadumancic/AutoGPT](https://github.com/lukadumancic/AutoGPT) …

agent2 entering the arena

---

arena/N.json

- **Agent Name:** N
- **Repository Link:** [gentaag/AutoGPT](https://github.com/gentaag/AutoGPT)
- **Why …

N entering the arena

---

arena/YOU.json

- **Agent Name:** YOU
- **Repository Link:** [gentaag/AutoGPT](https://github.com/gentaag/AutoGPT)
- …

YOU entering the arena

---

arena/podcast_agent.json

- **Agent Name:** podcast_agent
- **Repository Link:** [aliumujib/AutoGPT](https://github.com/aliumujib/AutoGPT) …

podcast_agent entering the arena

---

arena/TMarafon.json

- **Agent Name:** TMarafon
- **Team Members:** Thiago Marafon
- **Repository Link:** [TMarafon/AutoGPT](https://github.com/TMarafon/AutoGPT)
- **Starting Point:** Building from scratch.
- **Preliminary Ideas:** No idea for know. Just following the tutorial to learn about agents.
- **Target Prize:** Prize?
- **Why this Prize:** Just having fun.
- **Video Link:** (If you'd like, share a short video where you introduce your team and talk about your project. We'd love to see your enthusiastic faces!)
- …

TMarafon entering the arena

---

arena/SaveAsPDF2.json

- **Agent Name:** SaveAsPDF2
- **Repository Link:** [LFarmbot/AutoFarm](https://github.com/LFarmbot/AutoFarm) …

SaveAsPDF2 entering the arena

---

arena/Orange.json

- **Agent Name:** Orange
- **Repository Link:** [lewispeel/AutoGPT](https://github.com/lewispeel/AutoGPT) …

Orange entering the arena

---

arena/WarlockAgent.json

- **Agent Name:** WarlockAgent
- **Repository Link:** [warlockee/AutoGPT-wl](https://github.com/warlockee/AutoGPT-wl) …

WarlockAgent entering the arena

---

arena/Q.json

- **Agent Name:** Q
- **Repository Link:** [CopsGit/AutoGPT](https://github.com/CopsGit/AutoGPT)
- **Why …

Q entering the arena

---

arena/MangoAgent-4.json

- **Agent Name:** MangoAgent-4
- **Repository Link:** [stargatejy/MangoAI](https://github.com/stargatejy/MangoAI) …

MangoAgent-4 entering the arena

---

arena/bingoTesting.json

- **Agent Name:** bingoTesting
- **Repository Link:** [bingotyty/AutoGPT](https://github.com/bingotyty/AutoGPT) …

bingoTesting entering the arena

---

arena/qinghu3.json

qinghu3 entering the arena

---

arena/Ahmad.json

Ahmad entering the arena

---

arena/AGENT_JARVIS.json

- **Agent Name:** AGENT_JARVIS
- **Repository Link:** [filipjakubowski/AutoGPT](https://github.com/filipjakubowski/AutoGPT) …

AGENT_JARVIS entering the arena

---

arena/Susan.json

- **Agent Name:** Susan
- **Team Members:** Craig Constable
- **Repository Link:** [CodeZeno/Susan](https://github.com/CodeZeno/Susan)
- **Starting Point:** From scratch
- **Preliminary Ideas:** Looking to create an agent that can take the mental load off running a family. I want the agent to be able to communicate via various channels like email, Google Chat, possibly voice through Siri. I want it to manage schedules in a shared family calendar as well as private calendars for each member of the family. …

Susan entering the arena

---

arena/songyalei.json

- **Agent Name:** songyalei
- **Repository Link:** [songyalei/AutoGPT](https://github.com/songyalei/AutoGPT) …

songyalei entering the arena

---

frontend/README.md

Add a note for users on linux with chromium for building the frontend file
Otherwise, it will not build
https://asciinema.org/a/621783
Flutter needs to know where a compatible browser is for those that use chromium or another chrome derivative like vivaldi on linux 
Documentation

Update frontend readme doc

---

autogpts/forge/forge/sdk/routes/agent_protocol.py

Fixed import location of models
Had this issue locally after updating to master:
```shell
$ ./run agent start forge   
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/tom/Workspaces/aisummit/agent/AutoGPT/autogpts/forge/forge/__main__.py", line 6, in <module>
import forge.sdk.forge_log
File "/Users/tom/Workspaces/aisummit/agent/AutoGPT/autogpts/forge/forge/sdk/__init__.py", line 5, in <module>
from .agent import Agent
File "/Users/tom/Workspaces/aisummit/agent/AutoGPT/autogpts/forge/forge/sdk/agent.py", line 16, in <module>
from .routes.agent_protocol import base_router
File …
```

Update import path in agent_protocol.py

---

autogpts/autogpt/poetry.lock
autogpts/autogpt/pyproject.toml

- Added psycopg2-binary version 2.9.9 to the dependencies in pyproject.toml
- Updated the poetry.lock file with the new package information
This is required to use AutoGPT with PostgreSQL as a backend
Adds a dependency on [psycopg2](https://pypi.org/project/psycopg2/)

Add dependencies required to use PostgreSQL

---

autogpts/forge/forge/actions/finish.py

fix(forge): no module named 'sdk'

---

docs/content/forge/get-started.md

docs: Redirect AutoGPT users from Forge tutorial with warning

---

autogpts/autogpt/autogpt/commands/web_search.py
autogpts/autogpt/pyproject.toml
autogpts/forge/forge/actions/web/web_search.py
autogpts/forge/pyproject.toml

Updates `web_search` command for both `autogpt` and `forge` to adjust for breaking change in v5 of `duckduckgo_search`

fix(agent, forge): Conform `web_search.py` to `duckduckgo_search` v5

---

autogpts/autogpt/autogpt/app/main.py

Fix https://github.com/Significant-Gravitas/AutoGPT/commit/cf00c33f907b12e48218404f849c11beb568001b

fix(agent): Logging hotfix

---

autogpts/autogpt/autogpt/config/config.py

Try fixing https://github.com/Significant-Gravitas/AutoGPT/issues/7090
Change the `key_pattern` to support OpenAI Project API

fix(agent): Support OpenAI Project API keys

---

autogpts/autogpt/autogpt/agents/__init__.py
autogpts/autogpt/autogpt/agents/agent.py
autogpts/autogpt/autogpt/agents/base.py
autogpts/autogpt/autogpt/agents/features/watchdog.py
autogpts/autogpt/autogpt/agents/prompt_strategies/one_shot.py
autogpts/autogpt/autogpt/agents/protocols.py
autogpts/autogpt/autogpt/app/agent_protocol_server.py
autogpts/autogpt/autogpt/app/main.py
autogpts/autogpt/autogpt/components/event_history.py
autogpts/autogpt/autogpt/core/resource/model_providers/schema.py
autogpts/autogpt/autogpt/models/action_history.py
autogpts/autogpt/autogpt/models/utils.py

Make prompting & parsing more straightforward and improve typing throughout the application by using pydantic models for the agent's cycle output.
This is partially the result of work on XML support; the rest is to clean up connected code.
* Introduce `BaseAgentActionProposal`, `OneShotAgentActionProposal`, and `AssistantThoughts` models to replace `ThoughtProcessResponse`, `DEFAULT_RESPONSE_SCHEMA`
* Refactor and clean up code because now we don't need to do as much type checking everywhere
* Tweak `OneShot` response format instruction
Granular:
* `autogpt.agents.prompt_strategies.one_shot`
* Replace ThoughtProcessResponse`, `DEFAULT_RESPONSE_SCHEMA` and parsing logic by `AssistantThoughts` and `OneShotAgentActionProposal`
* (TANGENTIAL) Move response format instruction into main system …

refactor(agent)!: Use Pydantic models for `Agent` process output

---

.github/workflows/autogpts-ci.yml
cli.py

- Add a special case for cli to handle `autogpt` and `forge` agent
- Remove `forge` agent from smoke test ci

fix(ci): Fix cli and CI

---

frontend/lib/models/step_request_body.dart
frontend/lib/models/task_request_body.dart
frontend/lib/viewmodels/chat_viewmodel.dart
frontend/lib/views/chat/chat_view.dart

Frontend broke in #7171 because of changes to the request models in `forge.agent_protocol`.
Blocks #7196
* Sync changes made in `forge.agent_protocol.models` to frontend

fix(frontend): Sync models with `forge.agent_protocol`

---

README.md

___
Documentation
___
- Added a description of AutoGPT as a generalist LLM-based AI agent that can autonomously accomplish minor tasks.
- Included examples of tasks AutoGPT can perform, such as summarizing research papers, writing marketing content, and blogging about AI news.
- Updated the mission statement to align with the new description and examples.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add description and examples of AutoGPT to README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Added a description of AutoGPT as a generalist LLM-based AI agent.<br> <li> Included …

feat(docs): add example uses and description of autogpt to the readme

---

rnd/autogpt_server/autogpt_server/server/server.py

The server tests throw a warning from fastapi
swaps from an event system to lifecycle hook for fast api
___
___
- Replaced the event-based startup and shutdown hooks in the FastAPI application with an `asynccontextmanager` to manage the application lifespan.
- Ensured database connections are properly managed during the application lifecycle using the new lifespan context manager.
- Removed redundant event-based hooks for connecting and disconnecting the database.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>server.py</strong><dd><code>Replace event hooks with async lifespan context manager in FastAPI</code></dd></summary>
<hr> …

chore(rnd): Fix warning during server tests

---

autogpt/autogpt/app/main.py

When an agent is resumed from a mid-cycle state (having made a proposal but not executed it yet), `agent.propose_action()` is called and it crashes the application because `current_episode.action` is already set.
If `current_episode.action` is set but `current_episode.result` is not, use `action_proposal = current_episode.action` instead of `action_proposal = agent.propose_action()`

fix(agent): Fix resumption from mid-cycle state in CLI mode

---

autogpt/poetry.lock
autogpt/pyproject.toml
benchmark/poetry.lock
benchmark/pyproject.toml
forge/poetry.lock
forge/pyproject.toml

* Remove unused dependencies
* Move dependencies for moved code from `autogpt` to `forge`
* Loosen dependency for `uvicorn` to improve compatibility

chore(agent, forge, benchmark): Clean up dependencies

---

README.md

fix readme (broken link)
___
Documentation
___
- Fixed a broken link in the README file.
- Updated the Quickstart link to point to `FORGE-QUICKSTART.md`.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Fix broken link in README Quickstart section</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Fixed a broken link in the Quickstart section.<br> <li> Updated the link to point to <code>FORGE-QUICKSTART.md</code>.<br>
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7293/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8 …

fix readme (broken link)

---

forge/forge/llm/providers/anthropic.py

Closes https://github.com/Significant-Gravitas/AutoGPT/issues/7241
___
Enhancement
___
- Added support for the new `CLAUDE3_5_SONNET_v1` model in the `AnthropicModelName` enum.
- Updated the `ANTHROPIC_CHAT_MODELS` dictionary to include the new model with its respective attributes such as `prompt_token_cost`, `completion_token_cost`, `max_tokens`, and `has_function_call_api`.
___
<tr>
<td>
<details>
<summary><strong>anthropic.py</strong><dd><code>Add support for Claude 3.5 Sonnet model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

feat: Add support for Claude 3.5 Sonnet

---

rnd/autogpt_builder/src/app/page.tsx
rnd/autogpt_builder/src/components/Flow.tsx

* Needed for the "Edit flow" button of #7335
- Add `flowID` query parameter
- Add logic to load a flow from the server into the builder

feat(autogpt_builder): Enable loading an existing flow

---

rnd/autogpt_server/README.md
rnd/autogpt_server/autogpt_server/cli.py

When developing the server we need to have test data to work with. This PR adds a command that does this for us.
Added a populate-db command that adds a graph, graph execution and a schedule to run the graph every 5 mins.
___
Enhancement, Documentation
___
- Added a new `populate_db` command to the CLI to create test data including a graph, its execution, and a schedule.
- Updated the README with instructions on how to use the new `populate_db` command.
___
<tr>
<td>
<details>
<summary><strong>cli.py</strong><dd><code>Add `populate_db` command to CLI for creating test data</code>&nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/cli.py …

feast(agent server) Add populate db command

---

rnd/autogpt_server/autogpt_server/blocks/reddit.py
rnd/autogpt_server/autogpt_server/data/execution.py
rnd/autogpt_server/test/server/test_con_manager.py

Timestamps seem to be using different timezones. Fixed it by forcing all timestamps to be in UTC
___
Bug fix
___
- Fixed inconsistent timestamps by ensuring all timestamps use UTC in the `update_execution_status` function.
- Imported `timezone` from `datetime` to facilitate the change.
___
<tr>
<td>
<details>
<summary><strong>execution.py</strong><dd><code>Ensure all timestamps use UTC in execution status updates</code></dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/data/execution.py
<li>Imported <code>timezone</code> from <code>datetime</code>.<br> <li> Changed <code>datetime.now()</code> to <code>datetime.now(tz=timezone.utc)</code> to ensure …

fix(autogpt_server): Changed inconstant timestamps to all use UTC

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/ModalComponent.tsx
rnd/autogpt_builder/src/components/customnode.css
rnd/autogpt_builder/src/components/flow.css
rnd/autogpt_builder/src/components/modal.css
rnd/autogpt_builder/src/components/ui/textarea.tsx

worked on the node layout, added truncation to hard coded text input, continued to change over to shadcn
This is to address [7331](https://github.com/Significant-Gravitas/AutoGPT/issues/7331)

feat(agent_builder):  Updates to Builder GUI + Nodes

---

rnd/autogpt_server/test/executor/test_manager.py

___
Bug fix, Tests
___
- Fixed an issue in the `is_execution_completed` function where it did not correctly verify if all executions were completed.
- Added a condition to check that all executions have a status of `COMPLETED` before returning true.
- Ensured the test manager's queue is empty and the number of executions is exactly four.
___
<tr>
<td>
<details>
<summary><strong>test_manager.py</strong><dd><code>Fix execution completion check in test_manager.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/test/executor/test_manager.py
<li>Added a check to ensure all executions have a status of …

fix(agent_server): Fix async issue with executor integration test

---

rnd/autogpt_server/autogpt_server/executor/manager.py

`get_service_client` is expensive and should only be called once per process lifetime.
Avoid repeated call of `get_service_client` within on `execute_node` function during the block execution.
___
Enhancement, Bug fix
___
- Improved error handling in `get_execution_result` by changing `find_first_or_raise` to `find_first` and raising `ValueError` if execution is not found.
- Refactored import statements in `executor/manager.py` for better readability.
- Introduced `get_agent_server_client` function to streamline client retrieval.
- Adjusted code formatting and indentation for consistency.
- Enhanced error handling and logging in `executor/manager.py`.
___ …

fix(rnd): Avoid expensive call of get_service_client on block execution

---

rnd/autogpt_builder/src/components/CustomNode.tsx

Removing submit button, it was used only for dev/debug purposes. No longer needed
Removed the Submit Button from CustomNode.tsx
___
Enhancement
___
- Removed the `Submit` button from the `CustomNode` component as it was only used for development and debugging purposes.
- Deleted the `handleSubmit` function which was associated with the `Submit` button.
___
<tr>
<td>
<details>
<summary><strong>CustomNode.tsx</strong><dd><code>Remove submit button and related function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_builder/src/components/CustomNode.tsx …

feat(autogpt_builder) Remove submit button

---

rnd/autogpt_server/README.md

Fix Auto GPT server `Running The Server` doc
Fix Auto GPT server `Running The Server` doc

fix(doc): Fix Auto GPT server `Running The Server` doc

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/customnode.css

Data was not being persisted properly, so connections and inputs were going missing
- Added a unique to map backend nodes and frontend nodes (block id plus exact position)
- Added failed animation
- Added reset to neutral colours
___
Enhancement, Bug fix
___
- Added 'failed' status handling in CustomNode component.
- Improved node mapping and status handling in Flow component by adding 'backend_id' and using unique keys.
- Added CSS animations and transitions for node statuses, including a new 'failed' status.
___
<tr>
<td>
<details>
<summary><strong>CustomNode.tsx</strong><dd><code>Add 'failed' status handling in CustomNode component</code>&nbsp; &nbsp; …

feat(agpt_builder) Fix data persistance on agent execution

---

rnd/autogpt_builder/src/lib/autogpt_server_api.ts

fix to make monitor use the url in the env file

fix to make monitor use env

---

rnd/autogpt_builder/src/components/CustomNode.tsx

add button for showing/hiding optional inputs in nodes

feat(builder): add button for showing/hiding optional inputs

---

rnd/autogpt_builder/src/components/customnode.css

Tweak
___
- Changed the animation direction to `alternate` for smoother transitions in the `running`, `completed`, and `failed` classes.
- Updated the animation duration for the `running`, `completed`, and `failed` classes from 1s to 0.5s to account for the increased time to complete the full "ping-pong" animation.
___
<tr>
<td>
<details>
<summary><strong>customnode.css</strong><dd><code>Update animation timing and direction for status classes</code>&nbsp; </dd></summary>
<hr>
rnd/autogpt_builder/src/components/customnode.css
<li>Updated animation duration for <code>running</code>, <code>completed</code>, and <code>failed</code> classes <br>from 1s to …

chore(rnd): Update animation direction for customnode.css to "ping-pong"

---

rnd/autogpt_builder/src/app/layout.tsx
rnd/autogpt_builder/src/app/monitor/page.tsx

* Sequel to #7335
* Part 2 of implementing #7304
* Resolves #7378
* duration
* ~~cost~~ not currently implemented
* chart?
- Improve responsive grid layout
- Remove `container` class from `<main>` to utilize full screen width
- Improve detail views & add view for run details
- Make flow run list entries selectable
- Create `FlowInfo` and `FlowRunInfo` components
- Improve layout of `FlowRunsStats`
- Improve ScrollableLegend spacing & styling
- Hide scroll bar of scrollable legend
- Center legend items if there is space left
- Round icons
- Vertically align icons with labels
- FIX: Add condition to not display legend items for series with `legendType="none"`
- Add periodic 5s refresh of non-terminal flow run statuses
- Split off `refreshFlowRuns(flowID)` from `fetchFlowsAndRuns()`
- Add …

feat(autogpt_builder): Monitor page v0.2

---

docs/content/server/new_nodes.md
docs/mkdocs.yml

___
Documentation
___
- Added a new guide for creating nodes in the AutoGPT Agent Server, including detailed steps, code examples, and best practices.
- Updated the documentation sidebar to include a link to the new guide under the Server section.
___
<tr>
<td>
<details>
<summary><strong>new_nodes.md</strong><dd><code>Add guide for creating new nodes in AutoGPT Agent Server</code>&nbsp; </dd></summary>
<hr>
docs/content/server/new_nodes.md
<li>Added a comprehensive guide for creating new nodes in the AutoGPT <br>Agent Server.<br> <li> Included detailed steps and code examples for node creation.<br> <li> Provided information on input and output schemas, …

feat(docs): add server new node docs

---

rnd/autogpt_server/autogpt_server/blocks/wikipedia.py

Made changes requested by @majdyz and now it passes the tests

feat(autogpt_builder): Fixes to wikipedia block

---

rnd/autogpt_builder/src/app/monitor/page.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/lib/autogpt_server_api.ts

* Resolves #7467
* Blocks #7466
- Abstract request implementation out of individual endpoints
- Rename Flow -> Graph (in type, method, and variable names)

refactor(builder): Clean up `AutoGPTServerAPI` implementation

---

rnd/autogpt_builder/package.json
rnd/autogpt_builder/src/app/build/page.tsx
rnd/autogpt_builder/src/app/monitor/page.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/agent-import-form.tsx
rnd/autogpt_builder/src/components/ui/dialog.tsx
rnd/autogpt_builder/src/components/ui/dropdown-menu.tsx
rnd/autogpt_builder/src/components/ui/form.tsx
rnd/autogpt_builder/src/components/ui/input.tsx
rnd/autogpt_builder/src/components/ui/label.tsx
rnd/autogpt_builder/src/components/ui/switch.tsx
rnd/autogpt_builder/src/lib/autogpt_server_api.ts
rnd/autogpt_builder/src/lib/utils.ts
rnd/autogpt_builder/yarn.lock
rnd/autogpt_server/autogpt_server/data/graph.py

- #7444 (stage 1)
- Add export button to Agent Info viewer
- Add `exportAsJSONFile(..)` function to lib/utils.ts
- Add "Create" button + menu to Agent List
- Create `AgentImportForm` component and put it in a `Dialog`
- Support saving/editing Templates
- Add `templateID` query parameter to `/build`
- Use `templateID` query parameter in `AgentImportForm` redirect if imported as template
- Make `FlowEditor` suitable for saving/editing templates
- Add `template` (boolean) parameter to `FlowEditor` component
- Add conditions to all `createGraph` or `updateGraph` calls, to use `createTemplate`/`updateTemplate` if applicable
- Add "Save as Template" button, visible if the graph is new (unsaved)
- Hide "Save & Run Agent" button when editing a template
- fix inner alignment of `<Input …

feat(builder): Importing/exporting Agents and Templates

---

rnd/autogpt_server/autogpt_server/blocks/llm.py

Add support for the new `GPT-4o-mini` model in LLM block

feat(block): Add support for GPT-4O Mini model in LLM block

---

rnd/autogpt_builder/src/components/CustomNode.tsx

Removes unnecessary node output heading in CustomNode component

tweak(Builder): Remove unnecessary node output heading in CustomNode component

---

rnd/autogpt_server/autogpt_server/blocks/create_medium_post.py
rnd/autogpt_server/autogpt_server/blocks/search.py
rnd/autogpt_server/autogpt_server/data/model.py
rnd/autogpt_server/autogpt_server/util/settings.py

The linter fails because someone hasn't been waiting for it to pass
Fixes linting bugs in several blocks while trying to avoid real code changes
___
Bug fix
___
- Corrected type hints in `CreateMediumPostBlock` to fix linting errors.
- Improved readability and standardized string quotes in `search.py`.
- Removed trailing whitespace in `model.py`.
- Reformatted `openweathermap_api_key` field in `settings.py` for better readability.
___
<tr>
<td>
<details>
<summary><strong>create_medium_post.py</strong><dd><code>Fix type hints in CreateMediumPostBlock</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix(server): various linting errors

---

rnd/autogpt_server/autogpt_server/blocks/create_medium_post.py

Create Medium Post is missing test parameters to successfully pass the tests
Adds two parameters to the test for create medium post
___
Tests
___
- Added `license` parameter to the test input for creating a Medium post.
- Added `notify_followers` parameter to the test input for creating a Medium post.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>create_medium_post.py</strong><dd><code>Add missing parameters to create medium post test</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/blocks/create_medium_post.py
<li>Added <code>license</code> parameter to the test input.<br> <li> Added …

fix(server): add create medium post test missing params

---

rnd/autogpt_builder/src/components/flow.css

Moved sidebar down some to make it not overlap the

feat(Builder): Fix sidebar covering navbar

---

rnd/autogpt_server/README.md

Issue #7534 
Add Prerequisites Documentation for Poetry
___
Documentation
___
- Added instructions to install Poetry in the `README.md` file.
- Updated the setup steps to include configuring Poetry to use `.venv` in the project directory.
- Adjusted the numbering of the setup steps for clarity.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add Poetry installation and configuration steps in README</code></dd></summary>
<hr>
rnd/autogpt_server/README.md
<li>Added instructions to install Poetry.<br> <li> Updated setup steps to include Poetry configuration.<br> <li> Adjusted numbering for setup steps.<br>
</details>
</td>
<td><a …

Fix(rnd): Add Prerequisites Documentation in README.md (Server)

---

rnd/autogpt_server/autogpt_server/blocks/foreach_block.py

Adds a new Block: "For Each" for iterating over a given collection.

feat(Blocks): Add For-Each Block for iterating over a List.

---

.github/workflows/autogpt-server-ci.yml

The CI was broken cause it was looking for the wrong config in the wrong folder. 
Updated prisma commands to specify prisma config location
___
___
- Fixed the CI by specifying the correct Prisma schema location in the `prisma generate` and `prisma migrate dev` commands.
- Enhanced the CI workflow to ensure it points to the correct Prisma schema file.
___
<tr>
<td>
<details>
<summary><strong>autogpt-server-ci.yml</strong><dd><code>Fix and enhance Prisma commands in CI workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/autogpt-server-ci.yml
<li>Updated …

feat(ci) Fix migrations in CI

---

rnd/autogpt_server/autogpt_server/blocks/llm.py

https://github.com/Significant-Gravitas/AutoGPT/actions/runs/10062135192/job/27813889872 - broke linter, this fixes it
___
Enhancement, Formatting
___
- Fixed linting issues in `llm.py` by reformatting code for better readability.
- Adjusted indentation and spacing for consistency.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>llm.py</strong><dd><code>Fix linting and formatting issues in llm.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/blocks/llm.py
<li>Fixed linting issues by reformatting code for better readability.<br> <li> Adjusted …

feat(rnd) Fix linting and formatting

---

rnd/autogpt_server/autogpt_server/blocks/read_csv.py
rnd/autogpt_server/autogpt_server/data/block.py
rnd/autogpt_server/autogpt_server/data/model.py

We want the server to track who contributed to each block.
Adds basic contributor details to the block and updates Read CSV for an example of it workign

feat(server): author and contributor information on blocks

---

rnd/autogpt_server/autogpt_server/blocks/llm.py

___
Enhancement
___
- Added a new LLM model `OLLAMA_LLAMA3_405B` to the `LlmModel` enum.
- Updated the `MODEL_METADATA` dictionary to include metadata for the new `OLLAMA_LLAMA3_405B` model.
___
<tr>
<td>
<details>
<summary><strong>llm.py</strong><dd><code>Add support for `OLLAMA_LLAMA3_405B` model in LLM enum</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/blocks/llm.py
<li>Added a new LLM model <code>OLLAMA_LLAMA3_405B</code> to the <code>LlmModel</code> enum.<br> <li> Updated the <code>MODEL_METADATA</code> dictionary to include metadata for the new <br><code>OLLAMA_LLAMA3_405B</code> model.<br>
</details>
</td>
<td><a …

feat(blocks): Add 405b on ollama

---

rnd/autogpt_builder/src/components/Flow.tsx

Work on adding a way to ``CTRL + C`` and ``CTRL + V`` to the nodes so we can copy and paste single/multiple nodes
Addresses: https://github.com/Significant-Gravitas/AutoGPT/issues/7542
https://github.com/user-attachments/assets/fc53cb78-c638-4370-b733-1b6fba4ecb01

feat(Builder): Work on copy and paste of blocks

---

rnd/autogpt_server/.env.example
rnd/autogpt_server/README.advanced.md

___
documentation, enhancement
___
- Updated the `PRISMA_SCHEMA` path in `.env.example` to "postgres/schema.prisma".
- Enhanced setup instructions in `README.advanced.md`:
- Added step to copy `.env.example` to `.env`.
- Updated steps to run the PostgreSQL database and migrations.
- Improved instructions for generating Prisma client.
___
<tr>
<td>
<details>
<summary><strong>.env.example</strong><dd><code>Update PRISMA_SCHEMA path in .env.example</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/.env.example
- Updated the `PRISMA_SCHEMA` …

feat(server) Update readme

---

forge/tutorials/001_getting_started.md
forge/tutorials/002_blueprint_of_an_agent.md
forge/tutorials/003_crafting_agent_logic.md

/ replaced by %F in image file path
___
Bug fix, Documentation
___
- Fixed image file paths in multiple tutorial markdown files by replacing '/' with '%2F' to ensure proper image display.
- Updated image links in 'Getting Started', 'Blueprint of an Agent', and 'Crafting Agent Logic' tutorials to use the encoded path format.
___
<tr>
<td>
<details>
<summary><strong>001_getting_started.md</strong><dd><code>Fix image paths in 'Getting Started' tutorial</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
forge/tutorials/001_getting_started.md
<li>Updated image file paths by replacing '/' with '%2F' to …

fixes #7198

---

rnd/autogpt_server/.gitignore

We renamed the db file in the prisma but didn't add the new file to the gitignore
Adds the dev.db and journal files to the gitignore

fix(server): gitignore was missing new file name

---

docs/content/server/new_blocks.md

___
documentation
___
- Added a comprehensive wishlist of desired blocks for the AutoGPT Agent Server, categorized into Consumer Services, Social Media, E-commerce, Data/Information, and Business Tools.
- Provided examples and detailed descriptions for each category to guide contributors.
- Included instructions on how to contribute by editing the `new_blocks.md` file and opening a pull request.
___
<tr>
<td>
<details>
<summary><strong>new_blocks.md</strong><dd><code>Added wishlist of desired blocks for AutoGPT Agent Server</code></dd></summary>
<hr>
docs/content/server/new_blocks.md
<li>Added a new section listing desired blocks for the AutoGPT Agent …

docs(server): block wishlist

---

rnd/autogpt_builder/src/app/build/page.tsx
rnd/autogpt_builder/src/app/globals.css
rnd/autogpt_builder/src/app/layout.tsx
rnd/autogpt_builder/src/components/NavBar.tsx
rnd/autogpt_builder/src/components/flow.css
rnd/autogpt_builder/src/components/ui/sheet.tsx

Resolves: [UI Bug: Gap Appears in Sidebar When Scrolling ](https://github.com/Significant-Gravitas/AutoGPT/issues/7594)
This PR aims to improve the UI/UX on the `/builder` page. When users land on this page, it was scrollable, causing the scrollbar on the left-hand side to not stay fixed, resulting in a large gap above it as the user scrolled down. 
The page itself does not need to scroll since the UX is designed for users to add items onto the Flow component, which, with React Flow, has the ability to zoom and pan independently of the page. Keeping the user's focus on the experience of creating agents is crucial, so moving the logo to the header is ideal here.
With this in mind, the UI for the header needed a revamp to a more standardized approach. This will help with maintaining and …

feat(builder): UI / UX upgrade and simplification of tailwind styles

---

rnd/autogpt_server/autogpt_server/util/settings.py

___
___
- Added support for multiple methods of setting configurations outside of the `config.json` file, including environment variables and dotenv files.
- Removed the `env_file_encoding` parameter from the `Config` class.
- Modified the `settings_customise_sources` method to include additional configuration sources in a specific order.
___
<tr>
<td>
<details>
<summary><strong>settings.py</strong><dd><code>Enable multiple methods for setting configurations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/util/settings.py
<li>Added support for multiple configuration sources …

fix(server): enable other methods of setting configs outside of the config.json file

---

docs/content/server/ollama.md

Document running Ollama 
Added new docs on running ollama with NextGen AutoGPT
___
Documentation
___
- Added a new documentation file `ollama.md` under `docs/content/server/`.
- Provided detailed steps to set up and run Ollama with AutoGPT.
- Instructions include running Ollama, setting up the backend and frontend, and selecting the Ollama model in the UI.
___
<tr>
<td>
<details>
<summary><strong>ollama.md</strong><dd><code>Add documentation for running Ollama with AutoGPT</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/content/server/ollama.md
<li>Added new documentation for running Ollama with AutoGPT.<br> <li> …

feat(docs) Add how to run ollama with AutoGPT

---

docs/mkdocs.yml

Missed adding to mkdocs for ollama
Added ollama link to mkdocs
___
documentation
___
- Added a new link for 'Using Ollama' in the mkdocs navigation under 'The AutoGPT Server' section.
___
<tr>
<td>
<details>
<summary><strong>mkdocs.yml</strong><dd><code>Add 'Using Ollama' link to mkdocs navigation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/mkdocs.yml
<li>Added a new entry for 'Using Ollama' under 'The AutoGPT Server' <br>section.<br>
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7666/files#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6b …

docs(ollama) Add ollama to mkdocs

---

docs/content/server/setup.md
rnd/autogpt_builder/README.md

fix punctuation.
punctuation missing
added a period.
___
Documentation
___
- Added a missing period at the end of a sentence in `docs/content/server/setup.md`.
___
<tr>
<td>
<details>
<summary><strong>setup.md</strong><dd><code>Fix missing punctuation in setup guide</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/content/server/setup.md
- Added a missing period at the end of a sentence.
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7689/files#diff-6dbbff2042b46092fe3f8202ba851ac433b502f71b1a7823b58cbeb9 …

fix punctuation in setup.md

---

rnd/autogpt_builder/package.json
rnd/autogpt_builder/src/components/edit/ControlPanel.tsx
rnd/autogpt_builder/src/components/ui/separator.tsx
rnd/autogpt_builder/yarn.lock

This PR will be one of many for this feature: #7682 
The aim is for multiple smaller PR's for less merge conflicts upon mergers.
This PR aims to add UI components for an upcoming UI / UX update for our Agent Editor.
Introduced a new `ControlPanel` component that displays a panel with control icons and child components. Added a `Separator` component from Radix UI to differentiate sections within the control panel. Updated dependencies accordingly.
- Added a  `ControlPanel` component that displays a panel with control icons and child components. 
- Added a `Separator` component from ShadCn's Radix UI to differentiate sections within the control panel. Updated dependencies accordingly.
___
Enhancement, Dependencies
___
- Introduced a new `ControlPanel` component that displays a panel with …

feat(builder): Addition ControlPanel and Separator components

---

rnd/autogpt_server/autogpt_server/server/server.py

Error occurred when trying to create a graph from a template stored in the database. As a new graph_id was not assigned

Eerror when creating an agent from a template installed from

---

rnd/infra/helm/autogpt_builder/.helmignore
rnd/infra/helm/autogpt_builder/Chart.yaml
rnd/infra/helm/autogpt_builder/templates/NOTES.txt
rnd/infra/helm/autogpt_builder/templates/_helpers.tpl
rnd/infra/helm/autogpt_builder/templates/deployment.yaml
rnd/infra/helm/autogpt_builder/templates/hpa.yaml
rnd/infra/helm/autogpt_builder/templates/ingress.yaml
rnd/infra/helm/autogpt_builder/templates/managedcert.yaml
rnd/infra/helm/autogpt_builder/templates/service.yaml
rnd/infra/helm/autogpt_builder/templates/serviceaccount.yaml
rnd/infra/helm/autogpt_builder/templates/tests/test-connection.yaml
rnd/infra/helm/autogpt_builder/values.dev.yaml
rnd/infra/helm/autogpt_builder/values.yaml

Helm charts to deploy frontend pods
Add all the helm charts, including for ingres, svc, managedcerts etc. 
___
___
- Added Helm chart for `autogpt_builder` including templates for deployment, service, ingress, HPA, and service account.
- Defined helper templates for Kubernetes naming and labels.
- Added .helmignore file to specify patterns to ignore when building Helm packages.
- Created Chart.yaml for Helm chart metadata.
- Added NOTES.txt for post-deployment instructions.
- Configured development-specific and base Helm values in values.dev.yaml and values.yaml respectively.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr> …

feat(rnd, infra): Add deployment for frontend

---

docs/content/server/new_blocks.md

___
Documentation
___
- Added new agent idea for data analysis from xlsx data sets, including steps for sampling data, generating scripts, running Python scripts, and creating visualizations.
- Added new agent idea for Tiktok video search and download.
- Introduced a new section titled 'Marketing' in the documentation.
- Added a new agent idea for portfolio site design and enhancements under the 'Marketing' section.
___
<tr>
<td>
<details>
<summary><strong>new_blocks.md</strong><dd><code>Added new agent ideas and marketing section to documentation</code></dd></summary>
<hr>
docs/content/server/new_blocks.md
<li>Added new agent ideas for data analysis …

Add new agent ideas to docs

---

rnd/autogpt_builder/src/lib/autogpt-server-api/client.ts

We now have support for authentication on the backend for WS, so we need to support it on the frontend too.
Made connectWebSocket async to asynchronously fetch the token.
Appended token to ws url
Using this URL to make websocket calls.
___
Enhancement
___
- Made `connectWebSocket` asynchronous to fetch JWT token.
- Appended JWT token to WebSocket URL for authentication.
- Improved error handling for WebSocket connection.
- Added message handling for incoming WebSocket messages.
___
<tr>
<td>
<details>
<summary><strong>client.ts</strong><dd><code>Add JWT support and error handling in WebSocket connection</code></dd></summary>
<hr> …

feat(builder): Add jwt support on websockets

---

rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx

___
Bug fix
___
- Increased the width of the control panel in `BlocksControl.tsx` from `w-80` to `w-96` to ensure it accommodates its elements properly.
___
<tr>
<td>
<details>
<summary><strong>BlocksControl.tsx</strong><dd><code>Adjust control panel width to accommodate elements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx
- Increased the width of the control panel from `w-80` to `w-96`.
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7758/files#diff-28b4290fb343f3ffa516349fb003a22574e34bdf3749704ee9eeeba9644c03b9">+1/-1</a>&nbsp …

fix(builder): Fix the control panel being too narrow for its elements

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/NodeHandle.tsx
rnd/autogpt_builder/src/components/customnode.css
rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx
rnd/autogpt_builder/src/components/ui/input.tsx
rnd/autogpt_builder/src/lib/utils.ts

___
Enhancement, Bug fix
___
- Updated styling and layout for `CustomNode` component.
- Enhanced `NodeHandle` component with new styling properties.
- Improved layout and styling of `BlocksControl` component.
- Adjusted focus-visible ring color in `Input` component.
- Modified utility functions for type color handling.
- Cleaned up redundant CSS styles in `customnode.css`.
___
<tr>
<td>
<details>
<summary><strong>CustomNode.tsx</strong><dd><code>Update CustomNode component styling and layout adjustments</code></dd></summary>
<hr>
rnd/autogpt_builder/src/components/CustomNode.tsx
<li>Updated node styling with new classes and properties.<br> <li> Modified …

tweak(builder):  Node styling

---

rnd/autogpt_builder/Dockerfile
rnd/autogpt_builder/next.config.mjs
rnd/autogpt_builder/yarn.lock

___
Bug fix, Configuration changes
___
- Updated Dockerfile to copy `next.config.mjs` instead of `next.config.js`.
- Temporarily disabled TypeScript checks in Next.js configuration by setting `ignoreBuildErrors` to true.
___
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Update Dockerfile to use <code>next.config.mjs</code> instead of <code>next.config.js</code></code></dd></summary>
<hr>
rnd/autogpt_builder/Dockerfile
<li>Changed the copied configuration file from <code>next.config.js</code> to <br><code>next.config.mjs</code>.<br>
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7777/files#di …

fix(builder): Temporarily disbale TS checks

---

rnd/autogpt_builder/src/components/SupabaseProvider.tsx
rnd/autogpt_builder/src/lib/autogpt-server-api/client.ts
rnd/autogpt_builder/src/lib/autogpt-server-api/types.ts
rnd/autogpt_server/autogpt_server/data/user.py

___
___
- Modified `get_or_create_user` function in `user.py` to use the `get` method for safe dictionary access.
- Enhanced `SupabaseProvider.tsx` to create a user on the sign-in event by calling `api.createUser()`.
- Added a `createUser` method to the `AutoGPTServerAPI` class in `client.ts`.
- Introduced a `User` type definition in `types.ts`.
___
<tr>
<td>
<details>
<summary><strong>user.py</strong><dd><code>Safe dictionary access in `get_or_create_user` function</code>&nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/data/user.py
<li>Modified <code>get_or_create_user</code> function to use <code>get</code> method …

fix(builder,server) Add missing create user calls

---

rnd/autogpt_server/autogpt_server/blocks/discord.py
rnd/autogpt_server/autogpt_server/executor/manager.py

Make discord bot continuously running
Make discord bot continuously running & bug fixes.

fix(rnd): Make discord bot continuously running

---

docs/content/server/setup.md

Prisma database model command was missing from documentation.
Responding to issue #7726, included the `poetry run prisma generate` command in the documentation, necessary to setup the server.
___
Documentation
___
- Added the `poetry run prisma generate` command to the server setup documentation.
- Explained that this command is necessary to ensure the database schema is correctly mapped to the codebase.
- Highlighted that not running this command can lead to a `ModuleNotFoundError`.
___
<tr>
<td>
<details>
<summary><strong>setup.md</strong><dd><code>Add Prisma generate command to server setup documentation</code></dd></summary>
<hr> …

inclusion of poetry run prisma generate in the documentation

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx
rnd/autogpt_builder/src/lib/autogpt-server-api/types.ts
rnd/autogpt_builder/src/lib/utils.ts
rnd/autogpt_server/autogpt_server/blocks/agent.py
rnd/autogpt_server/autogpt_server/blocks/basic.py
rnd/autogpt_server/autogpt_server/blocks/llm.py
rnd/autogpt_server/autogpt_server/data/block.py

___
enhancement
___
- Updated block categories from `LLM` to `AI` in various blocks to better reflect their functionality.
- Split `INPUT_OUTPUT` category into separate `INPUT` and `OUTPUT` categories for better clarity.
- Added a new `LOGIC` category to handle programming logic blocks.
- Improved code formatting and readability in several places.
___
<tr>
<td>
<details>
<summary><strong>agent.py</strong><dd><code>Update block category for AutoGPTAgentBlock</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/autogpt_server/blocks/agent.py
- Changed block category …

Updated Block Categories

---

rnd/autogpt_server/autogpt_server/blocks/llm.py
rnd/autogpt_server/autogpt_server/blocks/text.py
rnd/autogpt_server/autogpt_server/data/graph.py
rnd/autogpt_server/autogpt_server/executor/manager.py

fix(rnd): Fix graph validation error message

---

rnd/autogpt_builder/src/components/CustomEdge.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/lib/autogpt-server-api/types.ts

- Add static link/connection support on the frontend and display them as dashed lines
- Remove queueing for static connections - there'll always be only one bead waiting at the end
- Make beads slightly larger and further from the end arrow

feat(builder): Support static connections

---

rnd/infra/helm/autogpt-server/templates/frontendconfig.yaml

We don't allow http, so no browser or user should be able to use http, we just redirect to https 
Added a FrontendConfig, which has redirectToHttps enabled, the response code is MOVED_PERMANENTLY_DEFAULT (in other words 301)
___
___
- Introduced a new `FrontendConfig` to ensure HTTP requests are always redirected to HTTPS.
- Enabled the `redirectToHttps` setting with a permanent redirect response code (301).
___
<tr>
<td>
<details>
<summary><strong>frontendconfig.yaml</strong><dd><code>Add FrontendConfig to enforce HTTPS redirection</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat(infra): Ensure http is always redirected to HTTPS

---

rnd/infra/terraform/environments/dev.tfvars
rnd/infra/terraform/main.tf

The builder service needs a service account to function
Created a new Google Service account with the following permissions: 
roles/container.developer
roles/cloudsql.client
roles/cloudsql.editor
roles/cloudsql.instanceUser
roles/iam.workloadIdentityUser
roles/compute.networkUser
roles/container.hostServiceAgentUser
___
___
- Added a new service account `dev-agpt-builder-sa` with necessary permissions for the builder service.
- Configured workload identity bindings for the new builder service account.
- Updated role bindings to include the builder service account across various roles.
- Modified module source paths in `main.tf` for consistency by removing the './' prefix.
___
<table><thead><tr><th></th><th align="left">Relevant …

feat(infra) Create builder account with necessary permissions

---

rnd/autogpt_builder/.env.example
rnd/autogpt_builder/package.json
rnd/autogpt_builder/src/app/layout.tsx
rnd/autogpt_builder/yarn.lock

So we can start tracking where people tend to get stuck and stop using the system
___
___
- Integrated Google Analytics into the application by adding the `GoogleAnalytics` component in the layout.
- Configured Google Analytics using a new environment variable `GA_MEASUREMENT_ID`.
- Updated `package.json` to include `@next/third-parties` as a dependency for Google Analytics support.
___
<tr>
<td>
<details>
<summary><strong>layout.tsx</strong><dd><code>Integrate Google Analytics into application layout</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_builder/src/app/layout.tsx …

feat(builder): Add google analytics to the project

---

rnd/infra/terraform/environments/dev.tfvars

Adding the required perms and service account for new websocket deployment
Create ws service account
Provide it with required permissions
Create workload identity binding so k8s service account can use the same permissions
___
enhancement
___
- Added a new service account `dev-agpt-ws-server-sa` for the WebSocket server in the development environment.
- Created a workload identity binding for the new WebSocket server service account.
- Updated various role bindings to include the new WebSocket server service account, ensuring it has the necessary permissions.
___
<tr>
<td>
<details>
<summary><strong>dev.tfvars</strong><dd><code>Add WebSocket server …

feat(infra): Add ws server infra changes

---

rnd/autogpt_server/Dockerfile

The autogpt_libs folder was missing
Adding missing folder in dockerfile
___
bug_fix
___
- Fixed a bug by adding the missing `autogpt_libs` folder to the Dockerfile, ensuring it is copied into the Docker image.
___
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Add missing `autogpt_libs` folder to Docker image</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/autogpt_server/Dockerfile
<li>Added a missing line to copy <code>rnd/autogpt_libs</code> into the Docker image.<br>
</details>
</td>
<td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7887/files#diff-add6a932e871b7d444fbebe6037f796dadc1 …

fix(rnd): Add missing libs folder

---

rnd/autogpt_builder/src/components/edit/control/BlocksControl.tsx
rnd/autogpt_server/autogpt_server/blocks/__init__.py
rnd/autogpt_server/autogpt_server/blocks/search.py
rnd/autogpt_server/autogpt_server/blocks/text.py

Boolean without default value is a UX problem. It's currently displayed as a toggle and it has no way to describe the `null` value.
So we need to prevent blocks from introducing a nullable boolean.
Add explicit check to prevent nullable boolean. Fix existing block field that has nullable boolean.

fix(rnd): Prevent boolean with no default value on AGPT-builder

---

.github/workflows/workflow-checker.yml

___
configuration changes
___
- Removed the debug information section from the GitHub Actions workflow file to streamline the workflow process.
- Eliminated echo statements that output event details, actor, and repository information, which were used for debugging purposes.
___
<tr>
<td>
<details>
<summary><strong>workflow-checker.yml</strong><dd><code>Remove debug information from GitHub workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/workflow-checker.yml
<li>Removed debug information section from the workflow.<br> <li> Simplified the workflow by …

Remove debug

---

rnd/autogpt_builder/src/components/Flow.tsx

This is a pr to fix copy-paste of text creating unintended blocks
Updated the check to prevent copy/paste if any modal is open or if the focus is on an input element
https://github.com/user-attachments/assets/7ed66188-a163-4e2d-baea-85c40b871498

Fix copy-paste of text creating unintended blocks

---

rnd/infra/terraform/environments/dev.tfvars

This is just the tf change from this https://github.com/Significant-Gravitas/AutoGPT/pull/7899/files/00467e42217e8bd87676ee271f8e06c207bd7c42#diff-afbe1103c303a8001bc8c27865476c0e3d97707e560b5b023a627798504f5e38
but while that's in review I want to have this in so I don't mess up any terraform state while working on the next few features.
Pull in IP change from https://github.com/Significant-Gravitas/AutoGPT/pull/7899/files/00467e42217e8bd87676ee271f8e06c207bd7c42#diff-afbe1103c303a8001bc8c27865476c0e3d97707e560b5b023a627798504f5e38
___
configuration changes
___
- Updated the Terraform configuration to include a new static IP name `agpt-ws-server-ip` in the `dev.tfvars` file.
- This change is intended to unblock other work by ensuring the Terraform state is not disrupted while new …

feat(infra): Add websockets IP

---

rnd/autogpt_builder/src/components/CustomNode.tsx

Fix issue: https://github.com/Significant-Gravitas/AutoGPT/issues/7911

fix(builder): Prevent overflow in node output

---

.vscode/all-projects.code-workspace
rnd/market/market/db.py
rnd/market/market/routes/admin.py
rnd/market/market/routes/agents.py
rnd/market/market/routes/search.py
rnd/market/migrations/20240829002156_make_featured_category_a_list_of_categories_and_is_featured_is_active/migration.sql
rnd/market/schema.prisma

The featured process and submission backend did weird stuff
- Adds submission status for some more queries
- make featured agents able to take multiple categories
- minor dx stuff
- (theoretically) Breaking Migrations
___
enhancement, bug_fix
___
- Enhanced the agent feature management by introducing `featuredCategories` and `isActive` fields.
- Improved the search functionality by adding a `submission_status` filter.
- Fixed naming inconsistencies in the agent routes related to submission status.
- Updated the database schema and migrations to support new feature management logic.
- Added new projects to the workspace configuration.
___
<tr>
<td> …

fix(market): fixes to submission server

---

rnd/autogpt_builder/package.json
rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/yarn.lock

We have a copy block button on the blocks that does not work, this makes it work 
https://github.com/user-attachments/assets/b5b43154-5794-44e5-a5f6-d44b0183f874

Feat(Builder): Make the copy block button work

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/ui/input.tsx

Add null checking & remove console logs on Input UI component.
Add null checking & remove console logs on Input UI component

fix(rnd): Add null checking & remove console logs on Input UI component

---

rnd/autogpt_builder/yarn.lock
rnd/autogpt_server/autogpt_server/blocks/basic.py
rnd/autogpt_server/autogpt_server/blocks/discord.py
rnd/autogpt_server/autogpt_server/blocks/http.py
rnd/autogpt_server/autogpt_server/blocks/iteration.py
rnd/autogpt_server/autogpt_server/blocks/llm.py
rnd/autogpt_server/autogpt_server/blocks/maths.py
rnd/autogpt_server/autogpt_server/blocks/medium.py
rnd/autogpt_server/autogpt_server/blocks/reddit.py
rnd/autogpt_server/autogpt_server/blocks/rss.py
rnd/autogpt_server/autogpt_server/blocks/search.py
rnd/autogpt_server/autogpt_server/blocks/talking_head.py
rnd/autogpt_server/autogpt_server/blocks/text.py
rnd/autogpt_server/autogpt_server/blocks/time_blocks.py
rnd/autogpt_server/autogpt_server/blocks/youtube.py
rnd/autogpt_server/autogpt_server/usecases/block_autogen.py
rnd/autogpt_server/autogpt_server/usecases/reddit_marketing.py
rnd/autogpt_server/autogpt_server/usecases/sample.py
rnd/autogpt_server/test/data/test_graph.py
rnd/autogpt_server/test/executor/test_manager.py

Standardize block names with a focus of making them intuitive to a non-technical person.
Replace these names:
* TextLlmCallBlock -> AITextGeneratorBlock
* ObjectLlmCallBlock -> AIStructuredResponseBlock
* AdvancedLlmCallBlock -> AIConversationBlock
* CreateTalkingAvatarClipBlock -> CreateTalkingAvatarVideoBlock
* DiscordReaderBlock -> ReadDiscordMessagesBlock
* DiscordMessageSenderBlock -> SendDiscordMessageBlock
* YouTubeTranscriberBlock -> TranscribeYouTubeVideoBlock
* CreateMediumPostBlock -> PublishToMediumBlock
* ForEachBlock -> ListIteratorBlock
* MathsBlock -> CalculatorBlock
* CounterBlock -> CountItemsBlock
* ValueBlock -> StoreValueBlock
* PrintingBlock -> PrintToConsoleBlock
* DictionaryAddEntryBlock -> AddToDictionaryBlock
* ListAddEntryBlock -> AddToListBlock
* …

feat(rnd): Rename Blocks

---

rnd/autogpt_builder/src/components/Flow.tsx

This adds a check to make sure we cant make multiple connection between the same pins multiple times
https://github.com/user-attachments/assets/fb0e2a3f-6194-4bd5-ad04-c24a4f254c56

Feat(Builder): Fix Multiple Connections Between Pins

---

rnd/autogpt_builder/src/components/ui/card.tsx

fix(rnd): Fix overflowing card due to long block name

---

docs/content/server/setup.md

___
Documentation
___
- Updated the server setup documentation to include new steps for setting up the database using Docker Compose.
- Added instructions for running the server with Docker Compose, providing a more containerized approach.
- Modified the Prisma migration command to use the development schema, ensuring proper database setup.
___
<tr>
<td>
<details>
<summary><strong>setup.md</strong><dd><code>Update server setup documentation with Docker Compose instructions</code></dd></summary>
<hr>
docs/content/server/setup.md
<li>Updated database setup instructions to include Docker commands.<br> <li> Added steps to run the server using Docker …

docs(server): Update docs with new docker compose steps

---

rnd/autogpt_server/autogpt_server/cli.py
rnd/autogpt_server/autogpt_server/data/execution.py
rnd/autogpt_server/autogpt_server/data/graph.py
rnd/autogpt_server/autogpt_server/executor/manager.py
rnd/autogpt_server/autogpt_server/executor/scheduler.py
rnd/autogpt_server/autogpt_server/server/server.py
rnd/autogpt_server/autogpt_server/util/service.py
rnd/autogpt_server/poetry.lock

- Resolves #7940
A few minor annotation issues are significantly reducing our type checking coverage, and in some cases unnecessarily complicating our code.
- fix type propagation by `AppService.run_and_wait(..)`
- fix type propagation by `@expose` and add note
- fix type propagation by `wait(..)` in `.executor.manager.execute_node(..)`
- fix type propagation by `wait(..)` in `.executor.manager._enqueue_next_nodes(..)`
- remove unnecessary null checks for `.data.graph.get_node(..)`
- fix type issue in `ExecutionScheduler`
- reduce use of `# type: ignore` in `.data.execution`
- reduce usage of `# type: ignore` in `.executor.manager`
- reduce usage of `# type: ignore` in `.server`
- reduce usage of `# type: ignore` in cli.py
- update `pyright` to v1.1.378

fix(server): Fix type checking and propagation issues

---

rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/tutorial.ts

This is to update tutorial to work with latest block output UI + it added a way to call the "fit view" button so the tutorial is more guided and setup better
https://github.com/user-attachments/assets/303ff603-b49d-4a40-af4a-f4752d693ba1
Added a function for calling "fit view" ``fitViewToScreen`` and then updated the tutorial to use the new data output UI
___
enhancement
___
- Introduced a new `fitViewToScreen` function to automate the fitting of the view to the screen, enhancing the tutorial's guidance.
- Updated the tutorial to use the new data output UI, improving the user experience.
- Added `data-id` attributes to key elements for better identification and dynamic status tracking.
- Modified tutorial text and element selectors for improved clarity and user guidance.
- Added a new …

Feat(Builder): Update tutorial to work with latest block UI

---

rnd/autogpt_builder/src/components/tutorial.ts

Replace ``Math Block`` with ``Calculator Block`` in the tutorial because the blocks where renamed recently
Before 
Now 
___
enhancement
___
- Replaced all instances of "Math Block" with "Calculator Block" in the tutorial to reflect recent renaming of blocks.
- Adjusted the attachment positions for some tutorial steps to improve user guidance.
___
<tr>
<td>
<details>
<summary><strong>tutorial.ts</strong><dd><code>Update tutorial to use "Calculator Block" instead of "Math Block"</code></dd></summary>
<hr>
rnd/autogpt_builder/src/components/tutorial.ts
<li>Replaced references to "Math Block" with "Calculator Block" in <br>tutorial steps.<br> <li> Changed …

Feat(Builder): Replace ``Math Block`` with ``Calculator Block``

---

rnd/docker-compose.yml

___
___
- Enhanced the Docker Compose configuration by adding health check conditions for the `redis` and `postgres` services.
- Updated the `depends_on` directive to ensure that `redis` starts and `postgres` is healthy before starting dependent services.
___
<tr>
<td>
<details>
<summary><strong>docker-compose.yml</strong><dd><code>Add service health check conditions in Docker Compose</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rnd/docker-compose.yml
<li>Added health check conditions for <code>redis</code> and <code>postgres</code> services.<br> <li> Changed <code>depends_on</code> to include service …

update docker compose

---

.dockerignore
rnd/autogpt_server/Dockerfile
rnd/autogpt_server/Dockerfile.ws

Avoid full rebuild on each file change, by first copying the poetry.lock and prisma.schema files.
* Re-order dockerfile for poetry install and prisma generate
* Add .venv on dockerignore
___
___
- Reordered Dockerfile commands in `Dockerfile` and `Dockerfile.ws` to optimize the build process and avoid full rebuilds on each file change.
- Added `.venv` directory to `.dockerignore` to prevent unnecessary files from being included in the Docker image.
___
<tr>
<td>
<details>
<summary><strong>.dockerignore</strong><dd><code>Add `.venv` to Docker ignore list</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix(rnd): Dockerfile Avoid full rebuild on each file change

---

rnd/autogpt_builder/src/components/Flow.tsx

Fixes: When starting a tutorial on Safari the page constantly refreshes
___
bug_fix
___
- Fixed a bug in the tutorial routing logic that caused constant page refreshes on Safari by using Next.js router for navigation.
- Replaced direct window location manipulation with `router.push` to handle URL changes more effectively.
- Ensured that URL parameters are cleared correctly when resetting the tutorial.
___
<tr>
<td>
<details>
<summary><strong>Flow.tsx</strong><dd><code>Fix tutorial routing issue on Safari using Next.js router</code></dd></summary>
<hr>
rnd/autogpt_builder/src/components/Flow.tsx
<li>Imported <code>useRouter</code>, <code>usePathname</code>, …

fix(builder): update tutorial routing to work on safari

---

rnd/autogpt_server/README.md

docs(readme) Update readme to include non docker steps

---

rnd/autogpt_server/autogpt_server/data/queue.py

tweak(rnd,redis) Make redis logging more clear

---

rnd/autogpt_server/autogpt_server/blocks/http.py
rnd/autogpt_server/autogpt_server/blocks/rss.py

Categories didn't make sense 
Swaps the categories

fix: couple block categories improved

---

rnd/autogpt_builder/src/app/error.tsx
rnd/autogpt_builder/src/app/page.tsx
rnd/autogpt_builder/src/components/CustomEdge.tsx
rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/monitor/AgentFlowList.tsx
rnd/autogpt_builder/src/components/monitor/FlowInfo.tsx
rnd/autogpt_builder/src/components/node-input-components.tsx
rnd/autogpt_builder/src/components/ui/input.tsx
rnd/autogpt_builder/src/hooks/useAgentGraph.ts
rnd/autogpt_builder/src/hooks/useBezierPath.ts

Lint job fails because there are warning are errors present. Mostly react dependency arrays aren't exhaustively satisfied.
- Update dependency arrays
- Replace `'` with `&apos;` in JSX
- Rearrange code if necessary
- Fix edges not having color

refactor(builder): Fix linting warning and errors

---

rnd/autogpt_builder/src/app/error.tsx

fix(builder): Use escaped apostrophe

---

docs/content/server/setup.md

docs(server): Update docs

---

rnd/docker-compose.yml

docker nits

---

rnd/autogpt_server/README.md
rnd/autogpt_server/run_tests.py

tweak(rnd): Use docker compose not docker-compose

---

.dockerignore

.env is for local use, it's messing with cloud environment

tweak(rnd): Ignore .env in market

---

rnd/infra/helm/autogpt-market/values.dev.yaml

Market runs on 8005 and needs to be set on k8s

fix(rnd): Update port in market

---

rnd/market/market/app.py

GKE default health check seems to be checking on / not /health. Adding / endpoint til we can figure out why it won't adhere to /health

feat(rnd): Add k8s default health check

---

rnd/autogpt_server/Dockerfile
rnd/market/Dockerfile

Fix vulnerability in setup tools.

fix(autogpt_server): Fix vulnerability in Dockerfile 

---

rnd/docker-compose.yml

Fix merge conflict error, in docker compose

fix(rnd): incorrect docker image for migrate

---

rnd/autogpt_builder/.env.example

tweak(builder) Add local supabse credentials

---

rnd/autogpt_builder/.env.example

tweak(builder): Update .env.example server url with right port

---

rnd/docker-compose.combined.yml

tweak(rnd): add env var to docker compose so no messing with .env

---

rnd/README.md

docs(rnd): Update submodules info in readme

---

rnd/autogpt_builder/src/components/CreditButton.tsx
rnd/autogpt_builder/src/components/CustomNode.tsx
rnd/autogpt_builder/src/components/Flow.tsx
rnd/autogpt_builder/src/components/NavBar.tsx
rnd/autogpt_builder/src/components/ui/icons.tsx
rnd/autogpt_builder/src/hooks/useAgentGraph.ts
rnd/autogpt_builder/src/lib/autogpt-server-api/client.ts
rnd/autogpt_builder/src/lib/autogpt-server-api/types.ts
rnd/autogpt_server/.env.example
rnd/autogpt_server/autogpt_server/data/credit.py
rnd/autogpt_server/autogpt_server/server/rest_api.py
rnd/autogpt_server/autogpt_server/server/ws_api.py
rnd/autogpt_server/autogpt_server/util/settings.py
rnd/docker-compose.yml

Credit accounting is required to limit the excessive execution of costly blocks.
Added initial UI for block execution credit accounting.
https://github.com/user-attachments/assets/38585689-2d97-479d-bb73-de0a2cfcffce

feat(rnd): Add initial block execution credit accounting UI on AutoGPT Builder

---

rnd/autogpt_builder/src/lib/autogpt-server-api/client.ts
rnd/autogpt_builder/src/lib/autogpt-server-api/types.ts
rnd/autogpt_server/autogpt_server/server/integrations.py

This PR creates two Integrations-related endpoints:
- Resolves #8072 
- Resolves #8073

feat(server): Server endpoints to add `APIKeyCredentials` and remove credentials

---

.github/PULL_REQUEST_TEMPLATE.md

Updating PR template to make it more clear that this is guidance on what needs to be working (ie critical path)
Removed checkboxes, and updated wording
> [!NOTE] 
Only for the new autogpt platform, currently in rnd/

tweak(.github): Update pr template wording

---

.github/workflows/scripts/check_actions_status.py

Reduce interval from 3 minutes to 30 seconds to reduce CI lag

ci: Reduce PR Status Checker interval

---

autogpt_platform/frontend/src/lib/autogpt-server-api/baseClient.ts

The Monitor Page crashes when there are agents with no executions
> [!NOTE] 

fix(platform): Monitor page crashing when agents present with no runs

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/data/block.py
autogpt_platform/frontend/src/components/node-input-components.tsx

Issues:
* Default input fields are not properly populated in the UI.
* Custom input can't be set on enum type, e.g.: setting the title or making enum fields as non-advanced.
* Set model field title to "LLM Model"
* Set model fields as non advanced on AITextGenerator & AIStructuredResponseGenerator
* Fixed custom fields propagation on enum type by adding merge_props on ref replacement of json schema (block.py)
* Fixed default value to favor default over empty string.
> [!NOTE] 
- Edit an agent …

fix(platform): UI fixes; Fix default value on input fields & fix enum custom fields

---

autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx

Added this minor change to a new PR, to prevent invalidating approval of the larger PR.
- Change the style of the onOpenChange check
> [!NOTE] 

tweak(platform): Updated onOpenChange code style

---

autogpt_platform/infra/helm/autogpt-server/values.dev.yaml

The list in allowed cors wasn't being parsed properly.
Add quotes around allowed cors domains
> [!NOTE] 

fix(infra): Add missing quotes in helm values

---

docs/content/server/setup.md

A quick update to setup instructions in https://docs.agpt.co/server/setup/

tweak(docs): Update setup.md with git instructions.

---

autogpt_platform/infra/helm/redis-values.prod.yaml

We're going into production
Added values for production
Deployed & Tested & Running
> [!NOTE] 

feat(infra): Add prod redis values

---

autogpt_platform/infra/helm/autogpt-market/templates/backendconfig.yaml
autogpt_platform/infra/helm/autogpt-market/templates/deployment.yaml
autogpt_platform/infra/helm/autogpt-market/templates/service.yaml
autogpt_platform/infra/helm/autogpt-market/values.prod.yaml
autogpt_platform/infra/helm/autogpt-market/values.yaml

We're going into prod
Added prod values
Did some renaming for consistency as well (backend config, targetPort)
Removed unused code (cloudsql proxy no longer needed as we moved off CloudSQL, removed base health checks as we have them in dev and prod)
Updated ports
> [!NOTE] 

feat(infra): Add market prod

---

autogpt_platform/infra/helm/autogpt-market/values.prod.yaml

Platform is taken by backend
platform > market
> [!NOTE] 

tweak(infra): Update prod market ingres host

---

autogpt_platform/backend/backend/blocks/search.py

*Sample Agent for testers:*
[Web Scrape Test_v3.json](https://github.com/user-attachments/files/17192455/Web.Scrape.Test_v3.json)
Whilst Jina Reader is great for most purposes, I've found that it can be useful sometimes to literally just scrape a website for it's raw content. 
Note that this is a super simple implementation with no bot protection bypasses or anything of that sort.
Add raw content output option to ExtractWebsiteContentBlock as an advanced option.
Please see the sample agent above

tweak(blocks): Add option for simple raw content scraping to ExtractWebsiteContentBlock

---

autogpt_platform/frontend/src/components/Flow.tsx
autogpt_platform/frontend/src/components/NavBarButtons.tsx
autogpt_platform/frontend/src/components/TallyPopup.tsx

The block list keeps getting closed during the tutorial
[Video](https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/e02c24ec-0b43-4cc8-9756-0fef0c0424a6/7b1602d7-c13d-4355-a45b-78f94132fbe8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9lMDJjMjRlYy0wYjQzLTRjYzgtOTc1Ni0wZmVmMGMwNDI0YTYvN2IxNjAyZDctYzEzZC00MzU1LWE0NWItNzhmOTQxMzJmYmU4IiwiaWF0IjoxNzI2MDgwOTU4LCJleHAiOjMzMjk2NjQwOTU4fQ.qKZROEIfjhy6UhGtdBt4LYpEUB8KJ33ttRRWPZVW2jQ)
* Remove excessive check on tutorial (state + localstorage), remove state.
* Remove the usage of the native window router, replaced it with next/navigation.
> [!NOTE] 
- Create from scratch and execute an agent with at least 3 …

fix(platform): Fix unexpected closing block list on tutorial

---

autogpt_platform/backend/backend/data/block.py

Block data is persisted in the DB only for validation & data integrity purposes. The source of truth of the block data is the block code itself. Currently, changing the name or it of a block requires manual update to the db (the need of adding migration) which causes issues, especially when you switch branch and forth making the migration file gone & the folder persist.
Basically update block data when there is a data consistency.
> [!NOTE] 
- Edit an agent from monitor, and confirm it …

fix(platform): Add block data db auto-update

---

autogpt_platform/infra/helm/autogpt-server/values.prod.yaml

We provide anthropic support out of the box
Add just the key name in only prod
> [!NOTE] 

tweak(platform): Add Anthropic

---

autogpt_platform/infra/helm/autogpt-builder/values.dev.yaml

These values aren't secret so keeping them in the repo
Added to builder values.dev.yaml the non secret values
> [!NOTE] 

fix(platform,infra): Checkin non secret values 

---

autogpt_platform/backend/backend/server/rest_api.py

Health endpoint wasn't showing up
included health router in rest server
> [!NOTE] 

fix(platform): Include health router

---

.github/PULL_REQUEST_TEMPLATE.md

I've noticed we tend to forget about making the correct infra and configuration changes when we make local changes to the way the application runs. This breaks local dev flow for some people as well as the cloud. 
Adding a reminder for such changes
> [!NOTE] 

docs(pr_template): Add reminder for config and infra changes

---

autogpt_platform/infra/terraform/environments/prod.tfvars

Updating prod variable names for pools and service accounts.
Update the service account name and desc, and change project number
> [!NOTE] 
> [!NOTE] 
- …

fix(infra): Update variable names

---

.github/workflows/platform-autgpt-deploy-prod.yml

Fix the prod workload identity pool defined in the prod yaml
Changed project number to 1021527134101
> [!NOTE] 
> [!NOTE] 
- Adding new …

fix(ci): Fix the prod workload identity pool defined in the prod yaml

---

autogpt_platform/docker-compose.platform.yml

> [!NOTE] 
> [!NOTE] 
- New or …

fix(platform): Add local enc key

---

autogpt_platform/frontend/package.json
autogpt_platform/frontend/yarn.lock

> [!NOTE] 
> [!NOTE] 
- New or …

feat: bump elliptic to 6.6.0

---

autogpt_platform/frontend/src/components/agptui/SettingsInputForm.stories.tsx
autogpt_platform/frontend/src/components/agptui/SettingsInputForm.tsx
autogpt_platform/frontend/src/components/agptui/pages/SettingsPage.stories.tsx
autogpt_platform/frontend/src/components/agptui/pages/SettingsPage.tsx

This is to add the settings page, it will end up using the new nav bar + side bar that i updated in https://github.com/Significant-Gravitas/AutoGPT/pull/8518 once that has been added 😄 
Added SettingsInputForm.tsx
Added SettingsPage.tsx

feat(platform): Add settings page

---

autogpt_platform/frontend/src/components/agptui/ProfileInfoForm.tsx
autogpt_platform/frontend/src/components/agptui/SettingsInputForm.tsx

Updates to Profile and Settings page to remove all the extra edit/save buttons and replace it with a single set of buttons, Cancel and Save Changes

feat(platform): Updates to Profile and Settings page

---

autogpt_platform/frontend/src/components/agptui/BecomeACreator.tsx
autogpt_platform/frontend/src/components/agptui/CreatorCard.tsx
autogpt_platform/frontend/src/components/agptui/FeaturedStoreCard.tsx
autogpt_platform/frontend/src/components/agptui/Navbar.tsx
autogpt_platform/frontend/src/components/agptui/StoreCard.tsx
autogpt_platform/frontend/src/components/agptui/composite/AgentsSection.tsx
autogpt_platform/frontend/src/components/agptui/composite/FeaturedCreators.stories.tsx
autogpt_platform/frontend/src/components/agptui/composite/FeaturedCreators.tsx
autogpt_platform/frontend/src/components/agptui/composite/FeaturedSection.tsx
autogpt_platform/frontend/src/components/agptui/pages/AgentPage.tsx
autogpt_platform/frontend/src/components/agptui/pages/HomePage.tsx

Updates to the Home page 
The missing images are just place holders

feat(platform): Updates to Home page

---

autogpt_platform/backend/backend/blocks/count_words_and_char_block.py

This adds a word character count block, this was originally made by https://github.com/SerchioSD I simply updated it and made it into a PR
Adds a new ``count_words_and_char_block.py`` block which has the code
https://github.com/user-attachments/assets/28dee827-b26d-4f68-af7e-859fa77fe278

feat(blocks): Add Word Character Count Block

---

autogpt_platform/frontend/src/components/NodeHandle.tsx
autogpt_platform/frontend/src/lib/utils.ts

- resolve #8740
- Adding the ability to recognize integers to the handle.

fix(frontend): Add integer type definition for node handles

---

autogpt_platform/frontend/src/components/NodeHandle.tsx

- Resolve https://github.com/Significant-Gravitas/AutoGPT/issues/8913
Increase size of Connection pin

fix(frontend) : Increase size of connection pin in blocks

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/migrations/20241211160646_rename_credit_model_and_add_stripe_customer/migration.sql
autogpt_platform/backend/schema.prisma
autogpt_platform/backend/test/data/test_credit.py

First step for the PAYG System.
- Add `stripeCustomerId` to `User` model
- Rename model `UserBlockCredit` to `CreditTransaction`
- Rename model `UserBlockCreditType` to `CreditTransactionType`
- Update related code
- Add a migration
<details>
</details>
<details>
</details>

feat(backend): Update schema for PAYG System

---

autogpt_platform/backend/test/test_data_creator.py

Updates to the test_data_creator.py to make it work again, some databases updates caused this to stop working, now its fixed and works again. 
from what i can see ``agent_graph_execution_schedules`` was dropped so we remove that, and the ``UserBlockCredit`` was changed to ``CreditTransaction``

feat:(backend/test) update test_data_creator.py

---

classic/forge/forge/components/web/selenium.py

fix(forge): Update browser extension download URL

---

autogpt_platform/frontend/src/components/agptui/Navbar.tsx

This disables the theme toggle for now, I did not remove it incase we plan to properly add it back in the future

feat(frontend): Disable theme toggle

---

autogpt_platform/frontend/src/app/layout.tsx
autogpt_platform/frontend/src/app/store/page.tsx
autogpt_platform/frontend/src/components/agptui/FilterChips.tsx
autogpt_platform/frontend/src/components/agptui/Navbar.tsx
autogpt_platform/frontend/src/components/nav/NavBarButtons.tsx

Fixes #9067 
- Renamed elements from Agent Store to Marketplace

fix(store): Marketplace - Navbar should say "Marketplace" rather than "Agent Store"

---

autogpt_platform/frontend/src/components/agptui/NavbarLink.tsx
autogpt_platform/frontend/src/tests/pages/navbar.page.ts

The clickable area on the navbar was very small and the icons were not clickable
Wrap the icons as well in Link
<details>
</details>
<details>
</details>

fix(frontend): Make clickable area bigger

---

autogpt_platform/frontend/src/components/agptui/composite/FeaturedSection.tsx

I've increased the margin,  to the requested 60px 
Before:
Requested:

fix(store): Increase the margin below featured section

---

autogpt_platform/frontend/src/lib/autogpt-server-api/client.ts

[fix(store): remove debug logging of requests](https://github.com/Significant-Gravitas/AutoGPT/commit/bb13c864f038553a428dc9041e09d83ae8687eb0)
Remove this stuff:

fix(store): remove debug logging of requests

---

autogpt_platform/backend/backend/blocks/github/pull_requests.py

This adds a new block, Github Create Repository Block (GithubCreateRepositoryBlock) which lets you create a new github repo.
i have used this to make these repos so i know it works 
https://github.com/Bentlybro/discord-whisper-transcriber
https://github.com/Bentlybro/PyAGI-Framework
https://github.com/Bentlybro/FlaskNotes

feat(blocks): Add github create repo block

---

autogpt_platform/backend/backend/blocks/github/pull_requests.py

This adds a list stargazers block, its using https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#list-stargazers

feat(blocks): Add github list stargazers block

---

autogpt_platform/backend/backend/data/graph.py

- Fixed race condition in `create_graph` to preserve node order
- Resolves #9123

fix(backend): Fix intermittent failure of `test_agent_execution`

---

autogpt_platform/frontend/src/components/agptui/composite/FeaturedSection.tsx
autogpt_platform/frontend/src/components/ui/carousel.tsx

- resolves #8973 
Adding smooth scrolling and solving some weird interaction on carousal
- Update `CarouselPrevious`, `CarouselPrevious` and add `CarouselIndicator` in `carousel.tsx`  
- Add `CarouselPrevious`, `CarouselPrevious` and `CarouselIndicator` support in `FeaturedSection.tsx`
https://github.com/user-attachments/assets/ba9a22fa-ddf2-469f-ba8a-aee1a7fc5f78

feat(platform): fix carousel on store page

---

autogpt_platform/backend/migrations/20250105254106_migrate_brace_to_double_brace_string_format/migration.sql

https://github.com/Significant-Gravitas/AutoGPT/actions/runs/12696734339/job/35391431786
<details>
</details>
<details>
</details>

hotfix(backend): Increase statement timeout for the double brace migration

---

autogpt_platform/backend/backend/integrations/credentials_store.py
autogpt_platform/frontend/src/app/profile/page.tsx
autogpt_platform/frontend/src/app/store/(user)/integrations/page.tsx

<details>
</details>
<details>
</details>

feat: no longer require ollama key

---

autogpt_platform/frontend/src/components/node-input-components.tsx

- Adding support of default value in oneOf field in `node-input-components.tsx` file 
- Also I have manually tested it and it's working.

fix(frontend) : add default support in oneOf field

---

autogpt_platform/backend/backend/data/credit.py

The current state can cause this error:
```
if (snapshot_time.year, snapshot_time.month) == (cur_time.year, cur_time.month):
^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'year'
```
Which is caused by the timestamp return value possibly a string.
<details>
</details>
<details>
</details>

fix(backend): Fix get balance error on user with null running balance

---

autogpt_platform/frontend/src/app/reset_password/page.tsx

- Add `div` to recenter page elements
<details>
</details>
<details>
</details>

fix(frontend): Center reset password page

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/data/user.py
autogpt_platform/frontend/src/components/agptui/StoreCard.tsx

https://github.com/Significant-Gravitas/AutoGPT/pull/9296 caused these errors:
Removed customer email & return_url.
<details>
</details>
<details>
</details>

fix(backend): Fix broken top-up flow

---

autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/frontend/src/app/marketplace/(user)/credits/page.tsx

* Set the minimum auto top-up amount to 500.
* Add description on minimum and dollar value in the input box.
<details>
</details>
<details>
</details>

fix(backend): Set the minimum auto top-up amount to 500 credits

---

autogpt_platform/backend/backend/data/cost.py
autogpt_platform/backend/backend/data/credit.py

This PR makes auto-top-up more reliable:
* Auto top-up will not be executed more than once within a single execution.
* Auto top-up will always be executed even if it was previously failing.
* Auto top-up will never be called twice or triggered when the balance is more than the threshold, even in the concurrent block executions set-up.
<details>
</details>
<details>
</details>

feat(backend): Avoid multiple auto-top-ups within the same execution

---

autogpt_platform/frontend/src/hooks/useCredits.ts

Prevent exception when `NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY` is missing and update state management in `useCredits`.

fix(frontend): Prevent exception when Stripe env var is missing

---

autogpt_platform/frontend/src/components/monitor/FlowInfo.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunsList.tsx

While V2 Library is coming, this has been my pet peeve
to
<details>
</details>
<details>
</details>

fix(frontend): Minor UI changes; Align badges & buttons on LibraryV1

---

autogpt_platform/backend/backend/data/block_cost_config.py

The Smart Decision Maker block needs to have costs associated with it.
- Added config for SDM Block Costs

fix(platform): Add Block Costs for SDM Block

---

autogpt_platform/backend/backend/data/notifications.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/notifications/templates/agent_run.html.jinja2
autogpt_platform/backend/backend/notifications/templates/base.html.jinja2
autogpt_platform/backend/backend/util/text.py
autogpt_platform/backend/poetry.lock
autogpt_platform/backend/pyproject.toml

We want the agent run data to be accurate, which means we need to collect it in the right place and with the correct data
- Updates email templates
- Updates how we collect the data for the agent run event

feat(backend): Add cost on node & graph execution stats

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/routers/v1.py
autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/monitor/FlowRunsStatus.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts

- Resolves #9181
- Add agent run cost indication to `/monitoring` and `/library/agents/[id]`
Backend:
- Add `GraphExecutionMeta.cost` property - value sourced from `AgentGraphExecution.stats["cost"]`
- Run an agent

feat(platform): Cost indication for agent runs

---

autogpt_platform/backend/backend/util/request.py

We've disabled the request for security reasons, and the current request library breaks on the 301 web response. 
Add manually safe URL redirect on our web request layer.
<details>
</details>
<details>
</details>

feat(backend): Enable safe URL redirect on web requests for blocks

---

autogpt_platform/frontend/src/components/agptui/FeaturedAgentCard.tsx
autogpt_platform/frontend/src/components/agptui/composite/FeaturedSection.tsx

Simplify layout and styling for better responsiveness and maintainability. 
Reorganize markup to remove redundant wrappers and improve flexibility. 
Adjust FeaturedAgentCard to dynamically handle aspect ratios and optimize hover transitions.
**FeaturedAgentCard:**
- Removed fixed height/width constraints and replaced with flexible h-full container
- Simplified nested div structure by eliminating redundant containers
- Implemented proper aspect ratio (aspect-[4/3]) for consistent image display across devices
- Optimized hover transition by applying styles directly to Image component
- Removed redundant positioning attributes and unnecessary wrapper elements
**FeaturedSection:**
- Replaced arbitrary width calculations with responsive Tailwind classes
- Improved carousel item responsiveness …

fix(frontend): Refactor FeaturedSection and FeaturedAgentCard components.

---

autogpt_platform/frontend/src/app/error.tsx
autogpt_platform/frontend/src/app/globals.css
autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/PrimaryActionButton.tsx
autogpt_platform/frontend/src/components/TallyPopup.tsx
autogpt_platform/frontend/src/components/agptui/BecomeACreator.tsx
autogpt_platform/frontend/src/components/agptui/ProfileInfoForm.tsx
autogpt_platform/frontend/src/components/auth/AuthButton.tsx
autogpt_platform/frontend/src/components/edit/control/BlocksControl.tsx
autogpt_platform/frontend/src/components/edit/control/ControlPanel.tsx
autogpt_platform/frontend/src/components/edit/control/SaveControl.tsx
autogpt_platform/frontend/src/components/profile/settings/SettingsForm.tsx
autogpt_platform/frontend/src/components/ui/button.stories.tsx
autogpt_platform/frontend/src/components/ui/button.tsx

Reverts Significant-Gravitas/AutoGPT#9570
Some of the styling changes cause issues with existing parts of the application, and I don't know if partially reverting would cause issues with the other refactored components/elements.

Revert "fix(frontend): Consolidate Application Buttons to ShadcN Base Button Component"

---

autogpt_platform/backend/backend/blocks/github/_api.py
autogpt_platform/backend/backend/blocks/github/issues.py

As part of the code review agent, I found these blocks would be useful, but not required. Adds the ability to list comments on an issue and PR as well as update comments on an issue, pr and discussion
- Adds Listing comments block
- Adds updating comment block

feat(blocks): add list comments and update comment blocks

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/blocks/smart_decision_maker.py
autogpt_platform/backend/backend/util/service.py
autogpt_platform/frontend/src/components/OutputModalComponent.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.tsx

There are a few agent-loop issues that this PR is addressing:
* There is a lack of support for agent-loop in Anthropic.
* Duplicated system & user prompt as the main objective prompt in the agent loop.
* A long rendered text of conversation history by SmartDecisionMakerBlock agent-loop in the UI.
* A lack of execution input being rendered in the execution list making it harder to debug.
https://github.com/user-attachments/assets/be430000-bde0-40c6-8f2e-c97ce45b5ed1

feat(backend): Improve SmartDecisionMaker Agent-loop capability & add Anthropics support

---

autogpt_platform/backend/migrations/20250310095931_delete_duplicate_indices/migration.sql
autogpt_platform/backend/schema.prisma

Removed some indices in the marketplace table that were useless.
<details>
</details>
<details>
</details>

fix(backend): Remove useless agent marketplace indices

---

.github/workflows/platform-backend-ci.yml

<details>
</details>
<details>
</details>

fix(platform): Set Supabase CLI version

---

autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/agents/agent-run-draft-view.tsx
autogpt_platform/frontend/src/components/agptui/types.ts

- Resolves #9612
- Add icon to "Run" button in run draft view
- Add icons "Stop run" and "Run again" buttons in run view
- Purely visual changes, no functional test needed.
Technical changes are covered by the type checker.

feat(platform/library): Add icons to primary agent run action buttons

---

autogpt_platform/backend/backend/blocks/basic.py

Since a self-loop is now allowed for AddToListBlock, providing an entry pin using a static output will cause infinite execution.
This PR change avoid such scenario to be allowed.

fix(block): Avoid infinite loop execution on AddToListBlock self-loop

---

autogpt_platform/backend/backend/data/notifications.py

We accidently send several emails within 10 mins and we're gonna get blocked for spam if we keep it up
- moves 1 min to 60 min timer

fix(backend): drastically increase batching time for the agent run

---

autogpt_platform/backend/backend/data/graph.py
autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx
autogpt_platform/frontend/src/components/agents/agent-run-draft-view.tsx

- Related to #8784
- feat(frontend/library): Improve agent output styling & fix content overflow issue
- fix(frontend/library): Fix overlap between content and inset button of expandable input fields (#9650)
- fix(backend): Unbreak loading graph executions with missing inputs
- Run an agent with at least one input *not* filled out; view this run in the Library
- Run an agent that generates long output; view this run in the Library

fix(frontend/library): Improve agent I/O rendering

---

autogpt_platform/backend/backend/data/execution.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/backend/backend/server/conn_manager.py
autogpt_platform/backend/backend/server/ws_api.py
autogpt_platform/backend/test/server/test_con_manager.py
autogpt_platform/backend/test/server/test_ws_api.py

- Add `user_id` to WS subscription key
- Add error catching to WS message handler

fix(backend/ws): Add `user_id` to websocket event subscription key

---

autogpt_platform/backend/backend/util/service.py

Avoid connecting the same host and falling-back to defined api_host.

feat(backend): Avoid connecting the same host and falling-back to defined api_host

---

autogpt_platform/frontend/src/components/agptui/SearchBar.tsx
autogpt_platform/frontend/src/components/agptui/composite/HeroSection.tsx

- fix #8955 
Reduce the margin between the search bar and chips from 24px to 20px.

fix(marketplace): Reduce margin between search bar and chips to 20px

---

autogpt_platform/frontend/src/components/agptui/composite/AgentsSection.tsx

- fix #8998 
Replace padding with margin top and update UI spacing from 32px to 25px

fix(marketplace): Fix margin between divider and section on creators page

---

autogpt_platform/frontend/src/app/login/page.tsx
autogpt_platform/frontend/src/app/reset_password/page.tsx
autogpt_platform/frontend/src/app/signup/page.tsx
autogpt_platform/frontend/src/components/auth/AuthFeedback.tsx

I oopsed and had an extra unneeded parameter (as @majdyz pointed out) and wasn't respected everywhere it was used.
- Remove parameter
- update all the places AuthFeedback is called

fix(frontend): bad handling on error prompts

---

autogpt_platform/backend/backend/util/metrics.py
autogpt_platform/backend/poetry.lock
autogpt_platform/backend/pyproject.toml

Sentry just released logs so lets enrich our details there too
- Adds sentry logging
- Adds dependencies tracking all of our sentry integrations
- Adds environment tracking to sentry

feat(backend): baseline sentry logging

---

autogpt_platform/frontend/src/components/CustomNode.tsx
autogpt_platform/frontend/src/components/Flow.tsx

Fix https://github.com/Significant-Gravitas/AutoGPT/pull/9632
- Set default values from input schema to `hardcodedValues` in `CustomNode.tsx`

fix(frontend): Fill defaults from schema to `hardcodedValues` in `CustomNode.tsx`

---

autogpt_platform/backend/backend/blocks/apollo/models.py
autogpt_platform/backend/backend/blocks/apollo/organization.py
autogpt_platform/backend/backend/blocks/apollo/people.py
autogpt_platform/backend/backend/blocks/basic.py
autogpt_platform/backend/backend/blocks/code_executor.py
autogpt_platform/backend/backend/blocks/csv.py
autogpt_platform/backend/backend/blocks/exa/contents.py
autogpt_platform/backend/backend/blocks/exa/search.py
autogpt_platform/backend/backend/blocks/exa/similar.py
autogpt_platform/backend/backend/blocks/generic_webhook/triggers.py
autogpt_platform/backend/backend/blocks/github/triggers.py
autogpt_platform/backend/backend/blocks/http.py
autogpt_platform/backend/backend/blocks/hubspot/company.py
autogpt_platform/backend/backend/blocks/hubspot/contact.py
autogpt_platform/backend/backend/blocks/hubspot/engagement.py
autogpt_platform/backend/backend/blocks/io.py
autogpt_platform/backend/backend/blocks/iteration.py
autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/blocks/mem0.py
autogpt_platform/backend/backend/blocks/pinecone.py
autogpt_platform/backend/backend/blocks/slant3d/webhook.py
autogpt_platform/backend/backend/blocks/smart_decision_maker.py
autogpt_platform/backend/backend/blocks/smartlead/campaign.py
autogpt_platform/backend/backend/blocks/smartlead/models.py
autogpt_platform/backend/backend/blocks/twitter/direct_message/manage_direct_message.py
autogpt_platform/backend/backend/blocks/twitter/spaces/spaces_lookup.py
autogpt_platform/backend/backend/blocks/twitter/users/user_lookup.py

- Resolves #9792
- Replace all `default=[]` -> `default_factory=list`
- Replace all `default={}` -> `default_factory=dict`

fix(blocks): Fix block I/O value sharing

---

autogpt_platform/backend/backend/blocks/io.py

We were duplicating placeholder values across all agents 😨 
Deep copies the schema instead

feat: deep copy the schema 

---

autogpt_platform/autogpt_libs/autogpt_libs/utils/cache.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/server/routers/v1.py

Avoid other threads accessing the channel within the same process.

fix(backend): Avoid multithreaded pika access

---

docs/content/platform/getting-started.md

Updates to the setup docs to remove the old unneeded ``git submodule update --init --recursive --progress`` command + some other small tweaks around it

update(docs): Remove outdated submodule command from docs

---

autogpt_platform/frontend/src/app/onboarding/5-run/page.tsx

Onboarding executes original agent graph directly without waiting for marketplace agent to be added to user library.
- Execute library agent after it's already added to library

fix(frontend): Fix onboarding agent execution

---

autogpt_platform/frontend/package.json
autogpt_platform/frontend/src/app/globals.css
autogpt_platform/frontend/src/app/profile/(user)/credits/page.tsx
autogpt_platform/frontend/src/components/agptui/Wallet.tsx
autogpt_platform/frontend/src/components/agptui/WalletRefill.tsx
autogpt_platform/frontend/src/components/customnode.css
autogpt_platform/frontend/src/components/ui/tabs.tsx
autogpt_platform/frontend/src/hooks/useCredits.ts
autogpt_platform/frontend/tailwind.config.ts
autogpt_platform/frontend/yarn.lock

- Add top-up and auto-refill tabs in the Wallet
- Add shadcn `tabs` component
- Disable increase/decrease spinner buttons on number inputs across Platform (moved css from `customnode.css` to `globals.css`

feat(frontend): Wallet top-up and auto-refill

---

autogpt_platform/backend/backend/data/rabbitmq.py

For unknown reason publishing message can fail sometimes due to the connection being broken:
MessageQueue suddenly unavailable, connection simply broke, connection being reset, etc.
Adding a tenacity retry on AMQP or ConnectionError, which hopefully can alleviate the issue.

feat(backend): Add retry mechanism for pika publish_message

---

autogpt_platform/backend/backend/data/graph.py

Strip secrets, credentials when forking agent

fix(backend): Strip secrets, credentials when forking agent

---

autogpt_platform/backend/backend/blocks/smart_decision_maker.py
autogpt_platform/backend/backend/data/graph.py
autogpt_platform/frontend/src/app/(platform)/profile/(user)/integrations/page.tsx
autogpt_platform/frontend/src/hooks/useAgentGraph.tsx
autogpt_platform/frontend/src/lib/autogpt-server-api/types.ts
autogpt_platform/frontend/src/lib/utils.ts

Smart Decision Block was not able to work with sub agent with custom name input & the bead were not properly propagated in the execution UI. The scope of this PR is fixing it.
* Introduce an easy to parse format of tool edge: `{tool}_^_{func}_~_{arg}`. Graph using SmartDecisionBlock needs to be re-saved before execution to work.
* Reduce cluttering on a smart decision block logic.
* Fix beads not being shown for a smart decision block tool calling.

fix(block): Fix Smart Decision Block missing input beads & incompability with input in special characters

---

autogpt_platform/frontend/.env.example
autogpt_platform/frontend/src/app/(platform)/profile/(user)/integrations/page.tsx
autogpt_platform/frontend/src/app/(platform)/profile/(user)/layout.tsx
autogpt_platform/frontend/src/components/agptui/Wallet.tsx

Provide a system toggle for disabling the billing page:
NEXT_PUBLIC_SHOW_BILLING_PAGE

feat(frontend): Add billing page toggle

---

autogpt_platform/backend/backend/data/credit.py
autogpt_platform/backend/backend/executor/database.py
autogpt_platform/backend/backend/executor/manager.py
autogpt_platform/backend/backend/executor/utils.py
autogpt_platform/backend/backend/notifications/notifications.py
autogpt_platform/backend/backend/util/settings.py

* Avoid executing any agent with a zero balance.
* Make node execution count global across agents for a single user.

fix(backend): Avoid executing any agent with zero balance

---

autogpt_platform/backend/backend/blocks/google/sheets.py

Our oauth review wants us to drop this in favor of a diff scope that will require additional work
Disables the oauth sheets scopes in prod

fix: disable google sheets in prod based on oauth review

---

autogpt_platform/frontend/src/components/agents/agent-run-details-view.tsx

The goal of this change is a quick and temporary tweak to improve the displaying of output text in the Agent Runs screen.
This change is made anticipating that these outputs will be properly improved in the near future, and is thus just a temporary change in order to display text in a human readable format.  
There is one change in this PR:
- The class of the Agent Output textbox is changed to properly display text without impacting the design.
Below is a before and after of this change:
**Before**
**After**

fix(frontend/library): Quick Patch for Rendering Agent Outputs

---

autogpt_platform/backend/backend/data/notifications.py

John thinks an hourly email is a bit much; I'm inclined to agree.
swaps the time for dealing the batch for the agent runs from one hour to one day

feat(backend): send emails daily instead of hourly

---

autogpt_platform/frontend/src/app/(no-navbar)/onboarding/6-congrats/actions.ts

Revert congrats onboarding screen action of #9916

fix(frontend): Revert congrats onboarding screen action

---

autogpt_platform/backend/backend/blocks/google/gmail.py

- add a replyAll flag to Gmail reply block
- use original message recipients when none are provided
- `ruff check autogpt_platform/backend/backend/blocks/google/gmail.py`
- `isort autogpt_platform/backend/backend/blocks/google/gmail.py`
- `pyright autogpt_platform/backend/backend/blocks/google/gmail.py` *(fails: Import "google.oauth2.credentials" could not be resolved)*

Fix Gmail reply for missing recipients

---

autogpt_platform/backend/backend/blocks/llm.py
autogpt_platform/backend/backend/data/block_cost_config.py

This adds the latest claude 4 opus and sonnet to the platform
https://www.anthropic.com/news/claude-4

feat(Platform): add claude 4 sonnet and opus models to platform

---

autogpt_platform/frontend/src/app/(platform)/reset_password/actions.ts

- Fixes #10085
- Remove redirect from `sendResetEmail` server action

fix(frontend): Resolve perpetual loading state on password reset

---

.github/labeler.yml

- Fixes #10114
- Change file matching patterns OR to AND in auto-labeler config

dx: Fix file filter for `platform/backend` auto-label

---

autogpt_platform/backend/backend/executor/manager.py

Add the missing `send execution update` command on completed/update status change for the node execution.

fix(backend): execution UI did not receive completed / failed execution update

---

autogpt_platform/backend/backend/blocks/apollo/_api.py
autogpt_platform/backend/backend/blocks/apollo/models.py
autogpt_platform/backend/backend/blocks/apollo/organization.py
autogpt_platform/backend/backend/blocks/apollo/people.py
autogpt_platform/frontend/src/components/NodeOutputs.tsx

Current Apollo blocks only work with keywords; the huge number of list filter fields doesn't work because it's passing the wrong GET parameter (missing `[]`).
Change the GET request to a POST request for Apollo.

fix(blocks): Fix broken Apollo Blocks

---

autogpt_platform/backend/backend/data/block_cost_config.py

Add cost calculation for Apollo integration.

feat(block): Enable cloud Apollo integration cost

---

autogpt_platform/backend/backend/blocks/github/pull_requests.py

- Follow-up fix to #10138
AI erased a bit of functionality from the `GithubReadPullRequestBlock` in #10138. This PR puts it back and improves on the old format.
- Include full diff in `changes` output of `GithubReadPullRequestBlock`
- Use the `GithubReadPullRequestBlock` with `include_pr_changes` enabled

fix(blocks): Restore `GithubReadPullRequestBlock` diff output

---

autogpt_platform/frontend/.env.example
autogpt_platform/frontend/src/app/api/mutators/custom-mutator.ts

This pull request includes updates to the environment configuration and API mutator logic in the `autogpt_platform/frontend` directory. The changes aim to improve flexibility by introducing dynamic base URLs through environment variables.
Environment configuration updates:
* [`autogpt_platform/frontend/.env.example`](diffhunk://#diff-72012a00359825421736dc064be74187011cb5b0462bea1ed3a3c5ca80bb3117R2): Added `NEXT_PUBLIC_FRONTEND_BASE_URL` to define the base URL for the frontend dynamically.
API mutator logic updates:
* [`autogpt_platform/frontend/src/app/api/mutators/custom-mutator.ts`](diffhunk://#diff-28c5af33c7bd0ecddc1793aa6a27bfd5b4f979b62c29990538aceea3320d8be9L1-R1): Updated `BASE_URL` to use the `NEXT_PUBLIC_FRONTEND_BASE_URL` environment variable, enabling dynamic configuration …

fix(frontend): fix custom mutator of orval

---

autogpt_platform/frontend/src/components/molecules/Toast/styles.module.css
autogpt_platform/frontend/src/components/molecules/Toast/toast.stories.tsx
autogpt_platform/frontend/src/components/molecules/Toast/toaster.tsx

Style refinements on Toasts.
None

feat(toast): update styles

---

README.md

This PR simply removes the MIT Icon from the main README.md

fix(readme): Removes MIT icon from readme

---

autogpt_platform/backend/backend/blocks/csv.py
autogpt_platform/backend/backend/blocks/text.py
autogpt_platform/backend/poetry.lock
autogpt_platform/backend/pyproject.toml
autogpt_platform/backend/test/blocks/test_gmail.py
autogpt_platform/docker-compose.platform.yml

This PR adds Excel file support to CSV processing and enhances text file reading capabilities.
**ReadSpreadsheetBlock (formerly ReadCsvBlock):**
- Renamed `ReadCsvBlock` to `ReadSpreadsheetBlock` for better clarity
- Added Excel file support (.xlsx, .xls) with automatic conversion to CSV using pandas
- Enhanced parameter `file_in` to `file_input` for consistency
- Excel files are automatically detected by extension and converted to CSV format
- Maintains all existing CSV processing functionality (delimiters, headers, etc.)
- Graceful error handling when pandas library is not available
**FileReadBlock:**
- Enhanced text file reading with advanced chunking capabilities
- Added parameters: `skip_size`, `skip_rows`, `row_limit`, `size_limit`, `delimiter`
- Supports both character-based and …

feat(blocks): Add Excel support to ReadSpreadsheetBlock and introduced FileReadBlock

---

autogpt_platform/frontend/src/app/(platform)/login/page.tsx
autogpt_platform/frontend/src/app/(platform)/reset-password/page.tsx
autogpt_platform/frontend/src/app/(platform)/signup/page.tsx

Introduced an error on my previous PR: https://github.com/Significant-Gravitas/AutoGPT/pull/10397 ( `shouldRender` should be taken in account... )
None

fix(frontend): unhide catpcha

---

autogpt_platform/frontend/src/services/feature-flags/feature-flag-provider.tsx

Only initialise Launch Darkly if we have a user and the config is set. 
No

fix(frontend): launch darkly initialisation

---

autogpt_platform/backend/backend/monitoring/late_execution_monitor.py

We've been reporting agents that are stuck on the `QUEUED` status. This change includes the one on. RUNNING status that's been stuck for more than 24hours.
Report agent on RUNNING status for more than 24hours.

feat: Add alert for notifying stuck running agent for more than a day

---

autogpt_platform/frontend/src/components/layout/Navbar/components/AgentActivityDropdown/components/ActivityItem.tsx
autogpt_platform/frontend/src/components/layout/Navbar/components/AgentActivityDropdown/helpers.tsx
autogpt_platform/frontend/src/components/layout/Navbar/components/AgentActivityDropdown/useAgentActivityDropdown.ts

Fix the issue where sometimes the agent activity would show a link to agent runs that are not available in the library. So only show runs that can be verified in the library. Improve the display of the agent name as well 🤔 
None

fix(frontend): agent activity sometimes broken links

---

autogpt_platform/backend/backend/integrations/oauth/google.py

- Resolves #10489
- Fix Google OAuth token revocation
- Fix credentials object conversion in `GoogleOAuthHandler`

fix(backend): Fix Google OAuth token revocation

---

autogpt_platform/backend/backend/integrations/oauth/google.py

Reverts Significant-Gravitas/AutoGPT#10491 as revoking one token also expires any/all others associated with the same account

Revert "fix(backend): Fix Google OAuth token revocation"

---

autogpt_platform/frontend/pnpm-lock.yaml
autogpt_platform/frontend/src/app/api/__generated__/endpoints/store/store.ts
autogpt_platform/frontend/src/app/api/openapi.json
autogpt_platform/frontend/src/components/agptui/composite/PublishAgentPopout.tsx
autogpt_platform/frontend/src/components/layout/Navbar/components/AgentActivityDropdown/components/ActivityItem.tsx
autogpt_platform/frontend/src/components/layout/Navbar/components/AgentActivityDropdown/useAgentActivityDropdown.ts

My previous PR, https://github.com/Significant-Gravitas/AutoGPT/pull/10480, didn't fully resolve the issue of broken links sometimes appearing for some runs in the Agent Activity dropdown.
- Fixed the logic ( verified with a deployment in dev... )
- Simplified logic, making less API calls
- If we have an execution without a clear agent ID, we display it but don't link to it
- Re-generated API types ( _had to update call in dashboard agents because of it_ )  
None

fix(frontend): agent activity links (2)

---

autogpt_platform/backend/backend/blocks/smart_decision_maker.py

We oops and made loops
- Moves the yielding of the convo if and only if we don't finish

fix(backend): we're making loops

---

autogpt_platform/backend/backend/executor/manager.py

Graph evaluation should stop naturally once all the node execution are stopped.
Avoid stopping agent node evaluation when stopping graph

fix(backend/executor): Avoid stopping agent node evaluation when stopping graph

---

autogpt_platform/frontend/src/app/(platform)/signup/page.tsx

Not a helpful console log to land in production... We should disallow console logs all together on the Front-end code, but that is a separate, bigger PR...
None

fix(frontend): remove console.log

---

autogpt_platform/frontend/src/hooks/useCredentials.ts

We're showing invalid credential types on the selections  across the app
We go from (incorrect)
to this with the fix

fix(frontend): filter credentials to ones that are supported

---

autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/use-agent-runs.ts

- Fixes #10749
- Fix implementation of `useAgentRunsInfinite.upsertAgentRun(..)`

fix(frontend/library): Fix new runs not appearing in list

---

autogpt_platform/frontend/src/components/cron-scheduler-dialog.tsx

Should fix the issue where sometimes the schedule modal wouldn't appear when clicking on the CTA.
gent from monitor, and confirm it executes correctly
None

fix(frontend): use new dialog in schedule agent 

---

autogpt_platform/backend/backend/server/external/middleware.py
autogpt_platform/backend/backend/server/external/routes/v1.py

- Resolves #10782
- Use `Security(..)` for security dependencies
- Minor tweaks to auth mechanism (similar to #10720)

feat(backend/external-api): Make API key auth work in Swagger UI

---

autogpt_platform/frontend/instrumentation-client.ts
autogpt_platform/frontend/sentry.edge.config.ts
autogpt_platform/frontend/sentry.server.config.ts

- We want sentry to actually work so we can do testing

feat(frontend): re-enable sentry in dev

---

.github/workflows/claude.yml

claude can't write a pr descirption correclty the frist time to save his life
Adds gh pr edit to the list of allowed tools
None code change

ci: Add 'Bash(gh pr edit:*)' to allowed tools for claude

---

autogpt_platform/backend/backend/blocks/code_executor.py

- Resolves #11016
- Add more extensive outputs to Code Execution Block
- Rename "Response" output to "Main Text Output"

feat(blocks): Improve data output of code execution block

---

autogpt_platform/frontend/src/app/(platform)/library/agents/[id]/components/OldAgentLibraryView/components/agent-run-draft-view.tsx
autogpt_platform/frontend/src/components/__legacy__/Wallet.tsx

- Fix not being able to complete `MARKETPLACE_RUN_AGENT` task
- Fix confetti shooting on every refresh
- Fix confetti shooting from top-left corner

fix(frontend): Fix confetti

---

autogpt_platform/frontend/src/app/(platform)/admin/layout.tsx
autogpt_platform/frontend/src/app/(platform)/auth/callback/route.ts
autogpt_platform/frontend/src/app/(platform)/error.tsx
autogpt_platform/frontend/src/app/(platform)/error/helpers.ts
autogpt_platform/frontend/src/app/(platform)/error/page.tsx
autogpt_platform/frontend/src/app/(platform)/layout.tsx
autogpt_platform/frontend/src/app/(platform)/login/page.tsx
autogpt_platform/frontend/src/app/(platform)/marketplace/components/AgentPageLoading.tsx
autogpt_platform/frontend/src/app/(platform)/marketplace/components/CreatorPageLoading.tsx
autogpt_platform/frontend/src/app/(platform)/marketplace/components/MainAgentPage/MainAgentPage.tsx
autogpt_platform/frontend/src/app/(platform)/marketplace/components/MainCreatorPage/MainCreatorPage.tsx
autogpt_platform/frontend/src/app/(platform)/marketplace/components/MainMarketplacePage/MainMarketplacePage.tsx
autogpt_platform/frontend/src/app/(platform)/marketplace/components/MainMarketplacePageLoading.tsx
autogpt_platform/frontend/src/app/(platform)/profile/(user)/layout.tsx
autogpt_platform/frontend/src/app/global-error.tsx
autogpt_platform/frontend/src/components/__legacy__/Wallet.tsx
autogpt_platform/frontend/src/components/atoms/Avatar/Avatar.tsx
autogpt_platform/frontend/src/components/layout/Navbar/components/AccountMenu/AccountMenu.tsx
autogpt_platform/frontend/src/components/layout/Navbar/components/LoginButton.tsx
autogpt_platform/frontend/src/components/layout/Navbar/components/NavbarView.tsx
autogpt_platform/frontend/src/providers/onboarding/helpers.ts
autogpt_platform/frontend/src/providers/onboarding/onboarding-provider.tsx
autogpt_platform/frontend/src/services/storage/local-storage.ts
autogpt_platform/frontend/src/tests/pages/login.page.ts

- Moved non-UI logic into `providers/onboarding/helpers.ts` to reduce provider complexity.
- Memoized provider value and narrowed state updates to cut unnecessary re-renders.
- Deferred non-critical effects until after mount to lower initial JS work.
**Result:** faster initial render and smoother onboarding flows under load.
- Replaced `w-screen` with `w-full` in platform/admin/profile layouts and marketplace wrappers to avoid 100vw scrollbar overflow.
- Adjusted mobile navbar position (`right-0` instead of `-right-4`) to prevent off-viewport elements.
**Result:** removed horizontal scrolling on Marketplace, Library, and Settings pages; Build remains unaffected.
- Standardized global error handling in `app/global-error.tsx` for consistent display and user feedback.
- Added platform-scoped …

fix(frontend): performance and layout issues
